
obj-y	:= 	lt_api_vp890.o \
			lt_api_vp890_all_gr_909.o \
			lt_api_vp890_cap.o \
			lt_api_vp890_cap_ringers.o \
			lt_api_vp890_cross_connect.o \
			lt_api_vp890_dc_feed.o \
			lt_api_vp890_dc_voltage.o \
			lt_api_vp890_flt_dscrm.o \
			lt_api_vp890_line_v.o \
			lt_api_vp890_loopback.o \
			lt_api_vp890_master_socket.o \
			lt_api_vp890_on_off_hook_st.o \
			lt_api_vp890_pre_linev.o \
			lt_api_vp890_rd_bat_cond.o \
			lt_api_vp890_rd_loop_cond.o \
			lt_api_vp890_res_flt.o \
			lt_api_vp890_ringers.o \
			lt_api_vp890_ringing_st.o \
			lt_api_vp890_roh.o \
			lt_api_vp890_vvp_calculate_results.o 
 
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/microsemi/microsemi_verivoice_api/includes/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/microsemi/microsemi_verivoice_api/vp880_lt/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/microsemi/microsemi_verivoice_api/vp886_lt/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/microsemi/microsemi_verivoice_api/vp890_lt/
EXTRA_CFLAGS += -I$(DIR_VOIP)/include/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/$(MICROSEMI_LIB)/common/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/$(MICROSEMI_LIB)/includes/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/microsemi/microsemi_voicepath_api/arch/rtl89xxb/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/$(MICROSEMI_LIB)/vp890_api/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/$(MICROSEMI_LIB)/vp880_api/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/$(MICROSEMI_LIB)/vp886_api/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/$(MICROSEMI_LIB)/includes/linetest/
EXTRA_CFLAGS += -I$(DIR_VOIP)/voip_drivers/$(MICROSEMI_LIB)/vp886_api/linetest/

include $(DIR_VOIP)/rules.mak

