
extern void ip6t_eui64_init(void);
extern void ip6t_icmpv6_init(void);
extern void ip6t_length_init(void);
extern void ip6t_limit_init(void);
extern void ip6t_mac_init(void);
extern void ip6t_mark_init(void);
extern void ip6t_multiport_init(void);
extern void ip6t_owner_init(void);
extern void ip6t_standard_init(void);
extern void ip6t_tcp_init(void);
extern void ip6t_udp_init(void);
extern void ip6t_LOG_init(void);
extern void ip6t_MARK_init(void);
extern void ip6t_dscp_init(void);
extern void ip6t_DSCP_init(void);
extern void ip6t_IMQ_init(void);
extern void ip6t_iprange_init(void);
extern void ip6t_state_init(void);
extern void ip6t_rt_init(void);
extern void ip6t_ipv6header_init(void);
extern void ip6t_REJECT_init(void);
extern void ip6t_frag_init(void);
extern void ip6t_ah_init(void);
void init_extensions(void) {
	ip6t_eui64_init();
	ip6t_icmpv6_init();
	ip6t_length_init();
	ip6t_limit_init();
	ip6t_mac_init();
	ip6t_mark_init();
	ip6t_multiport_init();
	ip6t_owner_init();
	ip6t_standard_init();
	ip6t_tcp_init();
	ip6t_udp_init();
	ip6t_LOG_init();
	ip6t_MARK_init();
	ip6t_dscp_init();
	ip6t_DSCP_init();
	ip6t_IMQ_init();
	ip6t_iprange_init();
	ip6t_state_init();
	ip6t_rt_init();
	ip6t_ipv6header_init();
	ip6t_REJECT_init();
	ip6t_frag_init();
	ip6t_ah_init();
}
