
extern void ipt_ah_init(void);
extern void ipt_conntrack_init(void);
extern void ipt_dscp_init(void);
extern void ipt_ecn_init(void);
extern void ipt_esp_init(void);
extern void ipt_helper_init(void);
extern void ipt_icmp_init(void);
extern void ipt_iprange_init(void);
extern void ipt_length_init(void);
extern void ipt_limit_init(void);
extern void ipt_mac_init(void);
extern void ipt_mark_init(void);
extern void ipt_multiport_init(void);
extern void ipt_owner_init(void);
extern void ipt_pkttype_init(void);
extern void ipt_standard_init(void);
extern void ipt_state_init(void);
extern void ipt_tcp_init(void);
extern void ipt_tcpmss_init(void);
extern void ipt_tos_init(void);
extern void ipt_ttl_init(void);
extern void ipt_udp_init(void);
extern void ipt_unclean_init(void);
extern void ipt_DNAT_init(void);
extern void ipt_DSCP_init(void);
extern void ipt_ECN_init(void);
extern void ipt_LOG_init(void);
extern void ipt_MARK_init(void);
extern void ipt_MASQUERADE_init(void);
extern void ipt_MIRROR_init(void);
extern void ipt_REDIRECT_init(void);
extern void ipt_REJECT_init(void);
extern void ipt_SNAT_init(void);
extern void ipt_TCPMSS_init(void);
extern void ipt_TOS_init(void);
extern void ipt_ULOG_init(void);
extern void ipt_TRIGGER_init(void);
extern void ipt_CLASSIFY_init(void);
extern void ipt_IMQ_init(void);
extern void ipt_TTL_init(void);
extern void ipt_iplimit_init(void);
extern void ipt_udplimit_init(void);
extern void ipt_string_init(void);
extern void ipt_recent_init(void);
extern void ipt_realm_init(void);
extern void ipt_NETMAP_init(void);
void init_extensions(void) {
	ipt_ah_init();
	ipt_conntrack_init();
	ipt_dscp_init();
	ipt_ecn_init();
	ipt_esp_init();
	ipt_helper_init();
	ipt_icmp_init();
	ipt_iprange_init();
	ipt_length_init();
	ipt_limit_init();
	ipt_mac_init();
	ipt_mark_init();
	ipt_multiport_init();
	ipt_owner_init();
	ipt_pkttype_init();
	ipt_standard_init();
	ipt_state_init();
	ipt_tcp_init();
	ipt_tcpmss_init();
	ipt_tos_init();
	ipt_ttl_init();
	ipt_udp_init();
	ipt_unclean_init();
	ipt_DNAT_init();
	ipt_DSCP_init();
	ipt_ECN_init();
	ipt_LOG_init();
	ipt_MARK_init();
	ipt_MASQUERADE_init();
	ipt_MIRROR_init();
	ipt_REDIRECT_init();
	ipt_REJECT_init();
	ipt_SNAT_init();
	ipt_TCPMSS_init();
	ipt_TOS_init();
	ipt_ULOG_init();
	ipt_TRIGGER_init();
	ipt_CLASSIFY_init();
	ipt_IMQ_init();
	ipt_TTL_init();
	ipt_iplimit_init();
	ipt_udplimit_init();
	ipt_string_init();
	ipt_recent_init();
	ipt_realm_init();
	ipt_NETMAP_init();
}
