#ifndef		_ADSLVARS_H_
#define		_ADSLVARS_H_

CVoidType	adslInit (void);


/*
 * MIB entry declarations 
 */
// adslMIB.1.1
#define ADSLMIBOBJECTSNUM					6

#define ADSLLINETBL							1
#define ADSLATUCPHYSTBL					2
#define ADSLATURPHYSTBL					3
#define ADSLATUCPERFDATATBL				6
#define ADSLATURPERFDATATBL				7
#define ADSLLINEALARMCONFTBL				15


// adslMIB.1.1.1.1
#define ADSLLINETBLNUM						1

#define ADSLLINECODING						1

// adslMIB.1.1.2.1
#define ADSLATUCPHYSTBLNUM				2

#define ADSLATUCINVVENDORID				2
#define ADSLATUCINVVERSIONNUMBER			3

// adslMIB.1.1.3.1
#define ADSLATURPHYSTBLNUM				4

#define ADSLATURINVSERIALNUMBER			1
#define ADSLATURINVVENDORID				2
#define ADSLATURINVVERSIONNUMBER			3
#define ADSLATURCURRSNRMGN				4

// adslMIB.1.1.6.1
#define ADSLATUCPERFDATATBLNUM			6

#define ADSLATUCPERFLOFS					1
#define ADSLATUCPERFLOSS					2
#define ADSLATUCPERFCURR15MINLOFS		10
#define ADSLATUCPERFCURR15MINLOSS		11
#define ADSLATUCPERFCURR1DAYLOFS			17
#define ADSLATUCPERFCURR1DAYLOSS			18

// adslMIB.1.1.7.1
#define ADSLATURPERFDATATBLNUM			12

#define ADSLATURPERFLOFS					1
#define ADSLATURPERFLOSS					2
#define ADSLATURPERFLPRS					3
#define ADSLATURPERFESS					4
#define ADSLATURPERFCURR15MINLOFS		8
#define ADSLATURPERFCURR15MINLOSS		9
#define ADSLATURPERFCURR15MINLPRS		10
#define ADSLATURPERFCURR15MINESS			11
#define ADSLATURPERFCURR1DAYLOFS			13
#define ADSLATURPERFCURR1DAYLOSS			14
#define ADSLATURPERFCURR1DAYLPRS			15
#define ADSLATURPERFCURR1DAYESS			16

// adslMIB.1.1.15.1
#define ADSLLINEALARMCONFTBLNUM					1

#define ADSLATURTHRESH15MINESS					15

#endif
