#ifndef		_ADSL2VARS_H_
#define		_ADSL2VARS_H_

#define ADSLATURPERFDATAEXTTABLE			19
#define ADSLCONFPROFILEEXTTABLE				20

#define ADSLATURPERFDATAEXTTABLENUM			4
#define ADSLATURPERFSTATSESL				1
#define ADSLATURPERFSTATUASL				2
#define ADSLATURPERFCURR15MINSESL			3
#define ADSLATURPERFCURR1DAYSESL			5

#define ADSLCONFPROFILEEXTTABLENUM			1
#define ADSLCONFPROFILELINETYPE				1

#endif