
#ifndef		_NSCRTVARS_H_
#define		_NSCRTVARS_H_

CVoidType	nscrtInit (void);

/*
 * MIB entry declarations 
 */
// NSCRTMIB //National Standardization Committee of Radio & Television 

//nscrt.1 

#define NSCRTPROPERTY	1 // table
#define NSCRTALARMS		2 // table
#define NSCRTCOMMON		3 // table
#define NSCRTTVMOD		4 
#define NSCRTQAMMOD		5
#define NSCRTOTD		6
#define NSCRTOTX		7
#define NSCRTUPOR		8
#define NSCRTDOR		9 // table
#define NSCRTFN			10 // table
#define NSCRTOA			11
#define NSCRTADD		12
#define NSCRTCAC		13		
#define NSCRTLINE		14
#define NSCRTLTDEFINEHFC 90

//nscrt.1.3.1
#define NSCRTCOMMONTABLENUM				19

#define NSCRTCOMMONELOGICALID			1
#define NSCRTCOMMONEVENDOR				2
#define NSCRTCOMMONEMODELNUMBER			3	
#define NSCRTCOMMONESERIALNUMBER			4
#define NSCRTCOMMONEVENDORINFO			5
#define NSCRTCOMMONESTATUS				6
#define NSCRTCOMMONRESET					7
#define NSCRTCOMMONALARMDETECTIONCONTROL	8
#define NSCRTCOMMONNETWORKADDRESS			9
#define NSCRTCOMMONCHECKCODE				10
#define NSCRTCOMMONTRAPCOMMUNITYSTRING	11
#define NSCRTCOMMONTAMPERSTATUS			12
#define NSCRTCOMMONINTERNALTEMPERATURE	13	//require
#define NSCRTCOMMONTIME					14
#define NSCRTCOMMONVARBINDINGS			15
#define NSCRTCOMMONRESETCAUSE				16
#define NSCRTCOMMONCRAFTSTATUS			17
#define NSCRTCOMMONDEVICEOID				18
#define NSCRTCOMMONDEVICEID				19

//nscrt.1.9
#define NSCRTDORTABLENUM			9

#define NSCRTDORVENDOROID			1
#define NSCRTDORINPUTNUMBER			2
#define NSCRTDORINPUTTABLE			3 // table
#define NSCRTDOROUTPUTNUMBER 		4
#define NSCRTDOROUTPUTTABLE			5 // table
#define NSCRTDORNUMBERDCPOWERSUPPLY 6 
#define NSCRTDORDCPOWERSUPPLYMODE   7
#define NSCRTDORDCPOWERTABLE		8 // table
#define NSCRTDORUNITTABLE			9 // table


// nscrt.1.9.3.1
#define NSCRTDORINPUTTABLENUM		6

#define NSCRTDORINPUTINDEX			1
#define NSCRTDORINPUTPOWER			2	//require
#define NSCRTDORINPUTWAVELENGTHCONTROL	3
#define NSCRTDORINPUTSTATUS			4
#define NSCRTDORINPUTCHANNELNUMBER	5
#define NSCRTDORINPUTPOWERDBM		6


// nscrt.1.9.5.1
#define NSCRTDOROUTPUTTABLENUM		11

#define NSCRTDOROUTPUTINDEX			1
#define NSCRTDOROUTPUTCONTROL		2
#define NSCRTDOROUTPUTGAINTYPE		3
#define NSCRTDOROUTPUTLEVEL			4	//require
#define NSCRTDOROUTPUTRFPADLEVEL	5
#define NSCRTDOROUTPUTRFNANE		6
#define NSCRTDOROUTPUTLEVELSTATUS	40
#define NSCRTDOROUTPUTAGCSTATUS		41
#define NSCRTDOROUTPUTALCLEVEL		42
#define NSCRTDOROUTPUTMLCLEVEL		43
#define NSCRTDOROUTPUTSLOPELEVEL	44

// nscrt.1.9.8.1
#define NSCRTDORDCPOWERTABLENUM		4

#define NSCRTDORDCPOWERINDEX		1
#define NSCRTDORDCPOWERVOLTAGE		2	//require
#define NSCRTDORDCPOWERCURRENT		3
#define NSCRTDORDCPOWERNAME			4
















#endif