#ifndef __RTK_APOLLOMP_TABLE_STRUCT_H__
#define __RTK_APOLLOMP_TABLE_STRUCT_H__

/*
 * Include Files
 */
#include <common/rt_autoconf.h>

/* Superset Table Enum */
typedef enum rtk_apollomp_table_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NATt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATAt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2t,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASKt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2t,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DSt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_USt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASKt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34t,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34t,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSLt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UCt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSLt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLANt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ARP_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_BINDING_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_EXTERNAL_IP_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_IPV6_ROUTING_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_DROP_TRAPt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPT_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEIGHBOR_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NETIFt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEXT_HOP_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_PPPOE_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_WAN_TYPE_TABLEt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSAt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSBt,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATAt,
#endif

    APOLLOMP_TABLE_LIST_END,
} rtk_apollomp_table_list_t;


/* Internal Table Enum */
typedef enum rtk_int_apollomp_table_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_HSB_DATA_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_HSA_DATA_NAT_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_HSA_DATA_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_ACL_ACTION_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_ACL_DATA_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_ACL_DATA2_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_ACL_MASK_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_ACL_MASK2_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_CF_ACTION_DS_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_CF_ACTION_US_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_CF_MASK_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_CF_MASK_L34_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_CF_RULE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_CF_RULE_L34_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_L2_MC_DSL_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_L2_UC_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_L3_MC_DSL_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_L3_MC_ROUTE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_VLAN_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_ARP_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_BINDING_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_EXTERNAL_IP_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_IPV6_ROUTING_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_L3_ROUTING_DROP_TRAP_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_L3_ROUTING_LOCAL_ROUTE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_NAPT_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_NAPTR_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_NEIGHBOR_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_NETIF_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_NEXT_HOP_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_PPPOE_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_WAN_TYPE_TABLE_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_L34_HSA_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_L34_HSB_APOLLOMP,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    INT_APOLLOMP_HSA_DEBUG_DATA_APOLLOMP,
#endif

    INT_APOLLOMP_TABLE_LIST_END,
} rtk_int_apollomp_table_list_t;


typedef enum rtk_apollomp_hsb_data_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_SPAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_15tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_14tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_13tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_12tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_11tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_10tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_9tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_8tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_7tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_6tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_5tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_4tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_FIELD_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_USER_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_IP6_HN_RGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CKS_OK_L4tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CKS_OK_L3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_TTL_GT1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_TTL_GT5tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_GRE_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_ICMP_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_UDP_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_TCP_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_PPPOE_SESSIONtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_DIPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_SIPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_TOS_DSCPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_IP_TYPEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_PTP_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_OMAPDUtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_RLPP_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_RLDP_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_LLC_OTHERtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_PPPOE_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_SNAP_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_ETHER_TYPEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CTAGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CTAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_STAGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_STAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_L3Ctf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_L4Ctf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_TXPMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_EFID_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_EFIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_PRISELtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_KEEPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_VSELtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_DISLRNtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_PSELtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_L34KEEPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_EXTSPAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_PPPOE_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_PPPOE_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_L2BRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_PON_SIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_CPUTAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_SAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_DAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_PON_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSB_DATA_TABLE_PKT_LENtf,
#endif

    APOLLOMP_HSB_DATA_TABLEFIELD_LIST_END,
} rtk_apollomp_hsb_data_tableField_list_t;


typedef enum rtk_apollomp_hsa_data_natField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_ENDSCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_BGDSCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_QIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_FLOODPKTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_RESERVEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_CPUPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_FWDRSNtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_PON_SIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_EXT_MASKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_DPMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_SPAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_PKTLENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_UNTAGSETtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_CTAG_PONACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_CTAG_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_VIDZEROtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_PRITAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_CTAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_PONVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_VIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_CFItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_PONPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_STAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_DEItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_UNTAGSETtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_STAG_TYPEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_SP2Stf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_VIDSELtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_FRCTAGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_FRCTAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_PONSVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_SVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_SVIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_PKT_SPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_PONSPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_SPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_USER_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_1P_REMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_1P_REM_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_DSCP_REMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_DSCP_REM_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_REGEN_CRCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_CPUKEEPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_KEEPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_PTPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_TCPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_UDPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_IPV4tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_IPV6tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_RFC1042tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_PPPOE_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L3Rtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_ORGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_IPMCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L2TRANStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L34TRANStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_SRC_MODtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_PPPOE_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_PPPOE_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_SMAC_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L3CKSUMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L4CKSUMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_NEWIPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_NEWPORTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_NEWDMACtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_TTLM1_EXTMASKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_TTLM1_PMASKtf,
#endif

    APOLLOMP_HSA_DATA_NATFIELD_LIST_END,
} rtk_apollomp_hsa_data_natField_list_t;


typedef enum rtk_apollomp_hsa_data_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_ENDSCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_BGDSCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_QIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_FLOODPKTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_RESERVEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_CPUPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_FWDRSNtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_PON_SIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_EXT_MASKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_DPMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_SPAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_PKTLENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_UNTAGSETtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_CTAG_PONACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_CTAG_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_VIDZEROtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_PRITAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_CTAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_PONVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_VIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_CFItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_PONPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_STAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_DEItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_UNTAGSETtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_STAG_TYPEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_SP2Stf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_VIDSELtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_FRCTAGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_FRCTAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_PONSVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_SVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_SVIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_PKT_SPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_PONSPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_SPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_USER_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_1P_REMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_1P_REM_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_DSCP_REMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_DSCP_REM_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_REGEN_CRCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_CPUKEEPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_KEEPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_PTPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_TCPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_UDPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_IPV4tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_IPV6tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_RFC1042tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_PPPOE_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_RESVtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_IDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_SECtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_NSECtf,
#endif

    APOLLOMP_HSA_DATA_TABLEFIELD_LIST_END,
} rtk_apollomp_hsa_data_tableField_list_t;


typedef enum rtk_apollomp_acl_action_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_HITtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_CFACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_CFIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_ACLINTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_PRIACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_PRIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_FWDACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_FWD_PMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_POLICACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_METER_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_SACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_SVIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_CACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_ACTION_TABLE_CVIDXtf,
#endif

    APOLLOMP_ACL_ACTION_TABLEFIELD_LIST_END,
} rtk_apollomp_acl_action_tableField_list_t;


typedef enum rtk_apollomp_acl_dataField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_FIELD7tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_FIELD6tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_FIELD5tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_FIELD4tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_FIELD3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_FIELD2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_FIELD1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_FIELD0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_PMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_TAGStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA_TYPEtf,
#endif

    APOLLOMP_ACL_DATAFIELD_LIST_END,
} rtk_apollomp_acl_dataField_list_t;


typedef enum rtk_apollomp_acl_data2Field_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_FIELD3_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_FIELD2_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_FIELD1_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_FIELD0_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_PMSK_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_TAGS_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_TYPE_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_FIELD2_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_FIELD1_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_FIELD0_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_PMSK_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_TAGS_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_DATA2_TYPE_1tf,
#endif

    APOLLOMP_ACL_DATA2FIELD_LIST_END,
} rtk_apollomp_acl_data2Field_list_t;


typedef enum rtk_apollomp_acl_maskField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_FIELD7tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_FIELD6tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_FIELD5tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_FIELD4tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_FIELD3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_FIELD2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_FIELD1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_FIELD0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_PMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_TAGStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK_TYPEtf,
#endif

    APOLLOMP_ACL_MASKFIELD_LIST_END,
} rtk_apollomp_acl_maskField_list_t;


typedef enum rtk_apollomp_acl_mask2Field_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_FIELD3_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_FIELD2_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_FIELD1_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_FIELD0_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_PMSK_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_TAGS_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_TYPE_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_FIELD2_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_FIELD1_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_FIELD0_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_PMSK_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_TAGS_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ACL_MASK2_TYPE_1tf,
#endif

    APOLLOMP_ACL_MASK2FIELD_LIST_END,
} rtk_apollomp_acl_mask2Field_list_t;


typedef enum rtk_apollomp_cf_action_dsField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_UNI_PMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_UNI_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_DSCP_REMARKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CF_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CFPRI_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CPRI_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CVID_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_C_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_C_VIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CSPRI_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CSVID_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CS_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CS_VIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_DS_CSACTtf,
#endif

    APOLLOMP_CF_ACTION_DSFIELD_LIST_END,
} rtk_apollomp_cf_action_dsField_list_t;


typedef enum rtk_apollomp_cf_action_usField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_COUNTER_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_LOGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_DROPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_ASSIGN_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_SID_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_DSCP_REMARKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CF_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CFPRI_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CPRI_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CVID_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_C_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_C_VIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CSPRI_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CSVID_ACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CS_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CS_VIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_ACTION_US_CSACTtf,
#endif

    APOLLOMP_CF_ACTION_USFIELD_LIST_END,
} rtk_apollomp_cf_action_usField_list_t;


typedef enum rtk_apollomp_cf_maskField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_ETH_TYPE_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_U_D_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_TOS_GEMIDX_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_VID_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_PRI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_INTER_PRI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_IF_STAG_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_IF_CTAG_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_UNI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_U_D_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_TOS_GEMIDX_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_VID_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_PRI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_INTER_PRI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_IF_STAG_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_IF_CTAG_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_UNI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_U_D_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_TOS_GEMIDX_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_VID_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_PRI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_INTER_PRI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_IF_STAG_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_IF_CTAG_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_UNI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_U_D_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_TOS_GEMIDX_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_VID_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_PRI_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_INTER_PRI_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_IF_STAG_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_IF_CTAG_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_UNI_3tf,
#endif

    APOLLOMP_CF_MASKFIELD_LIST_END,
} rtk_apollomp_cf_maskField_list_t;


typedef enum rtk_apollomp_cf_mask_l34Field_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_PORT_RNG_CHK_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IP_RNG_CHK_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_ACL_HIT_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_U_D_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_WAN_IF_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IP6_MCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IP4_MCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_MLDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IGMPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_DEItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_VID_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_PRI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_INTER_PRI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IF_STAG_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IF_CTAG_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_UNI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_U_D_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_TOS_GEMIDX_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_VID_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_PRI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_INTER_PRI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IF_STAG_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IF_CTAG_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_UNI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_U_D_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_TOS_GEMIDX_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_VID_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_PRI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_INTER_PRI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IF_STAG_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IF_CTAG_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_UNI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_U_D_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_TOS_GEMIDX_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_VID_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_PRI_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_INTER_PRI_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IF_STAG_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_IF_CTAG_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_MASK_L34_UNI_3tf,
#endif

    APOLLOMP_CF_MASK_L34FIELD_LIST_END,
} rtk_apollomp_cf_mask_l34Field_list_t;


typedef enum rtk_apollomp_cf_ruleField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_ETH_TYPE_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_U_D_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_TOS_GEMIDX_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_VID_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_PRI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_INTER_PRI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_IF_STAG_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_IF_CTAG_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_UNI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_U_D_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_TOS_GEMIDX_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_VID_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_PRI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_INTER_PRI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_IF_STAG_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_IF_CTAG_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_UNI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_U_D_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_TOS_GEMIDX_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_VID_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_PRI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_INTER_PRI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_IF_STAG_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_IF_CTAG_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_UNI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_U_D_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_TOS_GEMIDX_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_VID_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_PRI_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_INTER_PRI_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_IF_STAG_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_IF_CTAG_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_UNI_3tf,
#endif

    APOLLOMP_CF_RULEFIELD_LIST_END,
} rtk_apollomp_cf_ruleField_list_t;


typedef enum rtk_apollomp_cf_rule_l34Field_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_PORT_RNG_CHK_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IP_RNG_CHK_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_ACL_HIT_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_U_D_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_WAN_IF_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IP6_MCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IP4_MCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_MLDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IGMPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_DEItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_VID_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_PRI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_INTER_PRI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IF_STAG_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IF_CTAG_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_UNI_0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_U_D_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_TOS_GEMIDX_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_VID_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_PRI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_INTER_PRI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IF_STAG_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IF_CTAG_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_UNI_1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_U_D_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_TOS_GEMIDX_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_VID_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_PRI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_INTER_PRI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IF_STAG_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IF_CTAG_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_UNI_2tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_U_D_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_TOS_GEMIDX_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_VID_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_PRI_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_INTER_PRI_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IF_STAG_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_IF_CTAG_3tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_CF_RULE_L34_UNI_3tf,
#endif

    APOLLOMP_CF_RULE_L34FIELD_LIST_END,
} rtk_apollomp_cf_rule_l34Field_list_t;


typedef enum rtk_apollomp_l2_mc_dslField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_NOT_SALEARNtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_FWDPRI_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_FWDPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_EXT_MBRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_MBRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_IVL_SVLtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_L3LOOKUPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_VID_FIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_MC_DSL_MACtf,
#endif

    APOLLOMP_L2_MC_DSLFIELD_LIST_END,
} rtk_apollomp_l2_mc_dslField_list_t;


typedef enum rtk_apollomp_l2_ucField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_NOT_SALEARNtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_FWDPRI_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_FWDPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_ARP_USAGEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_EXT_DSL_SPAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_DA_BLKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_SA_BLKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_AUTHtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_AGEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_SPAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_SAPRI_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_FIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_EFIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_IVL_SVLtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_L3LOOKUPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_CVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L2_UC_MACtf,
#endif

    APOLLOMP_L2_UCFIELD_LIST_END,
} rtk_apollomp_l2_ucField_list_t;


typedef enum rtk_apollomp_l3_mc_dslField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_NOT_SALEARNtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_FWDPRI_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_FWDPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_EXT_MBRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_MBRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_GIP_ONLYtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_L3LOOKUPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_SIP_VIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_DSL_GIPtf,
#endif

    APOLLOMP_L3_MC_DSLFIELD_LIST_END,
} rtk_apollomp_l3_mc_dslField_list_t;


typedef enum rtk_apollomp_l3_mc_routeField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_NOT_SALEARNtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_FWDPRI_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_FWDPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_EXT_MBRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_MBRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_GIP_ONLYtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_L3LOOKUPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_WAN_SAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_EXT_FRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_L3_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_MC_ROUTE_GIPtf,
#endif

    APOLLOMP_L3_MC_ROUTEFIELD_LIST_END,
} rtk_apollomp_l3_mc_routeField_list_t;


typedef enum rtk_apollomp_vlanField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLAN_EXT_MBRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLAN_IVL_SVLtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLAN_METERIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLAN_POLICINGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLAN_VBPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLAN_VB_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLAN_FID_MSTItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLAN_UNTAGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_VLAN_MBRtf,
#endif

    APOLLOMP_VLANFIELD_LIST_END,
} rtk_apollomp_vlanField_list_t;


typedef enum rtk_apollomp_arp_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ARP_TABLE_NXTHOPIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_ARP_TABLE_VALIDtf,
#endif

    APOLLOMP_ARP_TABLEFIELD_LIST_END,
} rtk_apollomp_arp_tableField_list_t;


typedef enum rtk_apollomp_binding_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_BINDING_TABLE_BIND_PTLtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_BINDING_TABLE_WAN_TYPE_INDEXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_BINDING_TABLE_VID_LANtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_BINDING_TABLE_EXT_PMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_BINDING_TABLE_PORT_MASKtf,
#endif

    APOLLOMP_BINDING_TABLEFIELD_LIST_END,
} rtk_apollomp_binding_tableField_list_t;


typedef enum rtk_apollomp_external_ip_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_EXTERNAL_IP_TABLE_PRIORITYtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_EXTERNAL_IP_TABLE_PRIVALtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_EXTERNAL_IP_TABLE_NH_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_EXTERNAL_IP_TABLE_TYPEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_EXTERNAL_IP_TABLE_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_EXTERNAL_IP_TABLE_EXTIPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_EXTERNAL_IP_TABLE_INTIPtf,
#endif

    APOLLOMP_EXTERNAL_IP_TABLEFIELD_LIST_END,
} rtk_apollomp_external_ip_tableField_list_t;


typedef enum rtk_apollomp_ipv6_routing_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_IPV6_ROUTING_TABLE_RT2WANINFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_IPV6_ROUTING_TABLE_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_IPV6_ROUTING_TABLE_PROCESStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_IPV6_ROUTING_TABLE_NEXTHOPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_IPV6_ROUTING_TABLE_IP6_PREFIX_LENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_IPV6_ROUTING_TABLE_IP6_DIPtf,
#endif

    APOLLOMP_IPV6_ROUTING_TABLEFIELD_LIST_END,
} rtk_apollomp_ipv6_routing_tableField_list_t;


typedef enum rtk_apollomp_l3_routing_drop_trapField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_DROP_TRAP_RT2WANINFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_DROP_TRAP_INTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_DROP_TRAP_PROCESStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_DROP_TRAP_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_DROP_TRAP_MASKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_DROP_TRAP_IPtf,
#endif

    APOLLOMP_L3_ROUTING_DROP_TRAPFIELD_LIST_END,
} rtk_apollomp_l3_routing_drop_trapField_list_t;


typedef enum rtk_apollomp_l3_routing_global_routeField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_RT2WANINFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_IPDOMAINtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_NHALGOtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_NHNXTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_NH_ADDR_STARTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_NH_NUMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_INTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_PROCESStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_MASKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_IPtf,
#endif

    APOLLOMP_L3_ROUTING_GLOBAL_ROUTEFIELD_LIST_END,
} rtk_apollomp_l3_routing_global_routeField_list_t;


typedef enum rtk_apollomp_l3_routing_local_routeField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTE_RT2WANINFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTE_ARPENDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTE_ARPSTAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTE_DENTIFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTE_INTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTE_PROCESStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTE_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTE_MASKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L3_ROUTING_LOCAL_ROUTE_IPtf,
#endif

    APOLLOMP_L3_ROUTING_LOCAL_ROUTEFIELD_LIST_END,
} rtk_apollomp_l3_routing_local_routeField_list_t;


typedef enum rtk_apollomp_napt_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPT_TABLE_PRIORITYtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPT_TABLE_PRI_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPT_TABLE_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPT_TABLE_HASHIN_IDXtf,
#endif

    APOLLOMP_NAPT_TABLEFIELD_LIST_END,
} rtk_apollomp_napt_tableField_list_t;


typedef enum rtk_apollomp_naptr_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLE_PRIORITYtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLE_PRI_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLE_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLE_TCPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLE_EXTPRT_LSBtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLE_EXTIP_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLE_REM_HASHtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLE_INTPORTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NAPTR_TABLE_INTIPtf,
#endif

    APOLLOMP_NAPTR_TABLEFIELD_LIST_END,
} rtk_apollomp_naptr_tableField_list_t;


typedef enum rtk_apollomp_neighbor_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEIGHBOR_TABLE_VALIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEIGHBOR_TABLE_L2_TABLE_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEIGHBOR_TABLE_RT_MATCH_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEIGHBOR_TABLE_IP6IF_IDtf,
#endif

    APOLLOMP_NEIGHBOR_TABLEFIELD_LIST_END,
} rtk_apollomp_neighbor_tableField_list_t;


typedef enum rtk_apollomp_netifField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NETIF_MTUtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NETIF_ENRTRtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NETIF_MACMASKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NETIF_GMACtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NETIF_VLANIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NETIF_VALIDtf,
#endif

    APOLLOMP_NETIFFIELD_LIST_END,
} rtk_apollomp_netifField_list_t;


typedef enum rtk_apollomp_next_hop_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEXT_HOP_TABLE_KEEPPPPOPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEXT_HOP_TABLE_NXTHOPIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEXT_HOP_TABLE_PPPIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEXT_HOP_TABLE_IFIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_NEXT_HOP_TABLE_TYPEtf,
#endif

    APOLLOMP_NEXT_HOP_TABLEFIELD_LIST_END,
} rtk_apollomp_next_hop_tableField_list_t;


typedef enum rtk_apollomp_pppoe_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_PPPOE_TABLE_SESIDtf,
#endif

    APOLLOMP_PPPOE_TABLEFIELD_LIST_END,
} rtk_apollomp_pppoe_tableField_list_t;


typedef enum rtk_apollomp_wan_type_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_WAN_TYPE_TABLE_NXHOPTBIDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_WAN_TYPE_TABLE_WAN_TYPEtf,
#endif

    APOLLOMP_WAN_TYPE_TABLEFIELD_LIST_END,
} rtk_apollomp_wan_type_tableField_list_t;


typedef enum rtk_apollomp_l34_hsaField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_PPPOE_KEEPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_BIND_VIDTRANStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_INTERNAL_VLAN_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_REASONtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_L3L4TRANStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_L2TRANStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_ACTIONtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_L4HP_Vtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_L4HPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_FRAGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_DIFIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_DVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_PPPOE_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_PPPID_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_NEXTHOP_MAC_IDXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_L4_CHECKSUM_OFFSETtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_L3_CHECKSUM_OFFSETtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_PORTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSA_IPtf,
#endif

    APOLLOMP_L34_HSAFIELD_LIST_END,
} rtk_apollomp_l34_hsaField_list_t;


typedef enum rtk_apollomp_l34_hsbField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_IS_FROM_WAN_PORTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_L2BRIDGEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_IPFRAGOFStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_IPMFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_L4CSOKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_L3CSOKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_CPU_DIRECT_TXtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_UDP_NOCStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_PARS_FAILtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_PPPOE_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_SVLAN_TAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_TTLSTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_TYPEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_TCP_FLAG_PROTOCOL_PARSING_FAILURE_REASONtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_CVLAN_TAG_IFtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_SPAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_CVLANIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_LENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_DPORT_L4CHKSUMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_PPPOE_IDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_DIPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_SIPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_SPORT_ICMPID_CHKSUMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_L34_HSB_DMACtf,
#endif

    APOLLOMP_L34_HSBFIELD_LIST_END,
} rtk_apollomp_l34_hsbField_list_t;


typedef enum rtk_apollomp_hsa_debug_dataField_list_e
{
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_RESERVED_02tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_EPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_DSL_VCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_34PPPOEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_34SMACtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_RSV0tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_TTLPMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_TTLEXMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_NEWMACtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_NEWPRTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_NEWIPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L4CKSUMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L3CKSUMtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_PPPOEACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_SRC_MODtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L34TRANStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L2TRANStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_ORGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L3Rtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_RESERVED_01tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_SV_DEItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_STYPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PKTLEN_ORItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_QIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_STDSCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CPUPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_SPRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CORItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CMDYtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CRMStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CINStf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_RSV1tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CFItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PTPNSECtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PTPSECtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PTPACTtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REGENCRCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PPPOEtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_RFC1042tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_IPV6tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_IPV4tf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PTPtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REMDSCP_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REM1Q_PRItf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REMDSCP_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REM1Q_ENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_SVIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_INSTAGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_INCTAGtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PKTLENtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_SPAtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_DPCtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_EXTMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_VCMSKtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PONSIDtf,
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    APOLLOMP_HSA_DEBUG_DATA_TXHSA0_TRPRSNtf,
#endif

    APOLLOMP_HSA_DEBUG_DATAFIELD_LIST_END,
} rtk_apollomp_hsa_debug_dataField_list_t;

extern rtk_table_t rtk_apollomp_table_list[];


#endif    /* __RTK_APOLLOMP_TABLE_STRUCT_H__ */
