/*!
*  \brief   Loads IRAM binary data into Patch RAM
*
*           This file has been generated by means of the iram2hex.pl tool
*
*******************************************************************************
*
*  COPYRIGHT DOSCH & AMAND RESEARCH GMBH & CO.KG
*  DOSCH & AMAND RESEARCH GMBH & CO.KG Confidential
*
*******************************************************************************/

#include "tclib.h"
#include "embedded.h"

/* begin binary data: */
const char bin_data[] = /* 24 */
{0xA3,0x00,0xF5,0xEA,0x7F,0x00,0xF5,0xEA,0xA5,0x00,0xF5,0xEA,0xA8,0x00,0xF5,0xEA
,0xBE,0x00,0xF5,0xEA,0xC1,0xFF,0xF4,0xEA};
/* end of binary data. size = 24 bytes */

#define PRAM_START_ADDR 0x00300300

#define pPatchRam ((volatile u8*)PRAM_START_ADDR)

void              cmbs_PatchRAMLoad( void )
{
   int   i;

   for( i = 0; i < sizeof(bin_data); i++ )
   {
      pPatchRam[i] = bin_data[i];
   }
}
