/* confdefs.h */
#define PACKAGE_NAME "usbutils"
#define PACKAGE_TARNAME "usbutils"
#define PACKAGE_VERSION "003"
#define PACKAGE_STRING "usbutils 003"
#define PACKAGE_BUGREPORT "linux-usb@vger.kernel.org"
#define PACKAGE_URL ""
#define PACKAGE "usbutils"
#define VERSION "003"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _GNU_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define HAVE_BYTESWAP_H 1
