EXTRA_CFLAGS += -DCHIP_RTL8367RB
obj-y += port.o

obj-y += \
	rtk_api.o \
	rtl8367b_asicdrv_acl.o \
	rtl8367b_asicdrv.o \
	rtl8367b_asicdrv_cputag.o \
	rtl8367b_asicdrv_dot1x.o \
	rtl8367b_asicdrv_eav.o \
	rtl8367b_asicdrv_eee.o \
	rtl8367b_asicdrv_eeelldp.o \
	rtl8367b_asicdrv_fc.o \
	rtl8367b_asicdrv_green.o \
	rtl8367b_asicdrv_hsb.o \
	rtl8367b_asicdrv_igmp.o \
	rtl8367b_asicdrv_inbwctrl.o \
	rtl8367b_asicdrv_interrupt.o \
	rtl8367b_asicdrv_led.o \
	rtl8367b_asicdrv_lut.o \
	rtl8367b_asicdrv_meter.o \
	rtl8367b_asicdrv_mib.o \
	rtl8367b_asicdrv_mirror.o \
	rtl8367b_asicdrv_misc.o \
	rtl8367b_asicdrv_oam.o \
	rtl8367b_asicdrv_phy.o \
	rtl8367b_asicdrv_port.o \
	rtl8367b_asicdrv_portIsolation.o \
	rtl8367b_asicdrv_qos.o \
	rtl8367b_asicdrv_rldp.o \
	rtl8367b_asicdrv_rma.o \
	rtl8367b_asicdrv_rrcp.o \
	rtl8367b_asicdrv_scheduling.o \
	rtl8367b_asicdrv_specialCongest.o \
	rtl8367b_asicdrv_storm.o \
	rtl8367b_asicdrv_svlan.o \
	rtl8367b_asicdrv_trunking.o \
	rtl8367b_asicdrv_unknownMulticast.o \
	rtl8367b_asicdrv_vlan.o \
	smi.o

EXTRA_CFLAGS += -I$(DIR_LINUX)/drivers/net/rtl8367b
