/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 39101 $
 * $Date: 2013-05-03 17:35:27 +0800 (Fri, 03 May 2013) $
 *
 * Purpose : chip table declaration in the SDK.
 *
 * Feature : chip table declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/apollomp/rtk_apollomp_table_struct.h>
#include <hal/chipdef/apollomp/rtk_apollomp_tableField_list.h>

rtk_table_t rtk_apollomp_table_list[] =
{
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_HSB_DATA_TABLE */
        /* access table type */     0,
        /* table size */            1,
        /* total data registers */  20,
        /* total field numbers */   APOLLOMP_HSB_DATA_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_HSB_DATA_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_HSA_DATA_NAT */
        /* access table type */     0,
        /* table size */            1,
        /* total data registers */  13,
        /* total field numbers */   APOLLOMP_HSA_DATA_NATFIELD_LIST_END,
        /* table fields */          APOLLOMP_HSA_DATA_NAT_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_HSA_DATA_TABLE */
        /* access table type */     0,
        /* table size */            1,
        /* total data registers */  13,
        /* total field numbers */   APOLLOMP_HSA_DATA_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_HSA_DATA_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_ACL_ACTION_TABLE */
        /* access table type */     3,
        /* table size */            128,
        /* total data registers */  2,
        /* total field numbers */   APOLLOMP_ACL_ACTION_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_ACL_ACTION_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_ACL_DATA */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_ACL_DATAFIELD_LIST_END,
        /* table fields */          APOLLOMP_ACL_DATA_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_ACL_DATA2 */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_ACL_DATA2FIELD_LIST_END,
        /* table fields */          APOLLOMP_ACL_DATA2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_ACL_MASK */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_ACL_MASKFIELD_LIST_END,
        /* table fields */          APOLLOMP_ACL_MASK_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_ACL_MASK2 */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_ACL_MASK2FIELD_LIST_END,
        /* table fields */          APOLLOMP_ACL_MASK2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_CF_ACTION_DS */
        /* access table type */     5,
        /* table size */            512,
        /* total data registers */  2,
        /* total field numbers */   APOLLOMP_CF_ACTION_DSFIELD_LIST_END,
        /* table fields */          APOLLOMP_CF_ACTION_DS_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_CF_ACTION_US */
        /* access table type */     5,
        /* table size */            512,
        /* total data registers */  2,
        /* total field numbers */   APOLLOMP_CF_ACTION_USFIELD_LIST_END,
        /* table fields */          APOLLOMP_CF_ACTION_US_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_CF_MASK */
        /* access table type */     4,
        /* table size */            128,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_CF_MASKFIELD_LIST_END,
        /* table fields */          APOLLOMP_CF_MASK_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_CF_MASK_L34 */
        /* access table type */     4,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_CF_MASK_L34FIELD_LIST_END,
        /* table fields */          APOLLOMP_CF_MASK_L34_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_CF_RULE */
        /* access table type */     4,
        /* table size */            128,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_CF_RULEFIELD_LIST_END,
        /* table fields */          APOLLOMP_CF_RULE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_CF_RULE_L34 */
        /* access table type */     4,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_CF_RULE_L34FIELD_LIST_END,
        /* table fields */          APOLLOMP_CF_RULE_L34_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_L2_MC_DSL */
        /* access table type */     0,
        /* table size */            2112,
        /* total data registers */  4,
        /* total field numbers */   APOLLOMP_L2_MC_DSLFIELD_LIST_END,
        /* table fields */          APOLLOMP_L2_MC_DSL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_L2_UC */
        /* access table type */     0,
        /* table size */            2112,
        /* total data registers */  4,
        /* total field numbers */   APOLLOMP_L2_UCFIELD_LIST_END,
        /* table fields */          APOLLOMP_L2_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_L3_MC_DSL */
        /* access table type */     0,
        /* table size */            2112,
        /* total data registers */  4,
        /* total field numbers */   APOLLOMP_L3_MC_DSLFIELD_LIST_END,
        /* table fields */          APOLLOMP_L3_MC_DSL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_L3_MC_ROUTE */
        /* access table type */     0,
        /* table size */            2112,
        /* total data registers */  4,
        /* total field numbers */   APOLLOMP_L3_MC_ROUTEFIELD_LIST_END,
        /* table fields */          APOLLOMP_L3_MC_ROUTE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_VLAN */
        /* access table type */     1,
        /* table size */            4096,
        /* total data registers */  2,
        /* total field numbers */   APOLLOMP_VLANFIELD_LIST_END,
        /* table fields */          APOLLOMP_VLAN_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_ARP_TABLE */
        /* access table type */     8,
        /* table size */            512,
        /* total data registers */  1,
        /* total field numbers */   APOLLOMP_ARP_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_ARP_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_BINDING_TABLE */
        /* access table type */     6,
        /* table size */            32,
        /* total data registers */  1,
        /* total field numbers */   APOLLOMP_BINDING_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_BINDING_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_EXTERNAL_IP_TABLE */
        /* access table type */     4,
        /* table size */            8,
        /* total data registers */  3,
        /* total field numbers */   APOLLOMP_EXTERNAL_IP_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_EXTERNAL_IP_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_IPV6_ROUTING_TABLE */
        /* access table type */     5,
        /* table size */            4,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_IPV6_ROUTING_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_IPV6_ROUTING_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_L3_ROUTING_DROP_TRAP */
        /* access table type */     0,
        /* table size */            8,
        /* total data registers */  2,
        /* total field numbers */   APOLLOMP_L3_ROUTING_DROP_TRAPFIELD_LIST_END,
        /* table fields */          APOLLOMP_L3_ROUTING_DROP_TRAP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_L3_ROUTING_GLOBAL_ROUTE */
        /* access table type */     0,
        /* table size */            8,
        /* total data registers */  2,
        /* total field numbers */   APOLLOMP_L3_ROUTING_GLOBAL_ROUTEFIELD_LIST_END,
        /* table fields */          APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_L3_ROUTING_LOCAL_ROUTE */
        /* access table type */     0,
        /* table size */            8,
        /* total data registers */  2,
        /* total field numbers */   APOLLOMP_L3_ROUTING_LOCAL_ROUTEFIELD_LIST_END,
        /* table fields */          APOLLOMP_L3_ROUTING_LOCAL_ROUTE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_NAPT_TABLE */
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  1,
        /* total field numbers */   APOLLOMP_NAPT_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_NAPT_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_NAPTR_TABLE */
        /* access table type */     9,
        /* table size */            1024,
        /* total data registers */  3,
        /* total field numbers */   APOLLOMP_NAPTR_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_NAPTR_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_NEIGHBOR_TABLE */
        /* access table type */     11,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   APOLLOMP_NEIGHBOR_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_NEIGHBOR_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_NETIF */
        /* access table type */     3,
        /* table size */            8,
        /* total data registers */  3,
        /* total field numbers */   APOLLOMP_NETIFFIELD_LIST_END,
        /* table fields */          APOLLOMP_NETIF_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_NEXT_HOP_TABLE */
        /* access table type */     2,
        /* table size */            16,
        /* total data registers */  1,
        /* total field numbers */   APOLLOMP_NEXT_HOP_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_NEXT_HOP_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_PPPOE_TABLE */
        /* access table type */     1,
        /* table size */            8,
        /* total data registers */  1,
        /* total field numbers */   APOLLOMP_PPPOE_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_PPPOE_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_WAN_TYPE_TABLE */
        /* access table type */     7,
        /* table size */            8,
        /* total data registers */  1,
        /* total field numbers */   APOLLOMP_WAN_TYPE_TABLEFIELD_LIST_END,
        /* table fields */          APOLLOMP_WAN_TYPE_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_L34_HSA */
        /* access table type */     0,
        /* table size */            1,
        /* total data registers */  5,
        /* total field numbers */   APOLLOMP_L34_HSAFIELD_LIST_END,
        /* table fields */          APOLLOMP_L34_HSA_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_L34_HSB */
        /* access table type */     0,
        /* table size */            1,
        /* total data registers */  10,
        /* total field numbers */   APOLLOMP_L34_HSBFIELD_LIST_END,
        /* table fields */          APOLLOMP_L34_HSB_FIELDS
    },
#endif
#if defined(CONFIG_SDK_APOLLOMP)
    {   /* table name               INT_APOLLOMP_APOLLOMP_HSA_DEBUG_DATA */
        /* access table type */     0,
        /* table size */            1,
        /* total data registers */  16,
        /* total field numbers */   APOLLOMP_HSA_DEBUG_DATAFIELD_LIST_END,
        /* table fields */          APOLLOMP_HSA_DEBUG_DATA_FIELDS
    },
#endif
};

