/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 39101 $
 * $Date: 2013-05-03 17:35:27 +0800 (Fri, 03 May 2013) $
 *
 * Purpose : chip table field declaration in the SDK.
 *
 * Feature : chip table field declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/apollomp/rtk_apollomp_table_struct.h>

#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_HSB_DATA_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_HSB_DATA_TABLE_SPAtf */
        /* lsp */   586,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_15tf */
        /* lsp */   570,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_14tf */
        /* lsp */   554,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_13tf */
        /* lsp */   538,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_12tf */
        /* lsp */   522,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_11tf */
        /* lsp */   506,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_10tf */
        /* lsp */   490,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_9tf */
        /* lsp */   474,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_8tf */
        /* lsp */   458,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_7tf */
        /* lsp */   442,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_6tf */
        /* lsp */   426,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_5tf */
        /* lsp */   410,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_4tf */
        /* lsp */   394,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_3tf */
        /* lsp */   378,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_2tf */
        /* lsp */   362,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_1tf */
        /* lsp */   346,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_FIELD_0tf */
        /* lsp */   330,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_USER_VALIDtf */
        /* lsp */   314,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_IP6_HN_RGtf */
        /* lsp */   313,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CKS_OK_L4tf */
        /* lsp */   312,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CKS_OK_L3tf */
        /* lsp */   311,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_TTL_GT1tf */
        /* lsp */   310,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_TTL_GT5tf */
        /* lsp */   309,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_GRE_IFtf */
        /* lsp */   308,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_ICMP_IFtf */
        /* lsp */   307,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_UDP_IFtf */
        /* lsp */   306,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_TCP_IFtf */
        /* lsp */   305,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_PPPOE_SESSIONtf */
        /* lsp */   289,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_DIPtf */
        /* lsp */   257,
        /* len */   32,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_SIPtf */
        /* lsp */   225,
        /* len */   32,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_TOS_DSCPtf */
        /* lsp */   217,
        /* len */   8,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_IP_TYPEtf */
        /* lsp */   215,
        /* len */   2,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_PTP_IFtf */
        /* lsp */   214,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_OMAPDUtf */
        /* lsp */   213,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_RLPP_IFtf */
        /* lsp */   212,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_RLDP_IFtf */
        /* lsp */   211,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_LLC_OTHERtf */
        /* lsp */   210,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_PPPOE_IFtf */
        /* lsp */   209,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_SNAP_IFtf */
        /* lsp */   208,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_ETHER_TYPEtf */
        /* lsp */   192,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CTAGtf */
        /* lsp */   176,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CTAG_IFtf */
        /* lsp */   175,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_STAGtf */
        /* lsp */   159,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_STAG_IFtf */
        /* lsp */   158,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_L3Ctf */
        /* lsp */   157,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_L4Ctf */
        /* lsp */   156,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_TXPMSKtf */
        /* lsp */   150,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_EFID_ENtf */
        /* lsp */   149,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_EFIDtf */
        /* lsp */   146,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_PRISELtf */
        /* lsp */   145,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_PRItf */
        /* lsp */   142,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_KEEPtf */
        /* lsp */   141,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_VSELtf */
        /* lsp */   140,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_DISLRNtf */
        /* lsp */   139,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_PSELtf */
        /* lsp */   138,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_L34KEEPtf */
        /* lsp */   135,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_EXTSPAtf */
        /* lsp */   131,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_PPPOE_ACTtf */
        /* lsp */   129,
        /* len */   2,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_PPPOE_IDXtf */
        /* lsp */   126,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_L2BRtf */
        /* lsp */   125,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_PON_SIDtf */
        /* lsp */   118,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_CPUTAG_IFtf */
        /* lsp */   117,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_SAtf */
        /* lsp */   69,
        /* len */   48,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_DAtf */
        /* lsp */   21,
        /* len */   48,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_PON_IDXtf */
        /* lsp */   14,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSB_DATA_TABLE_PKT_LENtf */
        /* lsp */   0,
        /* len */   14,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_HSA_DATA_NAT_FIELDS[] = 
{
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_ENDSCtf */
        /* lsp */   402,
        /* len */   13,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_BGDSCtf */
        /* lsp */   389,
        /* len */   13,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_QIDtf */
        /* lsp */   364,
        /* len */   25,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_FLOODPKTtf */
        /* lsp */   363,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_RESERVEtf */
        /* lsp */   353,
        /* len */   10,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_CPUPRItf */
        /* lsp */   350,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_FWDRSNtf */
        /* lsp */   342,
        /* len */   8,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_PON_SIDtf */
        /* lsp */   335,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_EXT_MASKtf */
        /* lsp */   329,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_DPMtf */
        /* lsp */   315,
        /* len */   14,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_SPAtf */
        /* lsp */   312,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAB_PKTLENtf */
        /* lsp */   298,
        /* len */   14,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_UNTAGSETtf */
        /* lsp */   291,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_CTAG_PONACTtf */
        /* lsp */   287,
        /* len */   4,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_CTAG_ACTtf */
        /* lsp */   283,
        /* len */   4,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_VIDZEROtf */
        /* lsp */   282,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_PRITAG_IFtf */
        /* lsp */   281,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_CTAG_IFtf */
        /* lsp */   280,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_PONVIDtf */
        /* lsp */   268,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_VIDtf */
        /* lsp */   256,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_CFItf */
        /* lsp */   255,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_PONPRItf */
        /* lsp */   252,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAC_PRItf */
        /* lsp */   249,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_STAG_IFtf */
        /* lsp */   248,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_DEItf */
        /* lsp */   247,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_UNTAGSETtf */
        /* lsp */   240,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_STAG_TYPEtf */
        /* lsp */   239,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_SP2Stf */
        /* lsp */   238,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_VIDSELtf */
        /* lsp */   237,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_FRCTAGtf */
        /* lsp */   236,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_FRCTAG_IFtf */
        /* lsp */   235,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_PONSVIDtf */
        /* lsp */   223,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_SVIDtf */
        /* lsp */   211,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_SVIDXtf */
        /* lsp */   205,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_PKT_SPRItf */
        /* lsp */   202,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_PONSPRItf */
        /* lsp */   199,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAS_SPRItf */
        /* lsp */   196,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_USER_PRItf */
        /* lsp */   175,
        /* len */   21,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_1P_REMtf */
        /* lsp */   172,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_1P_REM_ENtf */
        /* lsp */   171,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_DSCP_REMtf */
        /* lsp */   165,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAM_DSCP_REM_ENtf */
        /* lsp */   164,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_REGEN_CRCtf */
        /* lsp */   163,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_CPUKEEPtf */
        /* lsp */   162,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_KEEPtf */
        /* lsp */   161,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_PTPtf */
        /* lsp */   160,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_TCPtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_UDPtf */
        /* lsp */   158,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_IPV4tf */
        /* lsp */   157,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_IPV6tf */
        /* lsp */   156,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_RFC1042tf */
        /* lsp */   155,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAF_PPPOE_IFtf */
        /* lsp */   154,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L3Rtf */
        /* lsp */   153,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_ORGtf */
        /* lsp */   152,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_IPMCtf */
        /* lsp */   151,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L2TRANStf */
        /* lsp */   150,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L34TRANStf */
        /* lsp */   149,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_SRC_MODtf */
        /* lsp */   148,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_PPPOE_IDXtf */
        /* lsp */   145,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_PPPOE_ACTtf */
        /* lsp */   143,
        /* len */   2,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_SMAC_IDXtf */
        /* lsp */   140,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L3CKSUMtf */
        /* lsp */   124,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_L4CKSUMtf */
        /* lsp */   108,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_NEWIPtf */
        /* lsp */   76,
        /* len */   32,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_NEWPORTtf */
        /* lsp */   60,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_NEWDMACtf */
        /* lsp */   12,
        /* len */   48,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_TTLM1_EXTMASKtf */
        /* lsp */   7,
        /* len */   5,
    },
    {   /* name     APOLLOMP_HSA_DATA_NAT_RNG_NHSAN_TTLM1_PMASKtf */
        /* lsp */   0,
        /* len */   7,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_HSA_DATA_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_ENDSCtf */
        /* lsp */   402,
        /* len */   13,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_BGDSCtf */
        /* lsp */   389,
        /* len */   13,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_QIDtf */
        /* lsp */   364,
        /* len */   25,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_FLOODPKTtf */
        /* lsp */   363,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_RESERVEtf */
        /* lsp */   353,
        /* len */   10,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_CPUPRItf */
        /* lsp */   350,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_FWDRSNtf */
        /* lsp */   342,
        /* len */   8,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_PON_SIDtf */
        /* lsp */   335,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_EXT_MASKtf */
        /* lsp */   329,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_DPMtf */
        /* lsp */   315,
        /* len */   14,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_SPAtf */
        /* lsp */   312,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAB_PKTLENtf */
        /* lsp */   298,
        /* len */   14,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_UNTAGSETtf */
        /* lsp */   291,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_CTAG_PONACTtf */
        /* lsp */   287,
        /* len */   4,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_CTAG_ACTtf */
        /* lsp */   283,
        /* len */   4,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_VIDZEROtf */
        /* lsp */   282,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_PRITAG_IFtf */
        /* lsp */   281,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_CTAG_IFtf */
        /* lsp */   280,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_PONVIDtf */
        /* lsp */   268,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_VIDtf */
        /* lsp */   256,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_CFItf */
        /* lsp */   255,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_PONPRItf */
        /* lsp */   252,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAC_PRItf */
        /* lsp */   249,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_STAG_IFtf */
        /* lsp */   248,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_DEItf */
        /* lsp */   247,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_UNTAGSETtf */
        /* lsp */   240,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_STAG_TYPEtf */
        /* lsp */   239,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_SP2Stf */
        /* lsp */   238,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_VIDSELtf */
        /* lsp */   237,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_FRCTAGtf */
        /* lsp */   236,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_FRCTAG_IFtf */
        /* lsp */   235,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_PONSVIDtf */
        /* lsp */   223,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_SVIDtf */
        /* lsp */   211,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_SVIDXtf */
        /* lsp */   205,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_PKT_SPRItf */
        /* lsp */   202,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_PONSPRItf */
        /* lsp */   199,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAS_SPRItf */
        /* lsp */   196,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_USER_PRItf */
        /* lsp */   175,
        /* len */   21,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_1P_REMtf */
        /* lsp */   172,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_1P_REM_ENtf */
        /* lsp */   171,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_DSCP_REMtf */
        /* lsp */   165,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAM_DSCP_REM_ENtf */
        /* lsp */   164,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_REGEN_CRCtf */
        /* lsp */   163,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_CPUKEEPtf */
        /* lsp */   162,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_KEEPtf */
        /* lsp */   161,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_PTPtf */
        /* lsp */   160,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_TCPtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_UDPtf */
        /* lsp */   158,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_IPV4tf */
        /* lsp */   157,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_IPV6tf */
        /* lsp */   156,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_RFC1042tf */
        /* lsp */   155,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAF_PPPOE_IFtf */
        /* lsp */   154,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_RESVtf */
        /* lsp */   89,
        /* len */   65,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_IDtf */
        /* lsp */   82,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_ACTtf */
        /* lsp */   80,
        /* len */   2,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_SECtf */
        /* lsp */   32,
        /* len */   48,
    },
    {   /* name     APOLLOMP_HSA_DATA_TABLE_RNG_NHSAP_PTP_NSECtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_ACL_ACTION_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_HITtf */
        /* lsp */   51,
        /* len */   1,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_CFACTtf */
        /* lsp */   49,
        /* len */   2,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_CFIDXtf */
        /* lsp */   42,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_ACLINTtf */
        /* lsp */   41,
        /* len */   1,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_PRIACTtf */
        /* lsp */   38,
        /* len */   3,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_PRIDXtf */
        /* lsp */   32,
        /* len */   6,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_FWDACTtf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_FWD_PMSKtf */
        /* lsp */   23,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_POLICACTtf */
        /* lsp */   22,
        /* len */   1,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_METER_IDXtf */
        /* lsp */   17,
        /* len */   5,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_SACTtf */
        /* lsp */   14,
        /* len */   3,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_SVIDXtf */
        /* lsp */   8,
        /* len */   6,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_CACTtf */
        /* lsp */   5,
        /* len */   3,
    },
    {   /* name     APOLLOMP_ACL_ACTION_TABLE_CVIDXtf */
        /* lsp */   0,
        /* len */   5,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_ACL_DATA_FIELDS[] = 
{
    {   /* name     APOLLOMP_ACL_DATA_VALIDtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     APOLLOMP_ACL_DATA_FIELD7tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA_FIELD6tf */
        /* lsp */   112,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA_FIELD5tf */
        /* lsp */   96,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA_FIELD4tf */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA_FIELD3tf */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA_FIELD2tf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA_FIELD1tf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA_FIELD0tf */
        /* lsp */   16,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA_PMSKtf */
        /* lsp */   9,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_DATA_TAGStf */
        /* lsp */   2,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_DATA_TYPEtf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_ACL_DATA2_FIELDS[] = 
{
    {   /* name     APOLLOMP_ACL_DATA2_VALIDtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     APOLLOMP_ACL_DATA2_FIELD3_0tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA2_FIELD2_0tf */
        /* lsp */   112,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA2_FIELD1_0tf */
        /* lsp */   96,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA2_FIELD0_0tf */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA2_PMSK_0tf */
        /* lsp */   73,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_DATA2_TAGS_0tf */
        /* lsp */   66,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_DATA2_TYPE_0tf */
        /* lsp */   64,
        /* len */   2,
    },
    {   /* name     APOLLOMP_ACL_DATA2_FIELD2_1tf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA2_FIELD1_1tf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA2_FIELD0_1tf */
        /* lsp */   16,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_DATA2_PMSK_1tf */
        /* lsp */   9,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_DATA2_TAGS_1tf */
        /* lsp */   2,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_DATA2_TYPE_1tf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_ACL_MASK_FIELDS[] = 
{
    {   /* name     APOLLOMP_ACL_MASK_FIELD7tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK_FIELD6tf */
        /* lsp */   112,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK_FIELD5tf */
        /* lsp */   96,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK_FIELD4tf */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK_FIELD3tf */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK_FIELD2tf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK_FIELD1tf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK_FIELD0tf */
        /* lsp */   16,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK_PMSKtf */
        /* lsp */   9,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_MASK_TAGStf */
        /* lsp */   2,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_MASK_TYPEtf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_ACL_MASK2_FIELDS[] = 
{
    {   /* name     APOLLOMP_ACL_MASK2_FIELD3_0tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK2_FIELD2_0tf */
        /* lsp */   112,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK2_FIELD1_0tf */
        /* lsp */   96,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK2_FIELD0_0tf */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK2_PMSK_0tf */
        /* lsp */   73,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_MASK2_TAGS_0tf */
        /* lsp */   66,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_MASK2_TYPE_0tf */
        /* lsp */   64,
        /* len */   2,
    },
    {   /* name     APOLLOMP_ACL_MASK2_FIELD2_1tf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK2_FIELD1_1tf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK2_FIELD0_1tf */
        /* lsp */   16,
        /* len */   16,
    },
    {   /* name     APOLLOMP_ACL_MASK2_PMSK_1tf */
        /* lsp */   9,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_MASK2_TAGS_1tf */
        /* lsp */   2,
        /* len */   7,
    },
    {   /* name     APOLLOMP_ACL_MASK2_TYPE_1tf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_CF_ACTION_DS_FIELDS[] = 
{
    {   /* name     APOLLOMP_CF_ACTION_DS_UNI_PMSKtf */
        /* lsp */   51,
        /* len */   7,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_UNI_ACTtf */
        /* lsp */   49,
        /* len */   2,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_DSCP_REMARKtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CF_PRItf */
        /* lsp */   45,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CFPRI_ACTtf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CPRI_ACTtf */
        /* lsp */   42,
        /* len */   2,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CVID_ACTtf */
        /* lsp */   40,
        /* len */   2,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_C_PRItf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_C_VIDtf */
        /* lsp */   25,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CSPRI_ACTtf */
        /* lsp */   23,
        /* len */   2,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CSVID_ACTtf */
        /* lsp */   21,
        /* len */   2,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CS_PRItf */
        /* lsp */   18,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CS_VIDtf */
        /* lsp */   6,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CACTtf */
        /* lsp */   3,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_ACTION_DS_CSACTtf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_CF_ACTION_US_FIELDS[] = 
{
    {   /* name     APOLLOMP_CF_ACTION_US_COUNTER_IDXtf */
        /* lsp */   59,
        /* len */   5,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_LOGtf */
        /* lsp */   58,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_DROPtf */
        /* lsp */   57,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_ASSIGN_IDXtf */
        /* lsp */   50,
        /* len */   7,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_SID_ACTtf */
        /* lsp */   49,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_DSCP_REMARKtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CF_PRItf */
        /* lsp */   45,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CFPRI_ACTtf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CPRI_ACTtf */
        /* lsp */   42,
        /* len */   2,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CVID_ACTtf */
        /* lsp */   40,
        /* len */   2,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_C_PRItf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_C_VIDtf */
        /* lsp */   25,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CSPRI_ACTtf */
        /* lsp */   23,
        /* len */   2,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CSVID_ACTtf */
        /* lsp */   21,
        /* len */   2,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CS_PRItf */
        /* lsp */   18,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CS_VIDtf */
        /* lsp */   6,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CACTtf */
        /* lsp */   3,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_ACTION_US_CSACTtf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_CF_MASK_FIELDS[] = 
{
    {   /* name     APOLLOMP_CF_MASK_ETH_TYPE_0tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     APOLLOMP_CF_MASK_U_D_0tf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_TOS_GEMIDX_0tf */
        /* lsp */   119,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_MASK_VID_0tf */
        /* lsp */   107,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_MASK_PRI_0tf */
        /* lsp */   104,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_INTER_PRI_0tf */
        /* lsp */   101,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_IF_STAG_0tf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_IF_CTAG_0tf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_UNI_0tf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_U_D_1tf */
        /* lsp */   95,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_TOS_GEMIDX_1tf */
        /* lsp */   87,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_MASK_VID_1tf */
        /* lsp */   75,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_MASK_PRI_1tf */
        /* lsp */   72,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_INTER_PRI_1tf */
        /* lsp */   69,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_IF_STAG_1tf */
        /* lsp */   68,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_IF_CTAG_1tf */
        /* lsp */   67,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_UNI_1tf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_U_D_2tf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_TOS_GEMIDX_2tf */
        /* lsp */   55,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_MASK_VID_2tf */
        /* lsp */   43,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_MASK_PRI_2tf */
        /* lsp */   40,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_INTER_PRI_2tf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_IF_STAG_2tf */
        /* lsp */   36,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_IF_CTAG_2tf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_UNI_2tf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_U_D_3tf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_TOS_GEMIDX_3tf */
        /* lsp */   23,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_MASK_VID_3tf */
        /* lsp */   11,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_MASK_PRI_3tf */
        /* lsp */   8,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_INTER_PRI_3tf */
        /* lsp */   5,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_IF_STAG_3tf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_IF_CTAG_3tf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_UNI_3tf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_CF_MASK_L34_FIELDS[] = 
{
    {   /* name     APOLLOMP_CF_MASK_L34_VALIDtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_PORT_RNG_CHK_0tf */
        /* lsp */   140,
        /* len */   4,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IP_RNG_CHK_0tf */
        /* lsp */   136,
        /* len */   4,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_ACL_HIT_0tf */
        /* lsp */   128,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_U_D_0tf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_WAN_IF_0tf */
        /* lsp */   124,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IP6_MCtf */
        /* lsp */   123,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IP4_MCtf */
        /* lsp */   122,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_MLDtf */
        /* lsp */   121,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IGMPtf */
        /* lsp */   120,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_DEItf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_VID_0tf */
        /* lsp */   107,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_PRI_0tf */
        /* lsp */   104,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_INTER_PRI_0tf */
        /* lsp */   101,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IF_STAG_0tf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IF_CTAG_0tf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_UNI_0tf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_U_D_1tf */
        /* lsp */   95,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_TOS_GEMIDX_1tf */
        /* lsp */   87,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_VID_1tf */
        /* lsp */   75,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_PRI_1tf */
        /* lsp */   72,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_INTER_PRI_1tf */
        /* lsp */   69,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IF_STAG_1tf */
        /* lsp */   68,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IF_CTAG_1tf */
        /* lsp */   67,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_UNI_1tf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_U_D_2tf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_TOS_GEMIDX_2tf */
        /* lsp */   55,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_VID_2tf */
        /* lsp */   43,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_PRI_2tf */
        /* lsp */   40,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_INTER_PRI_2tf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IF_STAG_2tf */
        /* lsp */   36,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IF_CTAG_2tf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_UNI_2tf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_U_D_3tf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_TOS_GEMIDX_3tf */
        /* lsp */   23,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_VID_3tf */
        /* lsp */   11,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_PRI_3tf */
        /* lsp */   8,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_INTER_PRI_3tf */
        /* lsp */   5,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IF_STAG_3tf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_IF_CTAG_3tf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_MASK_L34_UNI_3tf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_CF_RULE_FIELDS[] = 
{
    {   /* name     APOLLOMP_CF_RULE_VALIDtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_ETH_TYPE_0tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     APOLLOMP_CF_RULE_U_D_0tf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_TOS_GEMIDX_0tf */
        /* lsp */   119,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_RULE_VID_0tf */
        /* lsp */   107,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_RULE_PRI_0tf */
        /* lsp */   104,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_INTER_PRI_0tf */
        /* lsp */   101,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_IF_STAG_0tf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_IF_CTAG_0tf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_UNI_0tf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_U_D_1tf */
        /* lsp */   95,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_TOS_GEMIDX_1tf */
        /* lsp */   87,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_RULE_VID_1tf */
        /* lsp */   75,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_RULE_PRI_1tf */
        /* lsp */   72,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_INTER_PRI_1tf */
        /* lsp */   69,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_IF_STAG_1tf */
        /* lsp */   68,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_IF_CTAG_1tf */
        /* lsp */   67,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_UNI_1tf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_U_D_2tf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_TOS_GEMIDX_2tf */
        /* lsp */   55,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_RULE_VID_2tf */
        /* lsp */   43,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_RULE_PRI_2tf */
        /* lsp */   40,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_INTER_PRI_2tf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_IF_STAG_2tf */
        /* lsp */   36,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_IF_CTAG_2tf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_UNI_2tf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_U_D_3tf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_TOS_GEMIDX_3tf */
        /* lsp */   23,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_RULE_VID_3tf */
        /* lsp */   11,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_RULE_PRI_3tf */
        /* lsp */   8,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_INTER_PRI_3tf */
        /* lsp */   5,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_IF_STAG_3tf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_IF_CTAG_3tf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_UNI_3tf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_CF_RULE_L34_FIELDS[] = 
{
    {   /* name     APOLLOMP_CF_RULE_L34_VALIDtf */
        /* lsp */   144,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_PORT_RNG_CHK_0tf */
        /* lsp */   140,
        /* len */   4,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IP_RNG_CHK_0tf */
        /* lsp */   136,
        /* len */   4,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_ACL_HIT_0tf */
        /* lsp */   128,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_U_D_0tf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_WAN_IF_0tf */
        /* lsp */   124,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IP6_MCtf */
        /* lsp */   123,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IP4_MCtf */
        /* lsp */   122,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_MLDtf */
        /* lsp */   121,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IGMPtf */
        /* lsp */   120,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_DEItf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_VID_0tf */
        /* lsp */   107,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_PRI_0tf */
        /* lsp */   104,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_INTER_PRI_0tf */
        /* lsp */   101,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IF_STAG_0tf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IF_CTAG_0tf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_UNI_0tf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_U_D_1tf */
        /* lsp */   95,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_TOS_GEMIDX_1tf */
        /* lsp */   87,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_VID_1tf */
        /* lsp */   75,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_PRI_1tf */
        /* lsp */   72,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_INTER_PRI_1tf */
        /* lsp */   69,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IF_STAG_1tf */
        /* lsp */   68,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IF_CTAG_1tf */
        /* lsp */   67,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_UNI_1tf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_U_D_2tf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_TOS_GEMIDX_2tf */
        /* lsp */   55,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_VID_2tf */
        /* lsp */   43,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_PRI_2tf */
        /* lsp */   40,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_INTER_PRI_2tf */
        /* lsp */   37,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IF_STAG_2tf */
        /* lsp */   36,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IF_CTAG_2tf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_UNI_2tf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_U_D_3tf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_TOS_GEMIDX_3tf */
        /* lsp */   23,
        /* len */   8,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_VID_3tf */
        /* lsp */   11,
        /* len */   12,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_PRI_3tf */
        /* lsp */   8,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_INTER_PRI_3tf */
        /* lsp */   5,
        /* len */   3,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IF_STAG_3tf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_IF_CTAG_3tf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     APOLLOMP_CF_RULE_L34_UNI_3tf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_L2_MC_DSL_FIELDS[] = 
{
    {   /* name     APOLLOMP_L2_MC_DSL_VALIDtf */
        /* lsp */   88,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_MC_DSL_NOT_SALEARNtf */
        /* lsp */   87,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_MC_DSL_FWDPRI_ENtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_MC_DSL_FWDPRItf */
        /* lsp */   83,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L2_MC_DSL_EXT_MBRtf */
        /* lsp */   77,
        /* len */   6,
    },
    {   /* name     APOLLOMP_L2_MC_DSL_MBRtf */
        /* lsp */   70,
        /* len */   7,
    },
    {   /* name     APOLLOMP_L2_MC_DSL_IVL_SVLtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_MC_DSL_L3LOOKUPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_MC_DSL_VID_FIDtf */
        /* lsp */   48,
        /* len */   12,
    },
    {   /* name     APOLLOMP_L2_MC_DSL_MACtf */
        /* lsp */   0,
        /* len */   48,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_L2_UC_FIELDS[] = 
{
    {   /* name     APOLLOMP_L2_UC_VALIDtf */
        /* lsp */   88,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_NOT_SALEARNtf */
        /* lsp */   87,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_FWDPRI_ENtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_FWDPRItf */
        /* lsp */   83,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L2_UC_ARP_USAGEtf */
        /* lsp */   82,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_EXT_DSL_SPAtf */
        /* lsp */   79,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L2_UC_DA_BLKtf */
        /* lsp */   78,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_SA_BLKtf */
        /* lsp */   77,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_AUTHtf */
        /* lsp */   76,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_AGEtf */
        /* lsp */   73,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L2_UC_SPAtf */
        /* lsp */   70,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L2_UC_SAPRI_ENtf */
        /* lsp */   69,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_FIDtf */
        /* lsp */   65,
        /* len */   4,
    },
    {   /* name     APOLLOMP_L2_UC_EFIDtf */
        /* lsp */   62,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L2_UC_IVL_SVLtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_L3LOOKUPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L2_UC_CVIDtf */
        /* lsp */   48,
        /* len */   12,
    },
    {   /* name     APOLLOMP_L2_UC_MACtf */
        /* lsp */   0,
        /* len */   48,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_L3_MC_DSL_FIELDS[] = 
{
    {   /* name     APOLLOMP_L3_MC_DSL_VALIDtf */
        /* lsp */   88,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_DSL_NOT_SALEARNtf */
        /* lsp */   87,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_DSL_FWDPRI_ENtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_DSL_FWDPRItf */
        /* lsp */   83,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L3_MC_DSL_EXT_MBRtf */
        /* lsp */   77,
        /* len */   6,
    },
    {   /* name     APOLLOMP_L3_MC_DSL_MBRtf */
        /* lsp */   70,
        /* len */   7,
    },
    {   /* name     APOLLOMP_L3_MC_DSL_GIP_ONLYtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_DSL_L3LOOKUPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_DSL_SIP_VIDtf */
        /* lsp */   28,
        /* len */   32,
    },
    {   /* name     APOLLOMP_L3_MC_DSL_GIPtf */
        /* lsp */   0,
        /* len */   28,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_L3_MC_ROUTE_FIELDS[] = 
{
    {   /* name     APOLLOMP_L3_MC_ROUTE_VALIDtf */
        /* lsp */   88,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_NOT_SALEARNtf */
        /* lsp */   87,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_FWDPRI_ENtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_FWDPRItf */
        /* lsp */   83,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_EXT_MBRtf */
        /* lsp */   77,
        /* len */   6,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_MBRtf */
        /* lsp */   70,
        /* len */   7,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_GIP_ONLYtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_L3LOOKUPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_WAN_SAtf */
        /* lsp */   57,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_EXT_FRtf */
        /* lsp */   56,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_L3_IDXtf */
        /* lsp */   28,
        /* len */   28,
    },
    {   /* name     APOLLOMP_L3_MC_ROUTE_GIPtf */
        /* lsp */   0,
        /* len */   28,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_VLAN_FIELDS[] = 
{
    {   /* name     APOLLOMP_VLAN_EXT_MBRtf */
        /* lsp */   29,
        /* len */   6,
    },
    {   /* name     APOLLOMP_VLAN_IVL_SVLtf */
        /* lsp */   28,
        /* len */   1,
    },
    {   /* name     APOLLOMP_VLAN_METERIDXtf */
        /* lsp */   23,
        /* len */   5,
    },
    {   /* name     APOLLOMP_VLAN_POLICINGtf */
        /* lsp */   22,
        /* len */   1,
    },
    {   /* name     APOLLOMP_VLAN_VBPRItf */
        /* lsp */   19,
        /* len */   3,
    },
    {   /* name     APOLLOMP_VLAN_VB_ENtf */
        /* lsp */   18,
        /* len */   1,
    },
    {   /* name     APOLLOMP_VLAN_FID_MSTItf */
        /* lsp */   14,
        /* len */   4,
    },
    {   /* name     APOLLOMP_VLAN_UNTAGtf */
        /* lsp */   7,
        /* len */   7,
    },
    {   /* name     APOLLOMP_VLAN_MBRtf */
        /* lsp */   0,
        /* len */   7,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_ARP_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_ARP_TABLE_NXTHOPIDXtf */
        /* lsp */   1,
        /* len */   11,
    },
    {   /* name     APOLLOMP_ARP_TABLE_VALIDtf */
        /* lsp */   0,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_BINDING_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_BINDING_TABLE_BIND_PTLtf */
        /* lsp */   26,
        /* len */   2,
    },
    {   /* name     APOLLOMP_BINDING_TABLE_WAN_TYPE_INDEXtf */
        /* lsp */   23,
        /* len */   3,
    },
    {   /* name     APOLLOMP_BINDING_TABLE_VID_LANtf */
        /* lsp */   11,
        /* len */   12,
    },
    {   /* name     APOLLOMP_BINDING_TABLE_EXT_PMSKtf */
        /* lsp */   6,
        /* len */   5,
    },
    {   /* name     APOLLOMP_BINDING_TABLE_PORT_MASKtf */
        /* lsp */   0,
        /* len */   6,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_EXTERNAL_IP_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_EXTERNAL_IP_TABLE_PRIORITYtf */
        /* lsp */   72,
        /* len */   3,
    },
    {   /* name     APOLLOMP_EXTERNAL_IP_TABLE_PRIVALtf */
        /* lsp */   71,
        /* len */   1,
    },
    {   /* name     APOLLOMP_EXTERNAL_IP_TABLE_NH_IDXtf */
        /* lsp */   67,
        /* len */   4,
    },
    {   /* name     APOLLOMP_EXTERNAL_IP_TABLE_TYPEtf */
        /* lsp */   65,
        /* len */   2,
    },
    {   /* name     APOLLOMP_EXTERNAL_IP_TABLE_VALIDtf */
        /* lsp */   64,
        /* len */   1,
    },
    {   /* name     APOLLOMP_EXTERNAL_IP_TABLE_EXTIPtf */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     APOLLOMP_EXTERNAL_IP_TABLE_INTIPtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_IPV6_ROUTING_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_IPV6_ROUTING_TABLE_RT2WANINFtf */
        /* lsp */   143,
        /* len */   1,
    },
    {   /* name     APOLLOMP_IPV6_ROUTING_TABLE_VALIDtf */
        /* lsp */   142,
        /* len */   1,
    },
    {   /* name     APOLLOMP_IPV6_ROUTING_TABLE_PROCESStf */
        /* lsp */   140,
        /* len */   2,
    },
    {   /* name     APOLLOMP_IPV6_ROUTING_TABLE_NEXTHOPtf */
        /* lsp */   136,
        /* len */   4,
    },
    {   /* name     APOLLOMP_IPV6_ROUTING_TABLE_IP6_PREFIX_LENtf */
        /* lsp */   128,
        /* len */   8,
    },
    {   /* name     APOLLOMP_IPV6_ROUTING_TABLE_IP6_DIPtf */
        /* lsp */   0,
        /* len */   128,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_L3_ROUTING_DROP_TRAP_FIELDS[] = 
{
    {   /* name     APOLLOMP_L3_ROUTING_DROP_TRAP_RT2WANINFtf */
        /* lsp */   58,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_ROUTING_DROP_TRAP_INTtf */
        /* lsp */   40,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_ROUTING_DROP_TRAP_PROCESStf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     APOLLOMP_L3_ROUTING_DROP_TRAP_VALIDtf */
        /* lsp */   37,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_ROUTING_DROP_TRAP_MASKtf */
        /* lsp */   32,
        /* len */   5,
    },
    {   /* name     APOLLOMP_L3_ROUTING_DROP_TRAP_IPtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_FIELDS[] = 
{
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_RT2WANINFtf */
        /* lsp */   58,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_IPDOMAINtf */
        /* lsp */   55,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_NHALGOtf */
        /* lsp */   53,
        /* len */   2,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_NHNXTtf */
        /* lsp */   48,
        /* len */   5,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_NH_ADDR_STARTtf */
        /* lsp */   44,
        /* len */   4,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_NH_NUMtf */
        /* lsp */   41,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_INTtf */
        /* lsp */   40,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_PROCESStf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_VALIDtf */
        /* lsp */   37,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_MASKtf */
        /* lsp */   32,
        /* len */   5,
    },
    {   /* name     APOLLOMP_L3_ROUTING_GLOBAL_ROUTE_IPtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_L3_ROUTING_LOCAL_ROUTE_FIELDS[] = 
{
    {   /* name     APOLLOMP_L3_ROUTING_LOCAL_ROUTE_RT2WANINFtf */
        /* lsp */   58,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_ROUTING_LOCAL_ROUTE_ARPENDtf */
        /* lsp */   51,
        /* len */   7,
    },
    {   /* name     APOLLOMP_L3_ROUTING_LOCAL_ROUTE_ARPSTAtf */
        /* lsp */   44,
        /* len */   7,
    },
    {   /* name     APOLLOMP_L3_ROUTING_LOCAL_ROUTE_DENTIFtf */
        /* lsp */   41,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L3_ROUTING_LOCAL_ROUTE_INTtf */
        /* lsp */   40,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_ROUTING_LOCAL_ROUTE_PROCESStf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     APOLLOMP_L3_ROUTING_LOCAL_ROUTE_VALIDtf */
        /* lsp */   37,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L3_ROUTING_LOCAL_ROUTE_MASKtf */
        /* lsp */   32,
        /* len */   5,
    },
    {   /* name     APOLLOMP_L3_ROUTING_LOCAL_ROUTE_IPtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_NAPT_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_NAPT_TABLE_PRIORITYtf */
        /* lsp */   12,
        /* len */   3,
    },
    {   /* name     APOLLOMP_NAPT_TABLE_PRI_VALIDtf */
        /* lsp */   11,
        /* len */   1,
    },
    {   /* name     APOLLOMP_NAPT_TABLE_VALIDtf */
        /* lsp */   10,
        /* len */   1,
    },
    {   /* name     APOLLOMP_NAPT_TABLE_HASHIN_IDXtf */
        /* lsp */   0,
        /* len */   10,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_NAPTR_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_NAPTR_TABLE_PRIORITYtf */
        /* lsp */   79,
        /* len */   3,
    },
    {   /* name     APOLLOMP_NAPTR_TABLE_PRI_VALIDtf */
        /* lsp */   78,
        /* len */   1,
    },
    {   /* name     APOLLOMP_NAPTR_TABLE_VALIDtf */
        /* lsp */   76,
        /* len */   2,
    },
    {   /* name     APOLLOMP_NAPTR_TABLE_TCPtf */
        /* lsp */   75,
        /* len */   1,
    },
    {   /* name     APOLLOMP_NAPTR_TABLE_EXTPRT_LSBtf */
        /* lsp */   67,
        /* len */   8,
    },
    {   /* name     APOLLOMP_NAPTR_TABLE_EXTIP_IDXtf */
        /* lsp */   64,
        /* len */   3,
    },
    {   /* name     APOLLOMP_NAPTR_TABLE_REM_HASHtf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     APOLLOMP_NAPTR_TABLE_INTPORTtf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     APOLLOMP_NAPTR_TABLE_INTIPtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_NEIGHBOR_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_NEIGHBOR_TABLE_VALIDtf */
        /* lsp */   77,
        /* len */   1,
    },
    {   /* name     APOLLOMP_NEIGHBOR_TABLE_L2_TABLE_IDXtf */
        /* lsp */   66,
        /* len */   11,
    },
    {   /* name     APOLLOMP_NEIGHBOR_TABLE_RT_MATCH_IDXtf */
        /* lsp */   64,
        /* len */   2,
    },
    {   /* name     APOLLOMP_NEIGHBOR_TABLE_IP6IF_IDtf */
        /* lsp */   0,
        /* len */   64,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_NETIF_FIELDS[] = 
{
    {   /* name     APOLLOMP_NETIF_MTUtf */
        /* lsp */   65,
        /* len */   14,
    },
    {   /* name     APOLLOMP_NETIF_ENRTRtf */
        /* lsp */   64,
        /* len */   1,
    },
    {   /* name     APOLLOMP_NETIF_MACMASKtf */
        /* lsp */   61,
        /* len */   3,
    },
    {   /* name     APOLLOMP_NETIF_GMACtf */
        /* lsp */   13,
        /* len */   48,
    },
    {   /* name     APOLLOMP_NETIF_VLANIDtf */
        /* lsp */   1,
        /* len */   12,
    },
    {   /* name     APOLLOMP_NETIF_VALIDtf */
        /* lsp */   0,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_NEXT_HOP_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_NEXT_HOP_TABLE_KEEPPPPOPtf */
        /* lsp */   18,
        /* len */   1,
    },
    {   /* name     APOLLOMP_NEXT_HOP_TABLE_NXTHOPIDXtf */
        /* lsp */   7,
        /* len */   11,
    },
    {   /* name     APOLLOMP_NEXT_HOP_TABLE_PPPIDXtf */
        /* lsp */   4,
        /* len */   3,
    },
    {   /* name     APOLLOMP_NEXT_HOP_TABLE_IFIDXtf */
        /* lsp */   1,
        /* len */   3,
    },
    {   /* name     APOLLOMP_NEXT_HOP_TABLE_TYPEtf */
        /* lsp */   0,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_PPPOE_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_PPPOE_TABLE_SESIDtf */
        /* lsp */   0,
        /* len */   16,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_WAN_TYPE_TABLE_FIELDS[] = 
{
    {   /* name     APOLLOMP_WAN_TYPE_TABLE_NXHOPTBIDXtf */
        /* lsp */   2,
        /* len */   4,
    },
    {   /* name     APOLLOMP_WAN_TYPE_TABLE_WAN_TYPEtf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_L34_HSA_FIELDS[] = 
{
    {   /* name     APOLLOMP_L34_HSA_PPPOE_KEEPtf */
        /* lsp */   128,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSA_BIND_VIDTRANStf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSA_INTERNAL_VLAN_IFtf */
        /* lsp */   126,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSA_REASONtf */
        /* lsp */   120,
        /* len */   6,
    },
    {   /* name     APOLLOMP_L34_HSA_L3L4TRANStf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSA_L2TRANStf */
        /* lsp */   118,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSA_ACTIONtf */
        /* lsp */   116,
        /* len */   2,
    },
    {   /* name     APOLLOMP_L34_HSA_L4HP_Vtf */
        /* lsp */   115,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSA_L4HPtf */
        /* lsp */   112,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L34_HSA_FRAGtf */
        /* lsp */   111,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSA_DIFIDtf */
        /* lsp */   108,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L34_HSA_DVIDtf */
        /* lsp */   96,
        /* len */   12,
    },
    {   /* name     APOLLOMP_L34_HSA_PPPOE_IFtf */
        /* lsp */   94,
        /* len */   2,
    },
    {   /* name     APOLLOMP_L34_HSA_PPPID_IDXtf */
        /* lsp */   91,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L34_HSA_NEXTHOP_MAC_IDXtf */
        /* lsp */   80,
        /* len */   11,
    },
    {   /* name     APOLLOMP_L34_HSA_L4_CHECKSUM_OFFSETtf */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     APOLLOMP_L34_HSA_L3_CHECKSUM_OFFSETtf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     APOLLOMP_L34_HSA_PORTtf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     APOLLOMP_L34_HSA_IPtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_L34_HSB_FIELDS[] = 
{
    {   /* name     APOLLOMP_L34_HSB_IS_FROM_WAN_PORTtf */
        /* lsp */   311,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_L2BRIDGEtf */
        /* lsp */   310,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_IPFRAGOFStf */
        /* lsp */   309,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_IPMFtf */
        /* lsp */   308,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_L4CSOKtf */
        /* lsp */   307,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_L3CSOKtf */
        /* lsp */   306,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_CPU_DIRECT_TXtf */
        /* lsp */   305,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_UDP_NOCStf */
        /* lsp */   304,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_PARS_FAILtf */
        /* lsp */   303,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_PPPOE_IFtf */
        /* lsp */   302,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_SVLAN_TAG_IFtf */
        /* lsp */   301,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_TTLSTtf */
        /* lsp */   299,
        /* len */   2,
    },
    {   /* name     APOLLOMP_L34_HSB_TYPEtf */
        /* lsp */   296,
        /* len */   3,
    },
    {   /* name     APOLLOMP_L34_HSB_TCP_FLAG_PROTOCOL_PARSING_FAILURE_REASONtf */
        /* lsp */   288,
        /* len */   8,
    },
    {   /* name     APOLLOMP_L34_HSB_CVLAN_TAG_IFtf */
        /* lsp */   287,
        /* len */   1,
    },
    {   /* name     APOLLOMP_L34_HSB_SPAtf */
        /* lsp */   282,
        /* len */   5,
    },
    {   /* name     APOLLOMP_L34_HSB_CVLANIDtf */
        /* lsp */   270,
        /* len */   12,
    },
    {   /* name     APOLLOMP_L34_HSB_LENtf */
        /* lsp */   256,
        /* len */   14,
    },
    {   /* name     APOLLOMP_L34_HSB_DPORT_L4CHKSUMtf */
        /* lsp */   240,
        /* len */   16,
    },
    {   /* name     APOLLOMP_L34_HSB_PPPOE_IDtf */
        /* lsp */   224,
        /* len */   16,
    },
    {   /* name     APOLLOMP_L34_HSB_DIPtf */
        /* lsp */   96,
        /* len */   128,
    },
    {   /* name     APOLLOMP_L34_HSB_SIPtf */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     APOLLOMP_L34_HSB_SPORT_ICMPID_CHKSUMtf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     APOLLOMP_L34_HSB_DMACtf */
        /* lsp */   0,
        /* len */   48,
    },
};
#endif
#if defined(CONFIG_SDK_APOLLOMP)
rtk_tableField_t APOLLOMP_HSA_DEBUG_DATA_FIELDS[] = 
{
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_RESERVED_02tf */
        /* lsp */   474,
        /* len */   38,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_EPtf */
        /* lsp */   471,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_DSL_VCtf */
        /* lsp */   467,
        /* len */   4,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_34PPPOEtf */
        /* lsp */   451,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_34SMACtf */
        /* lsp */   403,
        /* len */   48,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_RSV0tf */
        /* lsp */   397,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_TTLPMSKtf */
        /* lsp */   396,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_TTLEXMSKtf */
        /* lsp */   391,
        /* len */   5,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_NEWMACtf */
        /* lsp */   343,
        /* len */   48,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_NEWPRTtf */
        /* lsp */   327,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_NEWIPtf */
        /* lsp */   295,
        /* len */   32,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L4CKSUMtf */
        /* lsp */   279,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L3CKSUMtf */
        /* lsp */   263,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_PPPOEACTtf */
        /* lsp */   261,
        /* len */   2,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_SRC_MODtf */
        /* lsp */   260,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L34TRANStf */
        /* lsp */   259,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L2TRANStf */
        /* lsp */   258,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_ORGtf */
        /* lsp */   257,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA1_L3Rtf */
        /* lsp */   256,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_RESERVED_01tf */
        /* lsp */   232,
        /* len */   24,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_SV_DEItf */
        /* lsp */   231,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_STYPtf */
        /* lsp */   230,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PKTLEN_ORItf */
        /* lsp */   216,
        /* len */   14,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_QIDtf */
        /* lsp */   209,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_STDSCtf */
        /* lsp */   196,
        /* len */   13,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CPUPRItf */
        /* lsp */   193,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_SPRItf */
        /* lsp */   190,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CORItf */
        /* lsp */   189,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CMDYtf */
        /* lsp */   188,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CRMStf */
        /* lsp */   187,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CINStf */
        /* lsp */   186,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CVIDtf */
        /* lsp */   174,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_RSV1tf */
        /* lsp */   172,
        /* len */   2,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_CFItf */
        /* lsp */   171,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PTPNSECtf */
        /* lsp */   139,
        /* len */   32,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PTPSECtf */
        /* lsp */   91,
        /* len */   48,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PTPACTtf */
        /* lsp */   89,
        /* len */   2,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REGENCRCtf */
        /* lsp */   88,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PPPOEtf */
        /* lsp */   87,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_RFC1042tf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_IPV6tf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_IPV4tf */
        /* lsp */   84,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PTPtf */
        /* lsp */   83,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REMDSCP_PRItf */
        /* lsp */   77,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REM1Q_PRItf */
        /* lsp */   74,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REMDSCP_ENtf */
        /* lsp */   73,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_REM1Q_ENtf */
        /* lsp */   72,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_SVIDtf */
        /* lsp */   60,
        /* len */   12,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_INSTAGtf */
        /* lsp */   59,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_INCTAGtf */
        /* lsp */   58,
        /* len */   1,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PKTLENtf */
        /* lsp */   44,
        /* len */   14,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_SPAtf */
        /* lsp */   41,
        /* len */   3,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_DPCtf */
        /* lsp */   37,
        /* len */   4,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_EXTMSKtf */
        /* lsp */   31,
        /* len */   6,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_VCMSKtf */
        /* lsp */   15,
        /* len */   16,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_PONSIDtf */
        /* lsp */   8,
        /* len */   7,
    },
    {   /* name     APOLLOMP_HSA_DEBUG_DATA_TXHSA0_TRPRSNtf */
        /* lsp */   0,
        /* len */   8,
    },
};
#endif

