/* 
 * Copyright (C) 2012 Realtek Semiconductor Corp.
 * All Rights Reserved.
 * 
 * This program is the proprietary software of Realtek Semiconductor
 * Corporation and/or its licensors, and only be used, duplicated,
 * modified or distributed under the authorized license from Realtek.
 * 
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 * THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 * 
 * AUTOMATIC GENERATED BY PYTHON SCRIPT. PLEASE DONOT MODIFY DIRECTLY.
 * 
 */


#ifndef __MIB_MACBRIDGEPORTFILTERTABLE_TABLE_H__
#define __MIB_MACBRIDGEPORTFILTERTABLE_TABLE_H__

/* Table MacBridgePortFilterTable attribute for STRING type define each entry length */
#define MIB_TABLE_MACFILTERTABLE_LEN (8)

/* Table MacBridgePortFilterTable attribute index */
#define MIB_TABLE_MACBRIDGEPORTFILTERTABLE_ATTR_NUM (2)
#define MIB_TABLE_MACBRIDGEPORTFILTERTABLE_ENTITYID_INDEX ((MIB_ATTR_INDEX)1)
#define MIB_TABLE_MACBRIDGEPORTFILTERTABLE_MACFILTERTABLE_INDEX ((MIB_ATTR_INDEX)2)

typedef struct mbpcdStateInfo_s
{
	UINT32 uniPortMask;
	UINT32 isConnect;
	void *node;
	UINT32 other_key;
}mbpcdStateInfo_t;

typedef enum 
{
	MAC_FILTER_TABLE_OPER_REMOVE = 0,
	MAC_FILTER_TABLE_OPER_CLEAR_ALL,
	MAC_FILTER_TABLE_OPER_ADD
}mac_Filter_table_oper_e;

typedef struct{
	union
    {
        struct
        {
            UINT32 entryIndex : 8;
			UINT32 oper : 2;
			UINT32 reserved : 4;
			UINT32 isSa : 1;
            UINT32 isFilter : 1;
            UINT32 mac : 16;
        } bit;
        UINT32 val;
    } firstWord;
	union
    {
        struct
        {
            UINT32 mac : 32;
        } bit;
        UINT32 val;
    } secondWord;
}omci_macFilter_raw_entry_t;

typedef struct macFilterTableEntry_s{
	
	omci_macFilter_raw_entry_t tableEntry;	
	LIST_ENTRY(macFilterTableEntry_s) entries;

}macFilterTableEntry_t;

/* Table MacBridgePortFilterTable attribute len, only string attrubutes have length definition */
typedef struct {
	UINT16   EntityId;
	CHAR     MACFilterTable[MIB_TABLE_MACFILTERTABLE_LEN];
	UINT16   curMacTableEntryCnt;
	LIST_HEAD(macFilterHead,macFilterTableEntry_s) head;
} __attribute__((aligned)) MIB_TABLE_MACBRIDGEPORTFILTERTABLE_T;


#endif /* __MIB_MACBRIDGEPORTFILTERTABLE_TABLE_H__ */
