#include <stdio.h>
#include <string.h>
#include "sc_util.h"
#include "sc_status.h"

static inline void printf_off( const char *fmt, ... ) {};

#define SCSTATUS_DEBUG

#ifdef SCSTATUS_DEBUG
#define STATUS_PRINTF           printf
#else
#define STATUS_PRINTF            printf_off
#endif

int SimStatusWord(unsigned short sw){
	unsigned char sw1 = (sw & 0xff00) >> 8;
	unsigned char sw2 = (sw & 0x00ff);
	//STATUS_PRINTF("%02x%02x\n", sw1, sw2);
	switch (sw1){
		case SW1_CORRECT:
			if ( sw2 == 0x00 )	return SW_NORMAL;
			//break;
		case SW1_CORRECT_WITH_PROACTIVE:
			STATUS_PRINTF("SW1_CORRECT_WITH_PROACTIVE\n");
			return SW_CORRECT_WITH_PROACTIVE;
			//break;
		case SW1_CORRECT_RESPONSE_DATA:
			STATUS_PRINTF("SW1_CORRECT_RESPONSE_DATA\n");
			return SW_NORMAL_WITH_DATA;
			//break;
		case SW1_SIMAPTOOLKIT_BUSY:
			STATUS_PRINTF("SW1_SIMAPTOOLKIT_BUSY\n");
			return SW_SIMAPTOOLKIT_BUSY;
			//break;
		case SW1_MEMORY_COMMAND:
			if ( (sw2 & 0xf0) == 0x00 ){
				STATUS_PRINTF("SW2_RETRY_X_TIMES\n");
				return SW_NORMAL_UPDATE_RETRY;
			}else if ( sw2 == 0x40 ){
				STATUS_PRINTF("SW2_MEMORY_PROBLEM\n");
				return SW_MEMORY_ERROR;
			}
			break;
		case SW1_REFERENCE:
			if ( sw2 == SW2_NO_EF_SELECT ){
				STATUS_PRINTF("SW2_NO_EF_SELECT\n");
				return SW_NO_EF_SELECT;
			}
			if ( (sw2 & SW2_OUTOFRANGE) == SW2_OUTOFRANGE ){
				STATUS_PRINTF("SW2_OUTOFRANGE\n");
				return SW_OUT_OF_RANGE;
			}
			if ( (sw2 & SW2_FILEID_NOTFOUND ) == SW2_FILEID_NOTFOUND ){
				STATUS_PRINTF("SW2_FILEID_NOTFOUND\n");
				return SW_FILEID_NOT_FOUND;
			}
			if ( (sw2 & SW2_FILE_INCONSISTENT ) == SW2_FILE_INCONSISTENT ){
				STATUS_PRINTF("SW2_FILE_INCONSISTENT\n");
				return SW_FILE_INCONSISTENT;
			}
			break;
		case SW1_SECURITY:
			//STATUS_PRINTF("SW1_SECURITY : %02x, %02x%02x\n", SW1_SECURITY, sw1, sw2);
			if ( (sw2 & SW2_CHV_NOT_INITIALIZED ) == SW2_CHV_NOT_INITIALIZED ){
				STATUS_PRINTF("SW2_CHV_NOT_INITIALIZED\n");
				return SW_CHV_NOT_INITIALIZED;
			}
			if ( (sw2 & SW2_BAD_ACCCOND_VERIFY_MORE_TRIES) == SW2_BAD_ACCCOND_VERIFY_MORE_TRIES ){
				STATUS_PRINTF("SW2_BAD_ACCCOND_VERIFY_MORE_TRIES\n");
				return SW_BAD_ACCCOND_VERIFY_MORE_TRIES;
			}
			if ( (sw2 & SW2_CONTRADICTION_CHV ) == SW2_CONTRADICTION_CHV ){
				STATUS_PRINTF("SW2_CONTRADICTION_CHV\n");
				return SW_CONTRADICTION_CHV;
			}
			if ( (sw2 & SW2_CONTRADICTION_INVALIDATION) == SW2_CONTRADICTION_INVALIDATION ){
				STATUS_PRINTF("SW2_CONTRADICTION_INVALIDATION\n");
				return SW_CONTRADICTION_INVALIDATION;
			}
			if ( (sw2 & SW2_VERIFY_NO_TRIES_CHV_BLOCKED) == SW2_VERIFY_NO_TRIES_CHV_BLOCKED ){
				STATUS_PRINTF("SW2_VERIFY_NO_TRIES_CHV_BLOCKED\n");
				return SW_VERIFY_NO_TRIES_CHV_BLOCKED;
			}
			if ( (sw2 & SW2_INCREASE_NOT_ALLOWED ) == SW2_INCREASE_NOT_ALLOWED ){
				STATUS_PRINTF("SW2_INCREASE_NOT_ALLOWED\n");
				return SW_INCREASE_NOT_ALLOWED;
			}
			if ( (sw2 & SW2_AUTH_ERROR ) == SW2_AUTH_ERROR ){
				STATUS_PRINTF("SW2_AUTH_ERROR\n");
				return SW_INCREASE_NOT_ALLOWED;
			}
			if ( (sw2 & SW2_SECURITY_SESSION_ASSOCIATE_EXPIRE ) == SW2_SECURITY_SESSION_ASSOCIATE_EXPIRE ){
				STATUS_PRINTF("SW2_SECURITY_SESSION_ASSOCIATE_EXPIRE\n");
				return SW_INCREASE_NOT_ALLOWED;
			}				
			break;
		case SW1_ERROR_P3:
			STATUS_PRINTF("SW1_ERROR_P3 : %02x, %02x%02x\n", SW1_ERROR_P3, sw2);
			return SW_ERROR_P3;
			//break;
		case SW1_ERROR_P1_P2:
			STATUS_PRINTF("SW1_ERROR_P1_P2 : %02x, %02x%02x\n", SW1_ERROR_P1_P2, sw2);
			return SW_ERROR_P1_P2;
			//break;
		case SW1_UNKNOWN_INS:
			STATUS_PRINTF("SW1_UNKNOWN_INS : %02x, %02x%02x\n", SW1_UNKNOWN_INS, sw2);
			return SW_UNKNOWN_INS;
			//break;
		case SW1_WROING_CLA:
			STATUS_PRINTF("SW1_WROING_CLA : %02x, %02x%02x\n", SW1_WROING_CLA, sw2);
			return SW_WRONG_CLA;
			//break;
		case SW1_TECHNICAL_PROBLEM:
			STATUS_PRINTF("SW1_TECHNICAL_PROBLEM : %02x, %02x%02x\n", SW1_TECHNICAL_PROBLEM, sw2);
			return SW_TECHNICAL_PROBLEM;
			//break;
		case SW1_WARNING1:
			if ( sw2 == SW2_RETURN_DATA_CORRUPTED ){
				STATUS_PRINTF("SW2_RETURN_DATA_CORRUPTED\n");
			}
			if ( sw2 == SW2_END_OF_FILE_REACH ){
				STATUS_PRINTF("SW2_END_OF_FILE_REACH\n");
			}		
			if ( sw2 == SW2_SELECTFILE_INVALIDATED ){
				STATUS_PRINTF("SW2_SELECTFILE_INVALIDATED\n");
			}
			if ( sw2 == SW2_SELECTFILE_TERMINATE ){
				STATUS_PRINTF("SW2_SELECTFILE_TERMINATE\n");
			}
			if ( sw2 == SW2_MORE_DATA_AVAILABLE ){
				STATUS_PRINTF("SW2_MORE_DATA_AVAILABLE\n");
			}	
			if ( sw2 == SW2_MORE_DATA_COMMAND_PEND ){
				STATUS_PRINTF("SW2_MORE_DATA_COMMAND_PEND\n");
			}
			if ( sw2 == SW2_RESPONSE_DATA_AVAILABLE ){
				STATUS_PRINTF("SW2_RESPONSE_DATA_AVAILABLE\n");
			}
			break;
		case SW1_WARNING2:
			if ( sw2 == SW2_MORE_DATA_EXPECT ){
				STATUS_PRINTF("SW2_MORE_DATA_EXPECT\n");
			}	
			if ( sw2 == SW2_MORE_DATA_COMMAND_PEND ){
				STATUS_PRINTF("SW2_MORE_DATA_COMMAND_PEND\n");
			}
			if ( sw2 == SW2_COMMAND_OK_RETRY_X ){
				STATUS_PRINTF("SW2_COMMAND_OK_RETRY_X\n");
			}
			break;
		case SW1_EXECUTE_ERROR_MEM_UNCHANGE:
			STATUS_PRINTF("SW2_COMMAND_OK_RETRY_X\n");
			break;
		case SW1_EXECUTE_ERROR_MEM_CHANGE:
			if ( sw2 == SW2_EXECUTE_MEMORY_PROBLEM )
				STATUS_PRINTF("SW2_EXECUTE_MEMORY_PROBLEM\n");
			break;
		case SW1_CLA_NOT_SUPPORT:
			if ( sw2 == SW2_LOGICAL_CH_NOT_SUPPORT ){
				STATUS_PRINTF("SW2_LOGICAL_CH_NOT_SUPPORT\n");
			}
			if ( sw2 == SW2_SECURE_MESSAGE_NOT_SUPPORT ){
				STATUS_PRINTF("SW2_SECURE_MESSAGE_NOT_SUPPORT\n");
			}
		case SW1_COMMAND_NOT_ALLOW:
			if ( sw2 == SW2_COMMAND_INCOMPATIBLE ){
				STATUS_PRINTF("SW2_COMMAND_INCOMPATIBLE\n");
			}
			if ( sw2 == SW2_SECURITY_STATUS_NOT_SATISFIED ){
				STATUS_PRINTF("SW2_SECURITY_STATUS_NOT_SATISFIED\n");
			}
			if ( sw2 == SW2_AUTHENTICATION_BLOCKED ){
				STATUS_PRINTF("SW2_AUTHENTICATION_BLOCKED\n");
			}
			if ( sw2 == SW2_REFERENCE_DATA_INVALIDATED ){
				STATUS_PRINTF("SW2_REFERENCE_DATA_INVALIDATED\n");
			}
			if ( sw2 == SW2_CONDITION_OF_USE_NOT_SATISFIED ){
				STATUS_PRINTF("SW2_CONDITION_OF_USE_NOT_SATISFIED\n");
			}
			if ( sw2 == SW2_COMMAND_NOT_ALLOWED ){
				STATUS_PRINTF("SW2_COMMAND_NOT_ALLOWED\n");
			}
			if ( sw2 == SW2_COMMAND_NOT_ALLOWED_SECURE_CH ){
				STATUS_PRINTF("SW2_COMMAND_NOT_ALLOWED_SECURE_CH\n");
			}
			break;
		case SW1_WROING_PARAMETER:
			if ( sw2 == SW2_INCORRECT_PARAMETER_IN_DATA ){
				STATUS_PRINTF("SW2_INCORRECT_PARAMETER_IN_DATA\n");
			}
			if ( sw2 == SW2_FUNCTION_NOT_SUPPORT ){
				STATUS_PRINTF("SW2_FUNCTION_NOT_SUPPORT\n");
			}
			if ( sw2 == SW2_FILE_NOT_FOUND ){
				STATUS_PRINTF("SW2_FILE_NOT_FOUND\n");
			}
			if ( sw2 == SW2_RECORD_NOT_FOUND ){
				STATUS_PRINTF("SW2_RECORD_NOT_FOUND\n");
			}
			if ( sw2 == SW2_NOT_ENOUGH_MEMORY ){
				STATUS_PRINTF("SW2_NOT_ENOUGH_MEMORY\n");
			}
			if ( sw2 == SW2_INCORRECT_P1_P2 ){
				STATUS_PRINTF("SW2_INCORRECT_P1_P2\n");
			}
			if ( sw2 == SW2_LC_INCONSISTENT_P1_P2 ){
				STATUS_PRINTF("SW2_LC_INCONSISTENT_P1_P2\n");
			}
			if ( sw2 == SW2_REFERENCE_DATA_NOT_FOUND ){
				STATUS_PRINTF("SW2_REFERENCE_DATA_NOT_FOUND\n");
			}			
			break;			
		default:
			STATUS_PRINTF("default %02x%02x\n", sw1, sw2);
			break;
	}
	
	return 0;
}

