#ifndef __SCSTATUS__
#define __SCSTATUS__




// Status Word
#define SW1_CORRECT	0x90
#define SW1_CORRECT_WITH_PROACTIVE	0x91
#define SW1_CORRECT_RESPONSE_DATA	0x9F

#define SW1_SIMAPTOOLKIT_BUSY	0x93

#define SW1_MEMORY_COMMAND	0x92
#define SW2_RETRY_X_TIMES	0x0F
#define SW2_MEMORY_PROBLEM	0x40

#define SW1_REFERENCE			0x94
#define SW2_NO_EF_SELECT		0x00
#define SW2_OUTOFRANGE			0x02
#define SW2_FILEID_NOTFOUND		0x04
#define SW2_FILE_INCONSISTENT	0x08

// application error
#define SW1_SECURITY						0x98
#define SW2_CHV_NOT_INITIALIZED				0x02
#define	SW2_BAD_ACCCOND_VERIFY_MORE_TRIES	0x04
#define SW2_CONTRADICTION_CHV				0x08
#define	SW2_CONTRADICTION_INVALIDATION		0x10
#define	SW2_VERIFY_NO_TRIES_CHV_BLOCKED		0x40
#define SW2_INCREASE_NOT_ALLOWED			0x50
#define SW2_AUTH_ERROR						0x62
#define SW2_SECURITY_SESSION_ASSOCIATE_EXPIRE	0x63

#define SW1_WARNING1				0x62
#define SW2_RETURN_DATA_CORRUPTED	0x81
#define SW2_END_OF_FILE_REACH		0x82
#define SW2_SELECTFILE_INVALIDATED	0x83
#define SW2_SELECTFILE_TERMINATE	0x85
#define SW2_MORE_DATA_AVAILABLE		0xF1
#define SW2_MORE_DATA_COMMAND_PEND	0xF2
#define SW2_RESPONSE_DATA_AVAILABLE	0xF3

// warning
#define SW1_WARNING2				0x63
#define SW2_MORE_DATA_EXPECT		0xF1
#define SW2_MORE_DATA_COMMAND_PEND	0xF2
#define SW2_COMMAND_OK_RETRY_X		0xC0

// execution error
#define SW1_EXECUTE_ERROR_MEM_UNCHANGE	0x64
#define SW1_EXECUTE_ERROR_MEM_CHANGE	0x65
#define SW2_EXECUTE_MEMORY_PROBLEM				0x81

// checking error
#define SW1_ERROR_P3			0x67
#define SW1_ERROR_P1_P2			0x6B
#define SW1_UNKNOWN_INS			0x6D
#define SW1_WROING_CLA			0x6E
#define SW1_TECHNICAL_PROBLEM	0x6F

// functions in CLA not support
#define SW1_CLA_NOT_SUPPORT				0x68
#define SW2_LOGICAL_CH_NOT_SUPPORT		0x81
#define SW2_SECURE_MESSAGE_NOT_SUPPORT	0x82

// command not allowed
#define SW1_COMMAND_NOT_ALLOW				0x69
#define SW2_COMMAND_INCOMPATIBLE			0x81
#define SW2_SECURITY_STATUS_NOT_SATISFIED	0x82
#define SW2_AUTHENTICATION_BLOCKED			0x83
#define SW2_REFERENCE_DATA_INVALIDATED		0x84
#define SW2_CONDITION_OF_USE_NOT_SATISFIED	0x85
#define SW2_COMMAND_NOT_ALLOWED				0x86
#define SW2_COMMAND_NOT_ALLOWED_SECURE_CH 	0x89

// wrong parameters
#define SW1_WROING_PARAMETER				0x6A
#define SW2_INCORRECT_PARAMETER_IN_DATA		0x80
#define SW2_FUNCTION_NOT_SUPPORT			0x81
#define	SW2_FILE_NOT_FOUND					0x82
#define SW2_RECORD_NOT_FOUND				0x83
#define SW2_NOT_ENOUGH_MEMORY				0x84
#define SW2_INCORRECT_P1_P2					0x86
#define SW2_LC_INCONSISTENT_P1_P2			0x87
#define	SW2_REFERENCE_DATA_NOT_FOUND		0x88

#define SW_NORMAL					1
#define SW_CORRECT_WITH_PROACTIVE	2
#define SW_NORMAL_WITH_DATA			3
#define SW_NORMAL_UPDATE_RETRY		4

#define SW_SIMAPTOOLKIT_BUSY		-1
#define SW_MEMORY_ERROR				-2
#define SW_NO_EF_SELECT				-3
#define SW_OUT_OF_RANGE				-4
#define SW_FILEID_NOT_FOUND			-5
#define SW_FILE_INCONSISTENT		-6
#define SW_CHV_NOT_INITIALIZED				-7
#define SW_BAD_ACCCOND_VERIFY_MORE_TRIES	-8
#define SW_CONTRADICTION_CHV	-9
#define SW_CONTRADICTION_INVALIDATION	-10
#define SW_VERIFY_NO_TRIES_CHV_BLOCKED	-11
#define SW_INCREASE_NOT_ALLOWED			-12
#define SW_ERROR_P3						-13
#define SW_ERROR_P1_P2					-14
#define SW_UNKNOWN_INS					-15
#define SW_WRONG_CLA					-16
#define SW_TECHNICAL_PROBLEM			-17

int SimStatusWord(unsigned short sw);

#endif
