
/* This is RTL9601B driver files */
/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 48948 $
 * $Date: 2014-06-30 11:42:18 +0800 (Mon, 30 Jun 2014) $
 *
 * Purpose : The RTL9601B chip driver
 *
 * Feature : RTL9601B chip driver
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allreg.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/rtl9601b/rtk_rtl9601b_reg_struct.h>
#include <hal/chipdef/rtl9601b/rtk_rtl9601b_table_struct.h>
#include <hal/chipdef/chip.h>
#include <hal/chipdef/driver.h>
#include <hal/mac/drv.h>

//#if defined(CONFIG_SDK_RTL9601B)
#if 0
static rtk_reg_t *rtl9601b_reg_list[] =
{
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_I2C_MASTER_CLOCK_DIV_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_I2C_IND_WIDTH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_I2C_IND_WD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_I2C_IND_ADR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_I2C_IND_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_I2C_IND_CMD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OCP_REG_IND_WIDTH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OCP_REG_IND_WD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OCP_REG_IND_ADR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OCP_REG_IND_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OCP_REG_IND_CMD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LEXRA0_IND_WD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LEXRA0_IND_ADR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LEXRA0_IND_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LEXRA0_IND_CMD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEPROM_DOWNLOAD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IO_LED_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IO_MODE_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SOFTWARE_RST_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PONCTRL_CS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_INTR_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_INTR_IMR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_INTR_IMS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_INTR_STAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG14_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG13_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG12_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG9_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG8_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG7_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG4_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG3_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DIAG_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DFR_TEST_RESUME_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BIST_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RAM_DVS_CFG0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RAM_DVS_CFG1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_INTEGRATION_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DATA_LED_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LED_ACTIVE_LOW_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LED_FORCE_VALUE_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LED_BLINK_RATE_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LED_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_LED_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FORCE_P_DMP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EN_FORCE_P_DMP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPHY_AFE_DBG_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MISCELLANEOUS_CONFIGURE0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_HTRAM_DVS_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DEBUG_SEL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DBG_BLK_SEL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CHIP_DEBUG_OUT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FPGA_VER_MAC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MODEL_NAME_INFO_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CHIP_INFO_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BONDING_INFO_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STRAPPING_INFO_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LAN_PORT_INTERFACE_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SDS1_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WRAP_GPHY_MISC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FIFO_ERR_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_REGCTRL_GLB_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPHY_SMI_CLK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPHY_IND_WD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPHY_IND_CMD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPHY_IND_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPHY_SMI_WD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPHY_SMI_CMD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPHY_SMI_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CFG_PHY_POLL_CMD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CFG_PHY_HOTCMD1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CFG_PHY_HOTCMD2_0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CFG_PHY_HOTCMD2_1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CFG_PHY_POLL_WD_0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CFG_PHY_POLL_WD_1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PERIOD_CMD0_RDDATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PERIOD_CMD1_RDDATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PERIOD_CMD2_RDDATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PERIOD_CMD3_RDDATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPHY_ABLTY_STATUS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_ABLTY_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FORCE_P_ABLTY_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_ABLTY_FORCE_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SDS0_PHY_SIDE_ABILITY_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SDS0_INTF_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SDS0_STATUS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SDS1_INTF_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SDS1_STATUS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SERDES_IND_WD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SERDES_IND_CMD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SERDES_IND_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DYNGASP_CTRL0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DYNGASP_TIMER_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ACCESS_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_IND_WD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_IND_CMD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_IND_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY3_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY4_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY5_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY6_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY7_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY8_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY9_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY10_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY11_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY12_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY13_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY14_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY15_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY16_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY17_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY18_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY19_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY20_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY21_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY22_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY23_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY24_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY25_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY26_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY27_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY28_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY29_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY30_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_ENTRY31_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_BOND_FRC_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_FRC_BONDING_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EFUSE_BOND_RSLT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_REGSWR1X_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_REGSWR2X_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_REGSWR3X_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_REGSWR4X_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_ACCEPT_MAX_LEN_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MAX_LENGTH_CFG1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MAX_LENGTH_CFG0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GLOBAL_MAC_L2_MISC_0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GLOBAL_MAC_L2_MISC_1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SWITCH_MAC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_TX_ERR_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_CGSTTIMER_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_MISC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GLB_MAC_MISC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CHANGE_DUPLEX_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CHANGE_DUPLEX_STATUS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MAC_DLYLNK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DIGITAL_INTERFACE_SELECT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CFG_PCSXF_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BYPS_ABLTY_LOCK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MAC_ACT_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_INBW_BOUND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_CFG_FRC_RATE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_CUR_RATE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CPU_TAG_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_00_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_01_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_02_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_03_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_04_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_05_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_06_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_07_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_08_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_09_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_0A_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_0B_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_0C_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_0D_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_0E_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_0F_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_10_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_11_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_12_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_13_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_14_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_15_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_16_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_17_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_18_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_19_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_1A_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_1B_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_1C_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_1D_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_1E_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_1F_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_20_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_21_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_22_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_23_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_24_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_25_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_26_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_27_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_28_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_29_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_2A_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_2B_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WSDS_DIG_2C_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_EEEP_PORT_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_EEECFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_EEETXMTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_EEERXMTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_TX_THR_GIGA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_TX_THR_FE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_RX_FC_REG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_MISC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_GIGA_CTRL0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_GIGA_CTRL1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_100M_CTRL0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_100M_CTRL1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_BURSTSIZE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_IFG_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_RXIDLE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEE_DECISION_WINDOW_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LOW_QUEUE_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_HIGH_QUEUE_MSK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_EEEP_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_TIMER_UNIT_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_TX_TIMER_GIGA_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_TX_TIMER_500M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_TX_TIMER_100M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_TX_GIGA_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_TX_500M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_TX_100M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_RATE_GIGA_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_RATE_500M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_RATE_100M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_SLEEP_STEP_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_WAKE_TIMER_GIGA_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_TIMER_GIGA_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_WAKE_TIMER_500M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_TIMER_500M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_WAKE_TIMER_100M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EEEP_RX_TIMER_100M_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_EEEPTXMTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_EEEPRXMTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PS_LINKID_GATCLK_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SW_PWRSAV_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RST_SYNC_FIFO_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LUT_UNKN_SA_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LUT_UNKN_UC_DA_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LUT_LEARN_OVER_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LUT_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LUT_AGEOUT_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LUT_LRN_LIMITNO_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_L2_LRN_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_L2_LRN_OVER_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_UNKN_L2_MC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_UNKN_IP4_MC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_UNKN_IP6_MC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_UNKN_MC_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LUT_BC_FLOOD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LUT_UNKN_MC_FLOOD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LUT_UNKN_UC_FLOOD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_L2_TBL_FLUSH_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_L2_TBL_FLUSH_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_VLAN_PORT_ACCEPT_FRAME_TYPE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_VLAN_INGRESS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_VLAN_EGRESS_TAG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_VLAN_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_VLAN_PB_VID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SVLAN_UPLINK_PMSK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SVLAN_P_SVID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SVLAN_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SVLAN_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_VLAN_PPB_VLAN_VAL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_VLAN_PORT_PPB_VLAN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MSTI_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL00_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL01_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL02_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL03_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL04_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL08_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL0D_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL0E_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL10_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL11_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL12_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL13_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL18_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL1A_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL20_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL21_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL22_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL_CDP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CTRL_SSTP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMA_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_L2_SRC_PORT_PERMIT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STORM_CTRL_UM_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STORM_CTRL_UC_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STORM_CTRL_MC_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STORM_CTRL_BC_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STORM_CTRL_UM_METER_IDX_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STORM_CTRL_UC_METER_IDX_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STORM_CTRL_MC_METER_IDX_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STORM_CTRL_BC_METER_IDX_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IGR_BWCTRL_P_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IGR_BWCTRL_GLB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_METER_TB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_METER_GLB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_METER_LB_EXCEED_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_METER_PKT_RATE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_PRIVATE_REASON_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_ACL_REASON_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_CF_REASON_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_PORT_TX_MIB_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_PORT_RX_MIB_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_PORT_OAM_MIB_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_BRIDGE_DOT1DTPLEARNEDENTRYDISCARDS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_ACL_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_ACL_CNT_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_ACL_CNT_TYPE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_ACL_CNT_RST_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_PORT_RST_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_RST_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_STAT_RST_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_Q_TX_FRAMES_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_MPCP_RX_DISC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_EPON_FEC_CORRECTED_BLOCKS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_EPON_FEC_UNCORRECTED_BLOCKS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_EPON_FEC_CODING_VIO_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_NOT_BROADCAST_BIT_NOT_ONU_LLID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_BROADCAST_BIT_PLUS_ONU_LLID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_BROADCAST_NOT_ONUID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_CRC8_ERRORS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_LLID_RX_BROADCAST_DROP_FRAMES_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_MPCP_TX_REPORT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_MPCP_EX_GATE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_ONUID_NOT_BROADCAST_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_STAT_DOT3_LLIDRXFRAMESDROP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_MPCP_TX_REG_REQ_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DOT3_MPCP_TX_REG_ACK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OMCI_DROP_PKT_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OMCI_TX_PKT_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OMCI_RX_PKT_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OMCI_TX_BYTE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OMCI_RX_BYTE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OMCI_CRC_ERROR_PKT_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_DROP_ALL_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PAUSE_ALL_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_GLB_FCOFF_HI_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_GLB_FCOFF_LO_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_GLB_HI_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_GLB_LO_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_P_HI_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_P_LO_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_P_FCOFF_HI_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_P_FCOFF_LO_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_Q_EGR_DROP_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_P_EGR_DROP_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_Q_EGR_GAP_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_P_EGR_GAP_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_P_Q_EGR_DROP_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_DBG_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CLR_MAX_USED_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_TOTAL_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PE_USED_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_Q_USED_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_TL_USED_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PUB_USED_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PUB_FCOFF_USED_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_P_USED_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_P_DBG_PKT_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PON_GLB_HI_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PON_GLB_LO_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PON_P_HI_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PON_P_LO_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PON_Q_EGR_DROP_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PON_Q_EGR_GAP_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_TH_TX_PREFET_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FC_PON_Q_EGR_FC_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PAGES_BEFORE_FCDROP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PAUSE_TIME_GLB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SC_P_CTRL_0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SC_P_CTRL_1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_QOS_INTPRI_TO_QID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_QOS_PORT_QMAP_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_QOS_PRI_REMAP_IN_CPU_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_LLID_SIDMAP_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_QOS_1Q_PRI_REMAP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_QOS_DSCP_REMAP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_QOS_PB_PRI_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PRI_SEL_TBL_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PRI_SEL_TBL_CTRL2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DSCP_WEIGHT_SEL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMK_DOT1Q_RMK_EN_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMK_1Q_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMK_DSCP_RMK_EN_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMK_DSCP_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMK_DSCP_INT_PRI_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMK_P_DSCP_SEL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMK_P_1P_SEL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WFQ_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EGR_BWCTRL_P_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LINE_RATE_1G_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LINE_RATE_500M_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LINE_RATE_100M_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LINE_RATE_10M_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OUTPUT_DROP_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OUTPUT_DROP_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WFQ_PORT_CFG0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WFQ_PORT_CFG1_7_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_WFQ_TYPE_PORT_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_APR_EN_PORT_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CPU_PORT_RATE_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_APR_METER_PORT_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_P_QUEUE_EMPTY_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_ACL_TEMPLATE_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CF_OP_DS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CF_OP_US_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CF_VALID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CF_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RMK_DSCP_CF_PRI_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_ACL_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_ACL_PERMIT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_ACL_ACTION_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_ACL_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RNG_CHK_VID_RNG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RNG_CHK_IP_RNG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RNG_CHK_L4PORT_RNG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RNG_CHK_PKTLEN_RNG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OAM_P_CTRL_0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OAM_P_CTRL_1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OAM_CTRL_0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_OAM_CTRL_1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_HSB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_HSB_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_HSA_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_HSA_TX_DBG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_HSARAM_5_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DBG_EP_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PAUSE_ALL_LW_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_HYS_PUSAL_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PORT_VM_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PORT_VM_RX_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PORT_VM_TX_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IGMP_GLB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IGMP_P_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_TBL_ACCESS_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_TBL_ACCESS_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_TBL_ACCESS_WR_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_TBL_ACCESS_RD_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PARSER_FIELD_SELTOR_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_SID_TO_QID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_QUEUE_SEL_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_QUEUE_SEL_IND_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_DPRU_RPT_PRD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_PIR_CIR_IFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_PORT_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_MODE_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PBO_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PBO_BASE_ADDR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_SID_STOP_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_SID_GLB_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_SID_RPV_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PONIP_DBG_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PONIP_TOTAL_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PONIP_SID_USED_PAGE_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BYTE_TOKEN_METER_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DBG_HSA_EP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PONIP_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_ARB_TIMEOUT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DSCRUNOUT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DRN_CMD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IP_MSTBASE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_DSC_USAGE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_RAM_DVSCFG_0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_RAM_DVSCFG_1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_RAM_DVSCFG_2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_US_FIFO_CTL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_IPSTS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_SID2QID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_DSCCTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_BW_THRES_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_DBA_IFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_FRC_RPT_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MOCIR_FRC_MD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MOCIR_FRC_VAL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_RPT_QSET_NUM_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_RPT_LVL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MOCIR_BPT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MOCIR_TH_H_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MOCIR_TH_L_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_OLT_BW_MTR_FULL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_TB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_SCH_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_QID_CIR_RATE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_QID_PIR_RATE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_SCH_QMAP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_TCONT_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_WFQ_TYPE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_WFQ_LEAKY_BUCKET_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PON_WFQ_WEIGHT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_INT_DLT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_RESET_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_VERSION_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_TEST_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_AES_BYPASS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_INTR_MASK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_INTR_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_INTR_DLT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_INTR_MASK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_INTR_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_ONU_ID_STATUS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_PLOAM_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_LOS_CFG_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_SUPERFRAME_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_PLOAM_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_PLOAM_MSG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_ALLOC_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_ALLOC_WR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_ALLOC_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_PORT_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_PORT_WR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_PORT_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_PORT_CNTR_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_PORT_CNTR_STAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_BIP_ERR_BLK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_BIP_ERR_BIT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_FEC_CORRECT_BIT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_FEC_CORRECT_BYTE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_FEC_CORRECT_CW_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_FEC_UNCOR_CW_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_LOM_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_PLOAM_ACPT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_PLOAM_FAIL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_BWM_FAIL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_BWM_INV_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_ACTIVE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_BWM_ACPT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_GEM_LOS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_HEC_CORRECT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_GEM_IDLE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_GEM_FAIL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_GEM_NON_IDLE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_MISC_CNTR_PLEN_CORRECT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_OMCI_PTI_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_ETH_PTI_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DS_FEC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PLOAM_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GEM_CNTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GEM_TOKEN_A_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BWMAP_CAP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BWMAP_BUF_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_TCONT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GEM_L_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GEM_H_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_DS_TRAFFIC_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_BWMAP_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_BWMAP_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_BWMAP_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_AES_INTR_DLT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_AES_INTR_MASK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_AES_INTR_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_AES_KEY_SWITCH_REQ_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_AES_KEY_SWITCH_TIME_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_AES_KEY_WORD_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_AES_WORD_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CTL_INFO_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CTL_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CIPHER_1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CIPHER_2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_KEY_EXPN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_RX_CNTR_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_RX_CNTR_STAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_FWD_CNTR_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_FWD_CNTR_STAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_MISC_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_MISC_CNTR_STAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_MC_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_MC_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_MC_WR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_MC_RD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_FRM_TIMEOUT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_MC_ADDR_PTN_IPV4_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_DS_MC_ADDR_PTN_IPV6_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CLASSIFY_BUF_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CLASSIFY_CNTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_ASSEMBLY_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MC_FILTER_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_INTR_DLT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_INTR_MASK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_INTR_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_ONU_ID_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_WRITE_PROTECT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_TX_PATTERN_CTL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_TX_PATTERN_BG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_TX_PATTERN_FG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_MIN_DELAY_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_EQD_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_LASER_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_BOH_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_BOH_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_PLOAM_IND_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_PLOAM_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_PLOAM_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_MISC_CNTR_IDX_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_MISC_CNTR_STAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_RDI_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_DG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_OPTIC_SD_TH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GTC_US_PROC_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BWM_TBL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BWM_MEM0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_BWM_MEM1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PLOAM_A_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_DBR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_US_INTR_DLT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_US_INTR_MASK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_US_INTR_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_US_PTI_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_US_ETH_GEM_RX_CNTR_IDX_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_US_ETH_GEM_RX_CNTR_STAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_US_PTN_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_PCFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GEM_BCNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FIFO_BANK0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_FIFO_BANK1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IDLE_BCNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GEM_PCNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_US_PORT_MAP_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_GPON_GEM_US_BYTE_STAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_TCONT_IDLE_BYTE_STAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_FEC_CONFIG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_ASIC_TIMING_ADJUST1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_ASIC_TIMING_ADJUST2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_RGSTR1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_RGSTR2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_DEBUG1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_DEBUG2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_TIMER_CONFIG1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_INTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_SYNC_TIME_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LASER_ON_OFF_TIME_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MIN_GRANT_START_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_MAX_GRANT_START_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_TIME_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EP_MISC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_LLID_TABLE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_MPCP_CTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_GRANT_LIST0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_GRANT_LIST1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_GRANT_LIST2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_TX_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_DECRYP_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_DECRYP_KEY0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_DECRYP_KEY1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_SCB_DECRYP_KEY0_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_SCB_DECRYP_KEY1_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_MISC_CFG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_LOCAL_TIME_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_REG_ACK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_REPORT_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_GATE_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_GRANT_SHIFT_START_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_THRESHOLD_REPORT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_GATE_ANA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_GATE_ANA_CNT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_TBL_ACCESS_STS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_EPON_TBL_ACCESS_RD_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_GLB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_GLB_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_ACL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_CVLAN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_DPM_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_L2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_MLTVLAN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_SVLAN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_EAV_AFBK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_INTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_LED_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_PER_PORT_MAC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_SDSREG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_SWCORE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_EPON_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_RMA_ATTACK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_BIST_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_EGR_OUTQ_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_EGR_SCH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_HSA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_METER_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_MIB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RGF_VER_ALE_PISO_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_GLB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_GLB_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_ACL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_CVLAN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_DPM_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_L2_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_MLTVLAN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_SVLAN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_EAV_AFBK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_INTR_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_LED_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_PER_PORT_MAC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_SDSREG_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_SWCORE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_EPON_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_RMA_ATTACK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_BIST_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_EGR_OUTQ_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_EGR_SCH_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_CF_US_1P_REMARK_EN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IP4MC_EGRESS_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_IP6MC_EGRESS_MODE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_HSA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_METER_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_MIB_CTRL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_reg_list[INT_RTL9601B_RSVD_ALE_PISO_RTL9601B],
#endif
};

static rtk_table_t *rtl9601b_table_list[] =
{
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_HSB_DATA_TABLE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_HSA_DATA_NAT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_HSA_DATA_TABLE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_ACL_ACTION_TABLE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_ACL_DATA_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_ACL_MASK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_CF_ACTION_DS_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_CF_ACTION_US_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_CF_MASK_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_CF_MASK_L34_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_CF_RULE_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_CF_RULE_ENHANCED_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_L2_MC_DSL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_L2_UC_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_L3_MC_DSL_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_VLAN_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_EPON_GRANT_RTL9601B],
#endif
#if defined(CONFIG_SDK_RTL9601B)
    &rtk_rtl9601b_table_list[INT_RTL9601B_HSA_DEBUG_DATA_RTL9601B],
#endif
};

static rtk_portmask_t rtl9601b_portmask_list[] =
{
    { .bits[0]=0x00000000, .bits[1]=0x00000000 }, /* reserved for no portlist case */
};

#endif /* end of defined(CONFIG_SDK_RTL9601B) */


/* RTL9601B mac driver service APIs */
rt_macdrv_t rtl9601b_macdrv =
{
    rtl9601b_init,          /* fMdrv_init        */
    rtl9601b_miim_read,     /* fMdrv_miim_read   */
    rtl9601b_miim_write,    /* fMdrv_miim_write  */
    rtl9601b_table_read,    /* fMdrv_table_read  */
    rtl9601b_table_write,   /* fMdrv_table_write */
    rtl9601b_table_clear,   /* fMdrv_table_clear */
}; /* end of rtl9601b_macdrv */


/* Definition RTL9601B Rev. A major driver */
rt_driver_t rtl9601b_a_driver =
{
    /* type            */ RT_DRIVER_RTL9601B,
    /* RTL chip ID     */ RTL9601B_CHIP_ID,
    /* RTL revision ID */ CHIP_REV_ID_0,
    /* register list   */ rtk_rtl9601b_reg_list,
    /* table list      */ rtk_rtl9601b_table_list,
    /* mac driver      */ &rtl9601b_macdrv,
    /* reg index max   */ RTL9601B_REG_LIST_END,
    /* regField index max */ RTL9601B_REGFIELD_LIST_END,
    /* table index max */ RTL9601B_TABLE_LIST_END,
}; /* end of rtl9601b_a_driver */
