/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 51237 $
 * $Date: 2014-09-11 19:33:55 +0800 (Thu, 11 Sep 2014) $
 *
 * Purpose : chip table declaration in the SDK.
 *
 * Feature : chip table declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/rtl9601b/rtk_rtl9601b_table_struct.h>
#include <hal/chipdef/rtl9601b/rtk_rtl9601b_tableField_list.h>

rtk_table_t rtk_rtl9601b_table_list[] =
{
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_HSB_DATA_TABLE */
        /* access table type */     0,
        /* table size */            1,
        /* total data registers */  18,
        /* total field numbers */   RTL9601B_HSB_DATA_TABLEFIELD_LIST_END,
        /* table fields */          RTL9601B_HSB_DATA_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_HSA_DATA_TABLE */
        /* access table type */     0,
        /* table size */            1,
        /* total data registers */  7,
        /* total field numbers */   RTL9601B_HSA_DATA_TABLEFIELD_LIST_END,
        /* table fields */          RTL9601B_HSA_DATA_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_HSA_DEBUG_DATA */
        /* access table type */     0,
        /* table size */            1,
        /* total data registers */  4,
        /* total field numbers */   RTL9601B_HSA_DEBUG_DATAFIELD_LIST_END,
        /* table fields */          RTL9601B_HSA_DEBUG_DATA_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_ACL_ACTION_TABLE */
        /* access table type */     3,
        /* table size */            64,
        /* total data registers */  1,
        /* total field numbers */   RTL9601B_ACL_ACTION_TABLEFIELD_LIST_END,
        /* table fields */          RTL9601B_ACL_ACTION_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_ACL_DATA */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   RTL9601B_ACL_DATAFIELD_LIST_END,
        /* table fields */          RTL9601B_ACL_DATA_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_ACL_MASK */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   RTL9601B_ACL_MASKFIELD_LIST_END,
        /* table fields */          RTL9601B_ACL_MASK_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_CF_ACTION_DS */
        /* access table type */     5,
        /* table size */            256,
        /* total data registers */  2,
        /* total field numbers */   RTL9601B_CF_ACTION_DSFIELD_LIST_END,
        /* table fields */          RTL9601B_CF_ACTION_DS_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_CF_ACTION_US */
        /* access table type */     5,
        /* table size */            256,
        /* total data registers */  2,
        /* total field numbers */   RTL9601B_CF_ACTION_USFIELD_LIST_END,
        /* table fields */          RTL9601B_CF_ACTION_US_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_CF_MASK */
        /* access table type */     4,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   RTL9601B_CF_MASKFIELD_LIST_END,
        /* table fields */          RTL9601B_CF_MASK_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_CF_MASK_L34 */
        /* access table type */     4,
        /* table size */            32,
        /* total data registers */  5,
        /* total field numbers */   RTL9601B_CF_MASK_L34FIELD_LIST_END,
        /* table fields */          RTL9601B_CF_MASK_L34_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_CF_RULE */
        /* access table type */     4,
        /* table size */            64,
        /* total data registers */  5,
        /* total field numbers */   RTL9601B_CF_RULEFIELD_LIST_END,
        /* table fields */          RTL9601B_CF_RULE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_CF_RULE_ENHANCED */
        /* access table type */     4,
        /* table size */            32,
        /* total data registers */  5,
        /* total field numbers */   RTL9601B_CF_RULE_ENHANCEDFIELD_LIST_END,
        /* table fields */          RTL9601B_CF_RULE_ENHANCED_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_L2_MC_DSL */
        /* access table type */     0,
        /* table size */            264,
        /* total data registers */  4,
        /* total field numbers */   RTL9601B_L2_MC_DSLFIELD_LIST_END,
        /* table fields */          RTL9601B_L2_MC_DSL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_L2_UC */
        /* access table type */     0,
        /* table size */            264,
        /* total data registers */  4,
        /* total field numbers */   RTL9601B_L2_UCFIELD_LIST_END,
        /* table fields */          RTL9601B_L2_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_L3_MC_DSL */
        /* access table type */     0,
        /* table size */            264,
        /* total data registers */  4,
        /* total field numbers */   RTL9601B_L3_MC_DSLFIELD_LIST_END,
        /* table fields */          RTL9601B_L3_MC_DSL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_VLAN */
        /* access table type */     1,
        /* table size */            4096,
        /* total data registers */  1,
        /* total field numbers */   RTL9601B_VLANFIELD_LIST_END,
        /* table fields */          RTL9601B_VLAN_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9601B)
    {   /* table name               INT_RTL9601B_RTL9601B_EPON_GRANT */
        /* access table type */     0,
        /* table size */            511,
        /* total data registers */  2,
        /* total field numbers */   RTL9601B_EPON_GRANTFIELD_LIST_END,
        /* table fields */          RTL9601B_EPON_GRANT_FIELDS
    },
#endif
};

