/*
 *  ## Please DO NOT edit this file!! ##
 *  This file is auto-generated from the register source files.
 *  Any modifications to this file will be LOST when it is re-generated.
 *
 *  ----------------------------------------------------------------
 *  (C) Copyright 2009 Realtek Semiconductor Corp.
 *
 *  This program is the proprietary software of Realtek Semiconductor
 *  Corporation and/or its licensors, and only be used, duplicated,
 *  modified or distributed under the authorized license from Realtek.
 *
 *  ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 *  THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 *  ----------------------------------------------------------------
 *  Purpose: chip register definition and structure of APOLLO
 *
 *  ----------------------------------------------------------------
 */

#ifndef __APOLLO_TABLE_STRUCT_H__
#define __APOLLO_TABLE_STRUCT_H__

#include <hal/chipdef/allmem.h>

typedef enum apollo_hsb_dataField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    HSB_DATA_SPAtf = 0,
    HSB_DATA_USER_FIELD_15tf,
    HSB_DATA_USER_FIELD_14tf,
    HSB_DATA_USER_FIELD_13tf,
    HSB_DATA_USER_FIELD_12tf,
    HSB_DATA_USER_FIELD_11tf,
    HSB_DATA_USER_FIELD_10tf,
    HSB_DATA_USER_FIELD_9tf,
    HSB_DATA_USER_FIELD_8tf,
    HSB_DATA_USER_FIELD_7tf,
    HSB_DATA_USER_FIELD_6tf = 10,
    HSB_DATA_USER_FIELD_5tf,
    HSB_DATA_USER_FIELD_4tf,
    HSB_DATA_USER_FIELD_3tf,
    HSB_DATA_USER_FIELD_2tf,
    HSB_DATA_USER_FIELD_1tf,
    HSB_DATA_USER_FIELD_0tf,
    HSB_DATA_USER_VALIDtf,
    HSB_DATA_CKS_OK_L4tf,
    HSB_DATA_CKS_OK_L3tf,
    HSB_DATA_TTL_GT1tf = 20,
    HSB_DATA_TTL_GT5tf,
    HSB_DATA_GRE_IFtf,
    HSB_DATA_ICMP_IFtf,
    HSB_DATA_UDP_IFtf,
    HSB_DATA_TCP_IFtf,
    HSB_DATA_PPPOE_SESSIONtf,
    HSB_DATA_DIPtf,
    HSB_DATA_SIPtf,
    HSB_DATA_TOS_DSCPtf,
    HSB_DATA_IP_TYPEtf = 30,
    HSB_DATA_PTP_IFtf,
    HSB_DATA_OMAPDUtf,
    HSB_DATA_RLPP_IFtf,
    HSB_DATA_RLDP_IFtf,
    HSB_DATA_LLC_OTHERtf,
    HSB_DATA_PPPOE_IFtf,
    HSB_DATA_SNAP_IFtf,
    HSB_DATA_ETHER_TYPEtf,
    HSB_DATA_CTAGtf,
    HSB_DATA_CTAG_IFtf = 40,
    HSB_DATA_STAGtf,
    HSB_DATA_STAG_IFtf,
    HSB_DATA_CPUTAG_L3Ctf,
    HSB_DATA_CPUTAG_L4Ctf,
    HSB_DATA_CPUTAG_TXPMSKtf,
    HSB_DATA_CPUTAG_EFID_ENtf,
    HSB_DATA_CPUTAG_EFIDtf,
    HSB_DATA_CPUTAG_PRISELtf,
    HSB_DATA_CPUTAG_PRItf,
    HSB_DATA_CPUTAG_KEEPtf = 50,
    HSB_DATA_CPUTAG_VSELtf,
    HSB_DATA_CPUTAG_DISLRNtf,
    HSB_DATA_CPUTAG_PSELtf,
    HSB_DATA_CPUTAG_EXTSPAtf,
    HSB_DATA_CPUTAG_PPPOE_ACTtf,
    HSB_DATA_CPUTAG_PPPOE_IDXtf,
    HSB_DATA_CPUTAG_L2BRtf,
    HSB_DATA_CPUTAG_PON_SIDtf,
    HSB_DATA_CPUTAG_DSL_VCMSKtf,
    HSB_DATA_CPUTAG_IFtf = 60,
    HSB_DATA_SAtf,
    HSB_DATA_DAtf,
    HSB_DATA_PON_IDXtf,
    HSB_DATA_PKT_LENtf,
#endif
    HSB_DATAFIELD_LIST_END = 65
} apollo_hsb_dataField_list_t;

typedef enum apollo_hsa_dataField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    HSA_DATA_RNG_NHSAB_ENDSCtf = 0,
    HSA_DATA_RNG_NHSAB_BGDSCtf,
    HSA_DATA_RNG_NHSAB_QIDtf,
    HSA_DATA_RNG_NHSAB_RESERVEtf,
    HSA_DATA_RNG_NHSAB_CPUPRItf,
    HSA_DATA_RNG_NHSAB_FWDRSNtf,
    HSA_DATA_RNG_NHSAB_PON_SIDtf,
    HSA_DATA_RNG_NHSAB_VC_SPAtf,
    HSA_DATA_RNG_NHSAB_VC_MASKtf,
    HSA_DATA_RNG_NHSAB_EXT_MASKtf,
    HSA_DATA_RNG_NHSAB_DPMtf = 10,
    HSA_DATA_RNG_NHSAB_SPAtf,
    HSA_DATA_RNG_NHSAB_PKTLENtf,
    HSA_DATA_RNG_NHSAC_UNTAGSETtf,
    HSA_DATA_RNG_NHSAC_CTAG_ACTtf,
    HSA_DATA_RNG_NHSAC_VIDZEROtf,
    HSA_DATA_RNG_NHSAC_PRITAG_IFtf,
    HSA_DATA_RNG_NHSAC_CTAG_IFtf,
    HSA_DATA_RNG_NHSAC_VIDtf,
    HSA_DATA_RNG_NHSAC_CFItf,
    HSA_DATA_RNG_NHSAC_PRItf = 20,
    HSA_DATA_RNG_NHSAS_STAG_IFtf,
    HSA_DATA_RNG_NHSAS_STAG_TYPEtf,
    HSA_DATA_RNG_NHSAS_SP2Stf,
    HSA_DATA_RNG_NHSAS_DEItf,
    HSA_DATA_RNG_NHSAS_VIDSELtf,
    HSA_DATA_RNG_NHSAS_FRCTAGtf,
    HSA_DATA_RNG_NHSAS_FRCTAG_IFtf,
    HSA_DATA_RNG_NHSAS_SVIDtf,
    HSA_DATA_RNG_NHSAS_SVIDXtf,
    HSA_DATA_RNG_NHSAS_PKT_SPRItf = 30,
    HSA_DATA_RNG_NHSAS_SPRItf,
    HSA_DATA_RNG_NHSAM_USER_PRItf,
    HSA_DATA_RNG_NHSAM_1P_REMtf,
    HSA_DATA_RNG_NHSAM_1P_REM_ENtf,
    HSA_DATA_RNG_NHSAM_DSCP_REMtf,
    HSA_DATA_RNG_NHSAM_DSCP_REM_ENtf,
    HSA_DATA_RNG_NHSAF_REGEN_CRCtf,
    HSA_DATA_RNG_NHSAF_KEEPtf,
    HSA_DATA_RNG_NHSAF_PTPtf,
    HSA_DATA_RNG_NHSAF_IPV4tf = 40,
    HSA_DATA_RNG_NHSAF_IPV6tf,
    HSA_DATA_RNG_NHSAF_RFC1042tf,
    HSA_DATA_RNG_NHSAF_PPPOE_IFtf,
    HSA_DATA_RNG_NHSAP_PTP_RESVtf,
    HSA_DATA_RNG_NHSAP_PTP_ACTtf,
    HSA_DATA_RNG_NHSAP_PTP_SECtf,
    HSA_DATA_RNG_NHSAP_PTP_NSECtf,
#endif
    HSA_DATAFIELD_LIST_END = 48
} apollo_hsa_dataField_list_t;

typedef enum apollo_hsa_data_natField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    HSA_DATA_NAT_RNG_NHSAB_ENDSCtf = 0,
    HSA_DATA_NAT_RNG_NHSAB_BGDSCtf,
    HSA_DATA_NAT_RNG_NHSAB_QIDtf,
    HSA_DATA_NAT_RNG_NHSAB_RESERVEtf,
    HSA_DATA_NAT_RNG_NHSAB_CPUPRItf,
    HSA_DATA_NAT_RNG_NHSAB_FWDRSNtf,
    HSA_DATA_NAT_RNG_NHSAB_PON_SIDtf,
    HSA_DATA_NAT_RNG_NHSAB_VC_SPAtf,
    HSA_DATA_NAT_RNG_NHSAB_VC_MASKtf,
    HSA_DATA_NAT_RNG_NHSAB_EXT_MASKtf,
    HSA_DATA_NAT_RNG_NHSAB_DPMtf = 10,
    HSA_DATA_NAT_RNG_NHSAB_SPAtf,
    HSA_DATA_NAT_RNG_NHSAB_PKTLENtf,
    HSA_DATA_NAT_RNG_NHSAC_UNTAGSETtf,
    HSA_DATA_NAT_RNG_NHSAC_CTAG_ACTtf,
    HSA_DATA_NAT_RNG_NHSAC_VIDZEROtf,
    HSA_DATA_NAT_RNG_NHSAC_PRITAG_IFtf,
    HSA_DATA_NAT_RNG_NHSAC_CTAG_IFtf,
    HSA_DATA_NAT_RNG_NHSAC_VIDtf,
    HSA_DATA_NAT_RNG_NHSAC_CFItf,
    HSA_DATA_NAT_RNG_NHSAC_PRItf = 20,
    HSA_DATA_NAT_RNG_NHSAS_STAG_IFtf,
    HSA_DATA_NAT_RNG_NHSAS_STAG_TYPEtf,
    HSA_DATA_NAT_RNG_NHSAS_SP2Stf,
    HSA_DATA_NAT_RNG_NHSAS_DEItf,
    HSA_DATA_NAT_RNG_NHSAS_VIDSELtf,
    HSA_DATA_NAT_RNG_NHSAS_FRCTAGtf,
    HSA_DATA_NAT_RNG_NHSAS_FRCTAG_IFtf,
    HSA_DATA_NAT_RNG_NHSAS_SVIDtf,
    HSA_DATA_NAT_RNG_NHSAS_SVIDXtf,
    HSA_DATA_NAT_RNG_NHSAS_PKT_SPRItf = 30,
    HSA_DATA_NAT_RNG_NHSAS_SPRItf,
    HSA_DATA_NAT_RNG_NHSAM_USER_PRItf,
    HSA_DATA_NAT_RNG_NHSAM_1P_REMtf,
    HSA_DATA_NAT_RNG_NHSAM_1P_REM_ENtf,
    HSA_DATA_NAT_RNG_NHSAM_DSCP_REMtf,
    HSA_DATA_NAT_RNG_NHSAM_DSCP_REM_ENtf,
    HSA_DATA_NAT_RNG_NHSAF_REGEN_CRCtf,
    HSA_DATA_NAT_RNG_NHSAF_KEEPtf,
    HSA_DATA_NAT_RNG_NHSAF_PTPtf,
    HSA_DATA_NAT_RNG_NHSAF_IPV4tf = 40,
    HSA_DATA_NAT_RNG_NHSAF_IPV6tf,
    HSA_DATA_NAT_RNG_NHSAF_RFC1042tf,
    HSA_DATA_NAT_RNG_NHSAF_PPPOE_IFtf,
    HSA_DATA_NAT_RNG_NHSAN_L3Rtf,
    HSA_DATA_NAT_RNG_NHSAN_ORGtf,
    HSA_DATA_NAT_RNG_NHSAN_L2TRANStf,
    HSA_DATA_NAT_RNG_NHSAN_L34TRANStf,
    HSA_DATA_NAT_RNG_NHSAN_SRC_MODtf,
    HSA_DATA_NAT_RNG_NHSAN_PPPOE_IDXtf,
    HSA_DATA_NAT_RNG_NHSAN_PPPOE_ACTtf = 50,
    HSA_DATA_NAT_RNG_NHSAN_SMAC_IDXtf,
    HSA_DATA_NAT_RNG_NHSAN_L3CKSUMtf,
    HSA_DATA_NAT_RNG_NHSAN_L4CKSUMtf,
    HSA_DATA_NAT_RNG_NHSAN_NEWIPtf,
    HSA_DATA_NAT_RNG_NHSAN_NEWPORTtf,
    HSA_DATA_NAT_RNG_NHSAN_NEWDMACtf,
    HSA_DATA_NAT_RNG_NHSAN_TTLM1_EXTMASKtf,
    HSA_DATA_NAT_RNG_NHSAN_TTLM1_PMASKtf,
#endif
    HSA_DATA_NATFIELD_LIST_END = 59
} apollo_hsa_data_natField_list_t;

typedef enum apollo_acl_actionField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    ACL_ACTION_CFACTtf = 0,
    ACL_ACTION_CFIDXtf,
    ACL_ACTION_ACLINTtf,
    ACL_ACTION_PRIACTtf,
    ACL_ACTION_PRIDXtf,
    ACL_ACTION_FWDACTtf,
    ACL_ACTION_FWD_PMSKtf,
    ACL_ACTION_POLICACTtf,
    ACL_ACTION_METER_IDXtf,
    ACL_ACTION_SACTtf,
    ACL_ACTION_SVIDXtf = 10,
    ACL_ACTION_CACTtf,
    ACL_ACTION_CVIDXtf,
#endif
    ACL_ACTIONFIELD_LIST_END = 13
} apollo_acl_actionField_list_t;

typedef enum apollo_acl_dataField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    ACL_DATA_VALIDtf = 0,
    ACL_DATA_FIELD7tf,
    ACL_DATA_FIELD6tf,
    ACL_DATA_FIELD5tf,
    ACL_DATA_FIELD4tf,
    ACL_DATA_FIELD3tf,
    ACL_DATA_FIELD2tf,
    ACL_DATA_FIELD1tf,
    ACL_DATA_FIELD0tf,
    ACL_DATA_PMSKtf,
    ACL_DATA_TAGStf = 10,
    ACL_DATA_TYPEtf,
#endif
    ACL_DATAFIELD_LIST_END = 12
} apollo_acl_dataField_list_t;

typedef enum apollo_acl_data2Field_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    ACL_DATA2_VALIDtf = 0,
    ACL_DATA2_FIELD3_0tf,
    ACL_DATA2_FIELD2_0tf,
    ACL_DATA2_FIELD1_0tf,
    ACL_DATA2_FIELD0_0tf,
    ACL_DATA2_PMSK_0tf,
    ACL_DATA2_TAGS_0tf,
    ACL_DATA2_TYPE_0tf,
    ACL_DATA2_FIELD2_1tf,
    ACL_DATA2_FIELD1_1tf,
    ACL_DATA2_FIELD0_1tf = 10,
    ACL_DATA2_PMSK_1tf,
    ACL_DATA2_TAGS_1tf,
    ACL_DATA2_TYPE_1tf,
#endif
    ACL_DATA2FIELD_LIST_END = 14
} apollo_acl_data2Field_list_t;

typedef enum apollo_acl_maskField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    ACL_MASK_FIELD7tf = 0,
    ACL_MASK_FIELD6tf,
    ACL_MASK_FIELD5tf,
    ACL_MASK_FIELD4tf,
    ACL_MASK_FIELD3tf,
    ACL_MASK_FIELD2tf,
    ACL_MASK_FIELD1tf,
    ACL_MASK_FIELD0tf,
    ACL_MASK_PMSKtf,
    ACL_MASK_TAGStf,
    ACL_MASK_TYPEtf = 10,
#endif
    ACL_MASKFIELD_LIST_END = 11
} apollo_acl_maskField_list_t;

typedef enum apollo_acl_mask2Field_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    ACL_MASK2_FIELD3_0tf = 0,
    ACL_MASK2_FIELD2_0tf,
    ACL_MASK2_FIELD1_0tf,
    ACL_MASK2_FIELD0_0tf,
    ACL_MASK2_PMSK_0tf,
    ACL_MASK2_TAGS_0tf,
    ACL_MASK2_TYPE_0tf,
    ACL_MASK2_FIELD2_1tf,
    ACL_MASK2_FIELD1_1tf,
    ACL_MASK2_FIELD0_1tf,
    ACL_MASK2_PMSK_1tf = 10,
    ACL_MASK2_TAGS_1tf,
    ACL_MASK2_TYPE_1tf,
#endif
    ACL_MASK2FIELD_LIST_END = 13
} apollo_acl_mask2Field_list_t;

typedef enum apollo_cf_action_dsField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    CF_ACTION_DS_UNI_PMSKtf = 0,
    CF_ACTION_DS_UNI_ACTtf,
    CF_ACTION_DS_CF_PRItf,
    CF_ACTION_DS_CFPRI_ACTtf,
    CF_ACTION_DS_CPRI_ACTtf,
    CF_ACTION_DS_CVID_ACTtf,
    CF_ACTION_DS_TAG_PRItf,
    CF_ACTION_DS_TAG_VIDtf,
    CF_ACTION_DS_CACTtf,
    CF_ACTION_DS_CSACTtf,
#endif
    CF_ACTION_DSFIELD_LIST_END = 10
} apollo_cf_action_dsField_list_t;

typedef enum apollo_cf_action_usField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    CF_ACTION_US_ASSIGN_IDXtf = 0,
    CF_ACTION_US_SID_ACTtf,
    CF_ACTION_US_CSPRI_ACTtf,
    CF_ACTION_US_CSVID_ACTtf,
    CF_ACTION_US_TAG_PRItf,
    CF_ACTION_US_TAG_VIDtf,
    CF_ACTION_US_CACTtf,
    CF_ACTION_US_CSACTtf,
#endif
    CF_ACTION_USFIELD_LIST_END = 8
} apollo_cf_action_usField_list_t;

typedef enum apollo_cf_maskField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    CF_MASK_ETH_TYPE_0tf = 0,
    CF_MASK_U_D_0tf,
    CF_MASK_TOS_GEMIDX_0tf,
    CF_MASK_VID_0tf,
    CF_MASK_PRI_0tf,
    CF_MASK_INTER_PRI_0tf,
    CF_MASK_IF_STAG_0tf,
    CF_MASK_IF_CTAG_0tf,
    CF_MASK_UNI_0tf,
    CF_MASK_U_D_1tf,
    CF_MASK_TOS_GEMIDX_1tf = 10,
    CF_MASK_VID_1tf,
    CF_MASK_PRI_1tf,
    CF_MASK_INTER_PRI_1tf,
    CF_MASK_IF_STAG_1tf,
    CF_MASK_IF_CTAG_1tf,
    CF_MASK_UNI_1tf,
    CF_MASK_U_D_2tf,
    CF_MASK_TOS_GEMIDX_2tf,
    CF_MASK_VID_2tf,
    CF_MASK_PRI_2tf = 20,
    CF_MASK_INTER_PRI_2tf,
    CF_MASK_IF_STAG_2tf,
    CF_MASK_IF_CTAG_2tf,
    CF_MASK_UNI_2tf,
    CF_MASK_U_D_3tf,
    CF_MASK_TOS_GEMIDX_3tf,
    CF_MASK_VID_3tf,
    CF_MASK_PRI_3tf,
    CF_MASK_INTER_PRI_3tf,
    CF_MASK_IF_STAG_3tf = 30,
    CF_MASK_IF_CTAG_3tf,
    CF_MASK_UNI_3tf,
#endif
    CF_MASKFIELD_LIST_END = 33
} apollo_cf_maskField_list_t;

typedef enum apollo_cf_ruleField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    CF_RULE_VALIDtf = 0,
    CF_RULE_ETH_TYPE_0tf,
    CF_RULE_U_D_0tf,
    CF_RULE_TOS_GEMIDX_0tf,
    CF_RULE_VID_0tf,
    CF_RULE_PRI_0tf,
    CF_RULE_INTER_PRI_0tf,
    CF_RULE_IF_STAG_0tf,
    CF_RULE_IF_CTAG_0tf,
    CF_RULE_UNI_0tf,
    CF_RULE_U_D_1tf = 10,
    CF_RULE_TOS_GEMIDX_1tf,
    CF_RULE_VID_1tf,
    CF_RULE_PRI_1tf,
    CF_RULE_INTER_PRI_1tf,
    CF_RULE_IF_STAG_1tf,
    CF_RULE_IF_CTAG_1tf,
    CF_RULE_UNI_1tf,
    CF_RULE_U_D_2tf,
    CF_RULE_TOS_GEMIDX_2tf,
    CF_RULE_VID_2tf = 20,
    CF_RULE_PRI_2tf,
    CF_RULE_INTER_PRI_2tf,
    CF_RULE_IF_STAG_2tf,
    CF_RULE_IF_CTAG_2tf,
    CF_RULE_UNI_2tf,
    CF_RULE_U_D_3tf,
    CF_RULE_TOS_GEMIDX_3tf,
    CF_RULE_VID_3tf,
    CF_RULE_PRI_3tf,
    CF_RULE_INTER_PRI_3tf = 30,
    CF_RULE_IF_STAG_3tf,
    CF_RULE_IF_CTAG_3tf,
    CF_RULE_UNI_3tf,
#endif
    CF_RULEFIELD_LIST_END = 34
} apollo_cf_ruleField_list_t;

typedef enum apollo_l2_mc_dslField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    L2_MC_DSL_VALIDtf = 0,
    L2_MC_DSL_NOT_SALEARNtf,
    L2_MC_DSL_FWDPRI_ENtf,
    L2_MC_DSL_FWDPRItf,
    L2_MC_DSL_EXT_MBRtf,
    L2_MC_DSL_MBRtf,
    L2_MC_DSL_DSL_MBRtf,
    L2_MC_DSL_IVL_SVLtf,
    L2_MC_DSL_L3LOOKUPtf,
    L2_MC_DSL_VID_FIDtf,
    L2_MC_DSL_MACtf = 10,
#endif
    L2_MC_DSLFIELD_LIST_END = 11
} apollo_l2_mc_dslField_list_t;

typedef enum apollo_l2_ucField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    L2_UC_VALIDtf = 0,
    L2_UC_NOT_SALEARNtf,
    L2_UC_FWDPRI_ENtf,
    L2_UC_FWDPRItf,
    L2_UC_ARP_USAGEtf,
    L2_UC_EXT_DSL_SPAtf,
    L2_UC_DA_BLKtf,
    L2_UC_SA_BLKtf,
    L2_UC_AUTHtf,
    L2_UC_AGEtf,
    L2_UC_SPAtf = 10,
    L2_UC_SAPRI_ENtf,
    L2_UC_FIDtf,
    L2_UC_EFIDtf,
    L2_UC_IVL_SVLtf,
    L2_UC_L3LOOKUPtf,
    L2_UC_CVIDtf,
    L2_UC_MACtf,
#endif
    L2_UCFIELD_LIST_END = 18
} apollo_l2_ucField_list_t;

typedef enum apollo_l3_mc_dslField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    L3_MC_DSL_VALIDtf = 0,
    L3_MC_DSL_NOT_SALEARNtf,
    L3_MC_DSL_FWDPRI_ENtf,
    L3_MC_DSL_FWDPRItf,
    L3_MC_DSL_EXT_MBRtf,
    L3_MC_DSL_MBRtf,
    L3_MC_DSL_DSL_MBRtf,
    L3_MC_DSL_GIP_ONLYtf,
    L3_MC_DSL_L3LOOKUPtf,
    L3_MC_DSL_SIP_VIDtf,
    L3_MC_DSL_GIPtf = 10,
#endif
    L3_MC_DSLFIELD_LIST_END = 11
} apollo_l3_mc_dslField_list_t;

typedef enum apollo_l3_mc_routeField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    L3_MC_ROUTE_VALIDtf = 0,
    L3_MC_ROUTE_NOT_SALEARNtf,
    L3_MC_ROUTE_FWDPRI_ENtf,
    L3_MC_ROUTE_FWDPRItf,
    L3_MC_ROUTE_EXT_MBRtf,
    L3_MC_ROUTE_MBRtf,
    L3_MC_ROUTE_DSL_MBRtf,
    L3_MC_ROUTE_GIP_ONLYtf,
    L3_MC_ROUTE_L3LOOKUPtf,
    L3_MC_ROUTE_WAN_SAtf,
    L3_MC_ROUTE_EXT_FRtf = 10,
    L3_MC_ROUTE_L3_IDXtf,
    L3_MC_ROUTE_GIPtf,
#endif
    L3_MC_ROUTEFIELD_LIST_END = 13
} apollo_l3_mc_routeField_list_t;

typedef enum apollo_vlanField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    VLAN_EXT_MBRtf = 0,
    VLAN_DSL_MBRtf,
    VLAN_IVL_SVLtf,
    VLAN_METERIDXtf,
    VLAN_POLICINGtf,
    VLAN_VBPRItf,
    VLAN_VB_ENtf,
    VLAN_FID_MSTItf,
    VLAN_UNTAGtf,
    VLAN_MBRtf,
#endif
    VLANFIELD_LIST_END = 10
} apollo_vlanField_list_t;

typedef enum apollo_arp_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    ARP_TABLE_NH_IDXtf = 0,
    ARP_TABLE_VALIDtf,
#endif
    ARP_TABLEFIELD_LIST_END = 2
} apollo_arp_tableField_list_t;

typedef enum apollo_external_ip_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    EXTERNAL_IP_TABLE_PRIORITYtf = 0,
    EXTERNAL_IP_TABLE_PRI_VALIDtf,
    EXTERNAL_IP_TABLE_NH_IDXtf,
    EXTERNAL_IP_TABLE_TYPEtf,
    EXTERNAL_IP_TABLE_VALIDtf,
    EXTERNAL_IP_TABLE_EXT_IPtf,
    EXTERNAL_IP_TABLE_INT_IPtf,
#endif
    EXTERNAL_IP_TABLEFIELD_LIST_END = 7
} apollo_external_ip_tableField_list_t;

typedef enum apollo_l3_routing_drop_trapField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    L3_ROUTING_DROP_TRAP_IS_INTERNALtf = 0,
    L3_ROUTING_DROP_TRAP_PROCESS_TYPEtf,
    L3_ROUTING_DROP_TRAP_VALIDtf,
    L3_ROUTING_DROP_TRAP_IP_MASKtf,
    L3_ROUTING_DROP_TRAP_IP_ADDRtf,
#endif
    L3_ROUTING_DROP_TRAPFIELD_LIST_END = 5
} apollo_l3_routing_drop_trapField_list_t;

typedef enum apollo_l3_routing_global_routeField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    L3_ROUTING_GLOBAL_ROUTE_IP_DOMAIN_NUMtf = 0,
    L3_ROUTING_GLOBAL_ROUTE_NH_ALGOtf,
    L3_ROUTING_GLOBAL_ROUTE_NH_IDXtf,
    L3_ROUTING_GLOBAL_ROUTE_NH_ADDR_STARTtf,
    L3_ROUTING_GLOBAL_ROUTE_NH_NUMtf,
    L3_ROUTING_GLOBAL_ROUTE_IS_INTERNALtf,
    L3_ROUTING_GLOBAL_ROUTE_PROCESS_TYPEtf,
    L3_ROUTING_GLOBAL_ROUTE_VALIDtf,
    L3_ROUTING_GLOBAL_ROUTE_IP_MASKtf,
    L3_ROUTING_GLOBAL_ROUTE_IP_ADDRtf,
#endif
    L3_ROUTING_GLOBAL_ROUTEFIELD_LIST_END = 10
} apollo_l3_routing_global_routeField_list_t;

typedef enum apollo_l3_routing_local_routeField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    L3_ROUTING_LOCAL_ROUTE_ARP_ADDR_ENDtf = 0,
    L3_ROUTING_LOCAL_ROUTE_ARP_ADDR_STARTtf,
    L3_ROUTING_LOCAL_ROUTE_DEST_NETIF_IDXtf,
    L3_ROUTING_LOCAL_ROUTE_IS_INTERNALtf,
    L3_ROUTING_LOCAL_ROUTE_PROCESS_TYPEtf,
    L3_ROUTING_LOCAL_ROUTE_VALIDtf,
    L3_ROUTING_LOCAL_ROUTE_IP_MASKtf,
    L3_ROUTING_LOCAL_ROUTE_IP_ADDRtf,
#endif
    L3_ROUTING_LOCAL_ROUTEFIELD_LIST_END = 8
} apollo_l3_routing_local_routeField_list_t;

typedef enum apollo_napt_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    NAPT_TABLE_PRItf = 0,
    NAPT_TABLE_PRI_VALIDtf,
    NAPT_TABLE_VALIDtf,
    NAPT_TABLE_HASH_IDXtf,
#endif
    NAPT_TABLEFIELD_LIST_END = 4
} apollo_napt_tableField_list_t;

typedef enum apollo_naptr_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    NAPTR_TABLE_PRIORITYtf = 0,
    NAPTR_TABLE_PRI_VALIDtf,
    NAPTR_TABLE_VALIDtf,
    NAPTR_TABLE_TCPtf,
    NAPTR_TABLE_EXTPORT_LSBtf,
    NAPTR_TABLE_EXT_IP_IDXtf,
    NAPTR_TABLE_REMOTE_HASHtf,
    NAPTR_TABLE_INT_PORTtf,
    NAPTR_TABLE_INT_IPtf,
#endif
    NAPTR_TABLEFIELD_LIST_END = 9
} apollo_naptr_tableField_list_t;

typedef enum apollo_netifField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    NETIF_MTUtf = 0,
    NETIF_EN_ROUNTINGtf,
    NETIF_MAC_MASKtf,
    NETIF_GATEWAY_MACtf,
    NETIF_VLAN_IDtf,
    NETIF_VALIDtf,
#endif
    NETIFFIELD_LIST_END = 6
} apollo_netifField_list_t;

typedef enum apollo_next_hop_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    NEXT_HOP_TABLE_NH_L2IDXtf = 0,
    NEXT_HOP_TABLE_PPPIDXtf,
    NEXT_HOP_TABLE_IFIDXtf,
    NEXT_HOP_TABLE_TYPEtf,
#endif
    NEXT_HOP_TABLEFIELD_LIST_END = 4
} apollo_next_hop_tableField_list_t;

typedef enum apollo_pppoe_tableField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    PPPOE_TABLE_SESSION_IDtf = 0,
#endif
    PPPOE_TABLEFIELD_LIST_END = 1
} apollo_pppoe_tableField_list_t;

typedef enum apollo_l34_hsaField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    L34_HSA_INTER_IFtf = 0,
    L34_HSA_REASONtf,
    L34_HSA_L34TRANStf,
    L34_HSA_L2TRANStf,
    L34_HSA_ACTIONtf,
    L34_HSA_L4_PRI_VALIDtf,
    L34_HSA_L4_PRI_SELtf,
    L34_HSA_FRAGtf,
    L34_HSA_DIFIDtf,
    L34_HSA_DVIDtf,
    L34_HSA_PPPOE_IFtf = 10,
    L34_HSA_PPPID_IDXtf,
    L34_HSA_NEXTHOP_MAC_IDXtf,
    L34_HSA_L4_CHKSUMtf,
    L34_HSA_L3_CHKSUMtf,
    L34_HSA_PORTtf,
    L34_HSA_IPtf,
#endif
    L34_HSAFIELD_LIST_END = 17
} apollo_l34_hsaField_list_t;

typedef enum apollo_l34_hsbField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    L34_HSB_L2BRIDGEtf = 0,
    L34_HSB_IPFRAG_Stf,
    L34_HSB_IPMFtf,
    L34_HSB_L4_CHKSUM_OKtf,
    L34_HSB_L3_CHKSUM_OKtf,
    L34_HSB_CPU_DIRECT_TXtf,
    L34_HSB_UDP_NO_CHKSUMtf,
    L34_HSB_PARSE_FAILtf,
    L34_HSB_PPPOE_IFtf,
    L34_HSB_SVLAN_IFtf,
    L34_HSB_TTLStf = 10,
    L34_HSB_TYPEtf,
    L34_HSB_TCP_FLAGtf,
    L34_HSB_CVLAN_IFtf,
    L34_HSB_SPAtf,
    L34_HSB_CVIDtf,
    L34_HSB_LENtf,
    L34_HSB_DPORT_L4CHKSUMtf,
    L34_HSB_PPPOE_IDtf,
    L34_HSB_DIPtf,
    L34_HSB_SIPtf = 20,
    L34_HSB_SPORT_ICMPID_CHKSUMtf,
    L34_HSB_DMACtf,
#endif
    L34_HSBFIELD_LIST_END = 23
} apollo_l34_hsbField_list_t;

typedef enum apollo_hsa_debug_dataField_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    HSA_DEBUG_DATA_TXHSA0_RESERVED_02tf = 0,
    HSA_DEBUG_DATA_TXHSA1_EPtf,
    HSA_DEBUG_DATA_TXHSA1_DSL_VCtf,
    HSA_DEBUG_DATA_TXHSA1_34PPPOEtf,
    HSA_DEBUG_DATA_TXHSA1_34SMACtf,
    HSA_DEBUG_DATA_TXHSA1_RSV0tf,
    HSA_DEBUG_DATA_TXHSA1_TTLPMSKtf,
    HSA_DEBUG_DATA_TXHSA1_TTLEXMSKtf,
    HSA_DEBUG_DATA_TXHSA1_NEWMACtf,
    HSA_DEBUG_DATA_TXHSA1_NEWPRTtf,
    HSA_DEBUG_DATA_TXHSA1_NEWIPtf = 10,
    HSA_DEBUG_DATA_TXHSA1_L4CKSUMtf,
    HSA_DEBUG_DATA_TXHSA1_L3CKSUMtf,
    HSA_DEBUG_DATA_TXHSA1_PPPOEACTtf,
    HSA_DEBUG_DATA_TXHSA1_SRC_MODtf,
    HSA_DEBUG_DATA_TXHSA1_L34TRANStf,
    HSA_DEBUG_DATA_TXHSA1_L2TRANStf,
    HSA_DEBUG_DATA_TXHSA1_ORGtf,
    HSA_DEBUG_DATA_TXHSA1_L3Rtf,
    HSA_DEBUG_DATA_TXHSA0_RESERVED_01tf,
    HSA_DEBUG_DATA_TXHSA0_SV_DEItf = 20,
    HSA_DEBUG_DATA_TXHSA0_STYPtf,
    HSA_DEBUG_DATA_TXHSA0_PKTLEN_ORItf,
    HSA_DEBUG_DATA_TXHSA0_QIDtf,
    HSA_DEBUG_DATA_TXHSA0_STDSCtf,
    HSA_DEBUG_DATA_TXHSA0_CPUPRItf,
    HSA_DEBUG_DATA_TXHSA0_SPRItf,
    HSA_DEBUG_DATA_TXHSA0_CORItf,
    HSA_DEBUG_DATA_TXHSA0_CMDYtf,
    HSA_DEBUG_DATA_TXHSA0_CRMStf,
    HSA_DEBUG_DATA_TXHSA0_CINStf = 30,
    HSA_DEBUG_DATA_TXHSA0_CVIDtf,
    HSA_DEBUG_DATA_TXHSA0_RSV1tf,
    HSA_DEBUG_DATA_TXHSA0_CFItf,
    HSA_DEBUG_DATA_TXHSA0_PTPNSECtf,
    HSA_DEBUG_DATA_TXHSA0_PTPSECtf,
    HSA_DEBUG_DATA_TXHSA0_PTPACTtf,
    HSA_DEBUG_DATA_TXHSA0_REGENCRCtf,
    HSA_DEBUG_DATA_TXHSA0_PPPOEtf,
    HSA_DEBUG_DATA_TXHSA0_RFC1042tf,
    HSA_DEBUG_DATA_TXHSA0_IPV6tf = 40,
    HSA_DEBUG_DATA_TXHSA0_IPV4tf,
    HSA_DEBUG_DATA_TXHSA0_PTPtf,
    HSA_DEBUG_DATA_TXHSA0_REMDSCP_PRItf,
    HSA_DEBUG_DATA_TXHSA0_REM1Q_PRItf,
    HSA_DEBUG_DATA_TXHSA0_REMDSCP_ENtf,
    HSA_DEBUG_DATA_TXHSA0_REM1Q_ENtf,
    HSA_DEBUG_DATA_TXHSA0_SVIDtf,
    HSA_DEBUG_DATA_TXHSA0_INSTAGtf,
    HSA_DEBUG_DATA_TXHSA0_INCTAGtf,
    HSA_DEBUG_DATA_TXHSA0_PKTLENtf = 50,
    HSA_DEBUG_DATA_TXHSA0_SPAtf,
    HSA_DEBUG_DATA_TXHSA0_DPCtf,
    HSA_DEBUG_DATA_TXHSA0_EXTMSKtf,
    HSA_DEBUG_DATA_TXHSA0_VCMSKtf,
    HSA_DEBUG_DATA_TXHSA0_PONSIDtf,
    HSA_DEBUG_DATA_TXHSA0_TRPRSNtf,
#endif
    HSA_DEBUG_DATAFIELD_LIST_END = 57
} apollo_hsa_debug_dataField_list_t;

typedef enum rtk_table_list_e
{
#if defined(CONFIG_SDK_APOLLO)
    HSB_DATAt = 0,
    HSA_DATAt,
    HSA_DATA_NATt,
    ACL_ACTIONt,
    ACL_DATAt,
    ACL_DATA2t,
    ACL_MASKt,
    ACL_MASK2t,
    CF_ACTION_DSt,
    CF_ACTION_USt,
    CF_MASKt = 10,
    CF_RULEt,
    L2_MC_DSLt,
    L2_UCt,
    L3_MC_DSLt,
    L3_MC_ROUTEt,
    VLANt,
    ARP_TABLEt,
    EXTERNAL_IP_TABLEt,
    L3_ROUTING_DROP_TRAPt,
    L3_ROUTING_GLOBAL_ROUTEt = 20,
    L3_ROUTING_LOCAL_ROUTEt,
    NAPT_TABLEt,
    NAPTR_TABLEt,
    NETIFt,
    NEXT_HOP_TABLEt,
    PPPOE_TABLEt,
    L34_HSAt,
    L34_HSBt,
    HSA_DEBUG_DATAt,
#endif
    TABLE_LIST_END = 30
} rtk_table_list_t;


#endif    /* __APOLLO_TABLE_STRUCT_H__ */

