/*
 *  ## Please DO NOT edit this file!! ##
 *  This file is auto-generated from the register source files.
 *  Any modifications to this file will be LOST when it is re-generated.
 *
 *  ----------------------------------------------------------------
 *  (C) Copyright 2009 Realtek Semiconductor Corp.
 *
 *  This program is the proprietary software of Realtek Semiconductor
 *  Corporation and/or its licensors, and only be used, duplicated,
 *  modified or distributed under the authorized license from Realtek.
 *
 *  ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 *  THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 *  ----------------------------------------------------------------
 *  Purpose: chip register definition and structure of APOLLO
 *
 *  ----------------------------------------------------------------
 */

#ifndef __APOLLO_REGFIELD_LIST_H__
#define __APOLLO_REGFIELD_LIST_H__

#include <hal/chipdef/allreg.h>

#if defined(CONFIG_SDK_APOLLO)
/* Module: Interface */
extern rtk_regField_t DIGITAL_INTERFACE_SELECT_FIELDS[];
extern rtk_regField_t SKIP_MII_RXER_FIELDS[];
extern rtk_regField_t EXT_RGMXF_FIELDS[];
extern rtk_regField_t I2C_CLOCK_DIV_FIELDS[];
extern rtk_regField_t MDX_MDC_DIV_FIELDS[];
extern rtk_regField_t EXT_TXC_DLY_FIELDS[];
extern rtk_regField_t GPHY_IND_WD_FIELDS[];
extern rtk_regField_t GPHY_IND_CMD_FIELDS[];
extern rtk_regField_t GPHY_IND_RD_FIELDS[];
extern rtk_regField_t EFUSE_IND_WD_FIELDS[];
extern rtk_regField_t EFUSE_IND_CMD_FIELDS[];
extern rtk_regField_t EFUSE_IND_RD_FIELDS[];
extern rtk_regField_t I2C_IND_WD_FIELDS[];
extern rtk_regField_t I2C_IND_CMD_FIELDS[];
extern rtk_regField_t I2C_IND_RD_FIELDS[];
extern rtk_regField_t TAB_IND_WD_FIELDS[];
extern rtk_regField_t TAB_IND_CMD_FIELDS[];
extern rtk_regField_t TAB_IND_RD_FIELDS[];
extern rtk_regField_t REGCTRL_GLB_FIELDS[];
extern rtk_regField_t IOPAD_CFG_FIELDS[];
extern rtk_regField_t IO_GPIO_EN2_FIELDS[];
extern rtk_regField_t IO_GPIO_EN1_FIELDS[];
extern rtk_regField_t IO_GPIO_EN0_FIELDS[];
extern rtk_regField_t IO_LED_EN_FIELDS[];
extern rtk_regField_t IO_MODE_EN_FIELDS[];
extern rtk_regField_t CFG_PCSXF_FIELDS[];
extern rtk_regField_t CFG_PHY_CTRL_FIELDS[];
extern rtk_regField_t CFG_PHY_POLL_CMD_FIELDS[];
extern rtk_regField_t CFG_PHY_POLL_ADR_0_FIELDS[];
extern rtk_regField_t CFG_PHY_POLL_ADR_1_FIELDS[];
extern rtk_regField_t CFG_PHY_POLL_INV_0_FIELDS[];
extern rtk_regField_t CFG_PHY_POLL_INV_1_FIELDS[];
extern rtk_regField_t CFG_PHY_POLL_WD_0_FIELDS[];
extern rtk_regField_t CFG_PHY_POLL_WD_1_FIELDS[];
extern rtk_regField_t CHIP_DEBUG_OUT_FIELDS[];

/* Module: Reset */
extern rtk_regField_t CHIP_RST_FIELDS[];

/* Module: Interrupt */
extern rtk_regField_t INTR_CTRL_FIELDS[];
extern rtk_regField_t INTR_IMR_FIELDS[];
extern rtk_regField_t INTR_IMS_FIELDS[];
extern rtk_regField_t INTR_STAT_FIELDS[];

/* Module: BIST & BISR */
extern rtk_regField_t BIST_CFG19_FIELDS[];
extern rtk_regField_t BIST_CFG18_FIELDS[];
extern rtk_regField_t BIST_CFG17_FIELDS[];
extern rtk_regField_t BIST_CFG16_FIELDS[];
extern rtk_regField_t BIST_CFG15_FIELDS[];
extern rtk_regField_t BIST_CFG14_FIELDS[];
extern rtk_regField_t BIST_CFG13_FIELDS[];
extern rtk_regField_t BIST_CFG12_FIELDS[];
extern rtk_regField_t BIST_CFG9_FIELDS[];
extern rtk_regField_t BIST_CFG8_FIELDS[];
extern rtk_regField_t BIST_CFG7_FIELDS[];
extern rtk_regField_t BIST_CFG4_FIELDS[];
extern rtk_regField_t BIST_CFG3_FIELDS[];
extern rtk_regField_t BIST_CFG2_FIELDS[];
extern rtk_regField_t BIST_CFG1_FIELDS[];
extern rtk_regField_t BIST_CFG0_FIELDS[];
extern rtk_regField_t DIAG_MODE_FIELDS[];
extern rtk_regField_t DFR_TEST_RESUME_FIELDS[];
extern rtk_regField_t BIST_CFG_FIELDS[];
extern rtk_regField_t RAM_DVS_CFG2_FIELDS[];
extern rtk_regField_t RAM_DVS_CFG3_FIELDS[];
extern rtk_regField_t PON_INTEGRATION_FIELDS[];

/* Module: CPU relative */

/* Module: LED */
extern rtk_regField_t LED_LED_FIELDS[];
extern rtk_regField_t DATA_LED_CFG_FIELDS[];
extern rtk_regField_t LED_ACTIVE_LOW_CFG_FIELDS[];
extern rtk_regField_t SERI_LED_ACTIVE_LOW_CFG_FIELDS[];
extern rtk_regField_t PWR_ON_LIGHT_EN_FIELDS[];
extern rtk_regField_t LED_FORCE_VALUE_CFG_FIELDS[];
extern rtk_regField_t LED_BLINK_RATE_CFG_FIELDS[];
extern rtk_regField_t LOW_RATE_BLINK_CFG_FIELDS[];
extern rtk_regField_t LED_EN_FIELDS[];

/* Module: HW Misc. */
extern rtk_regField_t FORCE_P_DMP_FIELDS[];
extern rtk_regField_t EN_FORCE_P_DMP_FIELDS[];
extern rtk_regField_t GLB_MAC_MISC_FIELDS[];
extern rtk_regField_t WRAP_GPHY_MISC_FIELDS[];

/* Module: Chp Information */
extern rtk_regField_t MODEL_NAME_INFO_FIELDS[];
extern rtk_regField_t CHIP_INFO_FIELDS[];
extern rtk_regField_t BOND_INFO_FIELDS[];
extern rtk_regField_t EFUSE_CFG_FIELDS[];
extern rtk_regField_t MISCELLANEOUS_CONFIGURE0_FIELDS[];
extern rtk_regField_t PHY_AD_FIELDS[];
extern rtk_regField_t FORCE_P_ABLTY_FIELDS[];
extern rtk_regField_t MDX_PHY_REG0_FIELDS[];
extern rtk_regField_t MDX_PHY_REG1_FIELDS[];
extern rtk_regField_t UPS_CTRL2_FIELDS[];
extern rtk_regField_t GATING_CLK_1_FIELDS[];
extern rtk_regField_t UPS_CTRL6_FIELDS[];
extern rtk_regField_t EEE_CFG_FIELDS[];
extern rtk_regField_t EEE_PAGE_FIELDS[];
extern rtk_regField_t EEE_EXT_PAGE_FIELDS[];
extern rtk_regField_t EEE_EN_SPD1000_FIELDS[];
extern rtk_regField_t EEE_EN_SPD100_FIELDS[];
extern rtk_regField_t EEE_LP_SPD1000_FIELDS[];
extern rtk_regField_t EEE_LP_SPD100_FIELDS[];
extern rtk_regField_t ROUTER_UPS_CFG_FIELDS[];
extern rtk_regField_t P_ABLTY_FIELDS[];
extern rtk_regField_t GPIO_CTRL_0_FIELDS[];
extern rtk_regField_t GPIO_CTRL_1_FIELDS[];
extern rtk_regField_t GPIO_CTRL_2_FIELDS[];
extern rtk_regField_t GPIO_CTRL_3_FIELDS[];
extern rtk_regField_t RTL_OUI_CFG_FIELDS[];
extern rtk_regField_t REVISON_CFG_FIELDS[];
extern rtk_regField_t MODEL_CFG_FIELDS[];
extern rtk_regField_t WAKELPI_SLOT_PRD_FIELDS[];
extern rtk_regField_t WAKELPI_SLOT_PG0_FIELDS[];
extern rtk_regField_t WAKELPI_SLOT_PG1_FIELDS[];
extern rtk_regField_t WAKELPI_SLOT_PG2_FIELDS[];
extern rtk_regField_t WAKELPI_SLOT_PG3_FIELDS[];
extern rtk_regField_t RGM_EEE_FIELDS[];
extern rtk_regField_t ABLTY_FORCE_MODE_FIELDS[];
extern rtk_regField_t DEBUG_SEL_FIELDS[];
extern rtk_regField_t RST_SYNC_FIFO_FIELDS[];
extern rtk_regField_t SDS_CFG_FIELDS[];
extern rtk_regField_t MAC_ACT_CFG_FIELDS[];
extern rtk_regField_t UTP_FIB_DET_CFG_FIELDS[];
extern rtk_regField_t CHIP_CFG_FIELDS[];
extern rtk_regField_t BYPS_ABLTY_LOCK_FIELDS[];
extern rtk_regField_t FIFO_ERR_STS_FIELDS[];
extern rtk_regField_t SDS_AN_RX_CFG_FIELDS[];
extern rtk_regField_t SDS_FIB_STATUS_FIELDS[];
extern rtk_regField_t EXT_STS_FIELDS[];
extern rtk_regField_t AFE_VER_FIELDS[];
extern rtk_regField_t SOFTWARE_RST_FIELDS[];
extern rtk_regField_t PON_MODE_CFG_FIELDS[];
extern rtk_regField_t PARSER_FIELD_SELTOR_CTRL_14_15_FIELDS[];
extern rtk_regField_t PARSER_FIELD_SELTOR_CTRL_12_13_FIELDS[];
extern rtk_regField_t PARSER_FIELD_SELTOR_CTRL_10_11_FIELDS[];
extern rtk_regField_t PARSER_FIELD_SELTOR_CTRL_8_9_FIELDS[];
extern rtk_regField_t PARSER_FIELD_SELTOR_CTRL_6_7_FIELDS[];
extern rtk_regField_t PARSER_FIELD_SELTOR_CTRL_4_5_FIELDS[];
extern rtk_regField_t PARSER_FIELD_SELTOR_CTRL_2_3_FIELDS[];
extern rtk_regField_t PARSER_FIELD_SELTOR_CTRL_0_1_FIELDS[];
extern rtk_regField_t HTRAM_DVS_CFG_FIELDS[];
extern rtk_regField_t RAM_DVS_CFG0_FIELDS[];
extern rtk_regField_t RAM_DVS_CFG1_FIELDS[];
extern rtk_regField_t HWPKT_GEN_STA_FIELDS[];
extern rtk_regField_t ALL_PORT_LKDN_TIME_FIELDS[];
extern rtk_regField_t MODE_EXT_FIELDS[];
extern rtk_regField_t GPHY_AFE_DBG_CFG_FIELDS[];
extern rtk_regField_t AD5_CTRL_FIELDS[];
extern rtk_regField_t PWM_CTRL1_FIELDS[];
extern rtk_regField_t PWM_CTRL2_FIELDS[];
extern rtk_regField_t TM_DLY_FIELDS[];
extern rtk_regField_t TM_CTRL_FIELDS[];
extern rtk_regField_t TM_STS_FIELDS[];
extern rtk_regField_t AD5_ALARM_FIELDS[];
extern rtk_regField_t AD5_DATA_FIELDS[];
extern rtk_regField_t TM_ALARM_FIELDS[];
extern rtk_regField_t CHIP_INF_SEL_FIELDS[];
extern rtk_regField_t AUTODET_CTRL_FIELDS[];
extern rtk_regField_t AUTODET_STS_FIELDS[];
extern rtk_regField_t SLIC_INSEL_CTRL_FIELDS[];
extern rtk_regField_t GPIO_CTRL_4_FIELDS[];
extern rtk_regField_t SYS_PKT_BUF_CTRL_FIELDS[];
extern rtk_regField_t DYNGASP_CTRL_FIELDS[];
extern rtk_regField_t BOND_STRAP_STS0_FIELDS[];
extern rtk_regField_t BOND_STRAP_STS1_FIELDS[];
extern rtk_regField_t BOND_STRAP_STS2_FIELDS[];

/* Module: MAC Control */
extern rtk_regField_t FPGA_VER_MAC_FIELDS[];
extern rtk_regField_t MAC_CPU_TAG_CTRL_FIELDS[];
extern rtk_regField_t MAC_CPU_TAG_AWARE_CTRL_FIELDS[];
extern rtk_regField_t ACCEPT_MAX_LEN_CTRL_FIELDS[];
extern rtk_regField_t MAX_LENGTH_CFG1_FIELDS[];
extern rtk_regField_t MAX_LENGTH_CFG0_FIELDS[];
extern rtk_regField_t MAX_LENGTH_LIMINT_IPG_FIELDS[];
extern rtk_regField_t IOL_RXDROP_CFG_FIELDS[];
extern rtk_regField_t CFG_BACKPRESSURE_FIELDS[];
extern rtk_regField_t CFG_UNHIOL_FIELDS[];
extern rtk_regField_t SWITCH_MAC_FIELDS[];
extern rtk_regField_t SWITCH_CTRL_FIELDS[];
extern rtk_regField_t INBW_BOUND_FIELDS[];
extern rtk_regField_t MAX_FIFO_SIZE_FIELDS[];
extern rtk_regField_t P_TX_ERR_CNT_FIELDS[];
extern rtk_regField_t P_CGSTTIMER_FIELDS[];
extern rtk_regField_t P_MISC_FIELDS[];
extern rtk_regField_t P_CFG_FRC_RATE_FIELDS[];
extern rtk_regField_t P0_CUR_RATE_FIELDS[];

/* Module: PHY & Serdes */
extern rtk_regField_t WSDS_ANA_00_FIELDS[];
extern rtk_regField_t WSDS_ANA_01_FIELDS[];
extern rtk_regField_t WSDS_ANA_02_FIELDS[];
extern rtk_regField_t WSDS_ANA_03_FIELDS[];
extern rtk_regField_t WSDS_ANA_04_FIELDS[];
extern rtk_regField_t WSDS_ANA_05_FIELDS[];
extern rtk_regField_t WSDS_ANA_06_FIELDS[];
extern rtk_regField_t WSDS_ANA_07_FIELDS[];
extern rtk_regField_t WSDS_ANA_08_FIELDS[];
extern rtk_regField_t WSDS_ANA_09_FIELDS[];
extern rtk_regField_t WSDS_ANA_0A_FIELDS[];
extern rtk_regField_t WSDS_ANA_0B_FIELDS[];
extern rtk_regField_t WSDS_ANA_0C_FIELDS[];
extern rtk_regField_t WSDS_ANA_0D_FIELDS[];
extern rtk_regField_t WSDS_ANA_0E_FIELDS[];
extern rtk_regField_t WSDS_ANA_0F_FIELDS[];
extern rtk_regField_t WSDS_ANA_10_FIELDS[];
extern rtk_regField_t WSDS_ANA_11_FIELDS[];
extern rtk_regField_t WSDS_ANA_12_FIELDS[];
extern rtk_regField_t WSDS_ANA_13_FIELDS[];
extern rtk_regField_t WSDS_ANA_14_FIELDS[];
extern rtk_regField_t WSDS_ANA_15_FIELDS[];
extern rtk_regField_t WSDS_ANA_16_FIELDS[];
extern rtk_regField_t WSDS_ANA_17_FIELDS[];
extern rtk_regField_t WSDS_ANA_18_FIELDS[];
extern rtk_regField_t WSDS_ANA_19_FIELDS[];
extern rtk_regField_t WSDS_ANA_1A_FIELDS[];
extern rtk_regField_t WSDS_ANA_1B_FIELDS[];
extern rtk_regField_t WSDS_ANA_1C_FIELDS[];
extern rtk_regField_t WSDS_ANA_1D_FIELDS[];
extern rtk_regField_t WSDS_ANA_1E_FIELDS[];
extern rtk_regField_t WSDS_ANA_1F_FIELDS[];
extern rtk_regField_t WSDS_ANA_20_FIELDS[];
extern rtk_regField_t WSDS_ANA_21_FIELDS[];
extern rtk_regField_t WSDS_ANA_22_FIELDS[];
extern rtk_regField_t WSDS_ANA_23_FIELDS[];
extern rtk_regField_t WSDS_ANA_24_FIELDS[];
extern rtk_regField_t WSDS_ANA_25_FIELDS[];
extern rtk_regField_t WSDS_DIG_00_FIELDS[];
extern rtk_regField_t WSDS_DIG_01_FIELDS[];
extern rtk_regField_t WSDS_DIG_02_FIELDS[];
extern rtk_regField_t WSDS_DIG_03_FIELDS[];
extern rtk_regField_t WSDS_DIG_04_FIELDS[];
extern rtk_regField_t WSDS_DIG_05_FIELDS[];
extern rtk_regField_t WSDS_DIG_06_FIELDS[];
extern rtk_regField_t WSDS_DIG_07_FIELDS[];
extern rtk_regField_t WSDS_DIG_08_FIELDS[];
extern rtk_regField_t WSDS_DIG_09_FIELDS[];
extern rtk_regField_t WSDS_DIG_0A_FIELDS[];
extern rtk_regField_t WSDS_DIG_0B_FIELDS[];
extern rtk_regField_t WSDS_DIG_0C_FIELDS[];
extern rtk_regField_t WSDS_DIG_0D_FIELDS[];
extern rtk_regField_t WSDS_DIG_0E_FIELDS[];
extern rtk_regField_t WSDS_DIG_0F_FIELDS[];
extern rtk_regField_t WSDS_DIG_10_FIELDS[];
extern rtk_regField_t WSDS_DIG_11_FIELDS[];
extern rtk_regField_t WSDS_DIG_12_FIELDS[];
extern rtk_regField_t WSDS_DIG_13_FIELDS[];
extern rtk_regField_t WSDS_DIG_14_FIELDS[];
extern rtk_regField_t WSDS_DIG_15_FIELDS[];
extern rtk_regField_t WSDS_DIG_16_FIELDS[];
extern rtk_regField_t WSDS_DIG_17_FIELDS[];
extern rtk_regField_t WSDS_DIG_18_FIELDS[];
extern rtk_regField_t WSDS_DIG_19_FIELDS[];
extern rtk_regField_t WSDS_DIG_1A_FIELDS[];
extern rtk_regField_t WSDS_DIG_1B_FIELDS[];
extern rtk_regField_t WSDS_DIG_1C_FIELDS[];
extern rtk_regField_t WSDS_DIG_1D_FIELDS[];
extern rtk_regField_t WSDS_DIG_1E_FIELDS[];
extern rtk_regField_t WSDS_DIG_1F_FIELDS[];
extern rtk_regField_t WSDS_DIG_20_FIELDS[];
extern rtk_regField_t WSDS_DIG_21_FIELDS[];
extern rtk_regField_t WSDS_DIG_22_FIELDS[];
extern rtk_regField_t WSDS_DIG_23_FIELDS[];
extern rtk_regField_t WSDS_DIG_24_FIELDS[];
extern rtk_regField_t WSDS_DIG_25_FIELDS[];
extern rtk_regField_t WSDS_DIG_26_FIELDS[];
extern rtk_regField_t WSDS_DIG_27_FIELDS[];
extern rtk_regField_t SDS_REG0_FIELDS[];
extern rtk_regField_t SDS_REG1_FIELDS[];
extern rtk_regField_t SDS_REG2_FIELDS[];
extern rtk_regField_t SDS_REG3_FIELDS[];
extern rtk_regField_t SDS_REG4_FIELDS[];
extern rtk_regField_t SDS_REG5_FIELDS[];
extern rtk_regField_t SDS_REG6_FIELDS[];
extern rtk_regField_t SDS_REG7_FIELDS[];
extern rtk_regField_t SDS_REG8_FIELDS[];
extern rtk_regField_t SDS_REG9_FIELDS[];
extern rtk_regField_t SDS_REG10_FIELDS[];
extern rtk_regField_t SDS_REG11_FIELDS[];
extern rtk_regField_t SDS_REG12_FIELDS[];
extern rtk_regField_t SDS_REG13_FIELDS[];
extern rtk_regField_t SDS_REG14_FIELDS[];
extern rtk_regField_t SDS_REG15_FIELDS[];
extern rtk_regField_t SDS_REG16_FIELDS[];
extern rtk_regField_t SDS_REG17_FIELDS[];
extern rtk_regField_t SDS_REG18_FIELDS[];
extern rtk_regField_t SDS_REG19_FIELDS[];
extern rtk_regField_t SDS_REG20_FIELDS[];
extern rtk_regField_t SDS_REG21_FIELDS[];
extern rtk_regField_t SDS_REG22_FIELDS[];
extern rtk_regField_t SDS_REG23_FIELDS[];
extern rtk_regField_t SDS_REG24_FIELDS[];
extern rtk_regField_t SDS_REG25_FIELDS[];
extern rtk_regField_t SDS_REG26_FIELDS[];
extern rtk_regField_t SDS_REG27_FIELDS[];
extern rtk_regField_t SDS_REG28_FIELDS[];
extern rtk_regField_t SDS_REG29_FIELDS[];
extern rtk_regField_t SDS_EXT_REG0_FIELDS[];
extern rtk_regField_t SDS_EXT_REG1_FIELDS[];
extern rtk_regField_t SDS_EXT_REG2_FIELDS[];
extern rtk_regField_t SDS_EXT_REG3_FIELDS[];
extern rtk_regField_t SDS_EXT_REG4_FIELDS[];
extern rtk_regField_t SDS_EXT_REG5_FIELDS[];
extern rtk_regField_t SDS_EXT_REG6_FIELDS[];
extern rtk_regField_t SDS_EXT_REG7_FIELDS[];
extern rtk_regField_t SDS_EXT_REG8_FIELDS[];
extern rtk_regField_t SDS_EXT_REG9_FIELDS[];
extern rtk_regField_t SDS_EXT_REG10_FIELDS[];
extern rtk_regField_t SDS_EXT_REG11_FIELDS[];
extern rtk_regField_t SDS_EXT_REG12_FIELDS[];
extern rtk_regField_t SDS_EXT_REG13_FIELDS[];
extern rtk_regField_t SDS_EXT_REG14_FIELDS[];
extern rtk_regField_t SDS_EXT_REG15_FIELDS[];
extern rtk_regField_t SDS_EXT_REG16_FIELDS[];
extern rtk_regField_t SDS_EXT_REG24_FIELDS[];
extern rtk_regField_t SDS_EXT_REG25_FIELDS[];
extern rtk_regField_t SDS_EXT_REG26_FIELDS[];
extern rtk_regField_t SDS_EXT_REG27_FIELDS[];
extern rtk_regField_t SDS_EXT_REG28_FIELDS[];
extern rtk_regField_t SDS_EXT_REG29_FIELDS[];
extern rtk_regField_t SDS_EXT_REG30_FIELDS[];
extern rtk_regField_t FIB_REG0_FIELDS[];
extern rtk_regField_t FIB_REG1_FIELDS[];
extern rtk_regField_t FIB_REG2_FIELDS[];
extern rtk_regField_t FIB_REG4_FIELDS[];
extern rtk_regField_t FIB_REG5_FIELDS[];
extern rtk_regField_t FIB_REG6_FIELDS[];
extern rtk_regField_t FIB_REG7_FIELDS[];
extern rtk_regField_t FIB_REG8_FIELDS[];
extern rtk_regField_t FIB_REG13_FIELDS[];
extern rtk_regField_t FIB_REG14_FIELDS[];
extern rtk_regField_t FIB_REG16_FIELDS[];
extern rtk_regField_t FIB_REG17_FIELDS[];
extern rtk_regField_t FIB_REG18_FIELDS[];
extern rtk_regField_t FIB_REG19_FIELDS[];
extern rtk_regField_t FIB_REG20_FIELDS[];
extern rtk_regField_t FIB_REG21_FIELDS[];
extern rtk_regField_t FIB_REG22_FIELDS[];
extern rtk_regField_t FIB_REG23_FIELDS[];
extern rtk_regField_t FIB_REG28_FIELDS[];
extern rtk_regField_t FIB_REG29_FIELDS[];
extern rtk_regField_t FIB_REG30_FIELDS[];
extern rtk_regField_t FIB_EXT_REG0_FIELDS[];
extern rtk_regField_t FIB_EXT_REG1_FIELDS[];
extern rtk_regField_t FIB_EXT_REG2_FIELDS[];
extern rtk_regField_t FIB_EXT_REG4_FIELDS[];
extern rtk_regField_t FIB_EXT_REG5_FIELDS[];
extern rtk_regField_t FIB_EXT_REG6_FIELDS[];
extern rtk_regField_t FIB_EXT_REG7_FIELDS[];
extern rtk_regField_t FIB_EXT_REG8_FIELDS[];
extern rtk_regField_t FIB_EXT_REG13_FIELDS[];
extern rtk_regField_t FIB_EXT_REG14_FIELDS[];
extern rtk_regField_t FIB_EXT_REG16_FIELDS[];
extern rtk_regField_t FIB_EXT_REG17_FIELDS[];
extern rtk_regField_t FIB_EXT_REG18_FIELDS[];
extern rtk_regField_t FIB_EXT_REG19_FIELDS[];
extern rtk_regField_t FIB_EXT_REG20_FIELDS[];
extern rtk_regField_t FIB_EXT_REG21_FIELDS[];
extern rtk_regField_t FIB_EXT_REG22_FIELDS[];
extern rtk_regField_t FIB_EXT_REG23_FIELDS[];
extern rtk_regField_t FIB_EXT_REG24_FIELDS[];
extern rtk_regField_t FIB_EXT_REG25_FIELDS[];
extern rtk_regField_t FIB_EXT_REG26_FIELDS[];
extern rtk_regField_t FIB_EXT_REG27_FIELDS[];
extern rtk_regField_t FIB_EXT_REG28_FIELDS[];
extern rtk_regField_t FIB_EXT_REG29_FIELDS[];
extern rtk_regField_t FIB_EXT_REG30_FIELDS[];

/* Module: RTCT */

/* Module: Power Saving */
extern rtk_regField_t EEE_TX_SEL_CTRL_FIELDS[];
extern rtk_regField_t EEE_TX_TIMER_100M_CTRL_FIELDS[];
extern rtk_regField_t EEE_TX_THR_100M_CTRL_FIELDS[];
extern rtk_regField_t EEE_TX_TIMER_GIGA_CTRL_FIELDS[];
extern rtk_regField_t EEE_TX_THR_GIGA_CTRL_FIELDS[];
extern rtk_regField_t EEE_PORT_CFG_FIELDS[];
extern rtk_regField_t EEEP_TIMER_UNIT_CTRL_FIELDS[];
extern rtk_regField_t EEEP_TX_100M_CTRL_FIELDS[];
extern rtk_regField_t EEEP_TX_GIGA_CTRL_FIELDS[];
extern rtk_regField_t EEEP_RX_RATE_100M_CTRL_FIELDS[];
extern rtk_regField_t EEEP_RX_RATE_GIGA_CTRL_FIELDS[];
extern rtk_regField_t EEEP_RX_SLEEP_STEP_CTRL_FIELDS[];
extern rtk_regField_t EEEP_RX_TIMER_100M_CTRL_FIELDS[];
extern rtk_regField_t EEEP_RX_TIMER_GIGA_CTRL_FIELDS[];
extern rtk_regField_t PS_GATCLK_SLCLK_CTRL_FIELDS[];
extern rtk_regField_t PS_LINKID_GATCLK_CTRL_FIELDS[];
extern rtk_regField_t PS_EEE_GATCLK_CTRL_FIELDS[];
extern rtk_regField_t P_EEECFG_FIELDS[];
extern rtk_regField_t P_EEETXMTR_FIELDS[];
extern rtk_regField_t P_EEERXMTR_FIELDS[];
extern rtk_regField_t P_EEEPTXMTR_FIELDS[];
extern rtk_regField_t P_EEEPRXMTR_FIELDS[];
extern rtk_regField_t EEE_TX_THR_GIGA_FIELDS[];
extern rtk_regField_t EEE_TX_THR_FE_FIELDS[];
extern rtk_regField_t EEE_RX_FC_REG_FIELDS[];
extern rtk_regField_t EEE_MISC_FIELDS[];
extern rtk_regField_t EEE_GIGA_CTRL0_FIELDS[];
extern rtk_regField_t EEE_GIGA_CTRL1_FIELDS[];
extern rtk_regField_t EEE_100M_CTRL0_FIELDS[];
extern rtk_regField_t EEE_100M_CTRL1_FIELDS[];
extern rtk_regField_t EEEP_TX_RATE_GIGA_FIELDS[];
extern rtk_regField_t EEEP_TX_RATE_100M_FIELDS[];
extern rtk_regField_t EEEP_RX_RATE_GIGA_FIELDS[];
extern rtk_regField_t EEEP_RX_RATE_100M_FIELDS[];
extern rtk_regField_t EEEP_GIGA_CTRL0_FIELDS[];
extern rtk_regField_t EEEP_GIGA_CTRL1_FIELDS[];
extern rtk_regField_t EEEP_GIGA_CTRL2_FIELDS[];
extern rtk_regField_t EEEP_100M_CTRL0_FIELDS[];
extern rtk_regField_t EEEP_100M_CT_FIELDS[];
extern rtk_regField_t EEEP_100M_CTRL2_FIELDS[];
extern rtk_regField_t EEEP_CTRL0_FIELDS[];
extern rtk_regField_t EEEP_CTRL1_FIELDS[];
extern rtk_regField_t EEE_BURSTSIZE_FIELDS[];
extern rtk_regField_t EEE_IFG_CFG_FIELDS[];

/* Module: Auto Fallback */
extern rtk_regField_t FB_CTRL_FIELDS[];
extern rtk_regField_t FB_P0_1_CFG_FIELDS[];
extern rtk_regField_t FB_P0_1_ERR_CNT_FIELDS[];
extern rtk_regField_t FB_P0_1_MONITOR_CNT_FIELDS[];
extern rtk_regField_t FB_P3_5_CFG_FIELDS[];
extern rtk_regField_t FB_P3_5_ERR_CNT_FIELDS[];
extern rtk_regField_t FB_P3_5_MONITOR_CNT_FIELDS[];

/* Module: Address Table Lookup */
extern rtk_regField_t LUT_UNMATCHED_SA_CTRL_FIELDS[];
extern rtk_regField_t LUT_UNKN_SA_CTRL_FIELDS[];
extern rtk_regField_t LUT_UNKN_UC_DA_CTRL_FIELDS[];
extern rtk_regField_t LUT_LEARN_OVER_CTRL_FIELDS[];
extern rtk_regField_t LUT_CFG_FIELDS[];
extern rtk_regField_t LUT_DIS_AGE_FIELDS[];
extern rtk_regField_t LUT_LRN_LIMITNO_FIELDS[];
extern rtk_regField_t L2_LRN_CNT_FIELDS[];
extern rtk_regField_t L2_LRN_OVER_STS_FIELDS[];
extern rtk_regField_t LUT_SYS_LRN_LIMITNO_FIELDS[];
extern rtk_regField_t L2_SYS_LRN_OVER_STS_FIELDS[];
extern rtk_regField_t L2_SYS_LRN_CNT_FIELDS[];
extern rtk_regField_t UNKN_L2_MC_FIELDS[];
extern rtk_regField_t UNKN_IP4_MC_FIELDS[];
extern rtk_regField_t UNKN_IP6_MC_FIELDS[];
extern rtk_regField_t UNKN_MC_PRI_FIELDS[];
extern rtk_regField_t LUT_BC_FLOOD_FIELDS[];
extern rtk_regField_t LUT_UNKN_MC_FLOOD_FIELDS[];
extern rtk_regField_t LUT_UNKN_UC_FLOOD_FIELDS[];
extern rtk_regField_t L2_EFID_FIELDS[];
extern rtk_regField_t LUT_SYS_LRN_OVER_CTRL_FIELDS[];

/* Module: Address Learning & Flush */
extern rtk_regField_t L2_TBL_FLUSH_CTRL_FIELDS[];
extern rtk_regField_t L2_TBL_FLUSH_EN_FIELDS[];

/* Module: L2 &IP Multicast */
extern rtk_regField_t L2_IPMC_VLAN_LEAKY_FIELDS[];
extern rtk_regField_t L2_IPMC_ISO_LEAKY_FIELDS[];

/* Module: (IEEE802.1Q) VLAN */
extern rtk_regField_t VLAN_PORT_ACCEPT_FRAME_TYPE_FIELDS[];
extern rtk_regField_t VLAN_INGRESS_FIELDS[];
extern rtk_regField_t VLAN_EGRESS_TAG_FIELDS[];
extern rtk_regField_t VLAN_MBR_CFG_FIELDS[];
extern rtk_regField_t VLAN_CTRL_FIELDS[];
extern rtk_regField_t VLAN_PB_EFID_FIELDS[];
extern rtk_regField_t VLAN_PB_EFIDEN_FIELDS[];
extern rtk_regField_t VLAN_PB_PRI_FIELDS[];
extern rtk_regField_t VLAN_PB_VIDX_FIELDS[];
extern rtk_regField_t VLAN_EGRESS_KEEP_FIELDS[];
extern rtk_regField_t VLAN_VC_VIDX_FIELDS[];
extern rtk_regField_t VLAN_EXT_VIDX_FIELDS[];

/* Module: (IEEE802.1ad) Provider Bridges/Q-in-Q */
extern rtk_regField_t SVLAN_UPLINK_PMSK_FIELDS[];
extern rtk_regField_t SVLAN_LOOK_UP_TYPE_FIELDS[];
extern rtk_regField_t SVLAN_MC2S_FIELDS[];
extern rtk_regField_t SVLAN_C2S_FIELDS[];
extern rtk_regField_t SVLAN_SP2C_FIELDS[];
extern rtk_regField_t SVLAN_EP_DMAC_CTRL_FIELDS[];
extern rtk_regField_t SVLAN_P_SVIDX_FIELDS[];
extern rtk_regField_t SVLAN_CTRL_FIELDS[];
extern rtk_regField_t SVLAN_CFG_FIELDS[];
extern rtk_regField_t SVLAN_MBRCFG_FIELDS[];

/* Module: (IEEE802.1v) Protocol-based VLAN */
extern rtk_regField_t VLAN_PPB_VLAN_VAL_FIELDS[];
extern rtk_regField_t VLAN_PORT_PPB_VLAN_FIELDS[];

/* Module: Link Aggregation */
extern rtk_regField_t PORT_TRUNK_GROUP_EN_FIELDS[];
extern rtk_regField_t PORT_TRUNK_CTRL_FIELDS[];
extern rtk_regField_t PORT_TRUNK_HASH_MAPPING_FIELDS[];

/* Module: Spanning Tree */
extern rtk_regField_t MSTI_CTRL_FIELDS[];

/* Module: Port Isolation */
extern rtk_regField_t PISO_P_CTRL_FIELDS[];
extern rtk_regField_t PISO_P_L34_CTRL_FIELDS[];
extern rtk_regField_t PISO_EXT_CTRL_FIELDS[];
extern rtk_regField_t PISO_EXT_L34_CTRL_FIELDS[];
extern rtk_regField_t PISO_VC_CTRL_FIELDS[];

/* Module: RMA */
extern rtk_regField_t RMA_CTRL00_FIELDS[];
extern rtk_regField_t RMA_CTRL01_FIELDS[];
extern rtk_regField_t RMA_CTRL02_FIELDS[];
extern rtk_regField_t RMA_CTRL03_FIELDS[];
extern rtk_regField_t RMA_CTRL04_FIELDS[];
extern rtk_regField_t RMA_CTRL08_FIELDS[];
extern rtk_regField_t RMA_CTRL0D_FIELDS[];
extern rtk_regField_t RMA_CTRL0E_FIELDS[];
extern rtk_regField_t RMA_CTRL10_FIELDS[];
extern rtk_regField_t RMA_CTRL11_FIELDS[];
extern rtk_regField_t RMA_CTRL12_FIELDS[];
extern rtk_regField_t RMA_CTRL13_FIELDS[];
extern rtk_regField_t RMA_CTRL18_FIELDS[];
extern rtk_regField_t RMA_CTRL1A_FIELDS[];
extern rtk_regField_t RMA_CTRL20_FIELDS[];
extern rtk_regField_t RMA_CTRL21_FIELDS[];
extern rtk_regField_t RMA_CTRL22_FIELDS[];
extern rtk_regField_t RMA_CTRL_CDP_FIELDS[];
extern rtk_regField_t RMA_CTRL_SSTP_FIELDS[];
extern rtk_regField_t RMA_CFG_FIELDS[];
extern rtk_regField_t EEELLDP_CTRL_0_FIELDS[];
extern rtk_regField_t EEELLDP_CTRL_1_FIELDS[];

/* Module: L2 Misc. */
extern rtk_regField_t L2_SRC_PORT_PERMIT_FIELDS[];
extern rtk_regField_t L2_SRC_VC_PERMIT_FIELDS[];
extern rtk_regField_t L2_SRC_EXT_PERMIT_FIELDS[];

/* Module: NIC & DMA */
extern rtk_regField_t NIC_ID_CRTL0_FIELDS[];
extern rtk_regField_t NIC_ID_CRTL1_FIELDS[];
extern rtk_regField_t NIC_MC_CRTL0_FIELDS[];
extern rtk_regField_t NIC_MC_CRTL1_FIELDS[];
extern rtk_regField_t NIC_MIB0_FIELDS[];
extern rtk_regField_t NIC_MIB1_FIELDS[];
extern rtk_regField_t NIC_MIB2_FIELDS[];
extern rtk_regField_t NIC_MIB3_FIELDS[];
extern rtk_regField_t NIC_MIB4_FIELDS[];
extern rtk_regField_t NIC_MIB5_FIELDS[];
extern rtk_regField_t NIC_MIB6_FIELDS[];
extern rtk_regField_t NIC_STS_FIELDS[];
extern rtk_regField_t NIC_COM_FIELDS[];
extern rtk_regField_t NIC_INTR_FIELDS[];
extern rtk_regField_t NIC_TC_FIELDS[];
extern rtk_regField_t NIC_RC_FIELDS[];
extern rtk_regField_t NIC_CPUTAG_FIELDS[];
extern rtk_regField_t NIC_CONFIG_FIELDS[];
extern rtk_regField_t NIC_CPUTAG1_FIELDS[];
extern rtk_regField_t NIC_MS_FIELDS[];
extern rtk_regField_t NIC_MIIA_FIELDS[];
extern rtk_regField_t NIC_SWINT_FIELDS[];
extern rtk_regField_t NIC_VLAN_FIELDS[];
extern rtk_regField_t NIC_LED_CR_FIELDS[];
extern rtk_regField_t NIC_TXFPD1_FIELDS[];
extern rtk_regField_t NIC_TXCDO1_FIELDS[];
extern rtk_regField_t NIC_TXFDP2_FIELDS[];
extern rtk_regField_t NIC_TXCDO2_FIELDS[];
extern rtk_regField_t NIC_TXFDP3_FIELDS[];
extern rtk_regField_t NIC_TXCDO3_FIELDS[];
extern rtk_regField_t NIC_TXFDP4_FIELDS[];
extern rtk_regField_t NIC_TXCDO4_FIELDS[];
extern rtk_regField_t NIC_TXFDP5_FIELDS[];
extern rtk_regField_t NIC_TXCDO5_FIELDS[];
extern rtk_regField_t NIC_RRING_ROUTING1_FIELDS[];
extern rtk_regField_t NIC_RRING_ROUTING2_FIELDS[];
extern rtk_regField_t NIC_RRING_ROUTING3_FIELDS[];
extern rtk_regField_t NIC_RRING_ROUTING4_FIELDS[];
extern rtk_regField_t NIC_RRING_ROUTING5_FIELDS[];
extern rtk_regField_t NIC_RRING_ROUTING6_FIELDS[];
extern rtk_regField_t NIC_RXFDP2_FIELDS[];
extern rtk_regField_t NIC_RXCDORINGRS2_FIELDS[];
extern rtk_regField_t NIC_RX_CPU_DESN2_FIELDS[];
extern rtk_regField_t NIC_RX_DES_THRES2_FIELDS[];
extern rtk_regField_t NIC_RXFDP3_FIELDS[];
extern rtk_regField_t NIC_RXCDORINGRS3_FIELDS[];
extern rtk_regField_t NIC_RX_CPU_DESN3_FIELDS[];
extern rtk_regField_t NIC_RX_DES_THRES3_FIELDS[];
extern rtk_regField_t NIC_RXFDP4_FIELDS[];
extern rtk_regField_t NIC_RXCDORINGRS4_FIELDS[];
extern rtk_regField_t NIC_RX_CPU_DESN4_FIELDS[];
extern rtk_regField_t NIC_RX_DES_THRES4_FIELDS[];
extern rtk_regField_t NIC_RXFDP5_FIELDS[];
extern rtk_regField_t NIC_RXCDORINGRS5_FIELDS[];
extern rtk_regField_t NIC_RX_CPU_DESN5_FIELDS[];
extern rtk_regField_t NIC_RX_DES_THRES5_FIELDS[];
extern rtk_regField_t NIC_RXFDP6_FIELDS[];
extern rtk_regField_t NIC_RXCDORINGRS6_FIELDS[];
extern rtk_regField_t NIC_RX_CPU_DESN6_FIELDS[];
extern rtk_regField_t NIC_RX_DES_THRES6_FIELDS[];
extern rtk_regField_t NIC_RXFDP1_FIELDS[];
extern rtk_regField_t NIC_RXCDORINGRS1_FIELDS[];
extern rtk_regField_t NIC_SMSA_FIELDS[];
extern rtk_regField_t NIC_PROBE_SELECT_FIELDS[];
extern rtk_regField_t NIC_DIAGNOSE1_FIELDS[];
extern rtk_regField_t NIC_RX_PSE1_TXC_OUT_SEL1_FIELDS[];
extern rtk_regField_t NIC_ETNRXCPU1_FIELDS[];
extern rtk_regField_t NIC_ETN_IO_CMD_FIELDS[];
extern rtk_regField_t NIC_ETN_IO_CMD1_FIELDS[];
extern rtk_regField_t NIC_WOL_FIELDS[];

/* Module: Storm Control (B/M/UM/DLF) */
extern rtk_regField_t STORM_CTRL_UM_CTRL_FIELDS[];
extern rtk_regField_t STORM_CTRL_UC_CTRL_FIELDS[];
extern rtk_regField_t STORM_CTRL_MC_CTRL_FIELDS[];
extern rtk_regField_t STORM_CTRL_BC_CTRL_FIELDS[];
extern rtk_regField_t STORM_CTRL_UM_METER_IDX_FIELDS[];
extern rtk_regField_t STORM_CTRL_UC_METER_IDX_FIELDS[];
extern rtk_regField_t STORM_CTRL_MC_METER_IDX_FIELDS[];
extern rtk_regField_t STORM_CTRL_BC_METER_IDX_FIELDS[];
extern rtk_regField_t STORM_CTRL_ALT_TYPE_SEL_FIELDS[];

/* Module: Bandwidth Control (Ingress/Egress) */
extern rtk_regField_t IGR_BWCTRL_P_CTRL_FIELDS[];
extern rtk_regField_t IGR_BWCTRL_GLB_CTRL_FIELDS[];

/* Module: Meter Marker */
extern rtk_regField_t METER_TB_CTRL_FIELDS[];
extern rtk_regField_t METER_GLB_CTRL_FIELDS[];
extern rtk_regField_t METER_LB_EXCEED_STS_FIELDS[];
extern rtk_regField_t PON_TB_CTRL_FIELDS[];

/* Module: 802.1X */
extern rtk_regField_t DOT1X_CFG_0_FIELDS[];
extern rtk_regField_t DOT1X_CFG_1_FIELDS[];
extern rtk_regField_t DOT1X_P_CTRL_FIELDS[];

/* Module: Denial-of-service attack prevention */
extern rtk_regField_t DOS_EN_FIELDS[];
extern rtk_regField_t DOS_DSL_EN_FIELDS[];
extern rtk_regField_t DOS_CFG_FIELDS[];
extern rtk_regField_t DOS_SYNFLOOD_TH_FIELDS[];
extern rtk_regField_t DOS_FINFLOOD_TH_FIELDS[];
extern rtk_regField_t DOS_ICMPFLOOD_TH_FIELDS[];

/* Module: Mirroring */
extern rtk_regField_t MIR_CTRL_FIELDS[];

/* Module: sFlow */

/* Module: Statistic Counters */
extern rtk_regField_t STAT_PRVTE_DROP_COUNTER_FIELDS[];
extern rtk_regField_t STAT_PORT_TX_MIB_FIELDS[];
extern rtk_regField_t STAT_PORT_RX_MIB_FIELDS[];
extern rtk_regField_t STAT_PORT_OAM_MIB_FIELDS[];
extern rtk_regField_t STAT_BRIDGE_DOT1DTPLEARNEDENTRYDISCARDS_FIELDS[];
extern rtk_regField_t STAT_ACL_CNT_FIELDS[];
extern rtk_regField_t STAT_CTRL_FIELDS[];
extern rtk_regField_t STAT_ACL_CNT_MODE_FIELDS[];
extern rtk_regField_t STAT_ACL_CNT_TYPE_FIELDS[];
extern rtk_regField_t STAT_ACL_CNT_RST_FIELDS[];
extern rtk_regField_t STAT_PORT_RST_FIELDS[];
extern rtk_regField_t STAT_RST_FIELDS[];
extern rtk_regField_t EPON_STAT_RST_FIELDS[];
extern rtk_regField_t DOT3_Q_TX_FRAMES_FIELDS[];
extern rtk_regField_t DOT3_MPCP_RX_DISC_FIELDS[];
extern rtk_regField_t DOT3_EPON_FEC_CORRECTED_BLOCKS_FIELDS[];
extern rtk_regField_t DOT3_EPON_FEC_UNCORRECTED_BLOCKS_FIELDS[];
extern rtk_regField_t DOT3_EPON_FEC_CODING_VIO_FIELDS[];
extern rtk_regField_t DOT3_NOT_BROADCAST_BIT_NOT_ONU_LLID_FIELDS[];
extern rtk_regField_t DOT3_BROADCAST_BIT_PLUS_ONU_LLID_FIELDS[];
extern rtk_regField_t DOT3_BROADCAST_NOT_ONUID_FIELDS[];
extern rtk_regField_t DOT3_CRC8_ERRORS_FIELDS[];
extern rtk_regField_t DOT3_LLID_RX_BROADCAST_DROP_FRAMES_FIELDS[];
extern rtk_regField_t DOT3_MPCP_TX_REPORT_FIELDS[];
extern rtk_regField_t DOT3_MPCP_EX_GATE_FIELDS[];
extern rtk_regField_t DOT3_ONUID_NOT_BROADCAST_FIELDS[];
extern rtk_regField_t STAT_DOT3_LLIDRXFRAMESDROP_FIELDS[];
extern rtk_regField_t DOT3_MPCP_TX_REG_REQ_FIELDS[];

/* Module: Flowcontrol & Backpressure Threshold */
extern rtk_regField_t FC_CTRL_FIELDS[];
extern rtk_regField_t FC_DROP_ALL_TH_FIELDS[];
extern rtk_regField_t FC_PAUSE_ALL_TH_FIELDS[];
extern rtk_regField_t FC_GLB_FCOFF_HI_TH_FIELDS[];
extern rtk_regField_t FC_GLB_FCOFF_LO_TH_FIELDS[];
extern rtk_regField_t FC_GLB_HI_TH_FIELDS[];
extern rtk_regField_t FC_GLB_LO_TH_FIELDS[];
extern rtk_regField_t FC_P_HI_TH_FIELDS[];
extern rtk_regField_t FC_P_LO_TH_FIELDS[];
extern rtk_regField_t FC_P_FCOFF_HI_TH_FIELDS[];
extern rtk_regField_t FC_P_FCOFF_LO_TH_FIELDS[];
extern rtk_regField_t FC_JUMBO_GLB_HI_TH_FIELDS[];
extern rtk_regField_t FC_JUMBO_GLB_LO_TH_FIELDS[];
extern rtk_regField_t FC_JUMBO_P_HI_TH_FIELDS[];
extern rtk_regField_t FC_JUMBO_P_LO_TH_FIELDS[];
extern rtk_regField_t FC_Q_EGR_DROP_TH_FIELDS[];
extern rtk_regField_t FC_P_EGR_DROP_TH_FIELDS[];
extern rtk_regField_t FC_Q_EGR_GAP_TH_FIELDS[];
extern rtk_regField_t FC_P_EGR_GAP_TH_FIELDS[];
extern rtk_regField_t FC_P_Q_EGR_DROP_EN_FIELDS[];
extern rtk_regField_t FC_DBG_CTRL_FIELDS[];
extern rtk_regField_t CLR_MAX_USED_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_TOTAL_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_PE_USED_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_Q_USED_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_TL_USED_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_PUB_USED_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_PUB_FCOFF_USED_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_PUB_JUMBO_USED_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_P_USED_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_P_DBG_PKT_PAGE_CNT_FIELDS[];
extern rtk_regField_t FC_PON_GLB_HI_TH_FIELDS[];
extern rtk_regField_t FC_PON_GLB_LO_TH_FIELDS[];
extern rtk_regField_t FC_PON_P_HI_TH_FIELDS[];
extern rtk_regField_t FC_PON_P_LO_TH_FIELDS[];
extern rtk_regField_t FC_PON_Q_EGR_DROP_IDX_FIELDS[];
extern rtk_regField_t FC_PON_Q_EGR_DROP_TH_FIELDS[];
extern rtk_regField_t FC_PON_Q_EGR_GAP_TH_FIELDS[];
extern rtk_regField_t FC_PON_Q_USED_PAGE_CTRL_FIELDS[];
extern rtk_regField_t FC_PON_Q_USED_PAGE_CNT_FIELDS[];
extern rtk_regField_t TH_TX_PREFET_FIELDS[];
extern rtk_regField_t LOW_QUEUE_TH_FIELDS[];
extern rtk_regField_t HIGH_QUEUE_MSK_FIELDS[];

/* Module: Congestion Avoidance */
extern rtk_regField_t SC_P_CTRL_0_FIELDS[];
extern rtk_regField_t SC_P_CTRL_1_FIELDS[];

/* Module: Packet Aging */

/* Module: (IEEE802.1p) Priority */

/* Module: Queue Management */
extern rtk_regField_t QOS_INTPRI_TO_QID_FIELDS[];
extern rtk_regField_t QOS_PORT_QMAP_CTRL_FIELDS[];
extern rtk_regField_t QOS_PRI_REMAP_IN_CPU_FIELDS[];

/* Module: Ingress Priority Decision */
extern rtk_regField_t QOS_1Q_PRI_REMAP_FIELDS[];
extern rtk_regField_t QOS_DSCP_REMAP_FIELDS[];
extern rtk_regField_t QOS_PB_PRI_FIELDS[];
extern rtk_regField_t PRI_SEL_TBL_CTRL_FIELDS[];
extern rtk_regField_t PRI_SEL_TBL_CTRL2_FIELDS[];

/* Module: Remarking */
extern rtk_regField_t RMK_DOT1Q_RMK_EN_CTRL_FIELDS[];
extern rtk_regField_t RMK_1Q_CTRL_FIELDS[];
extern rtk_regField_t RMK_DSCP_RMK_EN_CTRL_FIELDS[];
extern rtk_regField_t RMK_DSCP_CTRL_FIELDS[];
extern rtk_regField_t RMK_DSCP_INT_PRI_CTRL_FIELDS[];
extern rtk_regField_t RMK_P_DSCP_SEL_FIELDS[];

/* Module: Scheduling */
extern rtk_regField_t WFQ_CTRL_FIELDS[];
extern rtk_regField_t EGR_BWCTRL_P_CTRL_FIELDS[];
extern rtk_regField_t LINE_RATE_1G_FIELDS[];
extern rtk_regField_t LINE_RATE_100M_FIELDS[];
extern rtk_regField_t LINE_RATE_10M_FIELDS[];
extern rtk_regField_t WFQ_P02_CFG0_FIELDS[];
extern rtk_regField_t WFQ_P02_CFG1_7_FIELDS[];
extern rtk_regField_t WFQ_P46_CFG0_FIELDS[];
extern rtk_regField_t WFQ_P46_CFG1_7_FIELDS[];
extern rtk_regField_t WFQ_TYPE_P02_CFG_FIELDS[];
extern rtk_regField_t WFQ_TYPE_P46_CFG_FIELDS[];
extern rtk_regField_t APR_EN_P02_CFG_FIELDS[];
extern rtk_regField_t APR_EN_P46_CFG_FIELDS[];
extern rtk_regField_t CPU_PORT_RATE_CFG_FIELDS[];
extern rtk_regField_t APR_METER_P02_CFG_FIELDS[];
extern rtk_regField_t APR_METER_P46_CFG_FIELDS[];
extern rtk_regField_t P_QUEUE_EMPTY_FIELDS[];

/* Module: PIE Template */
extern rtk_regField_t ACL_TEMPLATE_CTRL_FIELDS[];

/* Module: Flow Classification (Flow Table) */
extern rtk_regField_t CF_OP_DS_FIELDS[];
extern rtk_regField_t CF_OP_US_FIELDS[];
extern rtk_regField_t CF_VALID_FIELDS[];
extern rtk_regField_t CF_CFG_FIELDS[];

/* Module: Ingress ACL */
extern rtk_regField_t ACL_EN_FIELDS[];
extern rtk_regField_t ACL_PERMIT_FIELDS[];
extern rtk_regField_t ACL_ACTION_FIELDS[];
extern rtk_regField_t ACL_CFG_FIELDS[];

/* Module: Range Check (port/vlan/ip/L4port) */
extern rtk_regField_t RNG_CHK_VID_RNG_FIELDS[];
extern rtk_regField_t RNG_CHK_IP_RNG_FIELDS[];
extern rtk_regField_t RNG_CHK_L4PORT_RNG_FIELDS[];
extern rtk_regField_t RNG_CHK_PKTLEN_RNG_FIELDS[];

/* Module: OAM */
extern rtk_regField_t OAM_P_CTRL_0_FIELDS[];
extern rtk_regField_t OAM_P_CTRL_1_FIELDS[];
extern rtk_regField_t OAM_CTRL_0_FIELDS[];
extern rtk_regField_t OAM_CTRL_1_FIELDS[];

/* Module: UDLD */

/* Module: RLDP & RLPP */
extern rtk_regField_t RLDP_CTRL_0_FIELDS[];
extern rtk_regField_t RLDP_CTRL_1_FIELDS[];
extern rtk_regField_t RLDP_CHK_STS_CTRL_FIELDS[];
extern rtk_regField_t RLDP_LP_STS_CTRL_FIELDS[];
extern rtk_regField_t RLDP_RNDM_NUM_FIELDS[];
extern rtk_regField_t RLDP_MAGIC_NUM_FIELDS[];
extern rtk_regField_t RLDP_P1_0_TX_EN_FIELDS[];
extern rtk_regField_t RLDP_P1_0_LP_ENTER_STS_FIELDS[];
extern rtk_regField_t RLDP_P1_0_LP_LEAVE_STS_FIELDS[];
extern rtk_regField_t RLDP_P1_0_LP_STS_FIELDS[];
extern rtk_regField_t RLDP_P1_0_CPU_LP_STS_FIELDS[];
extern rtk_regField_t RLDP_P1_0_LP_PNUM_FIELDS[];
extern rtk_regField_t RLDP_P3_5_TX_EN_FIELDS[];
extern rtk_regField_t RLDP_P3_5_LP_ENTER_STS_FIELDS[];
extern rtk_regField_t RLDP_P3_5_LP_LEAVE_STS_FIELDS[];
extern rtk_regField_t RLDP_P3_5_LP_STS_FIELDS[];
extern rtk_regField_t RLDP_P3_5_CPU_LP_STS_FIELDS[];
extern rtk_regField_t RLDP_P3_5_LP_PNUM_FIELDS[];
extern rtk_regField_t RLPP_CTRL_FIELDS[];

/* Module: Code Protection */

/* Module: Parser HSB */
extern rtk_regField_t HSB_CTRL_FIELDS[];
extern rtk_regField_t HSB_DATA_FIELDS[];

/* Module: HSM */

/* Module: Modifier HSA */
extern rtk_regField_t HSA_DATA_FIELDS[];

/* Module: Debugging (ALE, Loopback, Drop Mechanism, FC and QM) */
extern rtk_regField_t DBG_BLK_SEL_FIELDS[];
extern rtk_regField_t PORT_VM_EN_FIELDS[];
extern rtk_regField_t PORT_VM_RX_FIELDS[];
extern rtk_regField_t PORT_VM_TX_FIELDS[];

/* Module: Smart Packet Generator */
extern rtk_regField_t SPG_GLB_CTRL_FIELDS[];
extern rtk_regField_t SPG_PORT_TX_GRP_CTRL_FIELDS[];
extern rtk_regField_t SPG_PORT_STS_FIELDS[];
extern rtk_regField_t SPG_P_TX_GRP_CTRL_FIELDS[];
extern rtk_regField_t SPG_P_LEN_CTRL_FIELDS[];
extern rtk_regField_t SPG_P_TX_CNT_FIELDS[];
extern rtk_regField_t SPG_P_SA_FIELDS[];
extern rtk_regField_t SPG_P_DA_FIELDS[];
extern rtk_regField_t SPG_PAYLOAD_FIELDS[];
extern rtk_regField_t SPG_PORT_USER_PKT_FIELDS[];

/* Module: L3 Routing */

/* Module: IGMP snooping */
extern rtk_regField_t IGMP_MC_GROUP_FIELDS[];
extern rtk_regField_t IGMP_GLB_CTRL_FIELDS[];
extern rtk_regField_t IGMP_P_CTRL_FIELDS[];

/* Module: L3 Misc */
extern rtk_regField_t L34_GLB_CFG_FIELDS[];
extern rtk_regField_t L34_IPMC_TRAN_TBL_FIELDS[];

/* Module: Table Access */
extern rtk_regField_t TBL_ACCESS_CTRL_FIELDS[];
extern rtk_regField_t TBL_ACCESS_STS_FIELDS[];
extern rtk_regField_t TBL_ACCESS_WR_DATA_FIELDS[];
extern rtk_regField_t TBL_ACCESS_RD_DATA_FIELDS[];

/* Module: Special Trap */

/* Module: Ethernet AV */
extern rtk_regField_t AVB_PORT_EN_FIELDS[];
extern rtk_regField_t AVB_PRI_REMAP_FIELDS[];

/* Module: PTP (Precision Time Protocol) */
extern rtk_regField_t PTP_TIME_SEC_FIELDS[];
extern rtk_regField_t PTP_TIME_NSEC_FIELDS[];
extern rtk_regField_t PTP_TIME_OFFSET_SEC_FIELDS[];
extern rtk_regField_t PTP_TIME_OFFSET_8NSEC_FIELDS[];
extern rtk_regField_t PTP_TIME_FREQ_FIELDS[];
extern rtk_regField_t PTP_TIME_CTRL_FIELDS[];
extern rtk_regField_t PTP_IGR_MSG_ACT_FIELDS[];
extern rtk_regField_t PTP_EGR_MSG_ACT_FIELDS[];
extern rtk_regField_t PTP_MEANPATH_DEALY_FIELDS[];
extern rtk_regField_t PTP_LATCH_CORRECT_FIELDS[];
extern rtk_regField_t PTP_RX_TIME_FIELDS[];
extern rtk_regField_t PTP_P_TX_TIME_FIELDS[];

/* Module: Parser */
extern rtk_regField_t PARSER_FIELD_SELTOR_CTRL_FIELDS[];

/* Module: PON MAC Scheduling Config */
extern rtk_regField_t PON_CFG_FIELDS[];
extern rtk_regField_t PON_DRAINOUT_CTRL_FIELDS[];
extern rtk_regField_t PON_QID_TO_SID_FIELDS[];
extern rtk_regField_t PON_QID_CIR_RATE_FIELDS[];
extern rtk_regField_t PON_QID_PIR_RATE_FIELDS[];
extern rtk_regField_t PON_SCH_QMAP_FIELDS[];
extern rtk_regField_t PON_WFQ_WEIGHT_FIELDS[];
extern rtk_regField_t PON_WFQ_TYPE_FIELDS[];
extern rtk_regField_t FC_PON_Q_EGR_DROP_EN_FIELDS[];
extern rtk_regField_t PON_TCONT_EN_FIELDS[];
extern rtk_regField_t QUEUE_SEL_IND_FIELDS[];
extern rtk_regField_t QUEUE_SEL_IND_DATA_FIELDS[];
extern rtk_regField_t GPON_DPRU_RPT_PRD_FIELDS[];
extern rtk_regField_t PON_PORT_CTRL_FIELDS[];

/* Module: GPON MAC General Config */
extern rtk_regField_t GPON_INT_DLT_FIELDS[];
extern rtk_regField_t GPON_RESET_FIELDS[];
extern rtk_regField_t GPON_VERSION_FIELDS[];
extern rtk_regField_t GPON_TEST_FIELDS[];
extern rtk_regField_t GPON_AES_BYPASS_FIELDS[];
extern rtk_regField_t GPON_INTR_MASK_FIELDS[];
extern rtk_regField_t GPON_INTR_STS_FIELDS[];

/* Module: GTC Downstream */
extern rtk_regField_t GPON_GTC_DS_INTR_DLT_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_INTR_MASK_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_INTR_STS_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_ONU_ID_STATUS_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_CFG_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_PLOAM_CFG_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_LOS_CFG_STS_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_SUPERFRAME_CNT_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_PLOAM_IND_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_PLOAM_MSG_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_ALLOC_IND_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_ALLOC_WR_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_ALLOC_RD_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_PORT_IND_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_PORT_WR_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_PORT_RD_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_PORT_CNTR_IND_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_PORT_CNTR_STAT_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_BIP_ERR_BLK_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_BIP_ERR_BIT_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_FEC_CORRECT_BIT_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_FEC_CORRECT_BYTE_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_FEC_CORRECT_CW_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_FEC_UNCOR_CW_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_LOM_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_PLOAM_ACPT_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_PLOAM_FAIL_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_BWM_FAIL_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_BWM_INV_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_ACTIVE_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_BWM_ACPT_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_GEM_LOS_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_HEC_CORRECT_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_GEM_IDLE_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_GEM_FAIL_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_GEM_NON_IDLE_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_MISC_CNTR_PLEN_CORRECT_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_OMCI_PTI_FIELDS[];
extern rtk_regField_t GPON_GTC_DS_ETH_PTI_FIELDS[];
extern rtk_regField_t DS_FEC_FIELDS[]; 
extern rtk_regField_t PLOAM_FIELDS[]; 
extern rtk_regField_t GEM_CNTR_FIELDS[]; 
extern rtk_regField_t GEM_TOKEN_A_FIELDS[]; 
extern rtk_regField_t BWMAP_CAP_FIELDS[]; 
extern rtk_regField_t BWMAP_BUF_FIELDS[]; 
extern rtk_regField_t TCONT_FIELDS[]; 
extern rtk_regField_t GEM_L_FIELDS[]; 
extern rtk_regField_t GEM_H_FIELDS[]; 
extern rtk_regField_t GPON_GTC_DS_TRAFFIC_CFG_FIELDS[];

/* Module: BWMAP Capture */
extern rtk_regField_t GPON_BWMAP_CTRL_FIELDS[];
extern rtk_regField_t GPON_BWMAP_STS_FIELDS[];
extern rtk_regField_t GPON_BWMAP_DATA_FIELDS[];

/* Module: AES Decrypt */
extern rtk_regField_t GPON_AES_INTR_DLT_FIELDS[];
extern rtk_regField_t GPON_AES_INTR_MASK_FIELDS[];
extern rtk_regField_t GPON_AES_INTR_STS_FIELDS[];
extern rtk_regField_t GPON_AES_KEY_SWITCH_REQ_FIELDS[];
extern rtk_regField_t GPON_AES_KEY_SWITCH_TIME_FIELDS[];
extern rtk_regField_t GPON_AES_KEY_WORD_IND_FIELDS[];
extern rtk_regField_t GPON_AES_WORD_DATA_FIELDS[];
extern rtk_regField_t CTL_INFO_FIELDS[]; 
extern rtk_regField_t CTL_DATA_FIELDS[]; 
extern rtk_regField_t CIPHER_1_FIELDS[]; 
extern rtk_regField_t CIPHER_2_FIELDS[]; 
extern rtk_regField_t KEY_EXPN_FIELDS[]; 

/* Module: GEM Port Downstream */
extern rtk_regField_t GPON_GEM_DS_RX_CNTR_IND_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_RX_CNTR_STAT_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_FWD_CNTR_IND_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_FWD_CNTR_STAT_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_MISC_IND_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_MISC_CNTR_STAT_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_MC_CFG_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_MC_IND_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_MC_WR_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_MC_RD_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_FRM_TIMEOUT_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_MC_ADDR_PTN_IPV4_FIELDS[];
extern rtk_regField_t GPON_GEM_DS_MC_ADDR_PTN_IPV6_FIELDS[];
extern rtk_regField_t CLASSIFY_BUF_FIELDS[]; 
extern rtk_regField_t CLASSIFY_CNTR_FIELDS[]; 
extern rtk_regField_t ASSEMBLY_FIELDS[]; 
extern rtk_regField_t MC_FILTER_FIELDS[]; 

/* Module: GTC Upstream */
extern rtk_regField_t GPON_GTC_US_INTR_DLT_FIELDS[];
extern rtk_regField_t GPON_GTC_US_INTR_MASK_FIELDS[];
extern rtk_regField_t GPON_GTC_US_INTR_STS_FIELDS[];
extern rtk_regField_t GPON_GTC_US_ONU_ID_FIELDS[];
extern rtk_regField_t GPON_GTC_US_CFG_FIELDS[];
extern rtk_regField_t GPON_GTC_US_WRITE_PROTECT_FIELDS[];
extern rtk_regField_t GPON_GTC_US_TX_PATTERN_CTL_FIELDS[];
extern rtk_regField_t GPON_GTC_US_TX_PATTERN_BG_FIELDS[];
extern rtk_regField_t GPON_GTC_US_TX_PATTERN_FG_FIELDS[];
extern rtk_regField_t GPON_GTC_US_MIN_DELAY_FIELDS[];
extern rtk_regField_t GPON_GTC_US_EQD_FIELDS[];
extern rtk_regField_t GPON_GTC_US_LASER_FIELDS[];
extern rtk_regField_t GPON_GTC_US_BOH_CFG_FIELDS[];
extern rtk_regField_t GPON_GTC_US_BOH_DATA_FIELDS[];
extern rtk_regField_t GPON_GTC_US_PLOAM_IND_FIELDS[];
extern rtk_regField_t GPON_GTC_US_PLOAM_DATA_FIELDS[];
extern rtk_regField_t GPON_GTC_US_PLOAM_CFG_FIELDS[];
extern rtk_regField_t GPON_GTC_US_MISC_CNTR_IDX_FIELDS[];
extern rtk_regField_t GPON_GTC_US_MISC_CNTR_STAT_FIELDS[];
extern rtk_regField_t GPON_GTC_US_RDI_FIELDS[];
extern rtk_regField_t GPON_GTC_US_DG_FIELDS[];
extern rtk_regField_t GPON_GTC_US_OPTIC_SD_TH_FIELDS[];
extern rtk_regField_t GPON_GTC_US_PROC_MODE_FIELDS[];
extern rtk_regField_t BWM_TBL_FIELDS[]; 
extern rtk_regField_t BWM_MEM0_FIELDS[]; 
extern rtk_regField_t BWM_MEM1_FIELDS[]; 
extern rtk_regField_t PLOAM_A_FIELDS[]; 
extern rtk_regField_t DBR_FIELDS[]; 

/* Module: GEM Upstream */
extern rtk_regField_t GPON_GEM_US_INTR_DLT_FIELDS[];
extern rtk_regField_t GPON_GEM_US_INTR_MASK_FIELDS[];
extern rtk_regField_t GPON_GEM_US_INTR_STS_FIELDS[];
extern rtk_regField_t GPON_GEM_US_PTI_CFG_FIELDS[];
extern rtk_regField_t GPON_GEM_US_ETH_GEM_RX_CNTR_IDX_FIELDS[];
extern rtk_regField_t GPON_GEM_US_ETH_GEM_RX_CNTR_STAT_FIELDS[];
extern rtk_regField_t GPON_GEM_US_PTN_CTRL_FIELDS[];
extern rtk_regField_t PCFG_FIELDS[]; 
extern rtk_regField_t GEM_BCNT_FIELDS[]; 
extern rtk_regField_t FIFO_BANK0_FIELDS[]; 
extern rtk_regField_t FIFO_BANK1_FIELDS[]; 
extern rtk_regField_t IDLE_BCNT_FIELDS[]; 
extern rtk_regField_t GEM_PCNT_FIELDS[]; 
extern rtk_regField_t GPON_GEM_US_PORT_MAP_FIELDS[];
extern rtk_regField_t GPON_GEM_US_BYTE_STAT_FIELDS[];
extern rtk_regField_t TCONT_IDLE_BYTE_STAT_FIELDS[];

/* Module: EPON Configuration */
extern rtk_regField_t EPON_FEC_CONFIG_FIELDS[];
extern rtk_regField_t EPON_ASIC_TIMING_ADJUST1_FIELDS[];
extern rtk_regField_t EPON_ASIC_TIMING_ADJUST2_FIELDS[];
extern rtk_regField_t EPON_RGSTR1_FIELDS[];
extern rtk_regField_t EPON_RGSTR2_FIELDS[];
extern rtk_regField_t EPON_RGSTR3_FIELDS[];
extern rtk_regField_t EPON_DEBUG1_FIELDS[];
extern rtk_regField_t EPON_DEBUG2_FIELDS[];
extern rtk_regField_t EPON_TIMER_CONFIG1_FIELDS[];
extern rtk_regField_t EPON_INTR_FIELDS[];
extern rtk_regField_t SYNC_TIME_FIELDS[];
extern rtk_regField_t LASER_ON_OFF_TIME_FIELDS[];
extern rtk_regField_t MIN_GRANT_START_FIELDS[];
extern rtk_regField_t MAX_GRANT_START_FIELDS[];
extern rtk_regField_t EPON_TIME_CTRL_FIELDS[];
extern rtk_regField_t EP_MISC_FIELDS[];
extern rtk_regField_t LLID_TABLE_FIELDS[];
extern rtk_regField_t EPON_MPCP_CTR_FIELDS[];
extern rtk_regField_t EPON_GRANT_LIST0_FIELDS[];
extern rtk_regField_t EPON_GRANT_LIST1_FIELDS[];
extern rtk_regField_t EPON_GRANT_LIST2_FIELDS[];
extern rtk_regField_t EPON_TX_CTRL_FIELDS[];

/* Module: Table Access */
extern rtk_regField_t NAT_TBL_ACCESS_CTRL_FIELDS[];
extern rtk_regField_t NAT_TBL_ACCESS_CLR_FIELDS[];
extern rtk_regField_t NAT_TBL_ACCESS_RDDATA_FIELDS[];
extern rtk_regField_t NAT_TBL_ACCESS_WRDATA_FIELDS[];

/* Module: ALE and TM for L3L4 */
extern rtk_regField_t NIFP_FIELDS[];
extern rtk_regField_t NIFEP_FIELDS[];
extern rtk_regField_t NIFVCH_FIELDS[];
extern rtk_regField_t NIFVCL_FIELDS[];
extern rtk_regField_t SWTCR0_FIELDS[];
extern rtk_regField_t PP_AGE_FIELDS[];

/* Module: NAT HSB HAS */
extern rtk_regField_t HSBA_CTRL_FIELDS[];
extern rtk_regField_t HSB_DESC_FIELDS[];
extern rtk_regField_t HSA_DESC_FIELDS[];

/* Module: L4 Traffic Table0 */
extern rtk_regField_t L4_TRF0_FIELDS[];
extern rtk_regField_t L4_TRF1_FIELDS[];
extern rtk_regField_t ARP_TRF0_FIELDS[];
extern rtk_regField_t ARP_TRF1_FIELDS[];

/* Module: Temp Register */
extern rtk_regField_t RGF_VER_GLB_CTRL_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_GLB_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_ACL_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_CVLAN_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_DPM_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_L2_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_MLTVLAN_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_SVLAN_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_EEE_LLDP_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_RLDP_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_EAV_AFBK_FIELDS[];
extern rtk_regField_t RGF_VER_INTR_FIELDS[];
extern rtk_regField_t RGF_VER_LED_FIELDS[];
extern rtk_regField_t RGF_VER_PER_PORT_MAC_FIELDS[];
extern rtk_regField_t RGF_VER_SDSREG_FIELDS[];
extern rtk_regField_t RGF_VER_SWCORE_FIELDS[];
extern rtk_regField_t RGF_VER_EPON_CTRL_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_RMA_ATTACK_FIELDS[];
extern rtk_regField_t RGF_VER_BIST_CTRL_FIELDS[];
extern rtk_regField_t RGF_VER_EGR_OUTQ_FIELDS[];
extern rtk_regField_t RGF_VER_EGR_SCH_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_HSA_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_METER_FIELDS[];
extern rtk_regField_t RGF_VER_MAC_PON_FIELDS[];
extern rtk_regField_t RGF_VER_MIB_CTRL_FIELDS[];
extern rtk_regField_t RGF_VER_ALE_PISO_FIELDS[];
extern rtk_regField_t RSVD_GLB_CTRL_FIELDS[];
extern rtk_regField_t RSVD_ALE_GLB_FIELDS[];
extern rtk_regField_t RSVD_ALE_ACL_FIELDS[];
extern rtk_regField_t RSVD_ALE_CVLAN_FIELDS[];
extern rtk_regField_t RSVD_ALE_DPM_FIELDS[];
extern rtk_regField_t RSVD_ALE_L2_FIELDS[];
extern rtk_regField_t RSVD_ALE_MLTVLAN_FIELDS[];
extern rtk_regField_t RSVD_ALE_SVLAN_FIELDS[];
extern rtk_regField_t RSVD_ALE_EEE_LLDP_FIELDS[];
extern rtk_regField_t RSVD_ALE_RLDP_FIELDS[];
extern rtk_regField_t RSVD_ALE_EAV_AFBK_FIELDS[];
extern rtk_regField_t RSVD_INTR_FIELDS[];
extern rtk_regField_t RSVD_LED_FIELDS[];
extern rtk_regField_t RSVD_PER_PORT_MAC_FIELDS[];
extern rtk_regField_t RSVD_SDSREG_FIELDS[];
extern rtk_regField_t RSVD_SWCORE_FIELDS[];
extern rtk_regField_t RSVD_EPON_CTRL_FIELDS[];
extern rtk_regField_t RSVD_ALE_RMA_ATTACK_FIELDS[];
extern rtk_regField_t RSVD_BIST_CTRL_FIELDS[];
extern rtk_regField_t RSVD_EGR_OUTQ_FIELDS[];
extern rtk_regField_t RSVD_EGR_SCH_FIELDS[];
extern rtk_regField_t RSVD_ALE_HSA_FIELDS[];
extern rtk_regField_t RSVD_ALE_METER_FIELDS[];
extern rtk_regField_t RSVD_MAC_PON_FIELDS[];
extern rtk_regField_t RSVD_MIB_CTRL_FIELDS[];
extern rtk_regField_t RSVD_ALE_PISO_FIELDS[];
extern rtk_regField_t HSA_TX_DBG_FIELDS[];
extern rtk_regField_t MISCELLANEOUS_BONDING_FIELDS[];
extern rtk_regField_t MISCELLANEOUS_STRAPPING1_FIELDS[];
extern rtk_regField_t MISCELLANEOUS_STRAPPING0_FIELDS[];
extern rtk_regField_t SERI_LED_CLK_PER_FIELDS[];
extern rtk_regField_t SERI_LED_REFRESH_TIME_FIELDS[];
extern rtk_regField_t RAM_DVS_CFG4_FIELDS[];
extern rtk_regField_t RAM_DVS_CFG5_FIELDS[];
extern rtk_regField_t I2C_CLOCK_DIV_1_FIELDS[];
extern rtk_regField_t I2C_IND_WD_1_FIELDS[];
extern rtk_regField_t I2C_IND_CMD_1_FIELDS[];
extern rtk_regField_t I2C_IND_RD_1_FIELDS[];
#endif


#endif    /* __APOLLO_REGFIELD_LIST_H__ */

