#ifndef __MIB_SIM_H__
#define __MIB_SIM_H__
#include "mib_def.h"
#include "prmt_limit.h"

#define VOIP_SUPPORT 1
//#include "apmib.h"		//Alex
#include "voip_flash_client.h"

//extern voip_flash_share_t *g_pVoIPShare;

#define PROFILE_NAME_LEN		20
/* the default value of voice profile*/

#define _PATH_TMP_STATUS "/tmp/voipstatus"

typedef int boolean;

typedef enum {
    MIB_ID_START,
    /* -------------------- Argument type 0 ------------------------ */
    MIB_VOICE_SERVICE__ARG_TYPE0_END,		/* Reserved For VoiceService.{i}*/
	/* -------------------- Argument type 1 ------------------------ */
	/* Need instance number of PROFILE */
	MIB_VOICE_PROFILE__ENABLE,
	MIB_VOICE_PROFILE__RESET,
	MIB_VOICE_PROFILE__NUMBER_OF_LINES,
	MIB_VOICE_PROFILE__NAME,
	MIB_VOICE_PROFILE__SIGNALING_PROTOCOL,
	MIB_VOICE_PROFILE__MAX_SESSIONS,
	MIB_VOICE_PROFILE__DTMF_METHOD,
	MIB_VOICE_PROFILE__SERVICE_PROVIDE_INFO__NAME,
	MIB_VOICE_PROFILE__DIGIT_MAP_ENABLE,
	MIB_VOICE_PROFILE__DIGIT_MAP,
    MIB_VOICE_PROFILE__XCT_SERVER_TYPE,
    MIB_VOICE_PROFILE__XCT_START_DIGIT_TIMER,
    MIB_VOICE_PROFILE__XCT_INTER_DIGIT_TIMER_SHORT,
    MIB_VOICE_PROFILE__XCT_INTER_DIGIT_TIMER_LONG,
    MIB_VOICE_PROFILE__XCT_HANGING_REMINDER_TONE_TIMER,
    MIB_VOICE_PROFILE__XCT_BUSY_TONE_TIMER,
    MIB_VOICE_PROFILE__XCT_NO_ANSWER_TIMER,
    MIB_VOICE_PROFILE__XCT_DEFAULT_PROXY_INDEX,
	MIB_VOICE_PROFILE__SIP__PROXY_SERVER,
	MIB_VOICE_PROFILE__SIP__PROXY_SERVER_PORT,			
	MIB_VOICE_PROFILE__SIP__PROXY_SERVER_TRANSPORT,
	MIB_VOICE_PROFILE__SIP__REGISTRAR_SERVER,
	MIB_VOICE_PROFILE__SIP__REGISTRAR_SERVER_PORT,
	MIB_VOICE_PROFILE__SIP__REGISTRAR_SERVER_TRANSPORT,
	MIB_VOICE_PROFILE__SIP__USER_AGENT_DOMAIN,
	MIB_VOICE_PROFILE__SIP__USER_AGENT_PORT,
	MIB_VOICE_PROFILE__SIP__USER_AGENT_TRANSPORT,
	MIB_VOICE_PROFILE__SIP__OUTBOUND_PROXY,
	MIB_VOICE_PROFILE__SIP__OUTBOUND_PROXY_PORT,
	MIB_VOICE_PROFILE__SIP__ORGANIZATION,				
	MIB_VOICE_PROFILE__SIP__REGISTRATION_PERIOD,
	MIB_VOICE_PROFILE__SIP__XCT_STB_REGISTRATION_PERIOD,
	MIB_VOICE_PROFILE__SIP__VLANIDMARK,
	MIB_VOICE_PROFILE__SIP__DSCPMARK,
	MIB_VOICE_PROFILE__SIP__REGISTERRETRYINTERVAL,
	MIB_VOICE_PROFILE__SIP__REGISTEREXPIRES,
	/*proxy 2 for every fxs port */
	MIB_VOICE_PROFILE__SIP__XCT_STB_REGISTERRETRYINTERVAL,
	MIB_VOICE_PROFILE__SIP__XCT_STB_REGISTEREXPIRES,
	MIB_VOICE_PROFILE__SIP__XCT_STB_PROXY_SERVER,
	MIB_VOICE_PROFILE__SIP__XCT_STB_PROXY_SERVER_PORT,
	MIB_VOICE_PROFILE__SIP__XCT_STB_PROXY_SERVER_TRANSPORT,
	MIB_VOICE_PROFILE__SIP__XCT_STB_REGISTRAR_SERVER,
	MIB_VOICE_PROFILE__SIP__XCT_STB_REGISTRAR_SERVER_PORT,
	MIB_VOICE_PROFILE__SIP__XCT_STB_REGISTRAR_SERVER_TRANSPORT,
	MIB_VOICE_PROFILE__SIP__XCT_STB_OUTBOUND_PROXY,		//30
	MIB_VOICE_PROFILE__SIP__XCT_STB_OUTBOUND_PROXY_PORT,
	MIB_VOICE_PROFILE__SIP__XCT_STB_802_1PMARK,
	MIB_VOICE_PROFILE__SIP__XCT_HEARTBEATSWITCH,
	MIB_VOICE_PROFILE__SIP__XCT_HEARTBEATCYCLE,
	MIB_VOICE_PROFILE__SIP__XCT_HEARTBEATCOUNT,
	MIB_VOICE_PROFILE__SIP__INVITEEXPIRES,
	MIB_VOICE_PROFILE__SIP__XCT_INVITEEXPIRES,
	MIB_VOICE_PROFILE__RTP__VLANIDMARK,
	MIB_VOICE_PROFILE__RTP__DSCPMARK,
	MIB_VOICE_PROFILE__RTP__XCT_STB_802_1PMARK,
	MIB_VOICE_PROFILE__NUMBERINGPLAN__XCT_NUMBERPLAN,
	MIB_VOICE_PROFILE__FAXT38__ENABLE,
	MIB_VOICE_PROFILE__XCT_G711FAX__ENABLE,
    MIB_VOICE_PROFILE__XCT_G711FAX__CONTROLTYPE,
	MIB_VOICE_PROFILE__XCT_IADDIAG__IADDIAGNOSTICSSTATE,
	MIB_VOICE_PROFILE__XCT_IADDIAG__TESTSERVER,
	MIB_VOICE_PROFILE__XCT_IADDIAG__REGISTRESULT,
	MIB_VOICE_PROFILE__XCT_IADDIAG__REASON,
	MIB_VOICE_PROFILE__ARG_TYPE1_END,		/* End of Voice Profile Type 1*/
	/* Need instance number of PhyInterface */
	MIB_PHYINTERFACE__INTERFACEID,
	MIB_PHYINTERFACE__PHYPORT,
	MIB_PHYINTERFACE__TESTS__TESTSTATE,
	MIB_PHYINTERFACE__TESTS__TESTSELECTOR,
	MIB_PHYINTERFACE__TESTS__PHONECONNECTIVITY, 
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__TESTTYPE,
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__CALLEDNUMBER,
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__DAILDTMFCONFIRMENABLE,
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__DAILDTMFCONFIRMNUMBER,
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__DAILDTMFCONFIRMRESULT,
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__STATUS,
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__CONCLUSION,
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__CALLERFAILREASON,
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__CALLEDFAILREASON,
    MIB_PHYINTERFACE__TESTS__XCT_SIMULATETEST__FAILEDRESPONSECODE,
	MIB_PHYINTERFACE__ARG_TYPE1_END,		/* End of PhyInterface Type 2*/
	/* -------------------- Arguments type 2 ------------------------ */
	/* Need instance number of PROFILE and LINE */
	MIB_VOICE_PROFILE__LINE__ENABLE,
	MIB_VOICE_PROFILE__LINE__DIRECTORY_NUMBER,
	MIB_VOICE_PROFILE__LINE__STATUS,
	MIB_VOICE_PROFILE__LINE__XCT_ENABLE,
	MIB_VOICE_PROFILE__LINE__XCT_DIRECTORY_NUMBER,
	MIB_VOICE_PROFILE__LINE__SIP__AUTH_USER_NAME,
	MIB_VOICE_PROFILE__LINE__SIP__AUTH_PASSWORD,
	MIB_VOICE_PROFILE__LINE__SIP__URI,
	MIB_VOICE_PROFILE__LINE__SIP__XCT_AUTH_USER_NAME,
	MIB_VOICE_PROFILE__LINE__SIP__XCT_AUTH_PASSWORD,
	MIB_VOICE_PROFILE__LINE__SIP__XCT_URI,
	MIB_VOICE_PROFILE__LINE__STATS__PACKETS_SENT,				/* unused */	
	MIB_VOICE_PROFILE__LINE__STATS__PACKETS_RECEIVED,			/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__BYTES_SENT,					/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__BYTES_RECEIVED,				/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__PACKETS_LOST,				/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__INCOMING_CALLS_RECEIVED,	/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__INCOMING_CALLS_ANSWERED,	/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__INCOMING_CALLS_CONNECTED,	/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__INCOMING_CALLS_FAILED,		/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__OUTGOING_CALLS_ATTEMPTED,	/* unused */	
	MIB_VOICE_PROFILE__LINE__STATS__OUTGOING_CALLS_ANSWERED,	/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__OUTGOING_CALLS_CONNECTED,	/* unused */
	MIB_VOICE_PROFILE__LINE__STATS__OUTGOING_CALLS_FAILED,		/* unused */   
	MIB_VOICE_PROFILE__LINE__STATS__RESET_STATISTICS,
	MIB_VOICE_PROFILE__LINE__STATS__TOTAL_CALL_TIME,
	MIB_VOICE_PROFILE__LINE__VOIP_PROCESSING__TRANSMIT_GAIN,
	MIB_VOICE_PROFILE__LINE__VOIP_PROCESSING__RECEIVE_GAIN,
	MIB_VOICE_PROFILE__LINE__VOIP_PROCESSING__ECHO_CANCELLATION_ENABLE,
    MIB_VOICE_PROFILE__LINE__VOIP_PROCESSING__ECHO_CANCELLATION_INUSE,
    MIB_VOICE_PROFILE__LINE__VOIP_PROCESSING__ECHO_CANCELLATION_TAIL,
    MIB_VOICE_PROFILE__LINE__CALLING_FEATURES_CALLERIDNAME,
    MIB_VOICE_PROFILE__LINE__XCT_CALLING_FEATURES_CALLERIDNAME,
    MIB_VOICE_PROFILE__LINE__CALLING_FEATURES_CALLWAITING_ENABLE,
    MIB_VOICE_PROFILE__LINE__XCT_IMS__DIALTONEPATTERN,
    MIB_VOICE_PROFILE__LINE__XCT_IMS__MCIDSERVICE,
    MIB_VOICE_PROFILE__LINE__XCT_IMS__NODIALINGBEHAVIOUR,
    MIB_VOICE_PROFILE__LINE__XCT_IMS__HOLDSERVICE,
    MIB_VOICE_PROFILE__LINE__XCT_IMS__THREEPARTYSERVICE,
    MIB_VOICE_PROFILE__LINE__XCT_IMS__CONFERENCEURI,
    MIB_VOICE_PROFILE__LINE__XCT_IMS__HOTLINEURI,
    MIB_VOICE_PROFILE__LINE__XCT_IMS__CWSERVICE,
    MIB_VOICE_PROFILE__ARG_TYPE2_END,		/* End of Voice Profile Type 2*/
    /* Need instance number of PHYINTERFACE ID and POORQUALITYLIST ID */   
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__STATTIME,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__TXPACKETS,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__RXPACKETS,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__MEANDELAY,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__MEANJITTER,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__FRACTIONLOSS,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__LOCALIPADDRESS,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__LOCALUDPPORT,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__FARENDIPADDRESS,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__FARENDUDPPORT,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__MOSLQ,
    MIB_PHYINTERFACE__XCT_STATUS__POORQUALITYLIST__CODEC,
    MIB_PHYINTERFACE__ARG_TYPE2_END,		/* End of PhyInterface Type 2*/
	/* -------------------- Arguments type 3 ------------------------ */
	/* Need instance number of PROFILE, LINE and LIST */
	MIB_VOICE_PROFILE__LINE__SIP__CODEC__LIST__ENTRY_ID,	/* unused */
	MIB_VOICE_PROFILE__LINE__SIP__CODEC__LIST__CODEC,		/* unused */
	MIB_VOICE_PROFILE__LINE__SIP__CODEC__LIST__BITRATE,		/* unused */
	MIB_VOICE_PROFILE__LINE__SIP__CODEC__LIST__PACKETIZATION_PERIOD,				
	MIB_VOICE_PROFILE__LINE__SIP__CODEC__LIST__SILENCE_SUPPRESSION,
	MIB_VOICE_PROFILE__LINE__SIP__CODEC__LIST__PRIORITY,
	MIB_VOICE_PROFILE__ARG_TYPE3_END,		/* End of Voice Profile Type 3*/
	/* -------------------- ---------------- ------------------------ */	
	MIB_ID_EOF						/* keep it to be the last one */
} idMib_t;

void mib_config_clean(void);

extern int mib_get_type1( idMib_t idMib, unsigned int nInstNum1, 
				   void *pData );
extern int mib_set_type1( idMib_t idMib, unsigned int nInstNum1, 
				   void *pData );

extern int mib_get_type2( idMib_t idMib, unsigned int nInstNum1, 
				   unsigned int nInstNum2,
				   void *pData );
extern int mib_set_type2( idMib_t idMib, unsigned int nInstNum1, 
				   unsigned int nInstNum2,
				   void *pData );

extern int mib_get_type3( idMib_t idMib, unsigned int nInstNum1, 
				   unsigned int nInstNum2, unsigned int nInstNum3,
				   void *pData );
extern int mib_set_type3( idMib_t idMib, unsigned int nInstNum1, 
				   unsigned int nInstNum2, unsigned int nInstNum3,
				   void *pData );

#endif /* __MIB_SIM_H__ */

