obj-y += microsemi_voicepath_api/api_lib/
obj-y += microsemi_voicepath_api/arch/rtl89xxb/
obj-y += microsemi_voicepath_api/profiles/
ifeq "$(CONFIG_RTK_VOIP_DRIVERS_SLIC_MICROSEMI_LINETEST)" "y"
obj-y += microsemi_verivoice_api/common/
obj-y += microsemi_verivoice_api/vp880_lt/
obj-y += microsemi_verivoice_api/vp886_lt/
obj-y += microsemi_verivoice_api/vp890_lt/
endif
include $(DIR_VOIP)/rules.mak

