/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Gateway_jni */

#ifndef _Included_Gateway_jni
#define _Included_Gateway_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Gateway_jni
 * Method:    getWanIp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Gateway_1jni_getWanIp
  (JNIEnv *, jclass);

/*
 * Class:     Gateway_jni
 * Method:    getLoid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Gateway_1jni_getLoid
  (JNIEnv *, jclass);

/*
 * Class:     Gateway_jni
 * Method:    getUSB
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Gateway_1jni_getUSB
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
