# /**************************************
#  ecmh - Easy Cast du Multi Hub
#  by Jeroen Massar <jeroen@unfix.org>
# ***************************************
# $Author: masonyu $
# $Id: Makefile,v 1.1 2011/02/16 11:32:12 masonyu Exp $
# $Date: 2011/02/16 11:32:12 $
# **************************************/
#
# Tools Makefile
#

all:	mtrace6

mtrace6: mtrace6/
	$(MAKE) -C mtrace6 all

clean:
	$(MAKE) -C mtrace6 clean

# Mark targets as phony
.PHONY : all clean mtrace6

