#ifndef		_AUTOCONF_H_
#define		_AUTOCONF_H_

#define CONFIG_USER_SNMPD_MODULE_SYSTEM
#define CONFIG_USER_SNMPD_MODULE_IP
#define CONFIG_USER_SNMPD_MODULE_IFACE
#define CONFIG_USER_SNMPD_MODULE_TCP
#define CONFIG_USER_SNMPD_MODULE_ICMP
#define CONFIG_USER_SNMPD_MODULE_UDP

#define CONFIG_USER_SNMPD_MODULE_ADSL
//#define CONFIG_USER_SNMPD_MODULE_ATM

//#define CONFIG_USER_SNMPD_MODULE_FRAMEWORK

#define		AGENT_SYS_TEXT_SIZE		255

#endif

