
static ctc_eventAlarmCode_t ctc_alarmCode[] = {
    /* { Alarm Target, Alarm ID, Alarm Info Length } */
    /* ONU */
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_EQUIPMENT,               4 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_POWER,                   4 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_BATTERYMISSING,          0 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_BATTERYFAILURE,          0 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_BATTERYVOLTLOW,          4 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_PHYSICALINTRUSION,       0 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_ONUSELFTESTFAILURE,      4 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_ONUTEMPHIGH,             4 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_ONUTEMPLOW,              4 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_IADCONNECTIONFAILURE,    4 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_PONIFSWITCH,             4 },
    { CTC_VAR_REQBRANCH_INSTANT_ONU, CTC_OAM_ALARMCODE_SLEEPSTATUSUPDATE,       4 },
    /* PON IF */
    { CTC_VAR_REQBRANCH_INSTANT_NONE,  CTC_OAM_ALARMCODE_NONE,                  0 },
};

