subdir-y += packetGen
obj-y += packetGen/built-in.o

## RTL8196e hw. specific
obj-y += rtl865xc_testModel_L34_test.o
obj-y += rtl865xc_testModel.o


## Test Model body (hw. independant)
obj-y += modelTrace.o
obj-y += virtualMac.o
obj-y += testModel.o
