/* This file is auto-generated. DO NOT EDIT. */
#ifndef L2TP_OPTIONS_H
#define L2TP_OPTIONS_H

#include <config/autoconf.h>

#define L2TP_FEATURE_LOCAL_CONF_FILE

#define L2TP_FEATURE_LAC_SUPPORT
#define L2TP_FEATURE_LAIC_SUPPORT
#define L2TP_FEATURE_LAOC_SUPPORT
#ifdef CONFIG_USER_L2TPD_LNS
#define L2TP_FEATURE_LNS_SUPPORT
#define L2TP_FEATURE_LNIC_SUPPORT
#define L2TP_FEATURE_LNOC_SUPPORT
#endif

#endif
