/*
 * Copyright (C) 2012 Realtek Semiconductor Corp.
 * All Rights Reserved.
 *
 * This program is the proprietary software of Realtek Semiconductor
 * Corporation and/or its licensors, and only be used, duplicated,
 * modified or distributed under the authorized license from Realtek.
 *
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 * THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 */

/*
 * Include Files
 */
#include <common/debug/rt_log.h>
#include <dal/dal_mapper.h>
#include <dal/dal_common.h>
#include <dal/rtl9601b/dal_rtl9601b_mapper.h>
#include <dal/rtl9601b/dal_rtl9601b_switch.h>
#include <dal/rtl9601b/dal_rtl9601b_oam.h>
#include <dal/rtl9601b/dal_rtl9601b_classify.h>
#include <dal/rtl9601b/dal_rtl9601b_stp.h>
#include <dal/rtl9601b/dal_rtl9601b_gpon.h>
#include <dal/rtl9601b/dal_rtl9601b_vlan.h>
#include <dal/rtl9601b/dal_rtl9601b_gpio.h>
#include <dal/rtl9601b/dal_rtl9601b_intr.h>
#include <dal/rtl9601b/dal_rtl9601b_l2.h>
#include <dal/rtl9601b/dal_rtl9601b_port.h>
#include <dal/rtl9601b/dal_rtl9601b_ponmac.h>
#include <dal/rtl9601b/dal_rtl9601b_rate.h>
#include <dal/rtl9601b/dal_rtl9601b_stat.h>
#include <dal/rtl9601b/dal_rtl9601b_qos.h>
#include <dal/rtl9601b/dal_rtl9601b_i2c.h>
#include <dal/rtl9601b/dal_rtl9601b_svlan.h>
#include <dal/rtl9601b/dal_rtl9601b_acl.h>
#include <dal/rtl9601b/dal_rtl9601b_epon.h>
#include <dal/rtl9601b/dal_rtl9601b_trap.h>
#include <dal/rtl9601b/dal_rtl9601b_cpu.h>
#include <dal/rtl9601b/dal_rtl9601b_led.h>

/*
#include <dal/rtl9601b/dal_rtl9601b_trunk.h>
#include <dal/rtl9601b/dal_rtl9601b_mirror.h>
#include <dal/rtl9601b/dal_rtl9601b_rldp.h>
#include <dal/rtl9601b/dal_rtl9601b_dot1x.h>
#include <dal/rtl9601b/dal_rtl9601b_time.h>
*/
/*
 * Symbol Definition
 */

/*
 * Data Declaration
 */
static dal_mapper_t dal_rtl9601b_mapper =
{
    RTL9601B_CHIP_ID,
    ._init = dal_rtl9601b_init,

    /* Switch */
    .switch_init = dal_rtl9601b_switch_init,
    .switch_phyPortId_get = dal_rtl9601b_switch_phyPortId_get,
    .switch_logicalPort_get = dal_rtl9601b_switch_logicalPort_get,
    .switch_port2PortMask_set = dal_rtl9601b_switch_port2PortMask_set,
    .switch_port2PortMask_clear = dal_rtl9601b_switch_port2PortMask_clear,
    .switch_portIdInMask_check = dal_rtl9601b_switch_portIdInMask_check,
    .switch_maxPktLenLinkSpeed_get = dal_rtl9601b_switch_maxPktLenLinkSpeed_get,
    .switch_maxPktLenLinkSpeed_set = dal_rtl9601b_switch_maxPktLenLinkSpeed_set,
    .switch_mgmtMacAddr_get = dal_rtl9601b_switch_mgmtMacAddr_get,
    .switch_mgmtMacAddr_set = dal_rtl9601b_switch_mgmtMacAddr_set,
    .switch_chip_reset = dal_rtl9601b_switch_chip_reset,
    .switch_version_get = dal_rtl9601b_switch_version_get,
    .switch_patch_info_get = NULL,
    .switch_csExtId_get = NULL,
    .switch_maxPktLenByPort_get = dal_rtl9601b_switch_maxPktLenByPort_get,
    .switch_maxPktLenByPort_set = dal_rtl9601b_switch_maxPktLenByPort_set,

    /*oam*/
    .oam_init = dal_rtl9601b_oam_init,
    .oam_parserAction_set = dal_rtl9601b_oam_parserAction_set,
    .oam_parserAction_get = dal_rtl9601b_oam_parserAction_get,
    .oam_multiplexerAction_set = dal_rtl9601b_oam_multiplexerAction_set,
    .oam_multiplexerAction_get = dal_rtl9601b_oam_multiplexerAction_get,

    /* STP */
    .stp_init = dal_rtl9601b_stp_init,
    .stp_mstpState_get = dal_rtl9601b_stp_mstpState_get,
    .stp_mstpState_set = dal_rtl9601b_stp_mstpState_set,


     /* VLAN */
    .vlan_init                                  = dal_rtl9601b_vlan_init,
    .vlan_create                                = dal_rtl9601b_vlan_create,
    .vlan_destroy                               = dal_rtl9601b_vlan_destroy,
    .vlan_destroyAll                            = dal_rtl9601b_vlan_destroyAll,
    .vlan_fid_get                               = NULL,
    .vlan_fid_set                               = NULL,
    .vlan_fidMode_get                           = dal_rtl9601b_vlan_fidMode_get,
    .vlan_fidMode_set                           = dal_rtl9601b_vlan_fidMode_set,
    .vlan_port_get                              = dal_rtl9601b_vlan_port_get,
    .vlan_port_set                              = dal_rtl9601b_vlan_port_set,
    .vlan_extPort_get                           = NULL,
    .vlan_extPort_set                           = NULL,
    .vlan_stg_get                               = NULL,
    .vlan_stg_set                               = NULL,
    .vlan_priority_get                          = NULL,
    .vlan_priority_set                          = NULL,
    .vlan_priorityEnable_get                    = NULL,
    .vlan_priorityEnable_set                    = NULL,
    .vlan_policingEnable_get                    = NULL,
    .vlan_policingEnable_set                    = NULL,
    .vlan_policingMeterIdx_get                  = NULL,
    .vlan_policingMeterIdx_set                  = NULL,
    .vlan_portAcceptFrameType_get               = dal_rtl9601b_vlan_portAcceptFrameType_get,
    .vlan_portAcceptFrameType_set               = dal_rtl9601b_vlan_portAcceptFrameType_set,
    .vlan_vlanFunctionEnable_get                = dal_rtl9601b_vlan_vlanFunctionEnable_get,
    .vlan_vlanFunctionEnable_set                = dal_rtl9601b_vlan_vlanFunctionEnable_set,
    .vlan_portIgrFilterEnable_get               = dal_rtl9601b_vlan_portIgrFilterEnable_get,
    .vlan_portIgrFilterEnable_set               = dal_rtl9601b_vlan_portIgrFilterEnable_set,
    .vlan_leaky_get                             = NULL,
    .vlan_leaky_set                             = NULL,
    .vlan_portLeaky_get                         = NULL,
    .vlan_portLeaky_set                         = NULL,
    .vlan_keepType_get                          = dal_rtl9601b_vlan_keepType_get,
    .vlan_keepType_set                          = dal_rtl9601b_vlan_keepType_set,
    .vlan_portPvid_get                          = dal_rtl9601b_vlan_portPvid_get,
    .vlan_portPvid_set                          = dal_rtl9601b_vlan_portPvid_set,
    .vlan_extPortPvid_get                       = NULL,
    .vlan_extPortPvid_set                       = NULL,
    .vlan_protoGroup_get                        = dal_rtl9601b_vlan_protoGroup_get,
    .vlan_protoGroup_set                        = dal_rtl9601b_vlan_protoGroup_set,
    .vlan_portProtoVlan_get                     = dal_rtl9601b_vlan_portProtoVlan_get,
    .vlan_portProtoVlan_set                     = dal_rtl9601b_vlan_portProtoVlan_set,
    .vlan_tagMode_get                           = dal_rtl9601b_vlan_tagMode_get,
    .vlan_tagMode_set                           = dal_rtl9601b_vlan_tagMode_set,
    .vlan_portFid_get                           = NULL,
    .vlan_portFid_set                           = NULL,
    .vlan_portPriority_get                      = NULL,
    .vlan_portPriority_set                      = NULL,
    .vlan_portEgrTagKeepType_get                = NULL,
    .vlan_portEgrTagKeepType_set                = NULL,
    .vlan_transparentEnable_get                 = NULL,
    .vlan_transparentEnable_set                 = NULL,
    .vlan_cfiKeepEnable_get                     = dal_rtl9601b_vlan_cfiKeepEnable_get,
    .vlan_cfiKeepEnable_set                     = dal_rtl9601b_vlan_cfiKeepEnable_set,
    .vlan_reservedVidAction_get                 = dal_rtl9601b_vlan_reservedVidAction_get,
    .vlan_reservedVidAction_set                 = dal_rtl9601b_vlan_reservedVidAction_set,
    .vlan_tagModeIp4mc_get                      = NULL,
    .vlan_tagModeIp4mc_set                      = NULL,
    .vlan_tagModeIp6mc_get                      = NULL,
    .vlan_tagModeIp6mc_set                      = NULL,
    .vlan_lutSvlanHashState_set = dal_rtl9601b_vlan_lutSvlanHashState_set,
    .vlan_lutSvlanHashState_get = dal_rtl9601b_vlan_lutSvlanHashState_get,
	.vlan_extPortProtoVlan_set					= NULL,
	.vlan_extPortProtoVlan_get					= NULL,


    /* Mirror */
    .mirror_init                                = NULL,
    .mirror_portBased_set                       = NULL,
    .mirror_portBased_get                       = NULL,
    .mirror_portIso_set                         = NULL,
    .mirror_portIso_get                         = NULL,




    /*SVLAN*/
    .svlan_init = dal_rtl9601b_svlan_init,
    .svlan_create = dal_rtl9601b_svlan_create,
    .svlan_destroy = dal_rtl9601b_svlan_destroy,
    .svlan_portSvid_get = dal_rtl9601b_svlan_portSvid_get,
    .svlan_portSvid_set = dal_rtl9601b_svlan_portSvid_set,
    .svlan_servicePort_get = dal_rtl9601b_svlan_servicePort_get,
    .svlan_servicePort_set = dal_rtl9601b_svlan_servicePort_set,
    .svlan_memberPort_set = dal_rtl9601b_svlan_memberPort_set,
    .svlan_memberPort_get = dal_rtl9601b_svlan_memberPort_get,
    .svlan_tpidEntry_get = dal_rtl9601b_svlan_tpidEntry_get,
    .svlan_tpidEntry_set = dal_rtl9601b_svlan_tpidEntry_set,
    .svlan_priorityRef_set = dal_rtl9601b_svlan_priorityRef_set,
    .svlan_priorityRef_get = dal_rtl9601b_svlan_priorityRef_get,
    .svlan_memberPortEntry_set = NULL,
    .svlan_memberPortEntry_get = NULL,
    .svlan_ipmc2s_add = NULL,
    .svlan_ipmc2s_del = NULL,
    .svlan_ipmc2s_get = NULL,
    .svlan_l2mc2s_add = NULL,
    .svlan_l2mc2s_del = NULL,
    .svlan_l2mc2s_get = NULL,
    .svlan_sp2c_add = NULL,
    .svlan_sp2c_get = NULL,
    .svlan_sp2c_del = NULL,
    .svlan_dmacVidSelState_set = NULL,
    .svlan_dmacVidSelState_get = NULL,
    .svlan_unmatchAction_set = NULL,
    .svlan_unmatchAction_get = NULL,
    .svlan_untagAction_set = dal_rtl9601b_svlan_untagAction_set,
    .svlan_untagAction_get = dal_rtl9601b_svlan_untagAction_get,
    .svlan_c2s_add = NULL,
    .svlan_c2s_del = NULL,
    .svlan_c2s_get = NULL,
    .svlan_trapPri_get = NULL,
    .svlan_trapPri_set = NULL,
    .svlan_deiKeepState_get = dal_rtl9601b_svlan_deiKeepState_get,
    .svlan_deiKeepState_set = dal_rtl9601b_svlan_deiKeepState_set,
    .svlan_lookupType_get = NULL,
    .svlan_lookupType_set = NULL,
    .svlan_sp2cUnmatchCtagging_get = NULL,
    .svlan_sp2cUnmatchCtagging_set = NULL,
	.svlan_priority_get = NULL,
	.svlan_priority_set = NULL,
	.svlan_fid_get = NULL,
	.svlan_fid_set = NULL,
	.svlan_fidEnable_get = NULL,
	.svlan_fidEnable_set = NULL,
	.svlan_enhancedFid_get = NULL,
	.svlan_enhancedFid_set = NULL,
	.svlan_enhancedFidEnable_get = NULL,
	.svlan_enhancedFidEnable_set = NULL,
    .svlan_dmacVidSelForcedState_set = NULL,
    .svlan_dmacVidSelForcedState_get = NULL,
    .svlan_svlanFunctionEnable_get = dal_rtl9601b_svlan_svlanFunctionEnable_get,
    .svlan_svlanFunctionEnable_set = dal_rtl9601b_svlan_svlanFunctionEnable_set,
	.svlan_tpidEnable_get = NULL,
	.svlan_tpidEnable_set = NULL,
	.svlan_sp2cPriority_add = NULL,
	.svlan_sp2cPriority_get = NULL,

    /*acl*/
    .acl_init = dal_rtl9601b_acl_init,
    .acl_template_set = dal_rtl9601b_acl_template_set,
    .acl_template_get = dal_rtl9601b_acl_template_get,
    .acl_fieldSelect_set = dal_rtl9601b_acl_fieldSelect_set,
    .acl_fieldSelect_get = dal_rtl9601b_acl_fieldSelect_get,
    .acl_igrRuleEntry_get = dal_rtl9601b_acl_igrRuleEntry_get,
    .acl_igrRuleField_add = dal_rtl9601b_acl_igrRuleField_add,
    .acl_igrRuleEntry_add = dal_rtl9601b_acl_igrRuleEntry_add,
    .acl_igrRuleEntry_del = dal_rtl9601b_acl_igrRuleEntry_del,
    .acl_igrRuleEntry_delAll = dal_rtl9601b_acl_igrRuleEntry_delAll,
    .acl_igrUnmatchAction_set = dal_rtl9601b_acl_igrUnmatchAction_set,
    .acl_igrUnmatchAction_get = dal_rtl9601b_acl_igrUnmatchAction_get,
    .acl_igrState_set = dal_rtl9601b_acl_igrState_set,
    .acl_igrState_get = dal_rtl9601b_acl_igrState_get,
    .acl_ipRange_set = dal_rtl9601b_acl_ipRange_set,
    .acl_ipRange_get = dal_rtl9601b_acl_ipRange_get,
    .acl_vidRange_set = dal_rtl9601b_acl_vidRange_set,
    .acl_vidRange_get = dal_rtl9601b_acl_vidRange_get,
    .acl_portRange_set = dal_rtl9601b_acl_portRange_set,
    .acl_portRange_get = dal_rtl9601b_acl_portRange_get,
    .acl_packetLengthRange_set = dal_rtl9601b_acl_packetLengthRange_set,
    .acl_packetLengthRange_get = dal_rtl9601b_acl_packetLengthRange_get,
    .acl_igrRuleMode_set = NULL,
    .acl_igrRuleMode_get = NULL,
    .acl_igrPermitState_set = dal_rtl9601b_acl_igrPermitState_set,
    .acl_igrPermitState_get = dal_rtl9601b_acl_igrPermitState_get,
	.acl_dbgInfo_get = dal_rtl9601b_acl_dbgInfo_get,
	.acl_dbgHitReason_get = dal_rtl9601b_acl_dbgHitReason_get,

    /* QoS */
    .qos_init = dal_rtl9601b_qos_init,
    .qos_priSelGroup_get = dal_rtl9601b_qos_priSelGroup_get,
    .qos_priSelGroup_set = dal_rtl9601b_qos_priSelGroup_set,
    .qos_portPri_get = dal_rtl9601b_qos_portPri_get,
    .qos_portPri_set = dal_rtl9601b_qos_portPri_set,
    .qos_dscpPriRemapGroup_get = dal_rtl9601b_qos_dscpPriRemapGroup_get,
    .qos_dscpPriRemapGroup_set = dal_rtl9601b_qos_dscpPriRemapGroup_set,
    .qos_1pPriRemapGroup_get = dal_rtl9601b_qos_1pPriRemapGroup_get,
    .qos_1pPriRemapGroup_set = dal_rtl9601b_qos_1pPriRemapGroup_set,
    .qos_priMap_get = dal_rtl9601b_qos_priMap_get,
    .qos_priMap_set = dal_rtl9601b_qos_priMap_set,
    .qos_portPriMap_get = dal_rtl9601b_qos_portPriMap_get,
    .qos_portPriMap_set = dal_rtl9601b_qos_portPriMap_set,
    .qos_1pRemarkEnable_get = dal_rtl9601b_qos_1pRemarkEnable_get,
    .qos_1pRemarkEnable_set = dal_rtl9601b_qos_1pRemarkEnable_set,
    .qos_1pRemarkGroup_get = dal_rtl9601b_qos_1pRemarkGroup_get,
    .qos_1pRemarkGroup_set = dal_rtl9601b_qos_1pRemarkGroup_set,
    .qos_dscpRemarkEnable_get = dal_rtl9601b_qos_dscpRemarkEnable_get,
    .qos_dscpRemarkEnable_set = dal_rtl9601b_qos_dscpRemarkEnable_set,
    .qos_dscpRemarkGroup_get = dal_rtl9601b_qos_dscpRemarkGroup_get,
    .qos_dscpRemarkGroup_set = dal_rtl9601b_qos_dscpRemarkGroup_set,
    .qos_fwd2CpuPriRemap_get = dal_rtl9601b_qos_fwd2CpuPriRemap_get,
    .qos_fwd2CpuPriRemap_set = dal_rtl9601b_qos_fwd2CpuPriRemap_set,
    .qos_portDscpRemarkSrcSel_get = dal_rtl9601b_qos_portDscpRemarkSrcSel_get,
    .qos_portDscpRemarkSrcSel_set = dal_rtl9601b_qos_portDscpRemarkSrcSel_set,
    .qos_dscp2DscpRemarkGroup_get = dal_rtl9601b_qos_dscp2DscpRemarkGroup_get,
    .qos_dscp2DscpRemarkGroup_set = dal_rtl9601b_qos_dscp2DscpRemarkGroup_set,
    .qos_schedulingQueue_get = dal_rtl9601b_qos_schedulingQueue_get,
    .qos_schedulingQueue_set = dal_rtl9601b_qos_schedulingQueue_set,
    .qos_portPriSelGroup_get = dal_rtl9601b_qos_portPriSelGroup_get,
    .qos_portPriSelGroup_set = dal_rtl9601b_qos_portPriSelGroup_set,
    .qos_schedulingType_get = dal_rtl9601b_qos_schedulingType_get,
    .qos_schedulingType_set = dal_rtl9601b_qos_schedulingType_set,
    .qos_portDot1pRemarkSrcSel_get = dal_rtl9601b_qos_portDot1pRemarkSrcSel_get,
    .qos_portDot1pRemarkSrcSel_set = dal_rtl9601b_qos_portDot1pRemarkSrcSel_set,

    /*sec*/
    .sec_init = NULL,
    .sec_portAttackPreventState_get = NULL,
    .sec_portAttackPreventState_set = NULL,
    .sec_attackPrevent_get = NULL,
    .sec_attackPrevent_set = NULL,
    .sec_attackFloodThresh_get = NULL,
    .sec_attackFloodThresh_set = NULL,


    /*rate*/
    .rate_init = dal_rtl9601b_rate_init,
    .rate_portIgrBandwidthCtrlRate_get = dal_rtl9601b_rate_portIgrBandwidthCtrlRate_get,
    .rate_portIgrBandwidthCtrlRate_set = dal_rtl9601b_rate_portIgrBandwidthCtrlRate_set,
    .rate_portIgrBandwidthCtrlIncludeIfg_get = dal_rtl9601b_rate_portIgrBandwidthCtrlIncludeIfg_get,
    .rate_portIgrBandwidthCtrlIncludeIfg_set = dal_rtl9601b_rate_portIgrBandwidthCtrlIncludeIfg_set,
    .rate_portEgrBandwidthCtrlRate_get = dal_rtl9601b_rate_portEgrBandwidthCtrlRate_get,
    .rate_portEgrBandwidthCtrlRate_set = dal_rtl9601b_rate_portEgrBandwidthCtrlRate_set,
    .rate_egrBandwidthCtrlIncludeIfg_get = dal_rtl9601b_rate_egrBandwidthCtrlIncludeIfg_get,
    .rate_egrBandwidthCtrlIncludeIfg_set = dal_rtl9601b_rate_egrBandwidthCtrlIncludeIfg_set,
    .rate_portEgrBandwidthCtrlIncludeIfg_get = dal_rtl9601b_rate_portEgrBandwidthCtrlIncludeIfg_get,
    .rate_portEgrBandwidthCtrlIncludeIfg_set = dal_rtl9601b_rate_portEgrBandwidthCtrlIncludeIfg_set,
    .rate_egrQueueBwCtrlEnable_get = dal_rtl9601b_rate_egrQueueBwCtrlEnable_get,
    .rate_egrQueueBwCtrlEnable_set = dal_rtl9601b_rate_egrQueueBwCtrlEnable_set,
    .rate_egrQueueBwCtrlMeterIdx_get = dal_rtl9601b_rate_egrQueueBwCtrlMeterIdx_get,
    .rate_egrQueueBwCtrlMeterIdx_set = dal_rtl9601b_rate_egrQueueBwCtrlMeterIdx_set,
    .rate_stormControlMeterIdx_get = dal_rtl9601b_rate_stormControlMeterIdx_get,
    .rate_stormControlMeterIdx_set = dal_rtl9601b_rate_stormControlMeterIdx_set,
    .rate_stormControlPortEnable_get = dal_rtl9601b_rate_stormControlPortEnable_get,
    .rate_stormControlPortEnable_set = dal_rtl9601b_rate_stormControlPortEnable_set,
    .rate_stormControlEnable_get = dal_rtl9601b_rate_stormControlEnable_get,
    .rate_stormControlEnable_set = dal_rtl9601b_rate_stormControlEnable_set,
    .rate_stormBypass_set = dal_rtl9601b_rate_stormBypass_set,
    .rate_stormBypass_get = dal_rtl9601b_rate_stormBypass_get,
    .rate_shareMeter_set = dal_rtl9601b_rate_shareMeter_set,
    .rate_shareMeter_get = dal_rtl9601b_rate_shareMeter_get,
    .rate_shareMeterBucket_set = dal_rtl9601b_rate_shareMeterBucket_set,
    .rate_shareMeterBucket_get = dal_rtl9601b_rate_shareMeterBucket_get,
    .rate_shareMeterExceed_get = dal_rtl9601b_rate_shareMeterExceed_get,
    .rate_shareMeterExceed_clear = dal_rtl9601b_rate_shareMeterExceed_clear,
    .rate_shareMeterMode_set = dal_rtl9601b_rate_shareMeterMode_set,
    .rate_shareMeterMode_get = dal_rtl9601b_rate_shareMeterMode_get,
	.rate_hostIgrBwCtrlState_set = NULL,
	.rate_hostIgrBwCtrlState_get = NULL,
	.rate_hostEgrBwCtrlState_set = NULL,
	.rate_hostEgrBwCtrlState_get = NULL,
	.rate_hostBwCtrlMeterIdx_set = NULL,
	.rate_hostBwCtrlMeterIdx_get = NULL,
	.rate_hostMacAddr_set = NULL,
	.rate_hostMacAddr_get = NULL,


    /* Classification */
    .classify_init                              = dal_rtl9601b_classify_init,
    .classify_cfgEntry_add                      = dal_rtl9601b_classify_cfgEntry_add,
    .classify_cfgEntry_get                      = dal_rtl9601b_classify_cfgEntry_get,
    .classify_cfgEntry_del                      = dal_rtl9601b_classify_cfgEntry_del,
    .classify_field_add                         = dal_rtl9601b_classify_field_add,
    .classify_unmatchAction_set                 = dal_rtl9601b_classify_unmatchAction_set,
    .classify_unmatchAction_get                 = dal_rtl9601b_classify_unmatchAction_get,
    .classify_portRange_set                     = NULL,
    .classify_portRange_get                     = NULL,
    .classify_ipRange_set                       = NULL,
    .classify_ipRange_get                       = NULL,
    .classify_cf_sel_set                        = NULL,
    .classify_cf_sel_get                        = NULL,
    .classify_cfPri2Dscp_set                    = dal_rtl9601b_classify_cfPri2Dscp_set,
    .classify_cfPri2Dscp_get                    = dal_rtl9601b_classify_cfPri2Dscp_get,
    .classify_permit_sel_set                    = NULL,
    .classify_permit_sel_get                    = NULL,
    .classify_us1pRemarkPrior_set               = NULL,
    .classify_us1pRemarkPrior_get               = NULL,
    .classify_templateCfgPattern0_set           = NULL,
    .classify_templateCfgPattern0_get           = NULL,
    .classify_entryNumPattern1_set              = NULL,
    .classify_entryNumPattern1_get              = NULL,
    .classify_defaultWanIf_set                  = NULL,
    .classify_defaultWanIf_get                  = NULL,

    /*PON MAC*/
    .ponmac_init = dal_rtl9601b_ponmac_init,
    .ponmac_queue_add = dal_rtl9601b_ponmac_queue_add,
    .ponmac_queue_get = dal_rtl9601b_ponmac_queue_get,
    .ponmac_queue_del = dal_rtl9601b_ponmac_queue_del,
    .ponmac_flow2Queue_set = dal_rtl9601b_ponmac_flow2Queue_set,
    .ponmac_flow2Queue_get = dal_rtl9601b_ponmac_flow2Queue_get,
    .ponmac_mode_get = dal_rtl9601b_ponmac_mode_get,
    .ponmac_mode_set = dal_rtl9601b_ponmac_mode_set,
    .ponmac_queueDrainOut_set = dal_rtl9601b_ponmac_queueDrainOut_set,
    .ponmac_opticalPolarity_get = dal_rtl9601b_ponmac_opticalPolarity_get,
    .ponmac_opticalPolarity_set = dal_rtl9601b_ponmac_opticalPolarity_set,
    .ponmac_losState_get = dal_rtl9601b_ponmac_losState_get,
    .ponmac_serdesCdr_reset = dal_rtl9601b_ponmac_serdesCdr_reset,
    .ponmac_linkState_get = dal_rtl9601b_ponmac_linkState_get,
    .ponmac_forceBerNotify_set = dal_rtl9601b_ponmac_forceBerNotify_set,
    .ponmac_bwThreshold_set = NULL,
    .ponmac_bwThreshold_get = NULL,
    .ponmac_maxPktLen_set = dal_rtl9601b_ponmac_maxPktLen_set,
    .ponmac_schedulingType_get = dal_rtl9601b_ponmac_schedulingType_get,
    .ponmac_schedulingType_set = dal_rtl9601b_ponmac_schedulingType_set,
    .ponmac_egrBandwidthCtrlRate_get = NULL,
    .ponmac_egrBandwidthCtrlRate_set = NULL,
    .ponmac_egrScheduleIdRate_get = dal_rtl9601b_ponmac_egrScheduleIdRate_get,
    .ponmac_egrScheduleIdRate_set = dal_rtl9601b_ponmac_egrScheduleIdRate_set,

    /* statistics */
    .stat_init                                  = dal_rtl9601b_stat_init,
    .stat_global_reset                          = dal_rtl9601b_stat_global_reset,
    .stat_port_reset                            = dal_rtl9601b_stat_port_reset,
    .stat_log_reset                             = dal_rtl9601b_stat_log_reset,
	.stat_hostCnt_reset							= NULL,
	.stat_hostCnt_get							= NULL,
	.stat_hostState_get							= NULL,
	.stat_hostState_set 						= NULL,
    .stat_rst_cnt_value_set                     = dal_rtl9601b_stat_rst_cnt_value_set,
    .stat_rst_cnt_value_get                     = dal_rtl9601b_stat_rst_cnt_value_get,
    .stat_global_get                            = dal_rtl9601b_stat_global_get,
    .stat_global_getAll                         = dal_rtl9601b_stat_global_getAll,
    .stat_port_get                              = dal_rtl9601b_stat_port_get,
    .stat_port_getAll                           = dal_rtl9601b_stat_port_getAll,
    .stat_log_get                               = dal_rtl9601b_stat_log_get,
    .stat_log_ctrl_set                          = dal_rtl9601b_stat_log_ctrl_set,
    .stat_log_ctrl_get                          = dal_rtl9601b_stat_log_ctrl_get,
    .stat_mib_cnt_mode_get                      = dal_rtl9601b_stat_mib_cnt_mode_get,
    .stat_mib_cnt_mode_set                      = dal_rtl9601b_stat_mib_cnt_mode_set,
    .stat_mib_latch_timer_get                   = dal_rtl9601b_stat_mib_latch_timer_get,
    .stat_mib_latch_timer_set                   = dal_rtl9601b_stat_mib_latch_timer_set,
    .stat_mib_sync_mode_get                     = dal_rtl9601b_stat_mib_sync_mode_get,
    .stat_mib_sync_mode_set                     = dal_rtl9601b_stat_mib_sync_mode_set,
    .stat_mib_count_tag_length_get              = NULL,
    .stat_mib_count_tag_length_set              = NULL,
    .stat_pktInfo_get                           = dal_rtl9601b_stat_pktInfo_get,

    /* Trunk */
    .trunk_init                                 = NULL,
    .trunk_distributionAlgorithm_get            = NULL,
    .trunk_distributionAlgorithm_set            = NULL,
    .trunk_port_get                             = NULL,
    .trunk_port_set                             = NULL,
    .trunk_hashMappingTable_get                 = NULL,
    .trunk_hashMappingTable_set                 = NULL,
    .trunk_mode_get                             = NULL,
    .trunk_mode_set                             = NULL,
    .trunk_trafficSeparate_get                  = NULL,
    .trunk_trafficSeparate_set                  = NULL,
    .trunk_portQueueEmpty_get                   = NULL,
    .trunk_trafficPause_get                     = NULL,
    .trunk_trafficPause_set                     = NULL,

    /* Port */
    .port_init                                  = dal_rtl9601b_port_init,
    .port_link_get                              = dal_rtl9601b_port_link_get,
    .port_speedDuplex_get                       = dal_rtl9601b_port_speedDuplex_get,
    .port_flowctrl_get                          = dal_rtl9601b_port_flowctrl_get,
    .port_phyAutoNegoEnable_get                 = dal_rtl9601b_port_phyAutoNegoEnable_get,
    .port_phyAutoNegoEnable_set                 = dal_rtl9601b_port_phyAutoNegoEnable_set,
    .port_phyAutoNegoAbility_get                = dal_rtl9601b_port_phyAutoNegoAbility_get,
    .port_phyAutoNegoAbility_set                = dal_rtl9601b_port_phyAutoNegoAbility_set,
    .port_phyForceModeAbility_get               = dal_rtl9601b_port_phyForceModeAbility_get,
    .port_phyForceModeAbility_set               = dal_rtl9601b_port_phyForceModeAbility_set,
    .port_phyMasterSlave_get                    = dal_rtl9601b_port_phyMasterSlave_get,
    .port_phyMasterSlave_set                    = dal_rtl9601b_port_phyMasterSlave_set,
    .port_phyTestMode_get                       = dal_rtl9601b_port_phyTestMode_get,
    .port_phyTestMode_set                       = dal_rtl9601b_port_phyTestMode_set,
    .port_phyReg_get                            = dal_rtl9601b_port_phyReg_get,
    .port_phyReg_set                            = dal_rtl9601b_port_phyReg_set,
    .port_cpuPortId_get                         = dal_rtl9601b_port_cpuPortId_get,
    .port_isolation_get                         = NULL,
    .port_isolation_set                         = NULL,
    .port_isolationExt_get                      = NULL,
    .port_isolationExt_set                      = NULL,
    .port_isolationL34_get                      = NULL,
    .port_isolationL34_set                      = NULL,
    .port_isolationExtL34_get                   = NULL,
    .port_isolationExtL34_set                   = NULL,
    .port_isolationEntry_get                    = NULL,
    .port_isolationEntry_set                    = NULL,
    .port_isolationEntryExt_get                 = NULL,
    .port_isolationEntryExt_set                 = NULL,
    .port_isolationCtagPktConfig_get            = NULL,
    .port_isolationCtagPktConfig_set            = NULL,
    .port_isolationL34PktConfig_get             = NULL,
    .port_isolationL34PktConfig_set             = NULL,
    .port_isolationIpmcLeaky_get                = NULL,
    .port_isolationIpmcLeaky_set                = NULL,
    .port_isolationPortLeaky_get                = NULL,
    .port_isolationPortLeaky_set                = NULL,
    .port_isolationLeaky_get                    = NULL,
    .port_isolationLeaky_set                    = NULL,
    .port_macRemoteLoopbackEnable_get           = dal_rtl9601b_port_macRemoteLoopbackEnable_get,
    .port_macRemoteLoopbackEnable_set           = dal_rtl9601b_port_macRemoteLoopbackEnable_set,
    .port_macLocalLoopbackEnable_get            = dal_rtl9601b_port_macLocalLoopbackEnable_get,
    .port_macLocalLoopbackEnable_set            = dal_rtl9601b_port_macLocalLoopbackEnable_set,
    .port_adminEnable_get                       = dal_rtl9601b_port_adminEnable_get,
    .port_adminEnable_set                       = dal_rtl9601b_port_adminEnable_set,
    .port_specialCongest_get                    = dal_rtl9601b_port_specialCongest_get,
    .port_specialCongest_set                    = dal_rtl9601b_port_specialCongest_set,
    .port_specialCongestStatus_get              = dal_rtl9601b_port_specialCongestStatus_get,
    .port_specialCongestStatus_clear            = dal_rtl9601b_port_specialCongestStatus_clear,
    .port_greenEnable_get                       = dal_rtl9601b_port_greenEnable_get,
    .port_greenEnable_set                       = dal_rtl9601b_port_greenEnable_set,
    .port_phyCrossOverMode_get                  = dal_rtl9601b_port_phyCrossOverMode_get,
    .port_phyCrossOverMode_set                  = dal_rtl9601b_port_phyCrossOverMode_set,
    .port_enhancedFid_get                       = NULL,
    .port_enhancedFid_set                       = NULL,
    .port_rtctResult_get                        = dal_rtl9601b_port_rtctResult_get,
    .port_rtct_start                            = dal_rtl9601b_port_rtct_start,
    .port_macForceAbility_set                   = dal_rtl9601b_port_macForceAbility_set,
    .port_macForceAbility_get                   = dal_rtl9601b_port_macForceAbility_get,
    .port_macForceAbilityState_set              = dal_rtl9601b_port_macForceAbilityState_set,
    .port_macForceAbilityState_get              = dal_rtl9601b_port_macForceAbilityState_get,
    .port_macExtMode_set                        = NULL,
    .port_macExtMode_get                        = NULL,
    .port_macExtRgmiiDelay_set                  = NULL,
    .port_macExtRgmiiDelay_get                  = NULL,
    .port_gigaLiteEnable_set                    = dal_rtl9601b_port_gigaLiteEnable_set,
    .port_gigaLiteEnable_get                    = dal_rtl9601b_port_gigaLiteEnable_get,


    /* Trap */
    .trap_init                                  = dal_rtl9601b_trap_init,
    .trap_reasonTrapToCpuPriority_get           = dal_rtl9601b_trap_reasonTrapToCpuPriority_get,
    .trap_reasonTrapToCpuPriority_set           = dal_rtl9601b_trap_reasonTrapToCpuPriority_set,
    .trap_igmpCtrlPkt2CpuEnable_get             = dal_rtl9601b_trap_igmpCtrlPkt2CpuEnable_get,
    .trap_igmpCtrlPkt2CpuEnable_set             = dal_rtl9601b_trap_igmpCtrlPkt2CpuEnable_set,
    .trap_mldCtrlPkt2CpuEnable_get              = dal_rtl9601b_trap_mldCtrlPkt2CpuEnable_get,
    .trap_mldCtrlPkt2CpuEnable_set              = dal_rtl9601b_trap_mldCtrlPkt2CpuEnable_set,
    .trap_portIgmpMldCtrlPktAction_get          = dal_rtl9601b_trap_portIgmpMldCtrlPktAction_get,
    .trap_portIgmpMldCtrlPktAction_set          = dal_rtl9601b_trap_portIgmpMldCtrlPktAction_set,
    .trap_l2McastPkt2CpuEnable_get              = dal_rtl9601b_trap_l2McastPkt2CpuEnable_get,
    .trap_l2McastPkt2CpuEnable_set              = dal_rtl9601b_trap_l2McastPkt2CpuEnable_set,
    .trap_ipMcastPkt2CpuEnable_get              = dal_rtl9601b_trap_ipMcastPkt2CpuEnable_get,
    .trap_ipMcastPkt2CpuEnable_set              = dal_rtl9601b_trap_ipMcastPkt2CpuEnable_set,
    .trap_rmaAction_get                         = dal_rtl9601b_trap_rmaAction_get,
    .trap_rmaAction_set                         = dal_rtl9601b_trap_rmaAction_set,
    .trap_rmaPri_get                            = dal_rtl9601b_trap_rmaPri_get,
    .trap_rmaPri_set                            = dal_rtl9601b_trap_rmaPri_set,
    .trap_oamPduAction_get                      = dal_rtl9601b_trap_oamPduAction_get,
    .trap_oamPduAction_set                      = dal_rtl9601b_trap_oamPduAction_set,
    .trap_oamPduPri_get                         = dal_rtl9601b_trap_oamPduPri_get,
    .trap_oamPduPri_set                         = dal_rtl9601b_trap_oamPduPri_set,
    .trap_uniTrapPriorityEnable_set             = NULL,
    .trap_uniTrapPriorityEnable_get             = NULL,
    .trap_uniTrapPriorityPriority_set           = NULL,
    .trap_uniTrapPriorityPriority_get           = NULL,


     /* L2 */
    .l2_init                                    = dal_rtl9601b_l2_init,
    .l2_flushLinkDownPortAddrEnable_get         = dal_rtl9601b_l2_flushLinkDownPortAddrEnable_get,
    .l2_flushLinkDownPortAddrEnable_set         = dal_rtl9601b_l2_flushLinkDownPortAddrEnable_set,
    .l2_ucastAddr_flush                         = dal_rtl9601b_l2_ucastAddr_flush,
    .l2_table_clear                             = dal_rtl9601b_l2_table_clear,
    .l2_limitLearningOverStatus_get             = NULL,
    .l2_limitLearningOverStatus_clear           = NULL,
    .l2_learningCnt_get                         = NULL,
    .l2_limitLearningCnt_get                    = NULL,
    .l2_limitLearningCnt_set                    = NULL,
    .l2_limitLearningCntAction_get              = NULL,
    .l2_limitLearningCntAction_set              = NULL,
    .l2_limitLearningEntryAction_get            = NULL,
    .l2_limitLearningEntryAction_set            = NULL,
    .l2_limitLearningPortMask_get               = NULL,
    .l2_limitLearningPortMask_set               = NULL,
    .l2_portLimitLearningOverStatus_get         = dal_rtl9601b_l2_portLimitLearningOverStatus_get,
    .l2_portLimitLearningOverStatus_clear       = dal_rtl9601b_l2_portLimitLearningOverStatus_clear,
    .l2_portLearningCnt_get                     = dal_rtl9601b_l2_portLearningCnt_get,
    .l2_portLimitLearningCnt_get                = dal_rtl9601b_l2_portLimitLearningCnt_get,
    .l2_portLimitLearningCnt_set                = dal_rtl9601b_l2_portLimitLearningCnt_set,
    .l2_portLimitLearningCntAction_get          = dal_rtl9601b_l2_portLimitLearningCntAction_get,
    .l2_portLimitLearningCntAction_set          = dal_rtl9601b_l2_portLimitLearningCntAction_set,
    .l2_aging_get                               = dal_rtl9601b_l2_aging_get,
    .l2_aging_set                               = dal_rtl9601b_l2_aging_set,
    .l2_portAgingEnable_get                     = dal_rtl9601b_l2_portAgingEnable_get,
    .l2_portAgingEnable_set                     = dal_rtl9601b_l2_portAgingEnable_set,
    .l2_lookupMissAction_get                    = dal_rtl9601b_l2_lookupMissAction_get,
    .l2_lookupMissAction_set                    = dal_rtl9601b_l2_lookupMissAction_set,
    .l2_portLookupMissAction_get                = dal_rtl9601b_l2_portLookupMissAction_get,
    .l2_portLookupMissAction_set                = dal_rtl9601b_l2_portLookupMissAction_set,
    .l2_lookupMissFloodPortMask_get             = dal_rtl9601b_l2_lookupMissFloodPortMask_get,
    .l2_lookupMissFloodPortMask_set             = dal_rtl9601b_l2_lookupMissFloodPortMask_set,
    .l2_lookupMissFloodPortMask_add             = dal_rtl9601b_l2_lookupMissFloodPortMask_add,
    .l2_lookupMissFloodPortMask_del             = dal_rtl9601b_l2_lookupMissFloodPortMask_del,
    .l2_newMacOp_get                            = dal_rtl9601b_l2_newMacOp_get,
    .l2_newMacOp_set                            = dal_rtl9601b_l2_newMacOp_set,
    .l2_nextValidAddr_get                       = dal_rtl9601b_l2_nextValidAddr_get,
    .l2_nextValidAddrOnPort_get                 = dal_rtl9601b_l2_nextValidAddrOnPort_get,
    .l2_nextValidMcastAddr_get                  = dal_rtl9601b_l2_nextValidMcastAddr_get,
    .l2_nextValidIpMcastAddr_get                = dal_rtl9601b_l2_nextValidIpMcastAddr_get,
    .l2_nextValidEntry_get                      = dal_rtl9601b_l2_nextValidEntry_get,
    .l2_addr_add                                = dal_rtl9601b_l2_addr_add,
    .l2_addr_del                                = dal_rtl9601b_l2_addr_del,
    .l2_addr_get                                = dal_rtl9601b_l2_addr_get,
    .l2_addr_delAll                             = dal_rtl9601b_l2_addr_delAll,
    .l2_mcastAddr_add                           = dal_rtl9601b_l2_mcastAddr_add,
    .l2_mcastAddr_del                           = dal_rtl9601b_l2_mcastAddr_del,
    .l2_mcastAddr_get                           = dal_rtl9601b_l2_mcastAddr_get,
    .l2_illegalPortMoveAction_get               = NULL,
    .l2_illegalPortMoveAction_set               = NULL,
    .l2_ipmcMode_get                            = dal_rtl9601b_l2_ipmcMode_get,
    .l2_ipmcMode_set                            = dal_rtl9601b_l2_ipmcMode_set,
    .l2_ipv6mcMode_get                          = NULL,
    .l2_ipv6mcMode_set                          = NULL,
    .l2_ipmcGroupLookupMissHash_get             = NULL,
    .l2_ipmcGroupLookupMissHash_set             = NULL,
    .l2_ipmcGroup_add                           = NULL,
    .l2_ipmcGroupExtPortmask_add                = NULL,
    .l2_ipmcGroup_del                           = NULL,
    .l2_ipmcGroup_get                           = NULL,
    .l2_ipmcGroupExtPortmask_get                = NULL,
    .l2_portIpmcAction_get                      = dal_rtl9601b_l2_portIpmcAction_get,
    .l2_portIpmcAction_set                      = dal_rtl9601b_l2_portIpmcAction_set,
    .l2_ipMcastAddr_add                         = dal_rtl9601b_l2_ipMcastAddr_add,
    .l2_ipMcastAddr_del                         = dal_rtl9601b_l2_ipMcastAddr_del,
    .l2_ipMcastAddr_get                         = dal_rtl9601b_l2_ipMcastAddr_get,
    .l2_srcPortEgrFilterMask_get                = dal_rtl9601b_l2_srcPortEgrFilterMask_get,
    .l2_srcPortEgrFilterMask_set                = dal_rtl9601b_l2_srcPortEgrFilterMask_set,
    .l2_extPortEgrFilterMask_get                = NULL,
    .l2_extPortEgrFilterMask_set                = NULL,
	.l2_camState_set							= dal_rtl9601b_l2_camState_set,
	.l2_camState_get							= dal_rtl9601b_l2_camState_get,
	.l2_vidUnmatchAction_get					= NULL,
	.l2_vidUnmatchAction_set					= NULL,

    /* GPON */
	.gpon_init = dal_rtl9601b_gpon_init,
	.gpon_resetState_set = dal_rtl9601b_gpon_resetState_set,
	.gpon_resetDoneState_get = dal_rtl9601b_gpon_resetDoneState_get,
	.gpon_version_get = dal_rtl9601b_gpon_version_get,
	.gpon_test_get = dal_rtl9601b_gpon_test_get,
	.gpon_test_set = dal_rtl9601b_gpon_test_set,
	.gpon_topIntrMask_get = dal_rtl9601b_gpon_topIntrMask_get,
	.gpon_topIntrMask_set = dal_rtl9601b_gpon_topIntrMask_set,
	.gpon_topIntr_get = dal_rtl9601b_gpon_topIntr_get,
	.gpon_topIntr_disableAll = dal_rtl9601b_gpon_topIntr_disableAll,
	.gpon_gtcDsIntr_get = dal_rtl9601b_gpon_gtcDsIntr_get,
	.gpon_gtcDsIntrDlt_get = dal_rtl9601b_gpon_gtcDsIntrDlt_get,
	.gpon_gtcDsIntrMask_get = dal_rtl9601b_gpon_gtcDsIntrMask_get,
	.gpon_gtcDsIntrMask_set = dal_rtl9601b_gpon_gtcDsIntrMask_set,
	.gpon_onuId_set = dal_rtl9601b_gpon_onuId_set,
	.gpon_onuId_get = dal_rtl9601b_gpon_onuId_get,
	.gpon_onuState_set = dal_rtl9601b_gpon_onuState_set,
	.gpon_onuState_get = dal_rtl9601b_gpon_onuState_get,
	.gpon_dsBwmapCrcCheckState_set = dal_rtl9601b_gpon_dsBwmapCrcCheckState_set,
	.gpon_dsBwmapCrcCheckState_get = dal_rtl9601b_gpon_dsBwmapCrcCheckState_get,
	.gpon_dsBwmapFilterOnuIdState_set = dal_rtl9601b_gpon_dsBwmapFilterOnuIdState_set,
	.gpon_dsBwmapFilterOnuIdState_get = dal_rtl9601b_gpon_dsBwmapFilterOnuIdState_get,
	.gpon_dsPlendStrictMode_set = dal_rtl9601b_gpon_dsPlendStrictMode_set,
	.gpon_dsPlendStrictMode_get = dal_rtl9601b_gpon_dsPlendStrictMode_get,
	.gpon_dsScrambleState_set = dal_rtl9601b_gpon_dsScrambleState_set,
	.gpon_dsScrambleState_get = dal_rtl9601b_gpon_dsScrambleState_get,
	.gpon_dsFecBypass_set = dal_rtl9601b_gpon_dsFecBypass_set,
	.gpon_dsFecBypass_get = dal_rtl9601b_gpon_dsFecBypass_get,
	.gpon_dsFecThrd_set = dal_rtl9601b_gpon_dsFecThrd_set,
	.gpon_dsFecThrd_get = dal_rtl9601b_gpon_dsFecThrd_get,
	.gpon_extraSnTxTimes_set = dal_rtl9601b_gpon_extraSnTxTimes_set,
	.gpon_extraSnTxTimes_get = dal_rtl9601b_gpon_extraSnTxTimes_get,
	.gpon_dsPloamNomsg_set = dal_rtl9601b_gpon_dsPloamNomsg_set,
	.gpon_dsPloamNomsg_get = dal_rtl9601b_gpon_dsPloamNomsg_get,
	.gpon_dsPloamOnuIdFilterState_set = dal_rtl9601b_gpon_dsPloamOnuIdFilterState_set,
	.gpon_dsPloamOnuIdFilterState_get = dal_rtl9601b_gpon_dsPloamOnuIdFilterState_get,
	.gpon_dsPloamBcAcceptState_set = dal_rtl9601b_gpon_dsPloamBcAcceptState_set,
	.gpon_dsPloamBcAcceptState_get = dal_rtl9601b_gpon_dsPloamBcAcceptState_get,
	.gpon_dsPloamDropCrcState_set = dal_rtl9601b_gpon_dsPloamDropCrcState_set,
	.gpon_dsPloamDropCrcState_get = dal_rtl9601b_gpon_dsPloamDropCrcState_get,
	.gpon_cdrLosStatus_get = dal_rtl9601b_gpon_cdrLosStatus_get,
	.gpon_optLosStatus_get = dal_rtl9601b_gpon_optLosStatus_get,
	.gpon_losCfg_set = dal_rtl9601b_gpon_losCfg_set,
	.gpon_losCfg_get = dal_rtl9601b_gpon_losCfg_get,
	.gpon_dsPloam_get = dal_rtl9601b_gpon_dsPloam_get,
	.gpon_tcont_get = dal_rtl9601b_gpon_tcont_get,
	.gpon_tcont_set = dal_rtl9601b_gpon_tcont_set,
	.gpon_tcont_del = dal_rtl9601b_gpon_tcont_del,
	.gpon_dsGemPort_get = dal_rtl9601b_gpon_dsGemPort_get,
	.gpon_dsGemPort_set = dal_rtl9601b_gpon_dsGemPort_set,
	.gpon_dsGemPort_del = dal_rtl9601b_gpon_dsGemPort_del,
	.gpon_dsGemPortPktCnt_get = dal_rtl9601b_gpon_dsGemPortPktCnt_get,
	.gpon_dsGemPortByteCnt_get = dal_rtl9601b_gpon_dsGemPortByteCnt_get,
	.gpon_dsGtcMiscCnt_get = dal_rtl9601b_gpon_dsGtcMiscCnt_get,
	.gpon_dsOmciPti_set = dal_rtl9601b_gpon_dsOmciPti_set,
	.gpon_dsOmciPti_get = dal_rtl9601b_gpon_dsOmciPti_get,
	.gpon_dsEthPti_set = dal_rtl9601b_gpon_dsEthPti_set,
	.gpon_dsEthPti_get = dal_rtl9601b_gpon_dsEthPti_get,
	.gpon_aesKeySwitch_set = dal_rtl9601b_gpon_aesKeySwitch_set,
	.gpon_aesKeySwitch_get = dal_rtl9601b_gpon_aesKeySwitch_get,
	.gpon_aesKeyWord_set = dal_rtl9601b_gpon_aesKeyWord_set,
    .gpon_aesKeyWordActive_set = dal_rtl9601b_gpon_aesKeyWordActive_set,
	.gpon_irq_get = dal_rtl9601b_gpon_irq_get,
	.gpon_dsGemPortEthRxCnt_get = dal_rtl9601b_gpon_dsGemPortEthRxCnt_get,
	.gpon_dsGemPortEthFwdCnt_get = dal_rtl9601b_gpon_dsGemPortEthFwdCnt_get,
	.gpon_dsGemPortMiscCnt_get = dal_rtl9601b_gpon_dsGemPortMiscCnt_get,
	.gpon_dsGemPortFcsCheckState_get = dal_rtl9601b_gpon_dsGemPortFcsCheckState_get,
	.gpon_dsGemPortFcsCheckState_set = dal_rtl9601b_gpon_dsGemPortFcsCheckState_set,
	.gpon_dsGemPortBcPassState_set = dal_rtl9601b_gpon_dsGemPortBcPassState_set,
	.gpon_dsGemPortBcPassState_get = dal_rtl9601b_gpon_dsGemPortBcPassState_get,
	.gpon_dsGemPortNonMcPassState_set = dal_rtl9601b_gpon_dsGemPortNonMcPassState_set,
	.gpon_dsGemPortNonMcPassState_get = dal_rtl9601b_gpon_dsGemPortNonMcPassState_get,
	.gpon_dsGemPortMacFilterMode_set = dal_rtl9601b_gpon_dsGemPortMacFilterMode_set,
	.gpon_dsGemPortMacFilterMode_get = dal_rtl9601b_gpon_dsGemPortMacFilterMode_get,
	.gpon_dsGemPortMacForceMode_set = dal_rtl9601b_gpon_dsGemPortMacForceMode_set,
	.gpon_dsGemPortMacForceMode_get = dal_rtl9601b_gpon_dsGemPortMacForceMode_get,
	.gpon_dsGemPortMacEntry_set = dal_rtl9601b_gpon_dsGemPortMacEntry_set,
	.gpon_dsGemPortMacEntry_get = dal_rtl9601b_gpon_dsGemPortMacEntry_get,
	.gpon_dsGemPortMacEntry_del = dal_rtl9601b_gpon_dsGemPortMacEntry_del,
	.gpon_dsGemPortFrameTimeOut_set = dal_rtl9601b_gpon_dsGemPortFrameTimeOut_set,
	.gpon_dsGemPortFrameTimeOut_get = dal_rtl9601b_gpon_dsGemPortFrameTimeOut_get,
	.gpon_ipv4McAddrPtn_get = dal_rtl9601b_gpon_ipv4McAddrPtn_get,
	.gpon_ipv4McAddrPtn_set = dal_rtl9601b_gpon_ipv4McAddrPtn_set,
	.gpon_ipv6McAddrPtn_get = dal_rtl9601b_gpon_ipv6McAddrPtn_get,
	.gpon_ipv6McAddrPtn_set = dal_rtl9601b_gpon_ipv6McAddrPtn_set,
	.gpon_gtcUsIntr_get = dal_rtl9601b_gpon_gtcUsIntr_get,
	.gpon_gtcUsIntrDlt_get = dal_rtl9601b_gpon_gtcUsIntrDlt_get,
	.gpon_gtcUsIntrMask_get = dal_rtl9601b_gpon_gtcUsIntrMask_get,
	.gpon_gtcUsIntrMask_set = dal_rtl9601b_gpon_gtcUsIntrMask_set,
	.gpon_forceLaser_set = dal_rtl9601b_gpon_forceLaser_set,
	.gpon_forceLaser_get = dal_rtl9601b_gpon_forceLaser_get,
    .gpon_forcePRBS_set = dal_rtl9601b_gpon_forcePRBS_set,
    .gpon_forcePRBS_get = dal_rtl9601b_gpon_forcePRBS_get,
	.gpon_ploamState_set = dal_rtl9601b_gpon_ploamState_set,
	.gpon_ploamState_get = dal_rtl9601b_gpon_ploamState_get,
	.gpon_indNrmPloamState_set = dal_rtl9601b_gpon_indNrmPloamState_set,
	.gpon_indNrmPloamState_get = dal_rtl9601b_gpon_indNrmPloamState_get,
	.gpon_dbruState_set = dal_rtl9601b_gpon_dbruState_set,
	.gpon_dbruState_get = dal_rtl9601b_gpon_dbruState_get,
	.gpon_usScrambleState_set = dal_rtl9601b_gpon_usScrambleState_set,
	.gpon_usScrambleState_get = dal_rtl9601b_gpon_usScrambleState_get,
	.gpon_usBurstPolarity_set = dal_rtl9601b_gpon_usBurstPolarity_set,
	.gpon_usBurstPolarity_get = dal_rtl9601b_gpon_usBurstPolarity_get,
	.gpon_eqd_set = dal_rtl9601b_gpon_eqd_set,
	.gpon_laserTime_set = dal_rtl9601b_gpon_laserTime_set,
	.gpon_laserTime_get = dal_rtl9601b_gpon_laserTime_get,
	.gpon_burstOverhead_set = dal_rtl9601b_gpon_burstOverhead_set,
	.gpon_usPloam_set = dal_rtl9601b_gpon_usPloam_set,
	.gpon_usAutoPloam_set = dal_rtl9601b_gpon_usAutoPloam_set,
	.gpon_usPloamCrcGenState_set = dal_rtl9601b_gpon_usPloamCrcGenState_set,
	.gpon_usPloamCrcGenState_get = dal_rtl9601b_gpon_usPloamCrcGenState_get,
	.gpon_usPloamOnuIdFilterState_set = dal_rtl9601b_gpon_usPloamOnuIdFilterState_set,
	.gpon_usPloamOnuIdFilter_get = dal_rtl9601b_gpon_usPloamOnuIdFilter_get,
	.gpon_usPloamBuf_flush = dal_rtl9601b_gpon_usPloamBuf_flush,
	.gpon_usGtcMiscCnt_get = dal_rtl9601b_gpon_usGtcMiscCnt_get,
	.gpon_rdi_set = dal_rtl9601b_gpon_rdi_set,
	.gpon_rdi_get = dal_rtl9601b_gpon_rdi_get,
	.gpon_usSmalSstartProcState_set = dal_rtl9601b_gpon_usSmalSstartProcState_set,
	.gpon_usSmalSstartProcState_get = dal_rtl9601b_gpon_usSmalSstartProcState_get,
	.gpon_usSuppressLaserState_set = dal_rtl9601b_gpon_usSuppressLaserState_set,
	.gpon_usSuppressLaserState_get = dal_rtl9601b_gpon_usSuppressLaserState_get,
	.gpon_gemUsIntr_get = dal_rtl9601b_gpon_gemUsIntr_get,
	.gpon_gemUsIntrMask_get = dal_rtl9601b_gpon_gemUsIntrMask_get,
	.gpon_gemUsIntrMask_set = dal_rtl9601b_gpon_gemUsIntrMask_set,
	.gpon_gemUsForceIdleState_set = dal_rtl9601b_gpon_gemUsForceIdleState_set,
	.gpon_gemUsForceIdleState_get = dal_rtl9601b_gpon_gemUsForceIdleState_get,
	.gpon_gemUsPtiVector_set = dal_rtl9601b_gpon_gemUsPtiVector_set,
	.gpon_gemUsPtiVector_get = dal_rtl9601b_gpon_gemUsPtiVector_get,
	.gpon_gemUsEthCnt_get = dal_rtl9601b_gpon_gemUsEthCnt_get,
	.gpon_gemUsGemCnt_get = dal_rtl9601b_gpon_gemUsGemCnt_get,
	.gpon_gemUsPortCfg_set = dal_rtl9601b_gpon_gemUsPortCfg_set,
	.gpon_gemUsPortCfg_get = dal_rtl9601b_gpon_gemUsPortCfg_get,
	.gpon_gemUsDataByteCnt_get = dal_rtl9601b_gpon_gemUsDataByteCnt_get,
	.gpon_gemUsIdleByteCnt_get = dal_rtl9601b_gpon_gemUsIdleByteCnt_get,
	.gpon_dbruPeriod_get = dal_rtl9601b_gpon_dbruPeriod_get,
	.gpon_dbruPeriod_set = dal_rtl9601b_gpon_dbruPeriod_set,
	.gpon_gtcDsIntrDlt_check = dal_rtl9601b_gpon_gtcDsIntrDlt_check,
	.gpon_gtcUsIntrDlt_check = dal_rtl9601b_gpon_gtcUsIntrDlt_check,
	.gpon_gemUsIntrDlt_check = dal_rtl9601b_gpon_gemUsIntrDlt_check,
	.gpon_rogueOnt_set = dal_rtl9601b_gpon_rogueOnt_set,
	.gpon_drainOutDefaultQueue_set = dal_rtl9601b_gpon_drainOutDefaultQueue_set,
	.gpon_autoDisTx_set = dal_rtl9601b_gpon_autoDisTx_set,
	.gpon_scheInfo_get = dal_rtl9601b_gpon_scheInfo_get,
    .gpon_dataPath_reset = dal_rtl9601b_gpon_dataPath_reset,
    .gpon_dsOmciCnt_get = dal_rtl9601b_gpon_dsOmciCnt_get,
    .gpon_usOmciCnt_get = dal_rtl9601b_gpon_usOmciCnt_get,
    .gpon_gtcDsTodSuperFrame_set = NULL,
    .gpon_gtcDsTodSuperFrame_get = NULL,
    .gpon_dbruBlockSize_get = dal_rtl9601b_gpon_dbruBlockSize_get,
    .gpon_dbruBlockSize_set = dal_rtl9601b_gpon_dbruBlockSize_set,
    .gpon_flowctrl_adjust_byFlowNum = dal_rtl9601b_gpon_flowctrl_adjust_byFlowNum,

     /*interrupt*/
    .intr_init = dal_rtl9601b_intr_init,
    .intr_polarity_set = dal_rtl9601b_intr_polarity_set,
    .intr_polarity_get = dal_rtl9601b_intr_polarity_get,
    .intr_imr_set = dal_rtl9601b_intr_imr_set,
    .intr_imr_get = dal_rtl9601b_intr_imr_get,
    .intr_ims_get = dal_rtl9601b_intr_ims_get,
    .intr_ims_clear = dal_rtl9601b_intr_ims_clear,
    .intr_speedChangeStatus_get = dal_rtl9601b_intr_speedChangeStatus_get,
    .intr_speedChangeStatus_clear = dal_rtl9601b_intr_speedChangeStatus_clear,
    .intr_linkupStatus_get = dal_rtl9601b_intr_linkupStatus_get,
    .intr_linkupStatus_clear = dal_rtl9601b_intr_linkupStatus_clear,
    .intr_linkdownStatus_get = dal_rtl9601b_intr_linkdownStatus_get,
    .intr_linkdownStatus_clear = dal_rtl9601b_intr_linkdownStatus_clear,
    .intr_gphyStatus_get = dal_rtl9601b_intr_gphyStatus_get,
    .intr_gphyStatus_clear = dal_rtl9601b_intr_gphyStatus_clear,
    .intr_imr_restore = dal_rtl9601b_intr_imr_restore,

    /* RLDP and RLPP */
    .rldp_init = NULL,
    .rldp_config_set = NULL,
    .rldp_config_get = NULL,
    .rldp_portConfig_set = NULL,
    .rldp_portConfig_get = NULL,
    .rldp_status_get = NULL,
    .rldp_portStatus_get = NULL,
    .rldp_portStatus_clear = NULL,
    .rlpp_init = NULL,
    .rlpp_trapType_set = NULL,
    .rlpp_trapType_get = NULL,


    /*cpu*/
    .cpu_init = dal_rtl9601b_cpu_init,
    .cpu_awarePortMask_set = dal_rtl9601b_cpu_awarePortMask_set,
    .cpu_awarePortMask_get = dal_rtl9601b_cpu_awarePortMask_get,
    .cpu_tagFormat_set = NULL,
    .cpu_tagFormat_get = NULL,
    .cpu_trapInsertTag_set = dal_rtl9601b_cpu_trapInsertTag_set,
    .cpu_trapInsertTag_get = dal_rtl9601b_cpu_trapInsertTag_get,
    .cpu_tagAware_set = NULL,
    .cpu_tagAware_get = NULL,


    /*led*/
    .led_init               = dal_rtl9601b_led_init,
    .led_operation_get      = dal_rtl9601b_led_operation_get,
    .led_operation_set      = dal_rtl9601b_led_operation_set,
    .led_serialMode_get     = NULL,
    .led_serialMode_set     = NULL,
    .led_blinkRate_get      = dal_rtl9601b_led_blinkRate_get,
    .led_blinkRate_set      = dal_rtl9601b_led_blinkRate_set,
    .led_config_get         = dal_rtl9601b_led_config_get,
    .led_config_set         = dal_rtl9601b_led_config_set,
    .led_modeForce_get      = dal_rtl9601b_led_modeForce_get,
    .led_modeForce_set      = dal_rtl9601b_led_modeForce_set,
    .led_parallelEnable_get = dal_rtl9601b_led_parallelEnable_get,
    .led_parallelEnable_set = dal_rtl9601b_led_parallelEnable_set,

    /*dot1x*/
    .dot1x_init = NULL,
    .dot1x_unauthPacketOper_get = NULL,
    .dot1x_unauthPacketOper_set = NULL,
    .dot1x_portBasedEnable_get = NULL,
    .dot1x_portBasedEnable_set = NULL,
    .dot1x_portBasedAuthStatus_get = NULL,
    .dot1x_portBasedAuthStatus_set = NULL,
    .dot1x_portBasedDirection_get = NULL,
    .dot1x_portBasedDirection_set = NULL,
    .dot1x_macBasedEnable_get = NULL,
    .dot1x_macBasedEnable_set = NULL,
    .dot1x_macBasedDirection_get = NULL,
    .dot1x_macBasedDirection_set = NULL,
    .dot1x_guestVlan_get = NULL,
    .dot1x_guestVlan_set = NULL,
    .dot1x_guestVlanBehavior_get = NULL,
    .dot1x_guestVlanBehavior_set = NULL,
    .dot1x_trapPri_get = NULL,
    .dot1x_trapPri_set = NULL,

    /* L34 Function */
    .l34_init = NULL,
	.l34_netifTable_set = NULL,
	.l34_netifTable_get = NULL,
	.l34_arpTable_set = NULL,
	.l34_arpTable_get = NULL,
	.l34_arpTable_del = NULL,
	.l34_pppoeTable_set = NULL,
	.l34_pppoeTable_get = NULL,
	.l34_routingTable_set = NULL,
	.l34_routingTable_get = NULL,
	.l34_routingTable_del = NULL,
	.l34_nexthopTable_set = NULL,
	.l34_nexthopTable_get = NULL,
	.l34_extIntIPTable_set = NULL,
	.l34_extIntIPTable_get = NULL,
	.l34_extIntIPTable_del = NULL,
	.l34_naptInboundTable_set = NULL,
	.l34_naptInboundTable_get = NULL,
	.l34_naptOutboundTable_set = NULL,
	.l34_naptOutboundTable_get = NULL,
	.l34_ipmcTransTable_set = NULL,
	.l34_ipmcTransTable_get = NULL,
	.l34_table_reset = NULL,
	.l34_bindingTable_set = NULL,
	.l34_bindingTable_get = NULL,
	.l34_bindingAction_set = NULL,
	.l34_bindingAction_get = NULL,
	.l34_wanTypeTable_set = NULL,
	.l34_wanTypeTable_get = NULL,
	.l34_ipv6RoutingTable_set = NULL,
	.l34_ipv6RoutingTable_get = NULL,
	.l34_ipv6NeighborTable_set = NULL,
	.l34_ipv6NeighborTable_get = NULL,
	.l34_hsabMode_set = NULL,
	.l34_hsabMode_get = NULL,
	.l34_hsaData_get = NULL,
	.l34_hsbData_get = NULL,
	.l34_portWanMap_set = NULL,
	.l34_portWanMap_get = NULL,
	.l34_globalState_set = NULL,
	.l34_globalState_get = NULL,
	.l34_lookupMode_set = NULL,
	.l34_lookupMode_get = NULL,
	.l34_lookupPortMap_set = NULL,
	.l34_lookupPortMap_get = NULL,
	.l34_wanRoutMode_set = NULL,
	.l34_wanRoutMode_get = NULL,
	.l34_arpTrfIndicator_get = NULL,
	.l34_naptTrfIndicator_get = NULL,
	.l34_pppTrfIndicator_get = NULL,
	.l34_neighTrfIndicator_get = NULL,
	.l34_hsdState_set = NULL,
	.l34_hsdState_get = NULL,
	.l34_hwL4TrfWrkTbl_set = NULL,
	.l34_hwL4TrfWrkTbl_get = NULL,
	.l34_l4TrfTb_get = NULL,
	.l34_hwL4TrfWrkTbl_Clear = NULL,
	.l34_hwArpTrfWrkTbl_set = NULL,
	.l34_hwArpTrfWrkTbl_get = NULL,
	.l34_arpTrfTb_get = NULL,
	.l34_hwArpTrfWrkTbl_Clear = NULL,
	.l34_naptTrfIndicator_get_all = NULL,
	.l34_arpTrfIndicator_get_all = NULL,
	.l34_dsliteInfTable_set = NULL,
	.l34_dsliteInfTable_get = NULL,
	.l34_dsliteMcTable_set = NULL,
	.l34_dsliteMcTable_get = NULL,
    .l34_dsliteControl_set = NULL,
    .l34_dsliteControl_get = NULL,

    /*gpio function*/
    .gpio_init = dal_rtl9601b_gpio_init,
    .gpio_state_set = dal_rtl9601b_gpio_state_set,
    .gpio_state_get = dal_rtl9601b_gpio_state_get,
    .gpio_mode_set = dal_rtl9601b_gpio_mode_set,
    .gpio_mode_get = dal_rtl9601b_gpio_mode_get,
    .gpio_databit_get = dal_rtl9601b_gpio_databit_get,
    .gpio_databit_set = dal_rtl9601b_gpio_databit_set,
    .gpio_intr_get = dal_rtl9601b_gpio_intr_get,
    .gpio_intr_set = dal_rtl9601b_gpio_intr_set,
    .gpio_intrStatus_get = dal_rtl9601b_gpio_intrStatus_get,
    .gpio_intrStatus_clean = dal_rtl9601b_gpio_intrStatus_clean,

    /* I2C */
    .i2c_init = dal_rtl9601b_i2c_init,
    .i2c_enable_set = dal_rtl9601b_i2c_enable_set,
    .i2c_enable_get = dal_rtl9601b_i2c_enable_get,
    .i2c_width_set = dal_rtl9601b_i2c_width_set,
    .i2c_width_get = dal_rtl9601b_i2c_width_get,
    .i2c_write = dal_rtl9601b_i2c_write,
    .i2c_read = dal_rtl9601b_i2c_read,
    .i2c_clock_set = dal_rtl9601b_i2c_clock_set,
    .i2c_clock_get = dal_rtl9601b_i2c_clock_get,
    .i2c_eepMirror_set = dal_rtl9601b_i2c_eepMirror_set,
    .i2c_eepMirror_get = dal_rtl9601b_i2c_eepMirror_get,
    .i2c_eepMirror_write = dal_rtl9601b_i2c_eepMirror_write,
    .i2c_eepMirror_read = dal_rtl9601b_i2c_eepMirror_read,
    .i2c_dataWidth_set = dal_rtl9601b_i2c_dataWidth_set,
    .i2c_dataWidth_get = dal_rtl9601b_i2c_dataWidth_get,
    .i2c_addrWidth_set = dal_rtl9601b_i2c_addrWidth_set,
    .i2c_addrWidth_get = dal_rtl9601b_i2c_addrWidth_get,


    /* PTP Function */
    .time_portTransparentEnable_set = NULL,
    .time_portTransparentEnable_get = NULL,
    .time_init = NULL,
    .time_portPtpEnable_get = NULL,
    .time_portPtpEnable_set = NULL,
    .time_curTime_latch = NULL,
    .time_curTime_get = NULL,
    .time_refTime_get = NULL,
    .time_refTime_set = NULL,
    .time_frequency_set = NULL,
    .time_frequency_get = NULL,
    .time_ptpIgrMsgAction_set = NULL,
    .time_ptpIgrMsgAction_get = NULL,
    .time_ptpEgrMsgAction_set = NULL,
    .time_ptpEgrMsgAction_get = NULL,
    .time_meanPathDelay_set = NULL,
    .time_meanPathDelay_get = NULL,
    .time_rxTime_set = NULL,
    .time_rxTime_get = NULL,
    .time_ponTodTime_set = NULL,
    .time_ponTodTime_get = NULL,
    .time_portPtpTxIndicator_get = NULL,
    .time_todEnable_get = NULL,
    .time_todEnable_set = NULL,
    .time_ppsEnable_get = NULL,
    .time_ppsEnable_set = NULL,
    .time_ppsMode_get = NULL,
    .time_ppsMode_set = NULL,


    /* EPON */
    .epon_init = dal_rtl9601b_epon_init,
    .epon_intrMask_get = dal_rtl9601b_epon_intrMask_get,
    .epon_intrMask_set = dal_rtl9601b_epon_intrMask_set,
    .epon_intr_get = dal_rtl9601b_epon_intr_get,
    .epon_intr_disableAll = dal_rtl9601b_epon_intr_disableAll,
    .epon_llid_entry_set = dal_rtl9601b_epon_llid_entry_set,
    .epon_llid_entry_get = dal_rtl9601b_epon_llid_entry_get,
    .epon_forceLaserState_set = dal_rtl9601b_epon_forceLaserState_set,
    .epon_forceLaserState_get = dal_rtl9601b_epon_forceLaserState_get,
    .epon_laserTime_set = dal_rtl9601b_epon_laserTime_set,
    .epon_laserTime_get = dal_rtl9601b_epon_laserTime_get,
    .epon_syncTime_get = dal_rtl9601b_epon_syncTime_get,
    .epon_registerReq_get = dal_rtl9601b_epon_registerReq_get,
    .epon_registerReq_set = dal_rtl9601b_epon_registerReq_set,
    .epon_churningKey_set = dal_rtl9601b_epon_churningKey_set,
    .epon_churningKey_get = dal_rtl9601b_epon_churningKey_get,
    .epon_usFecState_get = dal_rtl9601b_epon_usFecState_get,
    .epon_usFecState_set = dal_rtl9601b_epon_usFecState_set,
    .epon_dsFecState_get = dal_rtl9601b_epon_dsFecState_get,
    .epon_dsFecState_set = dal_rtl9601b_epon_dsFecState_set,
    .epon_mibCounter_get = dal_rtl9601b_epon_mibCounter_get,
    .epon_mibGlobal_reset = dal_rtl9601b_epon_mibGlobal_reset,
    .epon_mibLlidIdx_reset = dal_rtl9601b_epon_mibLlidIdx_reset,
    .epon_losState_get = dal_rtl9601b_epon_losState_get,
    .epon_mpcpTimeoutVal_get = dal_rtl9601b_epon_mpcpTimeoutVal_get,
    .epon_mpcpTimeoutVal_set = dal_rtl9601b_epon_mpcpTimeoutVal_set,
    .epon_opticalPolarity_set = dal_9601b_epon_opticalPolarity_set,
    .epon_opticalPolarity_get = dal_9601b_epon_opticalPolarity_get,
    .epon_fecState_get = NULL,
    .epon_fecState_set = NULL,
    .epon_llidEntryNum_get = dal_rtl9601b_epon_llidEntryNum_get,
    .epon_thresholdReport_set = dal_rtl9601b_epon_thresholdReport_set,
    .epon_thresholdReport_get = dal_rtl9601b_epon_thresholdReport_get,
    .epon_dbgInfo_get = dal_rtl9601b_epon_dbgInfo_get,

};

/*
 * Macro Declaration
 */

/*
 * Function Declaration
 */


/* Module Name    :  */

/* Function Name:
 *      dal_rtl9601b_init
 * Description:
 *      Initilize DAL of smart switch
 * Input:
 *      None
 * Output:
 *      None
 * Return:
 *      RT_ERR_OK     - initialize success
 *      RT_ERR_FAILED - initialize fail
 * Note:
 *      RTK must call this function before do other kind of action.
 */
int32 dal_rtl9601b_init(void)
{
    return RT_ERR_OK;
} /* end of dal_rtl9601b_init */

/* Function Name:
 *      dal_rtl9601b_mapper_get
 * Description:
 *      Get DAL mapper function
 * Input:
 *      None
 * Output:
 *      None
 * Return:
 *      dal_mapper_t *     - mapper pointer
 * Note:
 */
dal_mapper_t *dal_rtl9601b_mapper_get(void)
{
    
    return &dal_rtl9601b_mapper;
} /* end of dal_rtl9601b_mapper_get */

