#ifndef WEB_LANGUAGE_DEFS_H
#define WEB_LANGUAGE_DEFS_H
#include "LINUX/options.h"
#ifdef EMBED
#include <linux/config.h>
#else
#include "../../../include/linux/autoconf.h"
#endif

//#define Tfast_config	"Fast Configure"
//#define Tfc_intro     "the fast configuration will help you finish the configuration step by step."
//#define Tattention    "attention:"
//#define Tatt_intro    "original configuration will be replaced by the fast configuration."
//#define Tint_conn_conf  "Internet Connection Configure -- ATM PVC config"
//#define Tint_conn_intro "please set VPI and VCI. Do not modify it, unless ISP need modify it."
//#define Tnext_step    "next step >"
//#define Tint_conn_type  "Internet Connection Configure -- connection type"
//#define Tconn_type_intro    "please select WAN connection type provided by ISP."
//#define Tconn_type    "WAN connection type:"
//#define Tencap_type   "encapsulation:"
//#define Tenter_vpi	"please Enter VPI (0~255)"
//#define Tinvalid_vpi	"invalid VPI!"
//#define Tenter_vci	"please enter VCI (0~65535)"
//#define Tinvalid_vci	"invalid VCI!"
//#define Tget_chain_err	"Get chain record error!\n"
//#define Tconn_exist	"Connection already exists, delete existed connection?"
//#define Tvc_exceed	"Error: Maximum number of VC exceeds !"
//#define Tadd_err		"Error! Add chain record."
//#define Tsecond_ip_err		"Set second IP-address error!"
//#define Tsecond_mask_err	"Set second subnet-mask error!"
//#define Tdhcp_err			"Set dhcp mode MIB error!"
//#define Tget_ip_err		"Get IP-address error!"
//#define Tget_mask_err	"Get Subnet Mask error!"
//#define Tdhcp_range_err	"Invalid DHCP client range!"
//#define Tset_start_ip_err		"Set DHCP client start range error!"
//#define Tset_end_ip_err		"Set DHCP client end range error!"
//#define Tset_lease_err		"Set DHCP lease time error!"
//#define Tset_ip_err		"Set IP-address error!"
//#define Tset_mask_err	"Set net mask error!"
#define Tinvalid_ip		multilang(LANG_TINVALID_IP)//"Invalid IP-address value!"
//#define Tinvalid_mask	"Invalid subnet-mask value!"
//#define Tinvalid_ip2		"Invalid second IP-address value!"
//#define Tinvalid_mask2	"Invalid second subnet-mask value!"
//#define Tip2vsip		"first Lan and second Lan must belong to different subNet!"
#define Tinvalid_start_ip	multilang(LANG_TINVALID_START_IP)//"Invalid DHCP start IP-address value!"
#define Tinvalid_end_ip	multilang(LANG_TINVALID_END_IP)//"Invalid DHCP end IP-address value!"
//#define Tinvalid_dhcp_ip	"DHCP address range error!"
//#define Tuser_long		"Error! User Name length too long."
//#define Tpassw_long	"Error! Password length too long."
//#define Tinvalid_ppp_type	"Invalid PPP type value!"
//#define Tconn_forever	", connect forever"
//#define Tconn_on_dem	", connect on demand, idle for %d minute"
//#define Tconn_manual	", connect manually"
//#define Tdd_hh_mm		"%dday %dhour %dmin"
//#define Tdhcp_ip_range	"DHCP IP Range"
//#define Tdhcp_lease_t	"DHCP Lease Time"
//#define Tnapt			"NAPT"
//#define Twan_ip		"WAN IP"
//#define Tres_gw		"Reserved Gateway"
//#define Tauto_assign	"auto assigned"
//#define Tno_wan_ip		"none"
//#define Tdnss			"DNS Server"
#define Tbytes			multilang(LANG_TBYTES)//"data bytes"
#define Tping_recv		multilang(LANG_TPING_RECV)//"%d bytes from %s: icmp_seq=%u"
#define Tping_stat		multilang(LANG_TPING_STAT)//"--- ping statistics ---"
#define Ttrans_pkt		multilang(LANG_TTRANS_PKT)//"%ld packets transmitted, "
#define Trecv_pkt		multilang(LANG_TRECV_PKT)//"%ld packets received."
#define Tno_conn		multilang(LANG_TNO_CONN)//"Connection not exists!"
#define Trecv_cell_suc	multilang(LANG_TRECV_CELL_SUC)//"Loopback cell received successfully !"
#define Trecv_cell_fail	multilang(LANG_TRECV_CELL_FAIL)//"Loopback failed !"
#define Tadsl_diag_suc	multilang(LANG_TADSL_DIAG_SUC)//"ADSL Diagnostics successful !!"
#define Tadsl_diag_fail	multilang(LANG_TADSL_DIAG_FAIL)//"ADSL Diagnostics failed !!"
#define Tdownstream		multilang(LANG_TDOWNSTREAM)//"Downstream"
#define Tupstream		multilang(LANG_TUPSTREAM)//"Upstream"
//#define Tloop_annu		"Loop Attenuation"
//#define Tsig_annu		"Signal Attenuation"
//#define Thlin_scale		"Hlin Scale"
//#define Tsnr_marg		"SNR Margin"
//#define Tattain_rate		"Attainable Rate"
//#define Tout_power		"Output Power"
#define Ttone_num		multilang(LANG_TTONE_NUM)//"Tone Number"
#define Tlan_conn_chk	multilang(LANG_TLAN_CONN_CHK)//"LAN Connection Check"
#define Ttest_eth_conn	multilang(LANG_TTEST_ETH_CONN)//"Test Ethernet LAN Connection"
#define Ttest_adsl_syn	multilang(LANG_TTEST_ADSL_SYN)//"Test ADSL Synchronization"
#define Ttest_oam_f5_seg	multilang(LANG_TTEST_OAM_F5_SEG)//"Test ATM OAM F5 Segment Loopback"
#define Ttest_oam_f5_end 	multilang(LANG_TTEST_OAM_F5_END)//"Test ATM OAM F5 End-to-end Loopback"
#define Ttest_oam_f4_seg	multilang(LANG_TTEST_OAM_F4_SEG)//"Test ATM OAM F4 Segment Loopback"
#define Ttest_oam_f4_end	multilang(LANG_TTEST_OAM_F4_END)//"Test ATM OAM F4 End-to-end Loopback"
#define Tadsl_conn_chk	multilang(LANG_TADSL_CONN_CHK)//"ADSL Connection Check"
#define Tint_conn_chk 	multilang(LANG_TINT_CONN_CHK)//"Internet Connection Check"
#define Ttest_ppps_conn	multilang(LANG_TTEST_PPPS_CONN)//"Test PPP Server Connection"
#define Ttest_auth		multilang(LANG_TTEST_AUTH)//"Test Authentication with ISP"
#define Ttest_assigned_ip	multilang(LANG_TTEST_ASSIGNED_IP)//"Test the assigned IP Address"
#define Tping_pri_dnss	multilang(LANG_TPING_PRI_DNSS)//"Ping Primary Domain Name Server"
#define Tback			multilang(LANG_TBACK)//"  Back  "
#define Tping_def_gw	multilang(LANG_TPING_DEF_GW)//"Ping Default Gateway"
#define Tadsl_diag_wait	multilang(LANG_TADSL_DIAG_WAIT)//"The test result will come out 3 minutes later and the page will refresh itself automatically. Please wait ...\n"
//#define Tppp_conn_excd	"Maximum number of PPPoE connections exceeds in this vc!"
//#define Tdef_gw_exist	"Default route already exists !"
//#define Tinvalid_wan_dhcp	"Invalid WAN DHCP value!"
//#define Tinvalid_gw		"Invalid reserved gateway IP-address value!"
//#define Tinvalid_dns_mode	"Invalid DNS mode value!"
#define Tinvalid_dns	multilang(LANG_TINVALID_DNS)//"Invalid DNS address!"
//#define Treboot_wd0		"The System is Restarting ..."
//#define Treboot_wd1		"The DSL bridge has been configured and is rebooting."
//#define Treboot_wd2		"Close the Configuration window and wait"\
//			" for 2 minutes before reopening your web browser."\
//			" If necessary, reconfigure your PC's IP address to match"\
//			" your new configuration.";
//#define Ttime_zone1		"System Date has been modified successfully."
//#define Ttime_zone2		"Please reflesh your \"Status\" page."
//#define Tset_tz			"set time zone error!"
//#define Tset_date_err	"cannot set date"
//#define Tset_ntp_ena	"Set enabled flag error!"
//#define Tset_ntp_svr	"Set NTP server error!"
//#define Tset_ntp_ip		"Set NTP server IP error!"
#define Tbrg_not_exist	multilang(LANG_TBRG_NOT_EXIST)//"br0 interface not exists !!"
#define Tyes			multilang(LANG_TYES)//"yes"
#define Tno				multilang(LANG_TNO)//"no"
//#define Tport_err		"port size error!"
//#define Twan_port		"wan port set error!"
#define Tsvr_port		multilang(LANG_TSVR_PORT)//"server port set error!"
//#define Tvrtsrv_rule	"execute virtual server rules failed!\n"
#define Tdmz_error		multilang(LANG_TDMZ_ERROR)//"Invalid IP address! It should be set within the current subnet."

#define strWrongIP multilang(LANG_STRWRONGIP)//"Invalid IP-address value!"
#define strSetIPerror multilang(LANG_STRSETIPERROR)//"Set IP-address error!"
#define strWrongMask multilang(LANG_STRWRONGMASK)//"Invalid subnet-mask value!"
#define strSetMaskerror multilang(LANG_STRSETMASKERROR)//"Set subnet-mask error!"

#define strGetDhcpModeerror multilang(LANG_STRGETDHCPMODEERROR)//"Get DHCP MIB error!"
#define strGetIperror multilang(LANG_STRGETIPERROR)//"Get IP-address error!"
#define strGetMaskerror multilang(LANG_STRGETMASKERROR)//"Get Subnet Mask error!"
#define strInvalidRange multilang(LANG_STRINVALIDRANGE)//"Invalid DHCP client range!"
#define strSetStarIperror multilang(LANG_STRSETSTARIPERROR)//"Set DHCP client start range error!"
#define strSetEndIperror multilang(LANG_STRSETENDIPERROR)//"Set DHCP client end range error!"
#define strSetLeaseTimeerror multilang(LANG_STRSETLEASETIMEERROR)//"Set DHCP lease time error!"
#define strSetDomainNameerror multilang(LANG_STRSETDOMAINNAMEERROR)//"Set DHCP Domain Name error!"
#define strInvalidGatewayerror multilang(LANG_STRINVALIDGATEWAYERROR)//"Invalid DHCP Server Gateway Address value!"
#define strSetGatewayerror multilang(LANG_STRSETGATEWAYERROR)//"Set DHCP Server Gateway Address error!"
#define strSetDhcpModeerror multilang(LANG_STRSETDHCPMODEERROR)//"Set DHCP error!"

#if defined(IP_BASED_CLIENT_TYPE) || defined(_PRMT_X_TELEFONICA_ES_DHCPOPTION_)
#define strInvalidRangepc multilang(LANG_STRINVALIDRANGEPC)//"invalid pc IP pool range!"
#define strInvalidRangecmr multilang(LANG_STRINVALIDRANGECMR)//"invalid camera IP pool range!"
#define strInvalidRangestb multilang(LANG_STRINVALIDRANGESTB)//"invalid stb IP pool range!"
#define strInvalidRangephn multilang(LANG_STRINVALIDRANGEPHN)//"invalid phone IP pool range!"
#define strInvalidTypeRange multilang(LANG_STRINVALIDTYPERANGE)//"device address should be in the range of DHCP address pool!"
#define strOverlapRange multilang(LANG_STROVERLAPRANGE)//"device address should not be overlapped!"
//#define strInvalidNstbRange "address for every equipment that is not a STB: From .33 until .200"
//#define strInvalidStbRage "For STB, it can use addresses from .200 on !"
//#define strInvalidOpt60	"option 60 can not be NULL!"
#define strInvalidOpchaddr	multilang(LANG_STRINVALIDOPCHADDR)//"invalid opch address"
#define strInvalidOpchport	multilang(LANG_STRINVALIDOPCHPORT)//"invalid opch port"

#define strSetPcStartIperror multilang(LANG_STRSETPCSTARTIPERROR)//"set pc IP pool start address failed!"
#define strSetPcEndIperror multilang(LANG_STRSETPCENDIPERROR)//"set pc IP pool end address failed!"
#define strSetCmrStartIperror multilang(LANG_STRSETCMRSTARTIPERROR)//"set camera IP pool start address failed!"
#define strSetCmrEndIperror multilang(LANG_STRSETCMRENDIPERROR)//"set camera IP pool end address failed!"
#define strSetStbStartIperror multilang(LANG_STRSETSTBSTARTIPERROR)//"set stb IP pool start address failed!"
#define strSetStbEndIperror multilang(LANG_STRSETSTBENDIPERROR)//"set stb IP pool end address failed!"
#define strSetPhnStartIperror multilang(LANG_STRSETPHNSTARTIPERROR)//"set phone IP pool start address failed!"
#define strSetPhnEndIperror multilang(LANG_STRSETPHNENDIPERROR)//"set phone IP pool end address failed!"
#endif

#define strDelChainerror multilang(LANG_STRDELCHAINERROR)//"Delete chain record error!"
#define strModChainerror multilang(LANG_STRMODCHAINERROR)//"Modify chain record error!"

#define strInvalDhcpsAddress multilang(LANG_STRINVALDHCPSADDRESS)//"Invalid DHCPS address value!"
#define strSetDhcpserror multilang(LANG_STRSETDHCPSERROR)//"Set DHCPS MIB error!"

#define strStaticipexist multilang(LANG_STRSTATICIPEXIST)//"This static ip configuration already exists!"

#define strConnectExist multilang(LANG_STRCONNECTEXIST)//"Connection already exists!"
#define strMaxVc multilang(LANG_STRMAXVC)//"Error: Maximum number of VC exceeds !"
#define strAddChainerror multilang(LANG_STRADDCHAINERROR)//"Error! Add chain record."
#define strTableFull multilang(LANG_STRTABLEFULL)//"Error! Table Full."

#define strUserNametoolong multilang(LANG_STRUSERNAMETOOLONG)//"Error! User Name length too long."
#define strUserNameempty multilang(LANG_STRUSERNAMEEMPTY)//"Error! User Name cannot be empty."
#define strPasstoolong multilang(LANG_STRPASSTOOLONG)//"Error! Password length too long."
#define strPassempty multilang(LANG_STRPASSEMPTY)//"Error! Password cannot be empty."
#define strInvalPPPType multilang(LANG_STRINVALPPPTYPE)//"Invalid PPP type value!"
#define strDrouteExist  multilang(LANG_STRDROUTEEXIST)//"Default route already exists !"
#define strACName multilang(LANG_STRACNAME)//"Error! AC-Name length too long."
#define strServerName multilang(LANG_STRSERVERNAME)//"Error! Service-Name length too long."

#define strInvalDHCP multilang(LANG_STRINVALDHCP)//"Invalid WAN DHCP value!"
#define strInvalIP multilang(LANG_STRINVALIP)//"Invalid IP-address value!"
#define strIPAddresserror multilang(LANG_STRIPADDRESSERROR)//"Error! IP address cannot be empty."
#define strInvalGateway multilang(LANG_STRINVALGATEWAY)//"Invalid remote IP-address value!"
#define strGatewayIpempty multilang(LANG_STRGATEWAYIPEMPTY)//"Error! Remote IP address cannot be empty."
#define strInvalMask multilang(LANG_STRINVALMASK)//"Invalid subnet mask value!"
#define strMaskempty multilang(LANG_STRMASKEMPTY)//"Error! Subnet mask cannot be empty."
#define strMruErr	multilang(LANG_STRMRUERR)//"Invalid MTU!"

#define strMaxNumPPPoE multilang(LANG_STRMAXNUMPPPOE)//"Maximum number of PPPoE connections exceeds in this vc!"



#define strSelectvc multilang(LANG_STRSELECTVC)//"Please select one vc!"
#define strGetChainerror multilang(LANG_STRGETCHAINERROR)//"Get chain record error!\n"
//#define strInvalidQos "Invalid QoS!"
//#define strInvalidPCR "Invalid PCR!"
//#define strInvalidCDVT "Invalid CDVT!"
//#define strInvalidSCR "Invalid SCR!"
//#define strInvalidMBS "Invalid MBS!"

#define strSetcommunityROerror multilang(LANG_STRSETCOMMUNITYROERROR)//"Set snmpCommunityRO mib error!"
#define strSetcommunityRWerror multilang(LANG_STRSETCOMMUNITYRWERROR)//"Set snmpCommunityRW mib error!"
#define strInvalTrapIp multilang(LANG_STRINVALTRAPIP)//"Invalid Trap IP value!"
#define strSetTrapIperror multilang(LANG_STRSETTRAPIPERROR)//"Set snmpTrapIpAddr mib error!"


#define strGetToneerror multilang(LANG_STRGETTONEERROR)//"ERROR: Get ADSL Tone MIB error!"
#define  WARNING_EMPTY_OLD_PASSWORD  multilang(LANG_WARNING_EMPTY_OLD_PASSWORD)//"ERROR: Old Password cannot be empty."
#define  WARNING_EMPTY_NEW_PASSWORD  multilang(LANG_WARNING_EMPTY_NEW_PASSWORD)//"ERROR: New Password cannot be empty."
#define WARNING_EMPTY_CONFIRMED_PASSWORD  multilang(LANG_WARNING_EMPTY_CONFIRMED_PASSWORD)//"ERROR: Confirmed Password cannot be empty."
#define WARNING_UNMATCHED_PASSWORD  multilang(LANG_WARNING_UNMATCHED_PASSWORD)//"ERROR: New Password is not the same as Confirmed Password."
#define WARNING_GET_PASSWORD  multilang(LANG_WARNING_GET_PASSWORD)//"ERROR,Get password failed!"
#define WARNING_SET_PASSWORD  multilang(LANG_WARNING_SET_PASSWORD)//"ERROR: Modify password failed!"
#define WARNING_WRONG_PASSWORD  multilang(LANG_WARNING_WRONG_PASSWORD)//"ERROR: wrong password!"
#define WARNING_WRONG_USER  multilang(LANG_WARNING_WRONG_USER)//"ERROR: wrong username!"


//#define COMMIT_REBOOT_TITLE    "Commit and Reboot"
//#define COMMIT_REBOOT_INFO " This page is used to commit changes to system memory and reboot your system."
//#define COMMIT_REBOOT_BUTTON  "<input type=\"submit\" value=\"Commit and Reboot\" name=\"save\" onclick=\"return saveClick()\">"

//#define SYSTEM_LOG_TITLE "System Log"

//for wireless setting
#define   strDisbWlanErr				multilang(LANG_STRDISBWLANERR)//"Set disabled flag error!"
#define   strInvdTxPower			multilang(LANG_STRINVDTXPOWER)//"Invalid TxPower value!"
#define   strSetMIBTXPOWErr		multilang(LANG_STRSETMIBTXPOWERR)//"Set MIB_TX_POWER error!"
#define   strInvdMode				multilang(LANG_STRINVDMODE)//"Invalid mode value!"
#define   strSetWPAWarn			multilang(LANG_STRSETWPAWARN)//"You cannot set client mode with WPA-RADIUS!<br><br>Please change the encryption method in security page first."
#define   strSetWEPWarn			multilang(LANG_STRSETWEPWARN)//"You cannot set client mode with WEP-802.1x!<br><br>Please change the encryption method in security page first."
//#define   strSetMIBWLANMODEErr		"Set MIB_WLAN_MODE error!"
#define   strSetSSIDErr				multilang(LANG_STRSETSSIDERR)//"Set SSID error!"
#define   strInvdChanNum			multilang(LANG_STRINVDCHANNUM)//"Invalid channel number!" 
#define   strSetChanErr				multilang(LANG_STRSETCHANERR)//"Set channel number error!"
//#define   strInvdNetType			"Invalid network type value!"
//#define   strSetMIBWLANTYPEErr		"Set MIB_WLAN_NETWORK_TYPE failed!"
#define   strInvdAuthType			multilang(LANG_STRINVDAUTHTYPE)//"Error! Invalid authentication value."
//#define   strSetAuthTypeErr			"Set authentication failed!"
//#define   strSetAdapRateErr			"Set rate adaptive failed!"
//#define   strSetFixdRateErr			"Set fix rate failed!"
#define   strSetBaseRateErr			multilang(LANG_STRSETBASERATEERR)//"Set Tx basic rate failed!"
#define   strSetOperRateErr			multilang(LANG_STRSETOPERRATEERR)//"Set Tx operation rate failed!"
//#define   strInvdTxRate				"invalud value of tx rate!"
#define   strInvdBrodSSID			multilang(LANG_STRINVDBRODSSID)//"Error! Invalid hiddenSSID value."
//#define   strSetBrodSSIDErr			"Set hidden ssid failed!"
#define   strInvdProtection             	multilang(LANG_STRINVDPROTECTION)//"Invalid protection setting "      //add by yq_zhou 2.10
#define   strInvdAggregation	                multilang(LANG_STRINVDAGGREGATION)//"Invalid aggregation setting"
#define   strInvdShortGI0 	                multilang(LANG_STRINVDSHORTGI0)//"Invalid short GI setting"
#define   strSetProtectionErr          	multilang(LANG_STRSETPROTECTIONERR)//"Set protection  error"
#define   strSetAggregationErr	  	multilang(LANG_STRSETAGGREGATIONERR)//"Set aggregation  error"
#define   strSetShortGI0Err			multilang(LANG_STRSETSHORTGI0ERR)//"Set guard interval error"
#define   strSetChanWidthErr  		multilang(LANG_STRSETCHANWIDTHERR)//"Set channel width error"
#define   strSetCtlBandErr 			multilang(LANG_STRSETCTLBANDERR)//"Set control sideband error"
//#define   strSetBandErr				multilang()"Set band error!"
#define   strEnabAccCtlErr			multilang(LANG_STRENABACCCTLERR)//"Set enabled access control error!"
#define   strInvdMACAddr			multilang(LANG_STRINVDMACADDR)//"Error! Invalid MAC address."
#define   strAddAcErrForFull			multilang(LANG_STRADDACERRFORFULL)//"Cannot add new entry because table is full!"
#define   strMACInList				multilang(LANG_STRMACINLIST)//"Entry already exists!"
#define   strAddListErr				multilang(LANG_STRADDLISTERR)//"Error! Add chain record."
#define   strDelListErr				multilang(LANG_STRDELLISTERR)//"Delete chain record error!"
#define   strFragThreshold			multilang(LANG_STRFRAGTHRESHOLD)//"Error! Invalid value of fragment threshold."
#define   strSetFragThreErr			multilang(LANG_STRSETFRAGTHREERR)//"Set fragment threshold failed!"
#define   strRTSThreshold			multilang(LANG_STRRTSTHRESHOLD)//"Error! Invalid value of RTS threshold."
#define   strSetRTSThreErr			multilang(LANG_STRSETRTSTHREERR)//"Set RTS threshold failed!"
#define   strInvdBeaconIntv			multilang(LANG_STRINVDBEACONINTV)//"Error! Invalid value of Beacon Interval."
#define   strSetBeaconIntvErr		multilang(LANG_STRSETBEACONINTVERR)//"Set Beacon interval failed!"
#define   strInvdPreamble			multilang(LANG_STRINVDPREAMBLE)//"Error! Invalid Preamble value."
#define   strSetPreambleErr			multilang(LANG_STRSETPREAMBLEERR)//"Set Preamble failed!"
#define   strInvdDTIMPerd			multilang(LANG_STRINVDDTIMPERD)//"Error! Invalid value of DTIM period."
#define   strSetDTIMErr				multilang(LANG_STRSETDTIMERR)//"Set DTIM period failed!"
//#define   strInvdIAPP				"Error! Invalid IAPP value."
//#define   strMIBIAPPDISBErr			"Set MIB_WLAN_IAPP_DISABLED failed!"
//#define   strSetRelayBlockErr			"Set block relay failed!"
#define   strSetLanWlanBlokErr		multilang(LANG_STRSETLANWLANBLOKERR)//"Set block ethernet to wireless failed!"
//#define   strSetWlanWMMErr			"Set WMM(QoS) to wireless failed!"
//#define   strMACAddr				"MAC Address"
//#define   strSelect					"Select"
#define   strGetMBSSIBTBLErr		multilang(LANG_STRGETMBSSIBTBLERR)//"Error! Get MIB_MBSSIB_TBL error."
#define   strGetMULTIAPTBLErr		multilang(LANG_STRGETMULTIAPTBLERR)//"Error! formWlanMultipleAP: Get MIB_MBSSIB_TBL for VAP error."
#define   strNotSuptSSIDType		multilang(LANG_STRNOTSUPTSSIDTYPE)//"Error! Not support this SSID TYPE."
#define   strNoSSIDTypeErr			multilang(LANG_STRNOSSIDTYPEERR)//"Error! no SSID TYPE."
#define   strNoEncryptionErr			multilang(LANG_STRNOENCRYPTIONERR)//"Error! no encryption method."
//#define   strInvdEncryptErr			"Invalid encryption method!"
//#define   strSetWLANENCRYPTErr		"Set MIB_WLAN_ENCRYPT mib error!"
#define   strSet8021xWarning		multilang(LANG_STRSET8021XWARNING)//"Error! 802.1x authentication cannot be used when device is set to client mode."
//#define   strSet1xEnabErr			"Set 1x enable flag error!"
//#define   strGetWLANWEPErr			"Get MIB_WLAN_WEP MIB error!"
#define   strSetWLANWEPErr			multilang(LANG_STRSETWLANWEPERR)//"Set WEP MIB error!"
#define   strSetWPARADIUSWarn		multilang(LANG_STRSETWPARADIUSWARN)//"Error! WPA-RADIUS cannot be used when device is set to client mode."
#define   strInvdWPAAuthValue		multilang(LANG_STRINVDWPAAUTHVALUE)//"Error! Invalid wpa authentication value."
//#define   strSetAUTHTYPEErr			"Set MIB_WLAN_AUTH_TYPE failed!"
#define   strNoPSKFormat			multilang(LANG_STRNOPSKFORMAT)//"Error! no psk format."
#define   strInvdPSKFormat			multilang(LANG_STRINVDPSKFORMAT)//"Error! invalid psk format."
#define   strSetWPAPSKFMATErr		multilang(LANG_STRSETWPAPSKFMATERR)//"Set MIB_WLAN_WPA_PSK_FORMAT failed!"
#define   strInvdPSKValue			multilang(LANG_STRINVDPSKVALUE)//"Error! invalid psk value."
#define   strSetWPAPSKErr			multilang(LANG_STRSETWPAPSKERR)//"Set MIB_WLAN_WPA_PSK error!"
//#define   strInvdRekeyDay			"Error! Invalid value of rekey day."
//#define   strInvdRekeyHr			"Error! Invalid value of rekey hr."
//#define   strInvdRekeyMin			"Error! Invalid value of rekey min."
//#define   strInvdRekeySec			"Error! Invalid value of rekey sec."
#define   strSetREKEYTIMEErr		multilang(LANG_STRSETREKEYTIMEERR)//"Set MIB_WLAN_WPA_GROUP_REKEY_TIME error!"
#define   strInvdRSPortNum			multilang(LANG_STRINVDRSPORTNUM)//"Error! Invalid value of RS port number."
//#define   strSetRSPortErr			"Set RS port error!"
#define   strNoIPAddr				multilang(LANG_STRNOIPADDR)//"No RS IP address!"
#define   strInvdRSIPValue			multilang(LANG_STRINVDRSIPVALUE)//"Invalid RS IP-address value!"
//#define   strSetIPAddrErr			"Set RS IP-address error!"
#define   strRSPwdTooLong			multilang(LANG_STRRSPWDTOOLONG)//"RS password length too long!"
//#define   strSetRSPwdErr			"Set RS password error!"
#define   strInvdRSRetry			multilang(LANG_STRINVDRSRETRY)//"Invalid RS retry value!"
#define   strSetRSRETRYErr			multilang(LANG_STRSETRSRETRYERR)//"Set MIB_WLAN_RS_RETRY error!"
#define   strInvdRSTime				multilang(LANG_STRINVDRSTIME)//"Invalid RS time value!"
#define   strSetRSINTVLTIMEErr		multilang(LANG_STRSETRSINTVLTIMEERR)//"Set MIB_WLAN_RS_INTERVAL_TIME error!"
#define   strInvdWepKeyLen			multilang(LANG_STRINVDWEPKEYLEN)//"Error! Invalid wepkeylen value."
//#define   strSetMIBWLANWEPErr		"Set MIB_WLAN_WEP failed!"
#define   strGetMBSSIBTBLUpdtErr	multilang(LANG_STRGETMBSSIBTBLUPDTERR)//"Error! Get MIB_MBSSIB_TBL error(Updated)."
//#define   strGetMBSSIBWEPTBLErr	"Error! Get MIB_MBSSIB_WEP_TBL error."
#define   strKeyLenMustExist			multilang(LANG_STRKEYLENMUSTEXIST)//"Key length must exist!"
#define   strInvdKeyLen				multilang(LANG_STRINVDKEYLEN)//"Invalid key length value!"
#define   strKeyTypeMustExist		multilang(LANG_STRKEYTYPEMUSTEXIST)//"Key type must exist!"
#define   strInvdKeyType			multilang(LANG_STRINVDKEYTYPE)//"Invalid key type value!"
#define   strSetWepKeyTypeErr		multilang(LANG_STRSETWEPKEYTYPEERR)//"Set WEP key type error!"
//#define   strInvdDeftKey				"Invalid default tx key id!"
//#define   strSetDeftKeyErr			"Set default tx key id error!"
#define   strInvdKey1Len			multilang(LANG_STRINVDKEY1LEN)//"Invalid key 1 length!"
#define   strInvdWEPKey1			multilang(LANG_STRINVDWEPKEY1)//"Invalid wep-key1 value!"
#define   strSetWEPKey1Err			multilang(LANG_STRSETWEPKEY1ERR)//"Set wep-key1 error!"
//#define   strInvdKey2Len			"Invalid key 2 length!"
//#define   strInvdWEPKey2			"Invalid wep-key2 value!"
//#define   strSetWEPKey2Err			"Set wep-key2 error!"
//#define   strInvdKey3Len			"Invalid key 3 length!"
//#define   strInvdWEPKey3			"Invalid wep-key3 value!"
//#define   strSetWEPKey3Err			"Set wep-key3 error!"
//#define   strInvdKey4Len			"Invalid key 4 length!"
//#define   strInvdWEPKey4			"Invalid wep-key4 value!"
//#define   strSetWEPKey4Err			"Set wep-key4 error!"
//#define   strGetMBSSIBWEPTLBUpdtErr   "Error! Get MIB_MBSSIB_WEP_TBL error(Updated)."
//#define   strWdsComment			"Comment"
#define   strSetEnableErr   			multilang(LANG_STRSETENABLEERR)//"Set enabled flag error!"
#define   strCommentTooLong 		multilang(LANG_STRCOMMENTTOOLONG)//"Error! Comment length too long."
#define   strGetEntryNumErr 			multilang(LANG_STRGETENTRYNUMERR)//"Get entry number error!" 
#define   strErrForTablFull 			multilang(LANG_STRERRFORTABLFULL)//"Cannot add new entry because table is full!" 
#define   strAddEntryErr    			multilang(LANG_STRADDENTRYERR)//"Add table entry error!"
#define   strDelRecordErr   			multilang(LANG_STRDELRECORDERR)//"Delete chain record error!"


//for web upgrade
#define   FILEOPENFAILED multilang(LANG_FILEOPENFAILED)//"File open error!"
#define   FILEWITHWRONGSIG	multilang(LANG_FILEWITHWRONGSIG)//"Invalid signature!"

//#define  INFO_ENABLED 	"Enabled"
//#define  INFO_DISABLED	"Disabled"
//for tr069
#if defined(_CWMP_MIB_)

#define strSetCerPasserror  multilang(LANG_STRSETCERPASSERROR)//"Set CPE Certificat's Password error!"
#define strACSURLWrong  multilang(LANG_STRACSURLWRONG)//"ACS's URL can't be empty!"
#define strSSLWrong multilang(LANG_STRSSLWRONG)//"CPE does not support SSL! URL should not start with 'https://'!"
#define strSetACSURLerror multilang(LANG_STRSETACSURLERROR)//"Set ACS's URL error!"
#define strSetUserNameerror multilang(LANG_STRSETUSERNAMEERROR)//"Set User Name error!"
#define strSetPasserror multilang(LANG_STRSETPASSERROR)//"Set Password error!"
#define strSetInformEnableerror multilang(LANG_STRSETINFORMENABLEERROR)//"Set Inform Enable error!"
#define strSetInformIntererror multilang(LANG_STRSETINFORMINTERERROR)//"Set Inform Interval error!"
#define strSetConReqUsererror multilang(LANG_STRSETCONREQUSERERROR)//"Set Connection Request UserName error!"
#define strSetConReqPasserror multilang(LANG_STRSETCONREQPASSERROR)//"Set Connection Request Password error!"
#define strSetCWMPFlagerror multilang(LANG_STRSETCWMPFLAGERROR)//"Set CWMP_FLAG error!"
#define strGetCWMPFlagerror multilang(LANG_STRGETCWMPFLAGERROR)//"Get CWMP_FLAG error!"
#define strUploaderror multilang(LANG_STRUPLOADERROR)//"Upload error!"
#define strMallocFail multilang(LANG_STRMALLOCFAIL)//"malloc failure!"
#define strArgerror multilang(LANG_STRARGERROR)//"Insufficient args\n"
#endif

//for dns web fmdns.c
#define Tinvalid_DNS_mode multilang(LANG_TINVALID_DNS_MODE)//"Invalid DNS mode value!"
#define TDNS_mib_get_error      multilang(LANG_TDNS_MIB_GET_ERROR)//"Get DNS MIB error!"
#define Tinvalid_DNS_address  	multilang(LANG_TINVALID_DNS_ADDRESS)//"Invalid DNS address value!"
#define TDNS_mib_set_error		multilang(LANG_TDNS_MIB_SET_ERROR)//"Set DNS MIB error!"

//for ipqos  fmqos.c  ip/portfilter, fmfwall.
#define Texceed_max_rules				multilang(LANG_TEXCEED_MAX_RULES)//"Error: Maximum number of Qos rule exceeds !"	
#define Tinvalid_source_ip   				multilang(LANG_TINVALID_SOURCE_IP)//"Error! Source IP."
#define Tinvalid_source_netmask 			multilang(LANG_TINVALID_SOURCE_NETMASK)//"Error! Source Netmask"
#define Tinvalid_source_port 				multilang(LANG_TINVALID_SOURCE_PORT)//"Error! Invalid source port."
#ifdef QOS_SPEED_LIMIT_SUPPORT
#define Tinvalid_pvc_bandwidth				multilang(LANG_TINVALID_PVC_BANDWIDTH)//"Error! Invalid pvc  bandwidth."
#endif
#define Tinvalid_destination_ip			multilang(LANG_TINVALID_DESTINATION_IP)//"Error! Destination IP."
#define Tinvalid_destination_netmask		multilang(LANG_TINVALID_DESTINATION_NETMASK)//"Error! Destination Netmask."
#define Tinvalid_destination_port			multilang(LANG_TINVALID_DESTINATION_PORT)//"Error! Invalid destination port."
#define Tinvalid_speed					multilang(LANG_TINVALID_SPEED)//"Error!Invalid speed"

//Operation about MIB
#define Tadd_chain_error				multilang(LANG_TADD_CHAIN_ERROR)//"Error! Add chain record."
#define Tdelete_chain_error				multilang(LANG_TDELETE_CHAIN_ERROR)//"Delete chain record error"
#define Tupdate_chain_error				multilang(LANG_TUPDATE_MIB_ERROR) //"Update MIB Chain record error
#define Tmod_chain_error				multilang(LANG_TMODIFY_MIB_ERROR)//"Modify MIB error"
#define Tset_mib_error				    multilang(LANG_TSET_MIB_ERROR) //"Set MIB error"
#define Tget_mib_error				    multilang(LANG_TGET_MIB_ERROR) //"Get MIB error"

//Generic Error
#define strInvalidValue multilang(LANG_INVALID_VALUE) //"Invalid value"

#define Tinvalid_if_ip					multilang(LANG_TINVALID_IF_IP)//"Error! invalid IP addr!"
#define Tinvalid_if_mask				multilang(LANG_TINVALID_IF_MASK)//"Error! invalid mask addr."

//for firewall ip/port filter, fmfwall.c

#define Tprotocol_empty							multilang(LANG_TPROTOCOL_EMPTY)//"Error! Protocol type cannot be empty."
#define Tinvalid_port_range							multilang(LANG_TINVALID_PORT_RANGE)//"Error! port range error"
#define Tinvalid_rule_action						multilang(LANG_TINVALID_RULE_ACTION)//"Invalid Rule Action value!"
#define Tinvalid_source_mac						multilang(LANG_TINVALID_SOURCE_MAC)//"Error! Invalid src MAC address."
#define Tinvalid_dest_mac						multilang(LANG_TINVALID_DEST_MAC)//"Error! Invalid dst MAC address."
#define Toutgoing_ippfilter   						multilang(LANG_TOUTGOING_IPPFILTER)//"Outgoing"
#define Tincoming_ippfilter						multilang(LANG_TINCOMING_IPPFILTER)//"Incoming"
#define Tdeny_ippfilter							multilang(LANG_TDENY_IPPFILTER)//"Deny"
#define Tallow_ippfilter						multilang(LANG_TALLOW_IPPFILTER)//"Allow"
#define Tinvalid_rule							multilang(LANG_TINVALID_RULE)//"Invaild! This is a duplicate or conflicting rule !"

//for dos
#define strSetDosSYSSYNFLOODErr   multilang(LANG_STRSETDOSSYSSYNFLOODERR)//"Set DoS SYSSYN_FLOOD error!"
#define strSetDosSYSFINFLOODErr   multilang(LANG_STRSETDOSSYSFINFLOODERR)//"Set DoS SYSFIN_FLOOD error!" 
#define strSetDosSYSUDPFLOODErr   multilang(LANG_STRSETDOSSYSUDPFLOODERR)//"Set DoS SYSUDP_FLOOD error!" 
#define strSetDosSYSICMPFLOODErr  multilang(LANG_STRSETDOSSYSICMPFLOODERR)//"Set DoS SYSICMP_FLOOD error!"
#define strSetDosPIPSYNFLOODErr   multilang(LANG_STRSETDOSPIPSYNFLOODERR)//"Set DoS PIPSYN_FLOOD error!"
#define strSetDosPIPFINFLOODErr   multilang(LANG_STRSETDOSPIPFINFLOODERR)//"Set DoS PIPFIN_FLOOD error!"
#define strSetDosPIPUDPFLOODErr   multilang(LANG_STRSETDOSPIPUDPFLOODERR)//"Set DoS PIPUDP_FLOOD error!"
#define strSetDosPIPICMPFLOODErr  multilang(LANG_STRSETDOSPIPICMPFLOODERR)//"Set DoS PIPICMP_FLOOD error!"
#define strSetDosIPBlockTimeErr   multilang(LANG_STRSETDOSIPBLOCKTIMEERR)//"Set DoS IP Block Timer error!"
#define strSetDosEnableErr        multilang(LANG_STRSETDOSENABLEERR)//"Set DoS enable error!"

//for wan config(static pppoe IP)
#define Tip_addr		multilang(LANG_TIP_ADDR)//"IP Address"
#define Tdynamic_ip		multilang(LANG_TDYNAMIC_IP)//"Dynamic IP"
#define Tstatic_ip		multilang(LANG_TSTATIC_IP)//"Static IP"

#define Tinvalid_ip_net		multilang(LANG_TINVALID_IP_NET)//"Invalid IP address! It should be set within the current subnet.\n"

#define TstrUrlExist        multilang(LANG_TSTRURLEXIST)//" FQDN already exists!"
#define TstrKeyExist        multilang(LANG_TSTRKEYEXIST)//" KEYword already exists!"
#define TMaxUrl             multilang(LANG_TMAXURL)//"Maximum number of FQDN records exceeds!"
#define TMaxKey             multilang(LANG_TMAXKEY)//"Maximum number of KEYWORD records exceeds!" 


#define strIpExist   multilang(LANG_STRIPEXIST)//"The IP addr has been exist!"
#define strMacExist	 multilang(LANG_STRMACEXIST)//"The MAC addr has been exist!"
#define strSetInterfaceerror   multilang(LANG_STRSETINTERFACEERROR)//"Set ACL's Interface error!"
#define strSetACLCAPerror  multilang(LANG_STRSETACLCAPERROR)//"Set ACL Capability error!"

#define strSetNatSessionError multilang(LANG_STRSETNATSESSIONERROR)//"Set Nat session limitation error!"

// Added by davian_kuo.
#define strSetMultiLangError multilang(LANG_SAVE_MULTI_LANG_ERR)

#define strInvaidPinCode multilang(LANG_INVALID_PIN_CODE) //"Invalid PIN Code"
#define strInvaidBackupTimer multilang(LANG_INVALID_BACKUP_TIMER_VALUE) //"Invalid backup timer value!"
#define strCantResolve multilang(LANG_ERROR_CANT_RESOLVE) //"Error: can't resolve"
#define strNoItemSelectedToDelete multilang(LANG_THERE_IS_NO_ITEM_SELECTED_TO_DELETE) //"There is no item selected to delete"
#define strMaximumRulesExceeded multilang(LANG_MAXIMUM_RULES_EXCEEDED) //"Maximum rules exceeded!"
#define strNoAddrMapType multilang(LANG_ERROR_NO_ADDRESS_MAP_TYPE) //"Error! No address Map Type!"
#define strInvalidAddrMapType multilang(LANG_INVALID_ADDRESS_MAP_TYPE) //"Invalid Address Map Type."
#define strInvalidIPAddrShouldInSubnet multilang(LANG_INVALID_IP_ADDRESS_IT_SHOULD_BE_SET_WITHIN_THE_CURRENT_SUBNET) //"Invalid IP address! It should be set within the current subnet."
#define strShouldBe multilang(LANG_SHOULD_BE) //"should be"
#define strFormatError multilang(LANG_FORMAT) //"format"
#define strShouldInSameSubnet multilang(LANG_SHOULD_BE_SAME_SUBNET) //"start,  end and static IP address shoud be in the same subnet!"
#define strNoSetError multilang(LANG_NO_SET_ERROR) //"No set"
#define strAddrConflict multilang(LANG_ADDR_CONFLICT) //"Address Conflict"
#define strGameNameConlict multilang(LANG_GAME_NAME_CONFLICT) //"Game Conflict"
#define strAtLeastSelectOne multilang(LANG_AT_LEAST_SELECT_ONE) //"At least select one"
#define strDeviceIsAlreadyExist multilang(LANG_DEVICE_IS_ALREADY_EXIST_IN_TABLE) //"device is already exist in table!"
#define strDestIPShouldBeLargerThanSrcIP multiliang(LANG_DESTINATION_IP_ADDRESS_SHOULD_BE_LARGER_THAN_SOURCE_IP_ADDRESS) //"destination IP address should be larger than source IP address!"

#endif
