.Dd Wed, 07 May 2003 15:55:00 +0200
.Dt RLOGIND 8
.Sh NAME
.Nm rlogind
.Nd remote login daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is the server for the 
.Xr rlogin 1
program.
The server provides a remote login facility with authentication
based on privileged port numbers from trusted hosts or a login prompt.
.Sh SEE ALSO
.Xr rsh 1 ,
.Xr rshd 8 ,
.Xr rlogin 1 ,
.Xr rcp 1 ,
.Xr rhosts 5 ,
RFC 1282.
