.Dd Wed, 07 May 2003 15:55:00 +0200
.Dt RSHD 8
.Sh NAME
.Nm rshd
.Nd remote shell daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is the server for the 
.Xr rsh 1
program.
The server provides a remote shell facility with authentication
based on privileged port numbers from trusted hosts.
.Sh SEE ALSO
.Xr rsh 1 ,
.Xr rlogin 1 ,
.Xr rlogind 8 ,
.Xr rcp 1 ,
.Xr rhosts 5 ,
RFC 1282.
