#
# Copyright (C) 2009 Realtek Semiconductor Corp.
#
# Makefile for SDK Linux RTCORE Module
#

SDK_BUILD = $(SDKDIR)/build
EXTRA_CFLAGS += -DCONFIG_SDK_KERNEL_LINUX
include $(SDK_BUILD)/Makefile.linux.kernel.rtcore

