


	.data
	.globl	sound_c1_8k_rin5
sound_c1_8k_rin5:
	.incbin	"./rtk_voip/voip_drivers/sound_c1_8k_rin5[16bitBEmono8k].raw"

	.globl	sound_c1_8k_rin10
sound_c1_8k_rin10:
	.incbin	"./rtk_voip/voip_drivers/sound_c1_8k_rin10[16bitBEmono8k].raw"

	.globl	sound_c1_8k_rin13p8
sound_c1_8k_rin13p8:
	.incbin	"./rtk_voip/voip_drivers/sound_c1_8k_rin13p8[16bitBEmono8k].raw"

	.globl	sound_c1_8k_rin15
sound_c1_8k_rin15:
	.incbin	"./rtk_voip/voip_drivers/sound_c1_8k_rin15[16bitBEmono8k].raw"

	.globl	sound_c1_8k_rin20
sound_c1_8k_rin20:
	.incbin	"./rtk_voip/voip_drivers/sound_c1_8k_rin20[16bitBEmono8k].raw"

	.globl	sound_c1_8k_rin30
sound_c1_8k_rin30:
	.incbin	"./rtk_voip/voip_drivers/sound_c1_8k_rin30[16bitBEmono8k].raw"
