#ifndef		_AUTOCONF_H_
#define		_AUTOCONF_H_

#define CONFIG_USER_SNMPD_MODULE_SYSTEM
#define CONFIG_USER_SNMPD_MODULE_IP
#define CONFIG_USER_SNMPD_MODULE_IFACE
#define CONFIG_USER_SNMPD_MODULE_TCP
#define CONFIG_USER_SNMPD_MODULE_ICMP
#define CONFIG_USER_SNMPD_MODULE_UDP

#ifdef CONFIG_DEV_xDSL
#define CONFIG_USER_SNMPD_MODULE_ADSL
#endif
#define CONFIG_USER_SNMPD_MODULE_ATM

//#define CONFIG_USER_SNMPD_MODULE_FRAMEWORK

#define		AGENT_SYS_TEXT_SIZE		255
// Added by Mason Yu
#ifdef CONFIG_USER_WIRELESS_TOOLS
#define CONFIG_USER_SNMPD_MODULE_WLAN
#endif


#endif

