/* RCM Common API */
#ifndef __RCM_TAPI_H
#define __RCM_TAPI_H

#include "voip_manager.h"
//#include "voip_types.h"


#define rcm_tapi_InitDSP(ch)		rtk_InitDSP(ch)
/* for DECT only */
#define rcm_tapi_SetDectPower(power)		rtk_SetDectPower(power)
#define rcm_tapi_GetDectPower(void)		rtk_GetDectPower(void)
#define rcm_tapi_GetDectPage(void)		rtk_GetDectPage(void)
#define rcm_tapi_GetDectButtonEvent(void)		rtk_GetDectButtonEvent(void)
#define rcm_tapi_SetDectLED(chid,state )		rtk_SetDectLED(chid,state )
#define rcm_tapi_SetRtpConfig(cfg)	rtk_SetRtpConfig(cfg)
#define rcm_tapi_SetRtcpConfig(cfg)	rtk_SetRtcpConfig(cfg)
#define rcm_tapi_GetRtcpLogger(chid,sid,logger )	rtk_GetRtcpLogger(chid,sid,logger )
#define rcm_tapi_SetRtpPayloadType(cfg)		rtk_SetRtpPayloadType(cfg)
#define rcm_tapi_SetRtpSessionState(chid,sid,state)		rtk_SetRtpSessionState(chid,sid,state)
#define rcm_tapi_SetThresholdVadCng( chid, mid,nThresVAD, nThresCNG, nModeCNG, nLevelCNG, nGainCNG ) rtk_SetThresholdVadCng( chid, mid,nThresVAD, nThresCNG, nModeCNG, nLevelCNG, nGainCNG )
#define rcm_tapi_DisableRingFXS(bDisable)	rtk_DisableRingFXS(bDisable)
#define rcm_tapi_SetRingFXS(chid, bRinging)	rtk_SetRingFXS(chid, bRinging)	
#define rcm_tapi_SetPlayTone(chid, sid, nTone, bFlag,Path)	rtk_SetPlayTone(chid, sid, nTone, bFlag,Path) 
#define rcm_tapi_VoIP_resource_check(chid, payload_type)	rtk_VoIP_resource_check(chid, payload_type)
#define rcm_tapi_Onhook_Reinit(chid)	rtk_Onhook_Reinit(chid)
#define rcm_tapi_GetDectEvent(chid, pval)	rtk_GetDectEvent(chid, pval)
#define rcm_tapi_GetFxsEvent(chid, pval)	rtk_GetFxsEvent(chid, pval)
#define rcm_tapi_GetFxoEvent(chid, pval)	rtk_GetFxoEvent(chid, pval)
#define rcm_tapi_GetRealFxoEvent(chid,pval)	rtk_GetRealFxoEvent(chid,pval)
#define rcm_tapi_SetTranSessionID(chid, sid)	rtk_SetTranSessionID(chid, sid)
#define rcm_tapi_GetTranSessionID(chid,  psid)	rtk_GetTranSessionID(chid,psid)
#define rcm_tapi_SetConference(stVoipMgr3WayCfg)	rtk_SetConference(stVoipMgr3WayCfg)
#define rcm_tapi_SetDTMFMODE(chid, mode)	rtk_SetDTMFMODE(chid, mode)
#define rcm_tapi_Set_echoTail(chid, echo_tail, nlp,at_stepsize,rt_stepsize,cng_flag)	rtk_Set_echoTail(chid, echo_tail, nlp,at_stepsize,rt_stepsize,cng_flag)	
#define rcm_tapi_Set_G168_LEC(chid, support_lec)	rtk_Set_G168_LEC(chid, support_lec)
#define rcm_tapi_Set_GET_EC_DEBUG(pstVoipEcDebug)	rtk_Set_GET_EC_DEBUG(pstVoipEcDebug)
#define rcm_tapi_Set_SLIC_Ring_Cadence(chid, cad_on_msec, cad_off_msec)	rtk_Set_SLIC_Ring_Cadence(chid, cad_on_msec, cad_off_msec)
#define rcm_tapi_Set_SLIC_Ring_Freq_Amp(chid, preset)	rtk_Set_SLIC_Ring_Freq_Amp(chid, preset)
#define rcm_tapi_Set_SLIC_Line_Voltage(chid,flag)	rtk_Set_SLIC_Line_Voltage(chid,flag)
#define rcm_tapi_Gen_SLIC_CPC(chid, cpc_ms)		rtk_Gen_SLIC_CPC(chid, cpc_ms)
#define rcm_tapi_Set_FXO_Ring_Detection(ring_on_msec, first_ringoff_msec, ring_off_msec) \
		rtk_Set_FXO_Ring_Detection(ring_on_msec, first_ringoff_msec, ring_off_msec)
#define rcm_tapi_Set_DAA_Tx_Gain(gain)	rtk_Set_DAA_Tx_Gain(gain)
#define rcm_tapi_Set_DAA_Rx_Gain(gain)	rtk_Set_DAA_Rx_Gain(gain)	
#define rcm_tapi_Set_Flash_Hook_Time(chid, min_time, time)	rtk_Set_Flash_Hook_Time(chid, min_time, time)
#define rcm_tapi_SetRFC2833SendByAP(chid, config)	rtk_SetRFC2833SendByAP(chid, config)
#define rcm_tapi_SetRFC2833TxConfig(chid, volume, tx_mode)	rtk_SetRFC2833TxConfig(chid, volume, tx_mode) 
#define rcm_tapi_SetRTPRFC2833(chid, sid, event, duration)	rtk_SetRTPRFC2833(chid, sid, event, duration)
#define rcm_tapi_LimitMaxRfc2833DtmfDuration(chid, duration_in_ms, bEnable)	rtk_LimitMaxRfc2833DtmfDuration(chid, duration_in_ms, bEnable)
#define rcm_tapi_GetRfc2833RxEvent(chid, mid, pent)	rtk_GetRfc2833RxEvent(chid, mid, pent)
#define rcm_tapi_SetFaxModemRfc2833(chid, relay_flag, removal_flag, tone_gen_flag)	rtk_SetFaxModemRfc2833(chid, relay_flag, removal_flag, tone_gen_flag)
#define rcm_tapi_SetDtmfCIDState(chid, str_cid) rtk_SetDtmfCIDState(chid, str_cid)
#define rcm_tapi_GetDtmfCIDState(chid, cid_state)	rtk_GetDtmfCIDState(chid, cid_state)
#define rcm_tapi_GetFaxModemEvent(chid, pval, pevent, flush)	rtk_GetFaxModemEvent(chid, pval, pevent, flush)
#define rcm_tapi_GetFaxEndDetect(chid, pval)	rtk_GetFaxEndDetect(chid, pval)
#define rcm_tapi_GetFaxDisDetect(chid, pval)	rtk_GetFaxDisDetect(chid, pval)
#define rcm_tapi_GetFaxDisTxDetect(chid, pval)	rtk_GetFaxDisTxDetect(chid, pval)
#define rcm_tapi_GetFaxDisRxDetect(chid, pval)	rtk_GetFaxDisRxDetect(chid, pval)
#define rcm_tapi_GetFxoLineVoltage(chid, pval)	rtk_GetFxoLineVoltage(chid, pval)
#define rcm_tapi_Gen_Dtmf_CID(chid,str_cid)	rtk_Gen_Dtmf_CID(chid,str_cid)
#define rcm_tapi_Gen_FSK_CID(chid, str_cid, str_date, str_cid_name, mode)	rtk_Gen_FSK_CID(chid, str_cid, str_date, str_cid_name, mode)
#define rcm_tapi_Gen_MDMF_FSK_CID(chid, pClid, num_clid_element)	rtk_Gen_MDMF_FSK_CID(chid, pClid, num_clid_element)
#define rcm_tapi_Gen_CID_And_FXS_Ring(chid, cid_mode, str_cid, str_date, str_cid_name, fsk_type, bRinging)	\
	rtk_Gen_CID_And_FXS_Ring(chid, cid_mode, str_cid, str_date, str_cid_name, fsk_type, bRinging)
#define rcm_tapi_Gen_FSK_VMWI(chid, state, mode)	rtk_Gen_FSK_VMWI(chid, state, mode)
#define rcm_tapi_Set_FSK_Area(chid, area)  rtk_Set_FSK_Area(chid, area)
#define rcm_tapi_Set_FSK_CLID_Para(para)	rtk_Set_FSK_CLID_Para(para)
#define rcm_tapi_Hold_Rtp(chid, sid, enable)	rtk_Hold_Rtp(chid, sid, enable)
#define rcm_tapi_enable_pcm(chid, bEnable)	rtk_enable_pcm(chid, bEnable)
#define rcm_tapi_Set_DTMF_CFG(chid, bEnable, dir)	rtk_Set_DTMF_CFG(chid, bEnable, dir)
#define rcm_tapi_Get_SLIC_Reg_Val(chid, reg, regdata)	rtk_Get_SLIC_Reg_Val(chid, reg, regdata)
#define rcm_tapi_Get_DAA_Used_By_Which_SLIC(chid)	rtk_Get_DAA_Used_By_Which_SLIC(chid)
#define rcm_tapi_DAA_on_hook(chid)	rtk_DAA_on_hook(chid)
#define rcm_tapi_DAA_off_hook(chid)		rtk_DAA_off_hook(chid)	
#define rcm_tapi_DAA_ring(chid)		rtk_DAA_ring(chid)
#define rcm_tapi_Set_Country(voip_ptr)		rtk_Set_Country(voip_ptr)
#define rcm_tapi_Set_Country_Impedance(country)		rtk_Set_Country_Impedance(country)
#define rcm_tapi_Set_Country_Tone(country)	rtk_Set_Country_Tone(country)
#define rcm_tapi_Set_Impedance(preset)	rtk_Set_Impedance(preset)
#define rcm_tapi_Set_Dis_Tone_Para(voip_ptr)	rtk_Set_Dis_Tone_Para(voip_ptr)
#define rcm_tapi_Set_Custom_Tone(custom, pstToneCfgParam)	rtk_Set_Custom_Tone(custom, pstToneCfgParam)
#define rcm_tapi_Use_Custom_Tone(dial, ringback,  busy,  waiting)	rtk_Use_Custom_Tone(dial, ringback,  busy,  waiting)
#define rcm_tapi_Set_SLIC_Reg_Val( chid,  reg,  len, regdata)	rtk_Set_SLIC_Reg_Val( chid,  reg,  len, regdata)
#define rcm_tapi_reset_slic(chid, law)	rtk_reset_slic(chid, law)
#define rcm_tapi_Set_PCM_Loop_Mode(group, mode, main_ch, mate_ch)	rtk_Set_PCM_Loop_Mode(group,mode,main_ch,mate_ch)
#define rcm_tapi_Set_FXS_FXO_Loopback( chid, enable)	rtk_Set_FXS_FXO_Loopback( chid, enable)
#define rcm_tapi_Set_FXS_OnHook_Trans_PCM_ON( chid)		rtk_Set_FXS_OnHook_Trans_PCM_ON( chid)
#define rcm_tapi_debug_with_watchdog( dbg_flag, watchdog)		rtk_debug_with_watchdog( dbg_flag, watchdog)
#define rcm_tapi_debug(dbg_flag)	rtk_debug(dbg_flag)

#ifdef CONFIG_RTK_VOIP_WAN_VLAN
#define rcm_tapi_switch_wan_3_vlan(voip_ptr)	rtk_switch_wan_3_vlan(voip_ptr)
#define rcm_tapi_switch_wan_2_vlan(voip_ptr)	rtk_switch_wan_2_vlan(voip_ptr)
#define rcm_tapi_switch_wan_vlan(voip_ptr)	rtk_switch_wan_vlan(voip_ptr)
#endif

#ifdef CONFIG_RTK_VOIP_IVR
#define rcm_tapi_IvrStartPlaying(  chid,ssid, dir, pszText2Speech )	rtk_IvrStartPlaying(  chid,ssid, dir, pszText2Speech ) 
#define rcm_tapi_IvrStartPlayG72363(  chid, ssid,nFrameCount, pData )	rtk_IvrStartPlayG72363(  chid,ssid, nFrameCount, pData )
#define rcm_tapi_IvrStartPlayG729(  chid, ssid, nFrameCount,   pData )	rtk_IvrStartPlayG729(  chid,ssid,  nFrameCount,   pData )
#endif

#define rcm_tapi_IvrPollPlaying(  chid,sid )	rtk_IvrPollPlaying(  chid ,sid )
#define rcm_tapi_IvrStopPlaying( chid,sid )		rtk_IvrStopPlaying( chid ,sid)
#define rcm_tapi_sip_register(chid, isOK)	rtk_sip_register(chid, isOK)
#define rcm_tapi_Set_CID_DTMF_MODE(chid, area, cid_dtmf_mode)	rtk_Set_CID_DTMF_MODE(chid, area, cid_dtmf_mode)
#define rcm_tapi_SIP_INFO_play_tone(  chid,   ssid,  tone, duration)	rtk_SIP_INFO_play_tone(  chid,   ssid,  tone, duration)
#define rcm_tapi_Set_SPK_AGC(chid,support_gain,adaptive_threshold)	rtk_Set_SPK_AGC(chid,support_gain,adaptive_threshold)
#define rcm_tapi_Set_SPK_AGC_LVL(chid, level)	rtk_Set_SPK_AGC_LVL(chid, level)
#define rcm_tapi_Set_SPK_AGC_GUP(chid, gain)	rtk_Set_SPK_AGC_GUP(chid, gain)
#define rcm_tapi_Set_SPK_AGC_GDOWN(chid, gain)	rtk_Set_SPK_AGC_GDOWN(chid, gain)

#define rcm_tapi_Set_MIC_AGC(chid,support_gain,adaptive_threshold)	rtk_Set_MIC_AGC(chid,support_gain,adaptive_threshold)
#define rcm_tapi_Set_MIC_AGC_LVL(chid, level)	rtk_Set_MIC_AGC_LVL(chid,level)
#define rcm_tapi_Set_MIC_AGC_GUP( chid,  gain)	rtk_Set_MIC_AGC_GUP(chid,gain)
#define rcm_tapi_Set_MIC_AGC_GDOWN( chid,  gain)	rtk_Set_MIC_AGC_GDOWN(chid,gain)
#define rcm_tapi_Dial_PSTN_Call_Forward( chid,  sid, cf_no_str)	rtk_Dial_PSTN_Call_Forward(chid,sid,cf_no_str)
#define rcm_tapi_Get_DAA_CallerID( chid, str_cid, str_date, str_name)	rtk_Get_DAA_CallerID(chid,str_cid,str_date,str_name)
#define	rcm_tapi_Get_VoIP_Feature()		rtk_Get_VoIP_Feature()
#define rcm_tapi_Set_CID_Det_Mode( chid,  auto_det,  cid_det_mode)		rtk_Set_CID_Det_Mode(chid,auto_det,cid_det_mode)
#define rcm_tapi_GetFskCIDState( chid,  cid_state)	rtk_GetFskCIDState(chid,cid_state)
#define rcm_tapi_Set_CID_FSK_GEN_MODE( chid,  isOK)		rtk_Set_CID_FSK_GEN_MODE(chid,isOK)
#define rcm_tapi_Set_Voice_Gain(chid, spk_gain, mic_gain)		rtk_Set_Voice_Gain(chid,spk_gain,mic_gain)
#define rcm_tapi_Set_AnswerTone_Det(chid,config_1,config_2,threshold)		rtk_Set_AnswerTone_Det(chid,config_1,config_2,threshold)
#define rcm_tapi_Gen_FSK_CID_VMWI( chid, str_cid, str_date, str_cid_name,  mode,  msg_type)	rtk_Gen_FSK_CID_VMWI(chid,str_cid,str_date,str_cid_name,mode,msg_type)
#define rcm_tapi_GetPhoneState( pstVoipCfg)	rtk_GetPhoneState(pstVoipCfg)
#define rcm_tapi_Set_GETDATA_Mode( pstVoipdataget_o)	rtk_Set_GETDATA_Mode(pstVoipdataget_o)
#define rcm_tapi_Set_Voice_Play( pstVoipdataput_o)	 rtk_Set_Voice_Play(pstVoipdataput_o)
#define  rcm_tapi_Get_Rtp_Statistics( chid,mid,  bReset, pstRtpRtcpStatistics )	rtk_GetRtpRtcpStatistics(chid,mid,bReset,pstRtpRtcpStatistics)
#define  rcm_tapi_Get_Session_Statistics(  chid,  sid, bReset, pstVoipSessionStatistics )	rtk_Get_Session_Statistics(chid,sid,bReset,pstVoipSessionStatistics)
#define  rcm_tapi_qos_set_dscp_priority( dscp,  priority)	rtk_qos_set_dscp_priority(dscp,priority)
#define  rcm_tapi_qos_reset_dscp_priority() rtk_qos_reset_dscp_priority()
#define  rcm_tapi_Set_Rtp_Tos(rtp_tos)	rtk_Set_Rtp_Tos(rtp_tos)
#define  rcm_tapi_Set_Rtp_Dscp(rtp_dscp) rtk_Set_Rtp_Dscp(rtp_dscp)
#define  rcm_tapi_Set_Sip_Tos(sip_tos)	rtk_Set_Sip_Tos(sip_tos)
#define  rcm_tapi_Set_Sip_Dscp( sip_dscp)	rtk_Set_Sip_Dscp(sip_dscp)
#ifdef CONFIG_RTK_VOIP_DRIVERS_IP_PHONE
#define  rcm_tapi_Set_IPhone(  function_type,   reg,   value)	rtk_Set_IPhone(function_type,reg,value)
#endif

/******************** New Add for AudioCodes Solution ****************/
#define  rcm_tapi_Onhook_Action( chid)	rtk_Onhook_Action(chid)
#define  rcm_tapi_Offhook_Action( chid)	rtk_Offhook_Action(chid)

/**********************************************************************/

#ifdef CONFIG_RTK_VOIP_IP_PHONE
#define rcm_tapi_GetIPPhoneHookStatus( pHookStatus )	rtk_GetIPPhoneHookStatus(pHookStatus)
#endif /* CONFIG_RTK_VOIP_IP_PHONE */

#define  rcm_tapi_Set_flush_fifo( chid)	 rtk_Set_flush_fifo(chid)
#define  rcm_tapi_line_check( chid)	rtk_line_check(chid)
#define  rcm_tapi_FXO_offhook( chid)	rtk_FxoOffHook(chid)
#define  rcm_tapi_FXO_onhook( chid)	rtk_FXO_onhook(chid)
#define  rcm_tapi_FXO_RingOn( chid)	rtk_FXO_RingOn(chid)
#define  rcm_tapi_FXO_Busy( chid)	 rtk_FXO_Busy(chid)
#define  rcm_tapi_gpio(action, pid, value, ret_value)	rtk_gpio(action,pid,value,ret_value)
#define  rcm_tapi_Set_LED_Display(  chid, LED_ID, mode )	rtk_Set_LED_Display(chid,LED_ID,mode)
#define  rcm_tapi_Set_SLIC_Relay( chid,  close1 )	rtk_Set_SLIC_Relay(chid,close1)
#define  rcm_tapi_Set_Pulse_Digit_Det(chid, enable, pause_time, min_break_ths, max_break_ths) 	rtk_Set_Pulse_Digit_Det(chid,enable,pause_time,min_break_ths,max_break_ths)
#define  rcm_tapi_Set_Dail_Mode( chid,  mode) rtk_Set_Dail_Mode(chid,mode)
#define  rcm_tapi_Get_Dail_Mode( chid) rtk_Get_Dail_Mode(chid)
#define  rcm_tapi_PulseDial_Gen_Cfg( pps, make_duration,  interdigit_duration)	rtk_PulseDial_Gen_Cfg(pps,make_duration,interdigit_duration)
#define  rcm_tapi_Gen_Pulse_Dial( chid,  digit) rtk_Gen_Pulse_Dial(chid,digit)
#define  rcm_tapi_Get_SLIC_Ram_Val( chid,  reg)	rtk_Get_SLIC_Ram_Val(chid,reg)
#define rcm_tapi_SLIC_Ram_Val( chid,  reg, value)	rtk_Set_SLIC_Ram_Val(chid,reg,value)
#define  rcm_tapi_SetFaxModemDet( chid,  mode)	rtk_SetFaxModemDet(chid,mode)
#define  rcm_tapi_GetPortLinkStatus( pstatus )	rtk_GetPortLinkStatus(pstatus)
#define  rcm_tapi_WTD_Reboot( reboot)	rtk_WTD_Reboot(reboot)
#define rcm_tapi_print( level, module, msg)	rtk_print(level,module,msg)
#define rcm_tapi_cp3_measure(cp3_voip_param)	rtk_cp3_measure(cp3_voip_param)
#define rcm_tapi_SetDspIdToDsp( dsp_id)	rtk_SetDspIdToDsp(dsp_id)
#define rcm_tapi_SetDspPhyId( phy_id)	rtk_SetDspPhyId(phy_id)
#define  rcm_tapi_CheckDspAllSoftwareReady( phy_id)	rtk_CheckDspAllSoftwareReady(phy_id)

#endif // __RCM_TAPI_H

