/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Board
 */
#define CONFIG_EXCEPTION_BASE (CONFIG_SYS_TEXT_BASE)
#define CONFIG_RTL9601C 1
#define CONFIG_SYS_TEXT_BASE 0x81C00000
#define CONFIG_LZMA 1
#define OTTO_BYPASS_DRAM_SZ_DET 1

/*
 * Flash Type
 */
#define CONFIG_SPI_NAND_FLASH 1
#undef  CONFIG_SPI_NOR_FLASH
#define CONFIG_SPI_NAND_FLASH_GEN ""1""
#define CONFIG_ECC_ENGINE 1
#define CONFIG_ECC_ENGINE_GEN ""1""
#define CONFIG_OTTO_ECC_GEN1 1
#define CONFIG_OTTO_SPI_NAND_GEN1 1
#define CONFIG_ECC_GEN "ecc_gen1"
#define CONFIG_SPI_NAND_GEN "spi_nand_gen1"

/*
 * Diagnosis Tools
 */
#define CONFIG_CMD_DRAM_TEST 1
#undef  CONFIG_CMD_CONCURENT_TEST
#undef  CONFIG_CMD_DRAM_AC_TEST

/*
 * otto features
 */
#define CONFIG_OTTO_FLASH_LAYOUT 1
#define CONFIG_LUNA_MULTI_BOOT 1
#undef  CONFIG_MULTICAST_UPGRADE
#define CONFIG_OTTO_FL_TO_MTDPARTS 1
#define CONFIG_EXTRA_ENV_SETTINGS "upv=tftp 80000000 vm.img;upvmimg ${fileaddr}\0   fx1000_init=mw bb000084 00000048\0   sgmii_init=mw bb000084 00000044\0"
#define CONFIG_SYS_HUSH_PARSER 1
#define CONFIG_EXTRA_ENV_SETTINGS_1 "sw_tryactive=2\0   sw_commit=0\0   sw_active=0\0   sw_version0=0\0   sw_version1=0\0   set_act0=if itest.s ${sw_active} != 0;then setenv sw_active 0;saveenv;fi\0   set_act1=if itest.s ${sw_active} != 1;then setenv sw_active 1;saveenv;fi\0   boot_by_commit=if itest.s ${sw_commit} == 0;then run set_act0;run b0;else run set_act1;run b1;fi\0   en_wdt=mw b8003268 e7c00000\0   boot_by_tryactive=if itest.s ${sw_tryactive} == 0;then setenv sw_tryactive 2;setenv sw_active 0;saveenv;run en_wdt;run b0;else setenv sw_tryactive 2;setenv sw_active 1;saveenv;run en_wdt;run b1;fi\0   bootcmd=if itest.s ${sw_tryactive} == 2; then run boot_by_commit;else run boot_by_tryactive;fi\0"
